import { ProductStatus } from '@prisma/client';

export const automotiveProducts = [
  {
    sku: 'PROD-AUT-001',
    name: '70mai Dash Cam Pro Plus+ A500S Dual Channel 2.7K',
    slug: '70mai-dash-cam-pro-plus-a500s-2-7k',
    description: 'Front 2.7K Ultra HD and rear 1080P dual-channel dash cam featuring Sony IMX335 sensor, built-in GPS, ADAS driver assistance, and 24H parking surveillance.',
    brand: '70mai',
    categorySlug: 'automotive',
    subcategorySlug: 'dash-cams-electronics',
    modelNumber: 'A500S-2',
    mrp: 11999,
    currentPrice: 9599,
    originalPrice: 11999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 25,
    lowStockThreshold: 5,
    rating: 4.8,
    reviewCount: 410,
    tags: ['70mai', 'dash cam', 'car camera', '2.7k dashcam', 'gps dash cam'],
    specifications: { Resolution: '2.7K (2592x1944P) Front + 1080P Rear', Sensor: 'Sony IMX335 Sensor', FieldOfView: '140 Degree FOV', Connectivity: 'Wi-Fi + 70mai App' },
    images: [
      { url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: '70mai Dash Cam Pro Plus A500S Mounted on Windshield' },
      { url: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: '70mai Sony IMX335 Camera Lens Aperture' },
      { url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: '70mai Rear Camera Module Unit' },
      { url: 'https://images.unsplash.com/photo-1508974239320-0a029497e820?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: '70mai 2.0 Inch IPS Screen Display Menu' },
    ],
    variants: [
      { sku: 'PROD-AUT-001-DUAL', name: 'Front 2.7K + Rear 1080P Kit', price: 9599, mrp: 11999, stockQuantity: 15, attributes: { Pack: 'Dual Channel' } },
      { sku: 'PROD-AUT-001-SGL', name: 'Front 2.7K Only', price: 7999, mrp: 9999, stockQuantity: 10, attributes: { Pack: 'Front Only' } },
    ]
  },
  {
    sku: 'PROD-AUT-002',
    name: 'Studds Thunder Full Face Helmet with Dual Visor (ECE & DOT Approved)',
    slug: 'studds-thunder-full-face-helmet-dual-visor',
    description: 'Aerodynamic full face motorcycle helmet featuring high-impact outer shell, dynamic ventilation system, UV resistant inner sun visor, and quick release buckle.',
    brand: 'Studds',
    categorySlug: 'automotive',
    subcategorySlug: 'riding-gear-helmets',
    modelNumber: 'THUN-D3-L',
    mrp: 2999,
    currentPrice: 2399,
    originalPrice: 2999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.7,
    reviewCount: 820,
    tags: ['studds', 'helmet', 'full face helmet', 'dual visor helmet', 'motorcycle helmet'],
    specifications: { Certification: 'ISI & ECE Certified', Visor: 'Dual Visor (Clear + Drop-down Inner Smoke)', Shell: 'High-Impact Thermoplastic', Lining: 'Hypoallergenic Washable Lining' },
    images: [
      { url: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Studds Thunder Full Face Helmet Matt Black Front' },
      { url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Studds Drop-Down Inner Sun Shield Mechanism' },
      { url: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Studds Top Vent Intake Port' },
      { url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Studds Quick Release Chin Strap Buckle' },
    ],
    variants: [
      { sku: 'PROD-AUT-002-L', name: 'Large (580mm) / Matt Black', price: 2399, mrp: 2999, stockQuantity: 25, attributes: { Size: 'Large (580mm)' } },
      { sku: 'PROD-AUT-002-XL', name: 'Extra Large (600mm) / Matt Black', price: 2399, mrp: 2999, stockQuantity: 15, attributes: { Size: 'XL (600mm)' } },
    ]
  },
  {
    sku: 'PROD-AUT-003',
    name: 'Michelin Digital Portable 12V Air Compressor Tyre Inflator',
    slug: 'michelin-digital-12v-tyre-inflator',
    description: 'High performance 12V digital tyre inflator with auto shut-off pre-set pressure, digital backlit LCD gauge, and built-in bright LED work light.',
    brand: 'Michelin',
    categorySlug: 'automotive',
    subcategorySlug: 'car-accessories-mounts',
    modelNumber: '12266',
    mrp: 5995,
    currentPrice: 4796,
    originalPrice: 5995,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 20,
    lowStockThreshold: 4,
    rating: 4.8,
    reviewCount: 390,
    tags: ['michelin', 'tyre inflator', 'car air pump', 'digital inflator', '12v inflator'],
    specifications: { Power: '12V Cigarette Lighter Socket', MaxPressure: '50 PSI for Cars', Accuracy: '+/- 1 PSI', Features: 'DPS Auto Preset Stop' },
    images: [
      { url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Michelin Digital 12V Tyre Inflator Body Front' },
      { url: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Michelin Backlit Digital LCD Pressure Display' },
      { url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Michelin Screw-On Brass Valve Nozzle Hose' },
      { url: 'https://images.unsplash.com/photo-1508974239320-0a029497e820?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Michelin Integrated LED Emergency Torch Light' },
    ],
    variants: [
      { sku: 'PROD-AUT-003-12V', name: 'Digital 12V Preset Model', price: 4796, mrp: 5995, stockQuantity: 20, attributes: { Model: '12V Digital' } }
    ]
  },
  {
    sku: 'PROD-AUT-004',
    name: 'Spigen OneTap MagSafe Car Phone Mount Air Vent',
    slug: 'spigen-onetap-magsafe-car-phone-mount',
    description: 'MagSafe compatible magnetic car phone mount with strong N52 neodymium magnets, 360-degree ball joint rotation, and twist-lock air vent clip.',
    brand: 'Spigen',
    categorySlug: 'automotive',
    subcategorySlug: 'car-accessories-mounts',
    modelNumber: 'ACP03790',
    mrp: 2999,
    currentPrice: 2099,
    originalPrice: 2999,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 35,
    lowStockThreshold: 7,
    rating: 4.8,
    reviewCount: 450,
    tags: ['spigen', 'magsafe car mount', 'magnetic phone holder', 'car phone mount', 'iphone car mount'],
    specifications: { Compatibility: 'iPhone 12 to 16 & MagSafe Cases', MountType: 'Air Vent Twist-Lock Clamp', Magnet: 'N52 Neodymium Ring', Rotation: '360 Degrees' },
    images: [
      { url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Spigen OneTap MagSafe Car Mount Vent Attached' },
      { url: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Spigen Magnetic Ring & Silicone Contact Pad' },
      { url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Spigen Twist Lock Air Vent Blade Clamp' },
      { url: 'https://images.unsplash.com/photo-1508974239320-0a029497e820?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Spigen iPhone Snap-On Magnetic Alignment' },
    ],
    variants: [
      { sku: 'PROD-AUT-004-BLK', name: 'Matte Black', price: 2099, mrp: 2999, stockQuantity: 35, attributes: { Color: 'Matte Black' } }
    ]
  },
  {
    sku: 'PROD-AUT-005',
    name: 'Alpinestars SP-8 v3 Leather Riding Gloves',
    slug: 'alpinestars-sp-8-v3-leather-riding-gloves',
    description: 'Universal track-tested sports motorcycle gloves crafted from full-grain goat leather, SP dual density knuckle protector, and patented 3rd and 4th finger bridge.',
    brand: 'Alpinestars',
    categorySlug: 'automotive',
    subcategorySlug: 'riding-gear-helmets',
    modelNumber: '3558321',
    mrp: 12999,
    currentPrice: 11049,
    originalPrice: 12999,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 15,
    lowStockThreshold: 3,
    rating: 4.9,
    reviewCount: 190,
    tags: ['alpinestars', 'sp-8 v3', 'riding gloves', 'leather motorcycle gloves', 'knuckle protection'],
    specifications: { Material: 'Full Grain Goat & Synthetic Leather', Protection: 'SP Dual Density Polymer Knuckle', Closure: 'Double Wrist Closure', Touchscreen: 'Touchscreen Compatible Index Finger' },
    images: [
      { url: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Alpinestars SP-8 v3 Leather Riding Gloves Pair' },
      { url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Alpinestars Dual Density Knuckle Guard Detail' },
      { url: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Alpinestars Palm Synthetic Suede Reinforcement' },
      { url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Alpinestars Velco Wrist Strap Branding' },
    ],
    variants: [
      { sku: 'PROD-AUT-005-M', name: 'Medium (M) / Black', price: 11049, mrp: 12999, stockQuantity: 8, attributes: { Size: 'Medium' } },
      { sku: 'PROD-AUT-005-L', name: 'Large (L) / Black', price: 11049, mrp: 12999, stockQuantity: 7, attributes: { Size: 'Large' } },
    ]
  },
  {
    sku: 'PROD-AUT-006',
    name: 'Anker Roav SmartClean High Suction Cordless Car Vacuum',
    slug: 'anker-roav-smartclean-cordless-car-vacuum',
    description: 'Portable handheld cordless car vacuum cleaner with 5.5KPa suction power, washable HEPA filter, and USB-C fast charging capability.',
    brand: 'Anker',
    categorySlug: 'automotive',
    subcategorySlug: 'car-accessories-mounts',
    modelNumber: 'R5111',
    mrp: 4999,
    currentPrice: 3499,
    originalPrice: 4999,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 25,
    lowStockThreshold: 5,
    rating: 4.6,
    reviewCount: 310,
    tags: ['anker', 'car vacuum', 'cordless vacuum', 'handheld car vacuum', 'hepa car cleaner'],
    specifications: { Suction: '5,500 Pa Suction Power', Weight: '560g Ultra Light', Battery: 'USB-C Rechargeable Li-ion', Filter: 'Washable High-Efficiency HEPA' },
    images: [
      { url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Anker Roav Cordless Car Vacuum Sleek Cylinder Body' },
      { url: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Anker Roav 2-in-1 Crevice & Brush Nozzle Attachment' },
      { url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Anker Roav Transparent Dust Cup Emptying' },
      { url: 'https://images.unsplash.com/photo-1508974239320-0a029497e820?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Anker Roav USB-C Charge Port & LED Light' },
    ],
    variants: [
      { sku: 'PROD-AUT-006-BLK', name: 'Black Metallic', price: 3499, mrp: 4999, stockQuantity: 25, attributes: { Color: 'Black Metallic' } }
    ]
  },
  {
    sku: 'PROD-AUT-007',
    name: 'DDPAI Z40 Dual GPS Dash Cam 3K Front & 1080P Rear',
    slug: 'ddpai-z40-dual-gps-dash-cam',
    description: 'Sony IMX335 5MP front 3K sensor dash camera with Sense Reality 2.0 telemetry overlay, D2 Save dual storage technology, and supercapacitor.',
    brand: 'DDPAI',
    categorySlug: 'automotive',
    subcategorySlug: 'dash-cams-electronics',
    modelNumber: 'DDPAI-Z40-GPS',
    mrp: 12999,
    currentPrice: 9749,
    originalPrice: 12999,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 20,
    lowStockThreshold: 4,
    rating: 4.8,
    reviewCount: 280,
    tags: ['ddpai', 'z40 dash cam', '3k dash cam', 'gps dash cam', 'dual dash cam'],
    specifications: { Resolution: '1944P (3K) Front + 1080P Rear', Storage: 'Supports MicroSD up to 128GB + NAND Flash Dual Fail-Safe', Capacitor: 'Supercapacitor Power', Sensor: '5MP Sony IMX335' },
    images: [
      { url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'DDPAI Z40 Dual Dash Cam Front & Rear Units' },
      { url: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'DDPAI Z40 2.0-inch IPS Display Screen' },
      { url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'DDPAI Sense Reality AR Interface App Screenshot' },
      { url: 'https://images.unsplash.com/photo-1508974239320-0a029497e820?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'DDPAI Compact Windshield Mounting Plate' },
    ],
    variants: [
      { sku: 'PROD-AUT-007-GPS', name: 'Dual 3K + Rear 1080P with Built-in GPS', price: 9749, mrp: 12999, stockQuantity: 20, attributes: { GPS: 'Built-in GPS' } }
    ]
  },
  {
    sku: 'PROD-AUT-008',
    name: 'Autofy Universal Waterproof Heavy-Duty Car Cover',
    slug: 'autofy-waterproof-heavy-duty-car-cover',
    description: 'Triple-stitched 100% waterproof all-weather car cover with soft cotton inner lining to prevent scratches, mirror pockets, and windproof buckle straps.',
    brand: 'Autofy',
    categorySlug: 'automotive',
    subcategorySlug: 'car-accessories-mounts',
    modelNumber: 'AF-CC-SUV',
    mrp: 2999,
    currentPrice: 1999,
    originalPrice: 2999,
    discount: 33.3,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 6,
    rating: 4.6,
    reviewCount: 510,
    tags: ['autofy', 'car cover', 'waterproof car cover', 'all weather cover', 'suv cover'],
    specifications: { Material: 'Heavy Duty Taffeta Polyester + Fleece Cotton Lining', Protection: '100% Waterproof & UV Protection', Features: 'Custom Mirror Pockets + Elastic Hem' },
    images: [
      { url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Autofy Silver Waterproof Car Cover Draped on SUV' },
      { url: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Autofy Soft Cotton Inner Fleece Layer Close' },
      { url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Autofy Windproof Wheel Buckle Strap' },
      { url: 'https://images.unsplash.com/photo-1508974239320-0a029497e820?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Autofy Zippered Storage Duffel Bag' },
    ],
    variants: [
      { sku: 'PROD-AUT-008-SED', name: 'Sedan Fit (Length 4.5m)', price: 1999, mrp: 2999, stockQuantity: 15, attributes: { Fit: 'Sedan Size' } },
      { sku: 'PROD-AUT-008-SUV', name: 'SUV / Creta Fit (Length 4.8m)', price: 2199, mrp: 3199, stockQuantity: 15, attributes: { Fit: 'SUV Size' } },
    ]
  },
  {
    sku: 'PROD-AUT-009',
    name: 'AXOR Apex Venom Full Face Graphics Helmet',
    slug: 'axor-apex-venom-full-face-helmet',
    description: 'High performance racing helmet with dual spoiler, Pinlock 30 anti-fog visor ready, ECE R22.05 certification, and washable anti-bacterial comfort liner.',
    brand: 'AXOR',
    categorySlug: 'automotive',
    subcategorySlug: 'riding-gear-helmets',
    modelNumber: 'AX-APX-VNM-L',
    mrp: 5494,
    currentPrice: 4669,
    originalPrice: 5494,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 25,
    lowStockThreshold: 5,
    rating: 4.8,
    reviewCount: 620,
    tags: ['axor', 'apex venom', 'racing helmet', 'graphics helmet', 'pinlock ready'],
    specifications: { Certification: 'ECE R22.05 & DOT Certified', Weight: '1500 +/- 50 grams', Visor: 'Anti-Scratch Clear Visor + Integrated Sun Visor', Pinlock: 'Pinlock 30 Included' },
    images: [
      { url: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'AXOR Apex Venom Graphic Helmet Front View' },
      { url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'AXOR Rear Dual Aerodynamic Spoiler' },
      { url: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'AXOR Pinlock Anti-Fog Lens Installed' },
      { url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'AXOR Breath Deflector & Chin Curtain' },
    ],
    variants: [
      { sku: 'PROD-AUT-009-L', name: 'Large (580mm) / Gloss Black Red', price: 4669, mrp: 5494, stockQuantity: 15, attributes: { Size: 'Large (580mm)' } },
      { sku: 'PROD-AUT-009-M', name: 'Medium (570mm) / Gloss Black Red', price: 4669, mrp: 5494, stockQuantity: 10, attributes: { Size: 'Medium (570mm)' } },
    ]
  },
  {
    sku: 'PROD-AUT-010',
    name: 'Baseus 160W Multi-Port Fast Car Charger Adapter',
    slug: 'baseus-160w-fast-car-charger-adapter',
    description: 'High-power 160W triple port (2x Type-C + 1x USB-A) car charger supporting Power Delivery 3.1 and Quick Charge 5.0 for charging laptops and phones.',
    brand: 'Baseus',
    categorySlug: 'automotive',
    subcategorySlug: 'car-accessories-mounts',
    modelNumber: 'CCBX-160C',
    mrp: 4999,
    currentPrice: 3749,
    originalPrice: 4999,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 6,
    rating: 4.8,
    reviewCount: 290,
    tags: ['baseus', 'car charger', '160w car charger', 'usb c car charger', 'laptop car charger'],
    specifications: { TotalOutput: '160 Watts Max', Ports: 'Type-C1 100W + Type-C2 30W + USB-A 30W', Protocols: 'PD3.1, QC5.0, PPS', Light: 'Ambient Ice Blue LED Halo' },
    images: [
      { url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Baseus 160W Fast Car Charger Metal Body Plugged In' },
      { url: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Baseus Triple USB Port Interface & Blue LED Ring' },
      { url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Baseus Gold-Plated Contact Pins Detail' },
      { url: 'https://images.unsplash.com/photo-1508974239320-0a029497e820?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Baseus 100W USB-C Braided Charging Cable Included' },
    ],
    variants: [
      { sku: 'PROD-AUT-010-160W', name: '160W Triple Port with 100W Cable', price: 3749, mrp: 4999, stockQuantity: 30, attributes: { Power: '160W' } }
    ]
  },
  {
    sku: 'PROD-AUT-011',
    name: 'Bosch Aerotwin Frameless Windshield Wiper Blades Pair',
    slug: 'bosch-aerotwin-frameless-wiper-blades-pair',
    description: 'OE aerodynamic frameless wiper blade pair featuring Power Protection Plus dual-rubber technology for streak-free wiping in heavy rain.',
    brand: 'Bosch',
    categorySlug: 'automotive',
    subcategorySlug: 'car-accessories-mounts',
    modelNumber: 'AR-24-16-A',
    mrp: 2499,
    currentPrice: 1874,
    originalPrice: 2499,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 35,
    lowStockThreshold: 7,
    rating: 4.8,
    reviewCount: 480,
    tags: ['bosch', 'aerotwin', 'wiper blades', 'frameless wipers', 'car wiper'],
    specifications: { Type: 'Frameless Aerodynamic Flat Blade', Technology: 'Power Protection Plus Synthetic Rubber', Adapter: 'Multi-Clip Adapter Set', Pack: 'Pair (24 in + 16 in)' },
    images: [
      { url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Bosch Aerotwin Wiper Blades Pair Installed on Windshield' },
      { url: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Bosch Dual Rubber Edge Profile Close' },
      { url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Bosch Multi-Clip Adapter Snap Fit' },
      { url: 'https://images.unsplash.com/photo-1508974239320-0a029497e820?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Bosch Yellow & Black Box Packaging' },
    ],
    variants: [
      { sku: 'PROD-AUT-011-2416', name: '24 Inch + 16 Inch Pair', price: 1874, mrp: 2499, stockQuantity: 20, attributes: { Size: '24 in / 16 in' } },
      { sku: 'PROD-AUT-011-2216', name: '22 Inch + 16 Inch Pair', price: 1874, mrp: 2499, stockQuantity: 15, attributes: { Size: '22 in / 16 in' } },
    ]
  },
  {
    sku: 'PROD-AUT-012',
    name: 'BOBO BM4 Jaw-Grip Waterproof Bicycle & Motorcycle Phone Mount',
    slug: 'bobo-bm4-jaw-grip-motorcycle-phone-mount',
    description: 'Heavy duty aluminum alloy handlebar phone mount with 360-degree rotation, vibration dampener module, and integrated USB fast charger.',
    brand: 'BOBO',
    categorySlug: 'automotive',
    subcategorySlug: 'riding-gear-helmets',
    modelNumber: 'BM4-USB',
    mrp: 2499,
    currentPrice: 1749,
    originalPrice: 2499,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.7,
    reviewCount: 650,
    tags: ['bobo', 'phone mount', 'motorcycle mobile holder', 'bike phone holder', 'usb phone mount'],
    specifications: { Material: 'CNC Machined Aluminum Alloy', PhoneSize: '4.0 to 7.0 Inches', Charger: '5V 2.5A USB Fast Charger', Waterproof: 'IP66 Rated' },
    images: [
      { url: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'BOBO BM4 Aluminum Jaw Grip Mount on Handlebar' },
      { url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'BOBO Steel Jaw Adjustment Screw' },
      { url: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'BOBO USB Charging Port Waterproof Cap' },
      { url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'BOBO Anti-Vibration Rubber Pad Inserts' },
    ],
    variants: [
      { sku: 'PROD-AUT-012-CHG', name: 'With USB Fast Charger', price: 1749, mrp: 2499, stockQuantity: 25, attributes: { Option: 'With Charger' } },
      { sku: 'PROD-AUT-012-NOCHG', name: 'Without Charger', price: 1299, mrp: 1899, stockQuantity: 15, attributes: { Option: 'Without Charger' } },
    ]
  },
  {
    sku: 'PROD-AUT-013',
    name: 'Vantrue N4 3 Channel 4K Dash Cam Front Inside Rear',
    slug: 'vantrue-n4-3-channel-4k-dash-cam',
    description: 'Triple channel dash cam recording 4K Front + 1080P Cabin + 1080P Rear simultaneously with Sony STARVIS sensors and 4 Infrared LED cabin night vision lights.',
    brand: 'Vantrue',
    categorySlug: 'automotive',
    subcategorySlug: 'dash-cams-electronics',
    modelNumber: 'N4-3CH',
    mrp: 29999,
    currentPrice: 23999,
    originalPrice: 29999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 10,
    lowStockThreshold: 2,
    rating: 4.9,
    reviewCount: 220,
    tags: ['vantrue', 'n4 dash cam', '3 channel dash cam', '4k dash cam', 'uber dash cam'],
    specifications: { Resolution: '4K (2160P) Front + 1080P Cabin + 1080P Rear', NightVision: '4 IR LED Cabin Lights + Sony STARVIS', ParkingMode: '24/7 Motion & Collision Detection', Capacitor: 'Supercapacitor' },
    images: [
      { url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Vantrue N4 Triple Channel Dash Cam Setup' },
      { url: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Vantrue Cabin Camera & 4 IR Night Vision LEDs' },
      { url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Vantrue Rear Waterproof Tailgate Camera' },
      { url: 'https://images.unsplash.com/photo-1508974239320-0a029497e820?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Vantrue 2.45-Inch Display Screen Menu' },
    ],
    variants: [
      { sku: 'PROD-AUT-013-3CH', name: '3-Channel (Front + Cabin + Rear)', price: 23999, mrp: 29999, stockQuantity: 10, attributes: { Pack: '3 Channel' } }
    ]
  },
  {
    sku: 'PROD-AUT-014',
    name: 'Armor All Complete Car Care Detailing Cleaning Kit',
    slug: 'armor-all-complete-car-care-kit',
    description: 'Comprehensive 4-piece car detailing kit including Protectant Spray, Ultra Shine Car Wash & Wax, Glass Wipes, and Tire Foam Cleaner.',
    brand: 'Armor All',
    categorySlug: 'automotive',
    subcategorySlug: 'car-accessories-mounts',
    modelNumber: 'AA-KIT-04',
    mrp: 2999,
    currentPrice: 2249,
    originalPrice: 2999,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 6,
    rating: 4.7,
    reviewCount: 380,
    tags: ['armor all', 'car cleaning kit', 'car detailing', 'car wax', 'tire shine'],
    specifications: { Includes: 'Protectant 473ml + Wash & Wax 473ml + Glass Cleaner + Tire Foam 500ml', Feature: 'UV Protection & Gloss Finish' },
    images: [
      { url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Armor All Complete Car Care Kit 4 Bottle Set' },
      { url: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Armor All Protectant Spray Dashboard Sheen' },
      { url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Armor All Tire Foam Deep Black Shine' },
      { url: 'https://images.unsplash.com/photo-1508974239320-0a029497e820?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Armor All Microfiber Cloth Included' },
    ],
    variants: [
      { sku: 'PROD-AUT-014-4P', name: '4-Piece Detailing Kit', price: 2249, mrp: 2999, stockQuantity: 30, attributes: { Pack: 'Set of 4' } }
    ]
  },
  {
    sku: 'PROD-AUT-015',
    name: 'NOCO Genius1 1A Smart Automatic Battery Charger & Maintainer',
    slug: 'noco-genius1-smart-battery-charger',
    description: 'Fully-automatic 6V and 12V battery charger, maintainer, and desulfator for lead-acid and lithium-ion automotive and motorcycle batteries.',
    brand: 'NOCO',
    categorySlug: 'automotive',
    subcategorySlug: 'car-accessories-mounts',
    modelNumber: 'GENIUS1',
    mrp: 4999,
    currentPrice: 3999,
    originalPrice: 4999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 20,
    lowStockThreshold: 4,
    rating: 4.9,
    reviewCount: 310,
    tags: ['noco', 'genius1', 'battery charger', 'trickle charger', 'car battery maintainer'],
    specifications: { Voltage: '6V & 12V Lead-Acid & Lithium', Current: '1 Amp Charging Current', Protection: 'Reverse Polarity & Overcharge Protection', Tech: 'Built-in Thermal Sensor' },
    images: [
      { url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'NOCO Genius1 Battery Charger Body & Clamps' },
      { url: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'NOCO Mode Button LED Indicator Lights' },
      { url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'NOCO Heavy Duty Eyelet Battery Clamp Terminals' },
      { url: 'https://images.unsplash.com/photo-1508974239320-0a029497e820?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'NOCO Compact Wall Plug & Cord' },
    ],
    variants: [
      { sku: 'PROD-AUT-015-1A', name: 'GENIUS1 (1-Amp 6V/12V)', price: 3999, mrp: 4999, stockQuantity: 20, attributes: { Output: '1-Amp' } }
    ]
  }
];
