import { ProductStatus } from '@prisma/client';

export const babyProductsData = [
  {
    sku: 'PROD-BBY-001',
    name: 'Chicco Bravo Trio Folding Stroller & KeyFit 30 Car Seat',
    slug: 'chicco-bravo-trio-travel-system-stroller',
    description: '3-in-1 travel system combining one-hand quick fold Bravo Stroller with top-rated KeyFit 30 Infant Car Seat and base.',
    brand: 'Chicco',
    categorySlug: 'baby-products',
    subcategorySlug: 'baby-strollers',
    modelNumber: '06079641990070',
    mrp: 44990,
    currentPrice: 38241,
    originalPrice: 44990,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 10,
    lowStockThreshold: 2,
    rating: 4.9,
    reviewCount: 320,
    tags: ['chicco', 'bravo trio', 'baby stroller', 'car seat combo', 'travel system'],
    specifications: { MaximumWeight: '22.6 kg (50 lbs)', Fold: 'One-Hand Smart Fold', Canopy: 'UPF 50+ Adjustable Canopy', CarSeat: 'Includes KeyFit 30 Base' },
    images: [
      { url: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Chicco Bravo Stroller & KeyFit Car Seat Combo' },
      { url: 'https://images.unsplash.com/photo-1544126592-807ade215a0b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Chicco One-Hand Smart Folding Handle Close' },
      { url: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Chicco Parent Tray Cup Holders & Storage' },
      { url: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Chicco KeyFit 30 Car Seat Click-In Latch Base' },
    ],
    variants: [
      { sku: 'PROD-BBY-001-GRY', name: 'Charcoal Grey & Black', price: 38241, mrp: 44990, stockQuantity: 6, attributes: { Color: 'Charcoal Grey' } },
      { sku: 'PROD-BBY-001-BLU', name: 'Apex Navy & Black', price: 38241, mrp: 44990, stockQuantity: 4, attributes: { Color: 'Apex Navy' } },
    ]
  },
  {
    sku: 'PROD-BBY-002',
    name: 'Graco Extend2Fit Convertible 3-in-1 Car Seat',
    slug: 'graco-extend2fit-convertible-car-seat',
    description: 'Grow-with-me car seat with 4-position extension panel providing up to 5 inches of additional legroom, allowing child to safely ride rear-facing longer.',
    brand: 'Graco',
    categorySlug: 'baby-products',
    subcategorySlug: 'baby-strollers',
    modelNumber: '1963288',
    mrp: 29990,
    currentPrice: 23992,
    originalPrice: 29990,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 15,
    lowStockThreshold: 3,
    rating: 4.8,
    reviewCount: 480,
    tags: ['graco', 'extend2fit', 'car seat', 'convertible car seat', 'rear facing car seat'],
    specifications: { RearFacingWeight: '1.8 kg to 22.5 kg', ForwardFacingWeight: '10 kg to 29.5 kg', Harness: 'Simply Safe Adjust 10-Position', Recline: '6-Position Recline' },
    images: [
      { url: 'https://images.unsplash.com/photo-1544126592-807ade215a0b?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Graco Extend2Fit Convertible Car Seat Front' },
      { url: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Graco 4-Position Extension Panel Unfolded' },
      { url: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Graco Dual Integrated Cup Holders Detail' },
      { url: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Graco LATCH InRight Attachment System' },
    ],
    variants: [
      { sku: 'PROD-BBY-002-Gotham', name: 'Gotham Black/Grey', price: 23992, mrp: 29990, stockQuantity: 15, attributes: { Color: 'Gotham Black/Grey' } }
    ]
  },
  {
    sku: 'PROD-BBY-003',
    name: 'Owlet Dream Sock Smart Baby Monitor with Oxygen Tracking',
    slug: 'owlet-dream-sock-smart-baby-monitor',
    description: 'FDA-cleared medical grade smart sock monitor wrapping around baby foot to track real-time oxygen level, heart rate, and sleep trends with Base Station alerts.',
    brand: 'Owlet',
    categorySlug: 'baby-products',
    subcategorySlug: 'nursery-furniture',
    modelNumber: 'BM06NNNNJ',
    mrp: 32990,
    currentPrice: 28041,
    originalPrice: 32990,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 12,
    lowStockThreshold: 2,
    rating: 4.9,
    reviewCount: 290,
    tags: ['owlet', 'dream sock', 'baby monitor', 'oxygen monitor', 'heart rate monitor'],
    specifications: { AgeRange: '0 to 18 Months', Parameters: 'Oxygen Level + Pulse Rate + Sleep Quality', Connection: 'WiFi + Bluetooth', App: 'Owlet Care App' },
    images: [
      { url: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Owlet Dream Sock Fabric Wrapper & Base Station' },
      { url: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Owlet Base Station Green Glowing Light Ring' },
      { url: 'https://images.unsplash.com/photo-1544126592-807ade215a0b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Owlet Sensor Pod Micro Pulse Oximeter' },
      { url: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Owlet Mobile App Real Time Metrics Display' },
    ],
    variants: [
      { sku: 'PROD-BBY-003-GRN', name: 'Mint Green Sock', price: 28041, mrp: 32990, stockQuantity: 6, attributes: { Color: 'Mint Green' } },
      { sku: 'PROD-BBY-003-PNK', name: 'Dusty Rose Sock', price: 28041, mrp: 32990, stockQuantity: 6, attributes: { Color: 'Dusty Rose' } },
    ]
  },
  {
    sku: 'PROD-BBY-004',
    name: 'Philips Avent Natural Response Baby Bottle Gift Set (Non-Food Utensil)',
    slug: 'philips-avent-natural-response-baby-bottle-set',
    description: 'Set of 4 anti-colic baby bottles with Natural Response nipples that release milk only when baby actively drinks, plus bottle brush and pacifiers.',
    brand: 'Philips Avent',
    categorySlug: 'baby-products',
    subcategorySlug: 'feeding-care',
    modelNumber: 'SCD838/11',
    mrp: 4995,
    currentPrice: 3996,
    originalPrice: 4995,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 6,
    rating: 4.8,
    reviewCount: 650,
    tags: ['philips avent', 'baby bottle', 'anti colic bottle', 'feeding bottle', 'bpa free bottle'],
    specifications: { Material: 'BPA-Free Polypropylene', Nipple: 'No-Drip Natural Response Nipple', Pack: '4 Bottles (2x125ml + 2x260ml) + Brush + Pacifiers', Valve: 'Anti-Colic Valve' },
    images: [
      { url: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Philips Avent Natural Response Bottle Set Array' },
      { url: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Philips Avent Breast-Shaped Soft Silicone Nipple' },
      { url: 'https://images.unsplash.com/photo-1544126592-807ade215a0b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Philips Avent Anti-Colic Vent Valve Close' },
      { url: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Philips Avent Bottle Cleaning Brush & Soother' },
    ],
    variants: [
      { sku: 'PROD-BBY-004-SET', name: 'Newborn Starter Set (4 Bottles)', price: 3996, mrp: 4995, stockQuantity: 30, attributes: { Pack: 'Starter Set' } }
    ]
  },
  {
    sku: 'PROD-BBY-005',
    name: 'Stokke Tripp Trapp High Chair with Baby Set',
    slug: 'stokke-tripp-trapp-wooden-high-chair',
    description: 'Iconic Scandinavian adjustable wooden high chair designed to bring baby right up to the dining table, crafted from solid European beech wood.',
    brand: 'Stokke',
    categorySlug: 'baby-products',
    subcategorySlug: 'nursery-furniture',
    modelNumber: 'STK-TT-BEEC',
    mrp: 28990,
    currentPrice: 24641,
    originalPrice: 28990,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 10,
    lowStockThreshold: 2,
    rating: 4.9,
    reviewCount: 380,
    tags: ['stokke', 'tripp trapp', 'high chair', 'wooden high chair', 'scandinavian nursery'],
    specifications: { Material: 'Solid European Beech Wood', WeightCapacity: 'Up to 136 kg (300 lbs)', Adjustability: 'Depth & Height Adjustable Seat & Footplate', Finish: 'Non-Toxic Water-Based Paint' },
    images: [
      { url: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Stokke Tripp Trapp Wooden High Chair Front' },
      { url: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Stokke Beech Wood Slotted Height Adjustment Track' },
      { url: 'https://images.unsplash.com/photo-1544126592-807ade215a0b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Stokke Baby Set Harness & Backrest Attachment' },
      { url: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Stokke High Chair at Dining Table Setup' },
    ],
    variants: [
      { sku: 'PROD-BBY-005-NAT', name: 'Natural Beech Wood', price: 24641, mrp: 28990, stockQuantity: 6, attributes: { Finish: 'Natural Beech' } },
      { sku: 'PROD-BBY-005-WHT', name: 'White Wash Beech Wood', price: 24641, mrp: 28990, stockQuantity: 4, attributes: { Finish: 'White Wash' } },
    ]
  },
  {
    sku: 'PROD-BBY-006',
    name: 'Medela Freestyle Hands-Free Double Electric Breast Pump',
    slug: 'medela-freestyle-hands-free-breast-pump',
    description: 'Wearable double electric breast pump featuring lightweight 76g anatomical collection cups that fit discreetly inside your nursing bra.',
    brand: 'Medela',
    categorySlug: 'baby-products',
    subcategorySlug: 'feeding-care',
    modelNumber: '101044158',
    mrp: 34990,
    currentPrice: 29741,
    originalPrice: 34990,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 12,
    lowStockThreshold: 3,
    rating: 4.8,
    reviewCount: 240,
    tags: ['medela', 'breast pump', 'wearable breast pump', 'hands free pump', 'nursing care'],
    specifications: { Tech: '2-Phase Expression Technology', Cups: 'Ultra-Lightweight 76g Collection Cups', Power: 'Rechargeable Li-ion Battery USB-C', App: 'Medela Family App Bluetooth' },
    images: [
      { url: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Medela Freestyle Hands Free Pump Unit & Cups' },
      { url: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Medela Anatomical 3-Piece Cup Assembly' },
      { url: 'https://images.unsplash.com/photo-1544126592-807ade215a0b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Medela Pocket Sized Motor Unit Digital Screen' },
      { url: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Medela USB-C Charging Cable & Milk Storage Bottle' },
    ],
    variants: [
      { sku: 'PROD-BBY-006-SET', name: 'Hands-Free Double Pump Set', price: 29741, mrp: 34990, stockQuantity: 12, attributes: { Pack: 'Complete Set' } }
    ]
  },
  {
    sku: 'PROD-BBY-007',
    name: 'Nanit Pro Smart Baby Monitor & Wall Mount Camera',
    slug: 'nanit-pro-smart-baby-monitor-wall-mount',
    description: '1080p HD overhead video baby monitor with split-screen viewing, crystal clear night vision, two-way audio, and Breathing Motion Tracking.',
    brand: 'Nanit',
    categorySlug: 'baby-products',
    subcategorySlug: 'nursery-furniture',
    modelNumber: 'N301US',
    mrp: 32990,
    currentPrice: 28041,
    originalPrice: 32990,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 15,
    lowStockThreshold: 3,
    rating: 4.9,
    reviewCount: 310,
    tags: ['nanit', 'nanit pro', 'baby monitor', 'hd nursery camera', 'smart monitor'],
    specifications: { Video: '1080p HD Overhead View', Mount: 'Safe-Cable Wall Mount', Security: '256-Bit AES Encryption', Features: 'Breathing Motion Monitoring' },
    images: [
      { url: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Nanit Pro Wall Mounted Overhead Nursery Camera' },
      { url: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Nanit Camera Lens & Soft Diffused Night Light Ring' },
      { url: 'https://images.unsplash.com/photo-1544126592-807ade215a0b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Nanit Cable Management Wall Channel' },
      { url: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Nanit App HD Video Stream & Sleep Analytics' },
    ],
    variants: [
      { sku: 'PROD-BBY-007-WM', name: 'Wall Mount Camera System', price: 28041, mrp: 32990, stockQuantity: 15, attributes: { Mount: 'Wall Mount' } }
    ]
  },
  {
    sku: 'PROD-BBY-008',
    name: 'Skip Hop Activity Center 3-Stage 360-Degree Bouncer',
    slug: 'skip-hop-activity-center-3-stage-bouncer',
    description: 'Designed in collaboration with pediatricians, this 3-stage activity center converts from a 360-degree rotating baby bouncer to a toddler play table.',
    brand: 'Skip Hop',
    categorySlug: 'baby-products',
    subcategorySlug: 'nursery-furniture',
    modelNumber: '304350',
    mrp: 18990,
    currentPrice: 15192,
    originalPrice: 18990,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 15,
    lowStockThreshold: 3,
    rating: 4.8,
    reviewCount: 410,
    tags: ['skip hop', 'activity center', 'baby bouncer', 'play table', 'toddler table'],
    specifications: { Stages: '3 Stages (Sit, Swivel, Bounce & Play -> Cruise -> Play Table)', Seat: '360-Degree Rotating Fabric Seat', Toys: '25+ Developmental Activities', Window: 'Discovery Window for Feet' },
    images: [
      { url: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Skip Hop 3-Stage Activity Center Front' },
      { url: 'https://images.unsplash.com/photo-1544126592-807ade215a0b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Skip Hop Discovery Window & Musical Piano Keyboard' },
      { url: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Skip Hop Clip-On Developmental Toys Array' },
      { url: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Skip Hop Converted Toddler Clean Play Table' },
    ],
    variants: [
      { sku: 'PROD-BBY-008-CLR', name: 'Explore & More White/Grey', price: 15192, mrp: 18990, stockQuantity: 15, attributes: { Color: 'White/Grey' } }
    ]
  },
  {
    sku: 'PROD-BBY-009',
    name: 'Ergobaby Omni 360 All-in-One Cool Air Mesh Carrier',
    slug: 'ergobaby-omni-360-cool-air-mesh-carrier',
    description: 'All-in-one ergonomic baby carrier featuring 4 carry positions (Front Inward, Front Outward, Hip & Back) with breathable 3D cool air mesh fabric.',
    brand: 'Ergobaby',
    categorySlug: 'baby-products',
    subcategorySlug: 'baby-strollers',
    modelNumber: 'BCS360PBLK',
    mrp: 17990,
    currentPrice: 14392,
    originalPrice: 17990,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 20,
    lowStockThreshold: 4,
    rating: 4.9,
    reviewCount: 510,
    tags: ['ergobaby', 'omni 360', 'baby carrier', 'cool air mesh', 'ergonomic carrier'],
    specifications: { BabyWeight: '3.2 kg to 20 kg (No Infant Insert Needed)', Positions: '4 Ergonomic Carry Positions', Fabric: '3D Breathable Cool Air Mesh', Belt: 'Lumbar Support Waistbelt' },
    images: [
      { url: 'https://images.unsplash.com/photo-1544126592-807ade215a0b?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Ergobaby Omni 360 Onyx Black Carrier Front' },
      { url: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Ergobaby 3D Cool Air Mesh Weave Close' },
      { url: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Ergobaby Lumbar Support Padded Waistbelt' },
      { url: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Ergobaby Detachable Storage Pouch' },
    ],
    variants: [
      { sku: 'PROD-BBY-009-BLK', name: 'Onyx Black Cool Air Mesh', price: 14392, mrp: 17990, stockQuantity: 12, attributes: { Color: 'Onyx Black' } },
      { sku: 'PROD-BBY-009-GRY', name: 'Pearl Grey Cool Air Mesh', price: 14392, mrp: 17990, stockQuantity: 8, attributes: { Color: 'Pearl Grey' } },
    ]
  },
  {
    sku: 'PROD-BBY-010',
    name: 'Dr. Brown’s Options+ Anti-Colic Glass Bottle Set (Non-Food Utensils)',
    slug: 'dr-browns-options-plus-glass-bottle-set',
    description: '4-pack borosilicate glass baby bottles featuring internal vent system clinically proven to reduce colic, spit-up, burping, and gas.',
    brand: "Dr. Brown's",
    categorySlug: 'baby-products',
    subcategorySlug: 'feeding-care',
    modelNumber: 'SB84005-P4',
    mrp: 4499,
    currentPrice: 3599,
    originalPrice: 4499,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 25,
    lowStockThreshold: 5,
    rating: 4.8,
    reviewCount: 410,
    tags: ['dr browns', 'glass baby bottles', 'anti colic bottles', 'options plus', 'feeding bottles'],
    specifications: { Material: 'Pharmaceutical-Grade Borosilicate Glass', Vent: 'Internal Anti-Colic Vent System', Pack: '4 Glass Bottles (2x150ml + 2x270ml)', Nipple: 'Soft Silicone Level 1' },
    images: [
      { url: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Dr. Brown’s Options+ Glass Bottles Pack of 4' },
      { url: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Dr. Brown’s Green Internal Vent Tube Assembly' },
      { url: 'https://images.unsplash.com/photo-1544126592-807ade215a0b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Dr. Brown’s Clear Borosilicate Glass Wall Thickness' },
      { url: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Dr. Brown’s Silicone Nipple & Travel Caps' },
    ],
    variants: [
      { sku: 'PROD-BBY-010-SET', name: '4 Bottle Glass Set', price: 3599, mrp: 4499, stockQuantity: 25, attributes: { Pack: 'Set of 4' } }
    ]
  },
  {
    sku: 'PROD-BBY-011',
    name: 'Munchkin Miracle 360 Trainer Sippy Cup Set (2-Pack Non-Food)',
    slug: 'munchkin-miracle-360-sippy-cup-2-pack',
    description: 'Dentist-recommended 360-degree spoutless rim toddler cup that automatically seals when child stops drinking to eliminate spills completely.',
    brand: 'Munchkin',
    categorySlug: 'baby-products',
    subcategorySlug: 'feeding-care',
    modelNumber: 'MNC-10804',
    mrp: 1499,
    currentPrice: 1199,
    originalPrice: 1499,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.8,
    reviewCount: 780,
    tags: ['munchkin', 'miracle 360', 'sippy cup', 'spill proof cup', 'toddler cup'],
    specifications: { Capacity: '207ml (7 oz) per cup', Material: 'BPA-Free Plastic', Rim: '360-Degree Edge Drinks from Any Side', Cleaning: 'Top Rack Dishwasher Safe' },
    images: [
      { url: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Munchkin Miracle 360 Trainer Cups 2 Pack Blue Pink' },
      { url: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Munchkin 360 Silicone Valve Disassembled' },
      { url: 'https://images.unsplash.com/photo-1544126592-807ade215a0b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Munchkin Trainer Handles Easy Grip' },
      { url: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Munchkin Packaging Box' },
    ],
    variants: [
      { sku: 'PROD-BBY-011-BLUGPNK', name: 'Blue & Pink (Pack of 2)', price: 1199, mrp: 1499, stockQuantity: 20, attributes: { Color: 'Blue/Pink' } },
      { sku: 'PROD-BBY-011-GRNPUR', name: 'Green & Purple (Pack of 2)', price: 1199, mrp: 1499, stockQuantity: 20, attributes: { Color: 'Green/Purple' } },
    ]
  },
  {
    sku: 'PROD-BBY-012',
    name: 'UBBI Steel Diaper Pail Odor Locking Can',
    slug: 'ubbi-steel-diaper-pail-odor-locking',
    description: 'Award-winning diaper pail crafted from powder-coated steel with rubber seals to lock in odors without requiring proprietary refill bags.',
    brand: 'UBBI',
    categorySlug: 'baby-products',
    subcategorySlug: 'nursery-furniture',
    modelNumber: '10005',
    mrp: 8990,
    currentPrice: 7192,
    originalPrice: 8990,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 20,
    lowStockThreshold: 4,
    rating: 4.7,
    reviewCount: 390,
    tags: ['ubbi', 'diaper pail', 'odor locking pail', 'steel diaper bin', 'nursery bin'],
    specifications: { Material: 'Powder-Coated Steel', Bags: 'Uses Any Standard Trash Bag', Capacity: 'Holds Up to 55 Diapers', Safety: 'Childproof Safety Lock' },
    images: [
      { url: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'UBBI Powder Coated Steel White Diaper Pail' },
      { url: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'UBBI Sliding Lid Mechanism & Rubber Seal' },
      { url: 'https://images.unsplash.com/photo-1544126592-807ade215a0b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'UBBI Child Safety Lock Knob Top' },
      { url: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'UBBI Interior Steel Chamber Opened' },
    ],
    variants: [
      { sku: 'PROD-BBY-012-WHT', name: 'Matte White Steel', price: 7192, mrp: 8990, stockQuantity: 10, attributes: { Color: 'Matte White' } },
      { sku: 'PROD-BBY-012-GRY', name: 'Slate Grey Steel', price: 7192, mrp: 8990, stockQuantity: 10, attributes: { Color: 'Slate Grey' } },
    ]
  },
  {
    sku: 'PROD-BBY-013',
    name: 'Baby Brezza Formula Pro Advanced Automated Formula Dispenser (Non-Food Machine)',
    slug: 'baby-brezza-formula-pro-advanced',
    description: 'Automated machine that instantly mixes, heats, and dispenses warm formula bottles with perfect consistency in seconds at the touch of a button.',
    brand: 'Baby Brezza',
    categorySlug: 'baby-products',
    subcategorySlug: 'feeding-care',
    modelNumber: 'FRP0046',
    mrp: 24990,
    currentPrice: 21241,
    originalPrice: 24990,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 10,
    lowStockThreshold: 2,
    rating: 4.8,
    reviewCount: 310,
    tags: ['baby brezza', 'formula pro', 'formula maker', 'baby bottle maker', 'instant formula'],
    specifications: { Mixing: 'Patented Air-Tight Powder Container', Temperature: '3 Heat Settings (Body Temp, Warm, Room)', Ounces: '2 to 10 oz Dispensing', Tank: '1.5L Dishwasher Safe Water Tank' },
    images: [
      { url: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Baby Brezza Formula Pro Advanced Front View' },
      { url: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Baby Brezza Digital Control Panel & Ounce Selector' },
      { url: 'https://images.unsplash.com/photo-1544126592-807ade215a0b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Baby Brezza Airtight Powder Container Hopper' },
      { url: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Baby Brezza Adjustable Bottle Tray' },
    ],
    variants: [
      { sku: 'PROD-BBY-013-WHT', name: 'White & Black', price: 21241, mrp: 24990, stockQuantity: 10, attributes: { Color: 'White/Black' } }
    ]
  },
  {
    sku: 'PROD-BBY-014',
    name: 'BabyBjörn Bouncer Bliss 3D Jersey Ergonomic Rocker',
    slug: 'babybjorn-bouncer-bliss-3d-jersey',
    description: 'Natural rocking baby bouncer requiring no batteries. Provides proper ergonomic support for newborn head and back with super-soft 3D jersey fabric.',
    brand: 'BabyBjörn',
    categorySlug: 'baby-products',
    subcategorySlug: 'nursery-furniture',
    modelNumber: '006028',
    mrp: 19990,
    currentPrice: 16991,
    originalPrice: 19990,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 15,
    lowStockThreshold: 3,
    rating: 4.9,
    reviewCount: 420,
    tags: ['babybjorn', 'bouncer bliss', 'baby rocker', 'natural bouncer', '3d jersey bouncer'],
    specifications: { WeightRange: '3.5 kg to 13 kg', Positions: '3 Recline Positions (Play, Rest, Sleep)', Power: 'Self-Rocking (No Batteries/Plugs)', Fabric: 'Oeko-Tex Certified 3D Jersey' },
    images: [
      { url: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'BabyBjörn Bouncer Bliss 3D Jersey Light Grey' },
      { url: 'https://images.unsplash.com/photo-1544126592-807ade215a0b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'BabyBjörn 3D Jersey Fabric Weave Closeup' },
      { url: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'BabyBjörn Safety Harness Button Lock' },
      { url: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'BabyBjörn Flat Fold Storage Mechanism' },
    ],
    variants: [
      { sku: 'PROD-BBY-014-GRY', name: 'Light Grey 3D Jersey', price: 16991, mrp: 19990, stockQuantity: 10, attributes: { Color: 'Light Grey' } },
      { sku: 'PROD-BBY-014-CHAR', name: 'Charcoal 3D Jersey', price: 16991, mrp: 19990, stockQuantity: 5, attributes: { Color: 'Charcoal' } },
    ]
  },
  {
    sku: 'PROD-BBY-015',
    name: 'Frida Baby NoseFrida The Snotsucker Nasal Aspirator Kit',
    slug: 'frida-baby-nosefrida-nasal-aspirator-kit',
    description: 'Doctor-recommended hygienic nasal aspirator creating seal with outside of baby nostril for non-invasive gentle snot removal with disposable hygiene filters.',
    brand: 'Frida Baby',
    categorySlug: 'baby-products',
    subcategorySlug: 'feeding-care',
    modelNumber: 'FB-NF-01',
    mrp: 1999,
    currentPrice: 1599,
    originalPrice: 1999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.8,
    reviewCount: 890,
    tags: ['frida baby', 'nosefrida', 'snotsucker', 'nasal aspirator', 'baby health care'],
    specifications: { Includes: '1 NoseFrida Aspirator + 4 Disposable Hygiene Filters + Storage Case', Material: 'BPA & Phthalate Free Medical Plastic', Safety: '100% Hygienic Filter Protection' },
    images: [
      { url: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Frida Baby NoseFrida Aspirator Kit Packaging' },
      { url: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Frida NoseFrida Blue Tube & Mouthpiece Assembly' },
      { url: 'https://images.unsplash.com/photo-1544126592-807ade215a0b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Frida Hygiene Filter Insert Chamber' },
      { url: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Frida Protective Hard Storage Travel Case' },
    ],
    variants: [
      { sku: 'PROD-BBY-015-KIT', name: 'NoseFrida Kit + 4 Filters', price: 1599, mrp: 1999, stockQuantity: 40, attributes: { Pack: 'Kit' } }
    ]
  }
];
