import { ProductStatus } from '@prisma/client';

export const beautyProducts = [
  {
    sku: 'PROD-BTY-001',
    name: 'Dyson Airwrap Multi-Styler Complete Long',
    slug: 'dyson-airwrap-multi-styler-long',
    description: 'Revolutionary hair styling tool powered by Dyson digital motor V9 and Coanda airflow to curl, shape, smooth, and hide flyaways without extreme heat.',
    brand: 'Dyson',
    categorySlug: 'beauty-personal-care',
    subcategorySlug: 'haircare-styling-tools',
    modelNumber: '400718-01',
    mrp: 49900,
    currentPrice: 45900,
    originalPrice: 49900,
    discount: 8.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 15,
    lowStockThreshold: 3,
    rating: 4.8,
    reviewCount: 320,
    tags: ['dyson', 'airwrap', 'hair styler', 'dyson long', 'coanda airflow'],
    specifications: { Power: '1300W', Airflow: '13.5 l/s', HeatControl: 'Intelligent Heat Control (under 150°C)', Weight: '660g' },
    images: [
      { url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Dyson Airwrap Multi-Styler Nickel Copper Body' },
      { url: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Dyson Airwrap Airflow Coanda Barrel' },
      { url: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Dyson Airwrap Brush Attachments Set' },
      { url: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Dyson Prussian Blue Storage Case' },
    ],
    variants: [
      { sku: 'PROD-BTY-001-NC', name: 'Nickel & Copper', price: 45900, mrp: 49900, stockQuantity: 8, attributes: { Color: 'Nickel/Copper' } },
      { sku: 'PROD-BTY-001-PB', name: 'Prussian Blue & Rich Copper', price: 47900, mrp: 51900, stockQuantity: 7, attributes: { Color: 'Prussian Blue/Copper' } },
    ]
  },
  {
    sku: 'PROD-BTY-002',
    name: 'Philips Norelco Multigroom Series 9000 Trimmer',
    slug: 'philips-norelco-multigroom-9000',
    description: 'All-in-one precision grooming kit with DualCut self-sharpening blades, 21 attachments for face, head, and body, and 6-hour lithium-ion run time.',
    brand: 'Philips',
    categorySlug: 'beauty-personal-care',
    subcategorySlug: 'grooming-trimmers',
    modelNumber: 'MG7750/49',
    mrp: 6995,
    currentPrice: 5245,
    originalPrice: 6995,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 6,
    rating: 4.7,
    reviewCount: 450,
    tags: ['philips', 'trimmer', 'beard trimmer', 'bodygroom', 'multigroom 9000'],
    specifications: { BatteryLife: '6 Hours', Blades: 'DualCut Steel Blades', Waterproof: '100% Washable', GuardCount: '21 Attachments' },
    images: [
      { url: 'https://images.unsplash.com/photo-1621607512214-68297480165e?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Philips Norelco Multigroom 9000 Trimmer Body' },
      { url: 'https://images.unsplash.com/photo-1503236823255-94609f598e71?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Philips DualCut Steel Blade Head' },
      { url: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Philips Trimmer Guard Attachments Array' },
      { url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Philips Travel Pouch' },
    ],
    variants: [
      { sku: 'PROD-BTY-002-SIL', name: 'Stainless Steel Trim Kit', price: 5245, mrp: 6995, stockQuantity: 30, attributes: { Color: 'Stainless Steel' } }
    ]
  },
  {
    sku: 'PROD-BTY-003',
    name: 'Bleu de Chanel Eau de Parfum Spray 100ml',
    slug: 'bleu-de-chanel-eau-de-parfum-100ml',
    description: 'An aromatic woody fragrance for men with amber and musky notes. Crisp grapefruit citrus top notes leading to a cedar and New Caledonian sandalwood base.',
    brand: 'Chanel',
    categorySlug: 'beauty-personal-care',
    subcategorySlug: 'perfumes-fragrances',
    modelNumber: 'CHANEL-BDC-100',
    mrp: 16500,
    currentPrice: 14850,
    originalPrice: 16500,
    discount: 10.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 20,
    lowStockThreshold: 4,
    rating: 4.9,
    reviewCount: 380,
    tags: ['chanel', 'bleu de chanel', 'perfume', 'edp', 'luxury fragrance', 'men perfume'],
    specifications: { Volume: '100ml / 3.4 fl oz', FragranceFamily: 'Woody Aromatic', Concentration: 'Eau de Parfum', Origin: 'Made in France' },
    images: [
      { url: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Bleu de Chanel Eau de Parfum Bottle Front' },
      { url: 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Bleu de Chanel Glass Thickness & Atomizer' },
      { url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Bleu de Chanel Magnetic Cap Double C Logo' },
      { url: 'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Bleu de Chanel Dark Navy Packaging Box' },
    ],
    variants: [
      { sku: 'PROD-BTY-003-100', name: '100ml Spray Bottle', price: 14850, mrp: 16500, stockQuantity: 12, attributes: { Volume: '100ml' } },
      { sku: 'PROD-BTY-003-50', name: '50ml Spray Bottle', price: 10500, mrp: 11800, stockQuantity: 8, attributes: { Volume: '50ml' } },
    ]
  },
  {
    sku: 'PROD-BTY-004',
    name: 'La Roche-Posay Anthelios UVMune 400 Oil Control Fluid SPF50+',
    slug: 'la-roche-posay-anthelios-spf50-oil-control',
    description: 'Dermatologist-recommended ultra-high protection facial sunscreen with Mexoryl 400 filter protecting against ultra-long UVA rays. Matte 12h finish.',
    brand: 'La Roche-Posay',
    categorySlug: 'beauty-personal-care',
    subcategorySlug: 'skincare-sunscreen',
    modelNumber: 'LRP-ANT-50',
    mrp: 2490,
    currentPrice: 2116,
    originalPrice: 2490,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.9,
    reviewCount: 520,
    tags: ['la roche posay', 'anthelios', 'sunscreen', 'spf50', 'dermatologist recommended', 'oil control'],
    specifications: { Volume: '50ml', Protection: 'SPF 50+ PA++++', Finish: 'Matte Oil Control', SkinType: 'Sensitive & Oily' },
    images: [
      { url: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'La Roche-Posay Anthelios SPF50 Fluid Bottle' },
      { url: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'La Roche-Posay Texture Drop on Skin' },
      { url: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'La Roche-Posay Precision Nozzle Tip' },
      { url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'La Roche-Posay Dermatological Outer Box' },
    ],
    variants: [
      { sku: 'PROD-BTY-004-50', name: '50ml Bottle', price: 2116, mrp: 2490, stockQuantity: 40, attributes: { Volume: '50ml' } }
    ]
  },
  {
    sku: 'PROD-BTY-005',
    name: 'Estée Lauder Advanced Night Repair Synchronized Multi-Recovery Complex',
    slug: 'estee-lauder-advanced-night-repair-serum',
    description: 'Patented Chronolux Power Signal Technology serum that deep hydrates, reduces visible signs of aging, firms skin, and boosts natural collagen production.',
    brand: 'Estée Lauder',
    categorySlug: 'beauty-personal-care',
    subcategorySlug: 'skincare-sunscreen',
    modelNumber: 'EL-ANR-50',
    mrp: 10500,
    currentPrice: 8925,
    originalPrice: 10500,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 25,
    lowStockThreshold: 5,
    rating: 4.8,
    reviewCount: 410,
    tags: ['estee lauder', 'advanced night repair', 'serum', 'anti aging', 'hyaluronic acid'],
    specifications: { Volume: '50ml / 1.7 oz', KeyIngredient: 'Tripeptide-32 & Hyaluronic Acid', Formula: 'Oil-Free Non-Acnegenic', Use: 'AM & PM' },
    images: [
      { url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Estée Lauder Advanced Night Repair Brown Glass Bottle' },
      { url: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Estée Lauder Glass Pipette Dropper Liquid Drop' },
      { url: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Estée Lauder Golden Cap Detail' },
      { url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Estée Lauder Icon Box Packaging' },
    ],
    variants: [
      { sku: 'PROD-BTY-005-50', name: '50ml Dropper Bottle', price: 8925, mrp: 10500, stockQuantity: 15, attributes: { Volume: '50ml' } },
      { sku: 'PROD-BTY-005-30', name: '30ml Dropper Bottle', price: 5800, mrp: 6900, stockQuantity: 10, attributes: { Volume: '30ml' } },
    ]
  },
  {
    sku: 'PROD-BTY-006',
    name: 'CeraVe Hydrating Facial Cleanser for Normal to Dry Skin',
    slug: 'cerave-hydrating-facial-cleanser-473ml',
    description: 'Developed with dermatologists containing 3 essential ceramides (1, 3, 6-II) and hyaluronic acid to cleanse, hydrate and restore protective skin barrier.',
    brand: 'CeraVe',
    categorySlug: 'beauty-personal-care',
    subcategorySlug: 'skincare-sunscreen',
    modelNumber: 'CV-HFC-473',
    mrp: 1850,
    currentPrice: 1572,
    originalPrice: 1850,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 50,
    lowStockThreshold: 10,
    rating: 4.8,
    reviewCount: 680,
    tags: ['cerave', 'hydrating cleanser', 'ceramides', 'skincare', 'facewash'],
    specifications: { Volume: '473ml / 16 fl oz', KeyIngredients: 'Ceramides 1, 3, 6-II + Hyaluronic Acid', Texture: 'Non-foaming Lotion', Formula: 'Fragrance Free' },
    images: [
      { url: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'CeraVe Hydrating Cleanser 473ml Pump Bottle' },
      { url: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'CeraVe Dispenser Pump Lock Mechanism' },
      { url: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'CeraVe Creamy Lotion Texture Spread' },
      { url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'CeraVe Rear Ingredients Label' },
    ],
    variants: [
      { sku: 'PROD-BTY-006-473', name: '473ml Pump Bottle', price: 1572, mrp: 1850, stockQuantity: 30, attributes: { Volume: '473ml' } },
      { sku: 'PROD-BTY-006-236', name: '236ml Bottle', price: 999, mrp: 1199, stockQuantity: 20, attributes: { Volume: '236ml' } },
    ]
  },
  {
    sku: 'PROD-BTY-007',
    name: 'Kérastase Elixir Ultime L’Huile Originale Hair Oil',
    slug: 'kerastase-elixir-ultime-hair-oil',
    description: 'Iconic beautifying hair oil infused with Sacred Marula Oil, Camellia Oil, and Argan Oil providing deep nourishment, 230°C heat protection, and 96h frizz control.',
    brand: 'Kérastase',
    categorySlug: 'beauty-personal-care',
    subcategorySlug: 'haircare-styling-tools',
    modelNumber: 'KER-EU-100',
    mrp: 4400,
    currentPrice: 3960,
    originalPrice: 4400,
    discount: 10.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 25,
    lowStockThreshold: 5,
    rating: 4.9,
    reviewCount: 290,
    tags: ['kerastase', 'hair oil', 'elixir ultime', 'argan oil', 'frizz control'],
    specifications: { Volume: '100ml', HeatProtection: 'Up to 230°C', KeyOils: 'Marula, Camellia, Argan', HairType: 'All Hair Types' },
    images: [
      { url: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Kérastase Elixir Ultime Golden Glass Bottle' },
      { url: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Kérastase Golden Oil Drop Texture' },
      { url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Kérastase Pump Nozzle Close' },
      { url: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Kérastase Gold Foil Box' },
    ],
    variants: [
      { sku: 'PROD-BTY-007-100', name: '100ml Glass Bottle', price: 3960, mrp: 4400, stockQuantity: 25, attributes: { Volume: '100ml' } }
    ]
  },
  {
    sku: 'PROD-BTY-008',
    name: 'Dior Sauvage Eau de Parfum Spray 100ml',
    slug: 'dior-sauvage-eau-de-parfum-100ml',
    description: 'Sensual and mysterious fragrance inspired by the desert at twilight. Calabrian Bergamot top notes combined with Papua New Guinean Vanilla absolute.',
    brand: 'Dior',
    categorySlug: 'beauty-personal-care',
    subcategorySlug: 'perfumes-fragrances',
    modelNumber: 'CD-SVG-100',
    mrp: 17500,
    currentPrice: 15750,
    originalPrice: 17500,
    discount: 10.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 18,
    lowStockThreshold: 4,
    rating: 4.9,
    reviewCount: 460,
    tags: ['dior', 'sauvage', 'dior sauvage', 'perfume', 'edp', 'luxury perfume'],
    specifications: { Volume: '100ml / 3.4 oz', Concentration: 'Eau de Parfum', KeyNotes: 'Calabrian Bergamot, Sichuan Pepper, Vanilla', MadeIn: 'France' },
    images: [
      { url: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Dior Sauvage Eau de Parfum Dark Gradient Bottle' },
      { url: 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Dior Sauvage Atomizer Spray Mist' },
      { url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Dior Sauvage CD Engraved Magnetic Cap' },
      { url: 'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Dior Sauvage Midnight Blue Box' },
    ],
    variants: [
      { sku: 'PROD-BTY-008-100', name: '100ml Spray Bottle', price: 15750, mrp: 17500, stockQuantity: 10, attributes: { Volume: '100ml' } },
      { sku: 'PROD-BTY-008-60', name: '60ml Spray Bottle', price: 11500, mrp: 12800, stockQuantity: 8, attributes: { Volume: '60ml' } },
    ]
  },
  {
    sku: 'PROD-BTY-009',
    name: 'Braun Series 9 Pro Electric Shaver for Men',
    slug: 'braun-series-9-pro-electric-shaver',
    description: 'World’s most efficient electric shaver with 5 shaving elements, ProLift trimmer for 1, 3 or 7-day beards, Sonic Technology (40,000 cross-cutting actions/min), and PowerCase charging.',
    brand: 'Braun',
    categorySlug: 'beauty-personal-care',
    subcategorySlug: 'grooming-trimmers',
    modelNumber: '9477cc',
    mrp: 39999,
    currentPrice: 33999,
    originalPrice: 39999,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 10,
    lowStockThreshold: 2,
    rating: 4.8,
    reviewCount: 160,
    tags: ['braun', 'series 9 pro', 'electric shaver', 'foil shaver', 'wet dry shaver'],
    specifications: { CuttingElements: '5 Shaving Elements', Technology: 'Sonic 40,000 cutting actions/min', Waterproof: '100% Wet & Dry', PowerCase: 'Includes Portable Charge Case' },
    images: [
      { url: 'https://images.unsplash.com/photo-1621607512214-68297480165e?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Braun Series 9 Pro Shaver Front View' },
      { url: 'https://images.unsplash.com/photo-1503236823255-94609f598e71?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Braun Series 9 Pro 5-Element Shaving Head' },
      { url: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Braun PowerCase Battery Charging Dock' },
      { url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Braun Clean & Charge Station' },
    ],
    variants: [
      { sku: 'PROD-BTY-009-SLV', name: 'Silver with PowerCase', price: 33999, mrp: 39999, stockQuantity: 10, attributes: { Color: 'Silver' } }
    ]
  },
  {
    sku: 'PROD-BTY-010',
    name: 'Minimalist 10% Niacinamide Face Serum with Zinc',
    slug: 'minimalist-10-niacinamide-face-serum',
    description: 'Nourishing daily serum formulated with 10% pure Niacinamide and 1% Zinc PCA to reduce acne marks, control sebum production, and enhance skin barrier function.',
    brand: 'Minimalist',
    categorySlug: 'beauty-personal-care',
    subcategorySlug: 'skincare-sunscreen',
    modelNumber: 'MIN-NIA-30',
    mrp: 599,
    currentPrice: 539,
    originalPrice: 599,
    discount: 10.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 60,
    lowStockThreshold: 12,
    rating: 4.6,
    reviewCount: 780,
    tags: ['minimalist', 'niacinamide', 'acne serum', 'zinc', 'blemish care'],
    specifications: { Volume: '30ml', ActiveIngredients: '10% Niacinamide + 1% Zinc PCA', pH: '5.5 - 6.5', SuitableFor: 'All Skin Types' },
    images: [
      { url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Minimalist 10% Niacinamide Dropper Bottle' },
      { url: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Minimalist Glass Pipette Serum Drop' },
      { url: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Minimalist White Minimal Label Detail' },
      { url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Minimalist Eco Carton Outer Box' },
    ],
    variants: [
      { sku: 'PROD-BTY-010-30', name: '30ml Glass Bottle', price: 539, mrp: 599, stockQuantity: 60, attributes: { Volume: '30ml' } }
    ]
  },
  {
    sku: 'PROD-BTY-011',
    name: 'Ghd Platinum+ Styler Professional Smart Hair Straightener',
    slug: 'ghd-platinum-plus-smart-straightener',
    description: 'Smart styler featuring Ultra-zone predictive technology that senses hair thickness and speed to maintain optimum 185°C styling temperature for 70% stronger hair.',
    brand: 'Ghd',
    categorySlug: 'beauty-personal-care',
    subcategorySlug: 'haircare-styling-tools',
    modelNumber: 'GHD-PLT-BLK',
    mrp: 23500,
    currentPrice: 19975,
    originalPrice: 23500,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 12,
    lowStockThreshold: 3,
    rating: 4.8,
    reviewCount: 210,
    tags: ['ghd', 'hair straightener', 'platinum plus', 'smart styler', 'ghd styler'],
    specifications: { Temperature: 'Optimum 185°C Constant', Technology: 'Ultra-zone Predictive', CableLength: '2.7m Swivel Cord', AutoSleep: 'After 30 mins' },
    images: [
      { url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Ghd Platinum+ Styler Matte Black Body' },
      { url: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Ghd Precision Milled Floating Ceramic Plates' },
      { url: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Ghd Wishbone Hinge & Power Button' },
      { url: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Ghd Heat Resistant Plate Guard' },
    ],
    variants: [
      { sku: 'PROD-BTY-011-BLK', name: 'Black Styler', price: 19975, mrp: 23500, stockQuantity: 6, attributes: { Color: 'Black' } },
      { sku: 'PROD-BTY-011-WHT', name: 'White Styler', price: 19975, mrp: 23500, stockQuantity: 6, attributes: { Color: 'White' } },
    ]
  },
  {
    sku: 'PROD-BTY-012',
    name: 'Yves Saint Laurent Black Opium Eau de Parfum 90ml',
    slug: 'ysl-black-opium-eau-de-parfum-90ml',
    description: 'Addictive gourmand floral fragrance dominated by black coffee, white flowers, and sweet vanilla. Edgy black glitter bottle.',
    brand: 'Yves Saint Laurent',
    categorySlug: 'beauty-personal-care',
    subcategorySlug: 'perfumes-fragrances',
    modelNumber: 'YSL-BO-90',
    mrp: 14500,
    currentPrice: 13050,
    originalPrice: 14500,
    discount: 10.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 18,
    lowStockThreshold: 4,
    rating: 4.9,
    reviewCount: 390,
    tags: ['ysl', 'black opium', 'perfume', 'women perfume', 'coffee vanilla fragrance'],
    specifications: { Volume: '90ml / 3.0 fl oz', FragranceFamily: 'Warm & Spicy Gourmand', KeyNotes: 'Black Coffee, White Flowers, Vanilla', MadeIn: 'France' },
    images: [
      { url: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'YSL Black Opium Glitter Bottle Front' },
      { url: 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'YSL Black Opium Circular Pink Window Close' },
      { url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'YSL Spray Atomizer Cap' },
      { url: 'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'YSL Black Shimmer Packaging Box' },
    ],
    variants: [
      { sku: 'PROD-BTY-012-90', name: '90ml Spray Bottle', price: 13050, mrp: 14500, stockQuantity: 10, attributes: { Volume: '90ml' } },
      { sku: 'PROD-BTY-012-50', name: '50ml Spray Bottle', price: 9200, mrp: 10500, stockQuantity: 8, attributes: { Volume: '50ml' } },
    ]
  },
  {
    sku: 'PROD-BTY-013',
    name: 'Laneige Lip Sleeping Mask Berry 20g',
    slug: 'laneige-lip-sleeping-mask-berry-20g',
    description: 'Leave-on lip mask that soothes and moisturizes flaky lips overnight with Berry Mix Complex vitamin C and antioxidant Moisture Wrap technology.',
    brand: 'Laneige',
    categorySlug: 'beauty-personal-care',
    subcategorySlug: 'skincare-sunscreen',
    modelNumber: 'LN-LSM-20',
    mrp: 1600,
    currentPrice: 1360,
    originalPrice: 1600,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 45,
    lowStockThreshold: 9,
    rating: 4.8,
    reviewCount: 620,
    tags: ['laneige', 'lip sleeping mask', 'berry lip mask', 'k-beauty', 'lip balm'],
    specifications: { NetWeight: '20g / 0.70 oz', Flavor: 'Sweet Berry', KeyIngredients: 'Berry Mix Complex + Vitamin C', Includes: 'Silicone Applicator Spatula' },
    images: [
      { url: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Laneige Lip Sleeping Mask Berry Pink Jar' },
      { url: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Laneige Pink Lip Mask Balm Swatch Texture' },
      { url: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Laneige Silicone Wand Applicator Tool' },
      { url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Laneige Outer Box Packaging' },
    ],
    variants: [
      { sku: 'PROD-BTY-013-BER', name: '20g Berry Flavor', price: 1360, mrp: 1600, stockQuantity: 25, attributes: { Flavor: 'Berry' } },
      { sku: 'PROD-BTY-013-GLM', name: '20g Gummy Bear Flavor', price: 1360, mrp: 1600, stockQuantity: 20, attributes: { Flavor: 'Gummy Bear' } },
    ]
  },
  {
    sku: 'PROD-BTY-014',
    name: 'Olaplex No.3 Hair Perfector Repairing Treatment',
    slug: 'olaplex-no3-hair-perfector-100ml',
    description: 'Concentrated weekly pre-shampoo treatment that repairs broken disulfide hair bonds caused by chemical bleaching, heat styling, and environmental stress.',
    brand: 'Olaplex',
    categorySlug: 'beauty-personal-care',
    subcategorySlug: 'haircare-styling-tools',
    modelNumber: 'OLP-NO3-100',
    mrp: 3200,
    currentPrice: 2880,
    originalPrice: 3200,
    discount: 10.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 6,
    rating: 4.8,
    reviewCount: 510,
    tags: ['olaplex', 'no 3', 'hair perfector', 'bond builder', 'damaged hair repair'],
    specifications: { Volume: '100ml', ActiveTech: 'Bis-Aminopropyl Diglycol Dimaleate', pH: '3.5 - 5.0', Use: 'Pre-Shampoo Treatment' },
    images: [
      { url: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Olaplex No.3 Hair Perfector Bottle Front' },
      { url: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Olaplex Creamy Lotion Treatment Texture' },
      { url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Olaplex Cap Seal & Dispenser Tip' },
      { url: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Olaplex Bottle Rear Instructions' },
    ],
    variants: [
      { sku: 'PROD-BTY-014-100', name: '100ml Bottle', price: 2880, mrp: 3200, stockQuantity: 30, attributes: { Volume: '100ml' } }
    ]
  },
  {
    sku: 'PROD-BTY-015',
    name: 'Panasonic Arc5 5-Blade Electric Shaver',
    slug: 'panasonic-arc5-5-blade-shaver',
    description: 'Japanese 5-blade shaving system with 30-degree nano-polished blades, 14,000 cpm ultra-fast linear motor drive, and active shaving sensor.',
    brand: 'Panasonic',
    categorySlug: 'beauty-personal-care',
    subcategorySlug: 'grooming-trimmers',
    modelNumber: 'ES-LV65-S',
    mrp: 18990,
    currentPrice: 15192,
    originalPrice: 18990,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 15,
    lowStockThreshold: 3,
    rating: 4.7,
    reviewCount: 140,
    tags: ['panasonic', 'arc5', 'electric shaver', '5 blade shaver', 'linear motor'],
    specifications: { MotorSpeed: '14,000 cpm Linear Motor', Blades: '5 Ultra-Thin Nanotech Blades', Display: '10-Stage LED Battery Status', Waterproof: 'Wet & Dry' },
    images: [
      { url: 'https://images.unsplash.com/photo-1621607512214-68297480165e?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Panasonic Arc5 Shaver Body Profile' },
      { url: 'https://images.unsplash.com/photo-1503236823255-94609f598e71?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Panasonic 5-Blade Multi-Flex Pivot Foil Head' },
      { url: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Panasonic Pop-Up Precision Trimmer Blade' },
      { url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Panasonic Travel Lock LED Display Panel' },
    ],
    variants: [
      { sku: 'PROD-BTY-015-SLV', name: 'Black & Silver Metallic', price: 15192, mrp: 18990, stockQuantity: 15, attributes: { Color: 'Silver Metallic' } }
    ]
  }
];
