import { ProductStatus } from '@prisma/client';

export const booksStationeryProducts = [
  {
    sku: 'PROD-BKS-001',
    name: 'Atomic Habits by James Clear (Hardcover Collector Edition)',
    slug: 'atomic-habits-hardcover-collector-edition',
    description: 'The #1 New York Times bestseller offering a proven framework for improving every day. Hardcover edition with custom ribbon marker and foil stamping.',
    brand: 'Penguin Random House',
    categorySlug: 'books-stationery',
    subcategorySlug: 'fiction-non-fiction-books',
    modelNumber: 'ISBN-9780735211292',
    mrp: 999,
    currentPrice: 699,
    originalPrice: 999,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 50,
    lowStockThreshold: 10,
    rating: 4.9,
    reviewCount: 1540,
    tags: ['books', 'atomic habits', 'james clear', 'self-help', 'hardcover book', 'bestseller'],
    specifications: { Format: 'Hardcover', Pages: '320 Pages', Publisher: 'Avery / Penguin', Language: 'English' },
    images: [
      { url: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Atomic Habits Hardcover Book Cover Front' },
      { url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Atomic Habits Open Pages Typography' },
      { url: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Atomic Habits Hardcover Spine Foil Emboss' },
      { url: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Atomic Habits Ribbon Bookmark Detail' },
    ],
    variants: [
      { sku: 'PROD-BKS-001-HC', name: 'Hardcover Deluxe Edition', price: 699, mrp: 999, stockQuantity: 30, attributes: { Binding: 'Hardcover' } },
      { sku: 'PROD-BKS-001-PB', name: 'Paperback Edition', price: 499, mrp: 799, stockQuantity: 20, attributes: { Binding: 'Paperback' } },
    ]
  },
  {
    sku: 'PROD-BKS-002',
    name: 'Moleskine Classic Hardcover Notebook Large Dotted',
    slug: 'moleskine-classic-hardcover-dotted-notebook',
    description: 'Iconic Italian hard cover notebook featuring ivory 70 gsm acid-free paper, expandable inner pocket, elastic closure band, and ribbon bookmark.',
    brand: 'Moleskine',
    categorySlug: 'books-stationery',
    subcategorySlug: 'notebooks-journals',
    modelNumber: 'QP062',
    mrp: 2495,
    currentPrice: 1996,
    originalPrice: 2495,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 6,
    rating: 4.8,
    reviewCount: 420,
    tags: ['moleskine', 'notebook', 'dotted journal', 'hardcover journal', 'stationery'],
    specifications: { Size: 'Large (13 x 21 cm)', Layout: 'Dotted Grid', Pages: '240 Pages', PaperWeight: '70 gsm Acid-Free' },
    images: [
      { url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Moleskine Black Dotted Notebook Closed Front' },
      { url: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Moleskine Dotted Ivory Pages Spread Open' },
      { url: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Moleskine Back Expandable Pocket Detail' },
      { url: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Moleskine Elastic Band & Ribbon Marker' },
    ],
    variants: [
      { sku: 'PROD-BKS-002-BLK', name: 'Black Hardcover / Dotted', price: 1996, mrp: 2495, stockQuantity: 15, attributes: { Color: 'Black' } },
      { sku: 'PROD-BKS-002-BLU', name: 'Sapphire Blue Hardcover / Dotted', price: 1996, mrp: 2495, stockQuantity: 15, attributes: { Color: 'Sapphire Blue' } },
    ]
  },
  {
    sku: 'PROD-BKS-003',
    name: 'Lamy Safari Charcoal Fine Nib Fountain Pen',
    slug: 'lamy-safari-charcoal-fountain-pen',
    description: 'Timeless German ergonomic design crafted from sturdy ABS plastic with matte charcoal finish, black chromium-plated steel nib, and flexible metal clip.',
    brand: 'Lamy',
    categorySlug: 'books-stationery',
    subcategorySlug: 'pens-desk-supplies',
    modelNumber: 'LAM-4000858',
    mrp: 3200,
    currentPrice: 2720,
    originalPrice: 3200,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 25,
    lowStockThreshold: 5,
    rating: 4.9,
    reviewCount: 380,
    tags: ['lamy', 'lamy safari', 'fountain pen', 'fine nib', 'german stationery'],
    specifications: { NibSize: 'Fine (F) Black Steel', Body: 'Matte ABS Plastic', InkMechanism: 'Cartridge / Converter Z28', Origin: 'Made in Germany' },
    images: [
      { url: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Lamy Safari Charcoal Fountain Pen Profile' },
      { url: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Lamy Black Steel Fine Nib Closeup' },
      { url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Lamy Triangular Grip Section & Ink Window' },
      { url: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Lamy Metal Wire Clip Cap Detail' },
    ],
    variants: [
      { sku: 'PROD-BKS-003-FINE', name: 'Fine Nib (F) / Charcoal', price: 2720, mrp: 3200, stockQuantity: 15, attributes: { Nib: 'Fine' } },
      { sku: 'PROD-BKS-003-MED', name: 'Medium Nib (M) / Charcoal', price: 2720, mrp: 3200, stockQuantity: 10, attributes: { Nib: 'Medium' } },
    ]
  },
  {
    sku: 'PROD-BKS-004',
    name: 'Parker Jotter Stainless Steel Gold Trim Ballpoint Pen',
    slug: 'parker-jotter-stainless-steel-gold-ballpoint',
    description: 'Iconic click-action ballpoint pen with polished stainless steel barrel, 23k gold plated arrow clip, and smooth Quinkflow ink refilling system.',
    brand: 'Parker',
    categorySlug: 'books-stationery',
    subcategorySlug: 'pens-desk-supplies',
    modelNumber: 'PAR-JOT-GT',
    mrp: 999,
    currentPrice: 799,
    originalPrice: 999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.8,
    reviewCount: 610,
    tags: ['parker', 'jotter', 'ballpoint pen', 'gold trim pen', 'gift pen'],
    specifications: { Mechanism: 'Retractable Click Button', Material: 'Stainless Steel with 23k Gold Plating', InkColor: 'Blue Medium Refill', Packaging: 'Parker Gift Box' },
    images: [
      { url: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Parker Jotter Stainless Gold Trim Pen' },
      { url: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Parker Gold Arrow Clip Closeup' },
      { url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Parker Click Button Engraving' },
      { url: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Parker Premium Gift Presentation Box' },
    ],
    variants: [
      { sku: 'PROD-BKS-004-GT', name: 'Stainless Steel Gold Trim', price: 799, mrp: 999, stockQuantity: 25, attributes: { Trim: 'Gold Trim' } },
      { sku: 'PROD-BKS-004-CT', name: 'Stainless Steel Chrome Trim', price: 699, mrp: 899, stockQuantity: 15, attributes: { Trim: 'Chrome Trim' } },
    ]
  },
  {
    sku: 'PROD-BKS-005',
    name: 'Sapiens: A Brief History of Humankind by Yuval Noah Harari',
    slug: 'sapiens-brief-history-of-humankind-harari',
    description: 'Bestselling exploration of human history from the Stone Age to the Silicon Age detailing cognitive, agricultural, and scientific revolutions.',
    brand: 'HarperCollins',
    categorySlug: 'books-stationery',
    subcategorySlug: 'fiction-non-fiction-books',
    modelNumber: 'ISBN-9780062316097',
    mrp: 599,
    currentPrice: 419,
    originalPrice: 599,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 45,
    lowStockThreshold: 9,
    rating: 4.8,
    reviewCount: 1250,
    tags: ['sapiens', 'yuval noah harari', 'history book', 'non fiction', 'bestseller book'],
    specifications: { Format: 'Paperback', Pages: '464 Pages', Publisher: 'Harper', Language: 'English' },
    images: [
      { url: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Sapiens Harari Paperback Book Cover' },
      { url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Sapiens Inner Chapter Illustrations' },
      { url: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Sapiens Back Cover Blurbs' },
      { url: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Sapiens Book Spine View' },
    ],
    variants: [
      { sku: 'PROD-BKS-005-PB', name: 'Paperback Edition', price: 419, mrp: 599, stockQuantity: 45, attributes: { Binding: 'Paperback' } }
    ]
  },
  {
    sku: 'PROD-BKS-006',
    name: 'Paperkraft Premium Hardcover Notebook 250 GSM Unruled',
    slug: 'paperkraft-premium-hardcover-notebook',
    description: 'Luxury artist journal featuring thick 250 GSM ultra-white virgin pulp paper ideal for fountain pens, watercoloring, gouache, and sketching.',
    brand: 'Paperkraft',
    categorySlug: 'books-stationery',
    subcategorySlug: 'notebooks-journals',
    modelNumber: 'PK-ART-250',
    mrp: 999,
    currentPrice: 799,
    originalPrice: 999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 6,
    rating: 4.7,
    reviewCount: 190,
    tags: ['paperkraft', 'art journal', '250 gsm paper', 'watercolor notebook', 'sketchbook'],
    specifications: { PaperWeight: '250 GSM Thick Paper', Size: 'A5 (14.8 x 21 cm)', Pages: '120 Pages (60 Sheets)', Binding: 'Lay-Flat Thread Bound' },
    images: [
      { url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Paperkraft Hardcover Journal Cover Front' },
      { url: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Paperkraft Thick 250 GSM Blank Page Open' },
      { url: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Paperkraft 180 Degree Lay Flat Binding' },
      { url: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Paperkraft PU Leatherette Texture' },
    ],
    variants: [
      { sku: 'PROD-BKS-006-A5', name: 'A5 Unruled / Black Leatherette', price: 799, mrp: 999, stockQuantity: 15, attributes: { Size: 'A5' } },
      { sku: 'PROD-BKS-006-BRN', name: 'A5 Unruled / Tan Leatherette', price: 799, mrp: 999, stockQuantity: 15, attributes: { Size: 'A5' } },
    ]
  },
  {
    sku: 'PROD-BKS-007',
    name: 'PILOT G2 Premium Gel Rollerball Pens (Pack of 5)',
    slug: 'pilot-g2-gel-pens-pack-of-5',
    description: 'America’s #1 selling gel pen featuring smooth writing dynamic gel ink, comfortable rubber grip, and durable retractable click top.',
    brand: 'PILOT',
    categorySlug: 'books-stationery',
    subcategorySlug: 'pens-desk-supplies',
    modelNumber: 'G2-07-PK5',
    mrp: 650,
    currentPrice: 520,
    originalPrice: 650,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 50,
    lowStockThreshold: 10,
    rating: 4.9,
    reviewCount: 780,
    tags: ['pilot', 'pilot g2', 'gel pen', 'rollerball pen', 'black gel pens'],
    specifications: { PointSize: '0.7mm Fine Point', InkType: 'Water Resistant Archival Gel', Pack: '5 Pens', Feature: 'Refillable' },
    images: [
      { url: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Pilot G2 Gel Pens Pack of 5 Array' },
      { url: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Pilot G2 Rubber Contour Grip Close' },
      { url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Pilot G2 Clear Barrel Gel Level Window' },
      { url: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Pilot G2 Writing Stroke Specimen' },
    ],
    variants: [
      { sku: 'PROD-BKS-007-BLK', name: 'Black Ink 0.7mm (Pack of 5)', price: 520, mrp: 650, stockQuantity: 30, attributes: { Color: 'Black Ink' } },
      { sku: 'PROD-BKS-007-BLU', name: 'Blue Ink 0.7mm (Pack of 5)', price: 520, mrp: 650, stockQuantity: 20, attributes: { Color: 'Blue Ink' } },
    ]
  },
  {
    sku: 'PROD-BKS-008',
    name: 'The Psychology of Money by Morgan Housel',
    slug: 'the-psychology-of-money-morgan-housel',
    description: 'Timeless lessons on wealth, greed, and happiness exploring 19 short stories detailing how people think about money and decision making.',
    brand: 'Harriman House',
    categorySlug: 'books-stationery',
    subcategorySlug: 'fiction-non-fiction-books',
    modelNumber: 'ISBN-9780857197689',
    mrp: 399,
    currentPrice: 279,
    originalPrice: 399,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 60,
    lowStockThreshold: 12,
    rating: 4.8,
    reviewCount: 1980,
    tags: ['psychology of money', 'morgan housel', 'finance book', 'investing', 'bestseller'],
    specifications: { Format: 'Paperback', Pages: '252 Pages', Publisher: 'Harriman House', Language: 'English' },
    images: [
      { url: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'The Psychology of Money Paperback Cover' },
      { url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Psychology of Money Table of Contents' },
      { url: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Psychology of Money Back Cover Quotes' },
      { url: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Psychology of Money Spine View' },
    ],
    variants: [
      { sku: 'PROD-BKS-008-PB', name: 'Paperback Edition', price: 279, mrp: 399, stockQuantity: 60, attributes: { Binding: 'Paperback' } }
    ]
  },
  {
    sku: 'PROD-BKS-009',
    name: 'Midori MD Notebook A5 Grid Paper Made in Japan',
    slug: 'midori-md-notebook-a5-grid',
    description: 'Minimalist Japanese notebook designed strictly for comfort writing featuring MD Paper that resists feathering and bleed-through, with glassine paper jacket.',
    brand: 'Midori',
    categorySlug: 'books-stationery',
    subcategorySlug: 'notebooks-journals',
    modelNumber: 'MID-15288006',
    mrp: 1499,
    currentPrice: 1274,
    originalPrice: 1499,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 25,
    lowStockThreshold: 5,
    rating: 4.9,
    reviewCount: 230,
    tags: ['midori', 'md notebook', 'japanese stationery', 'grid notebook', 'fountain pen paper'],
    specifications: { Size: 'A5 (210 x 148 mm)', Layout: '5mm Grid', Pages: '176 Pages', Origin: 'Made in Japan' },
    images: [
      { url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Midori MD A5 Notebook Glassine Jacket Cover' },
      { url: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Midori 5mm Cyan Grid Pages Spread Open' },
      { url: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Midori Exposed Cheesecloth Thread Spine' },
      { url: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Midori Index Sticker Sheet Included' },
    ],
    variants: [
      { sku: 'PROD-BKS-009-GRID', name: 'A5 / 5mm Grid', price: 1274, mrp: 1499, stockQuantity: 15, attributes: { Layout: 'Grid' } },
      { sku: 'PROD-BKS-009-RULE', name: 'A5 / Lined Ruled', price: 1274, mrp: 1499, stockQuantity: 10, attributes: { Layout: 'Lined' } },
    ]
  },
  {
    sku: 'PROD-BKS-010',
    name: 'Faber-Castell Pitt Artist Pen Dual Marker Set (Pack of 12)',
    slug: 'faber-castell-pitt-artist-pen-set-12',
    description: 'Professional Indian ink markers combining flexible brush nib for fine lines and broad strokes with lightfast, waterproof, odorless ink.',
    brand: 'Faber-Castell',
    categorySlug: 'books-stationery',
    subcategorySlug: 'pens-desk-supplies',
    modelNumber: 'FC-167150',
    mrp: 2999,
    currentPrice: 2399,
    originalPrice: 2999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 20,
    lowStockThreshold: 4,
    rating: 4.8,
    reviewCount: 310,
    tags: ['faber castell', 'pitt artist pen', 'brush markers', 'calligraphy pens', 'indian ink'],
    specifications: { Ink: 'Pigmented Indian Ink', Lightfastness: 'Maximum Highest Lightfastness', Pack: '12 Assorted Colors', Nib: 'Flexible Brush Nib' },
    images: [
      { url: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Faber-Castell Pitt Artist Pen 12 Set Wallet' },
      { url: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Faber-Castell Flexible Brush Tip Swatch' },
      { url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Faber-Castell Color Barrel Caps' },
      { url: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Faber-Castell Plastic Storage Case' },
    ],
    variants: [
      { sku: 'PROD-BKS-010-12', name: 'Set of 12 Assorted Colors', price: 2399, mrp: 2999, stockQuantity: 20, attributes: { Pack: '12 Colors' } }
    ]
  },
  {
    sku: 'PROD-BKS-011',
    name: 'Dune Deluxe Edition Hardcover by Frank Herbert',
    slug: 'dune-deluxe-edition-hardcover-frank-herbert',
    description: 'Stunning collector’s hardcover edition of sci-fi masterpiece Dune featuring gold foil stamped cloth cover, stained edges, endpaper map, and introduction.',
    brand: 'Penguin Ace',
    categorySlug: 'books-stationery',
    subcategorySlug: 'fiction-non-fiction-books',
    modelNumber: 'ISBN-9780593099971',
    mrp: 1999,
    currentPrice: 1599,
    originalPrice: 1999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 25,
    lowStockThreshold: 5,
    rating: 4.9,
    reviewCount: 650,
    tags: ['dune', 'frank herbert', 'sci fi book', 'deluxe edition', 'hardcover collector'],
    specifications: { Format: 'Hardcover Deluxe', Pages: '688 Pages', Features: 'Stained Edges + Map', Publisher: 'Ace Hardcover' },
    images: [
      { url: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Dune Deluxe Hardcover Blue Cloth Gold Foil Cover' },
      { url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Dune Arrakis Map Illustrated Endpapers' },
      { url: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Dune Stained Blue Page Edges' },
      { url: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Dune Book Spine Gold Stamping' },
    ],
    variants: [
      { sku: 'PROD-BKS-011-HC', name: 'Hardcover Collector Edition', price: 1599, mrp: 1999, stockQuantity: 25, attributes: { Binding: 'Hardcover' } }
    ]
  },
  {
    sku: 'PROD-BKS-012',
    name: 'Kokuyo Campus Twin Ring Notebook A5 Grid (Pack of 5)',
    slug: 'kokuyo-campus-twin-ring-notebook-a5-pack-5',
    description: 'Japanese high-efficiency spiral notebooks featuring silky smooth 70 gsm paper with smart dot grid ruling and flexible plastic covers.',
    brand: 'Kokuyo',
    categorySlug: 'books-stationery',
    subcategorySlug: 'notebooks-journals',
    modelNumber: 'KOK-CMP-5P',
    mrp: 999,
    currentPrice: 799,
    originalPrice: 999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.8,
    reviewCount: 410,
    tags: ['kokuyo', 'campus notebook', 'spiral notebook', 'japanese paper', 'stationery set'],
    specifications: { Size: 'A5', Sheets: '50 Sheets per notebook', Pack: '5 Notebooks (Pastel Colors)', Ruling: '6mm Dotted Lines' },
    images: [
      { url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Kokuyo Campus Pastel Notebooks 5 Pack Stack' },
      { url: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Kokuyo Dotted Line Smooth Paper Open' },
      { url: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Kokuyo Twin Ring Wire Binding Close' },
      { url: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Kokuyo Header Date Title Bar' },
    ],
    variants: [
      { sku: 'PROD-BKS-012-5P', name: 'Pastel Pack of 5 Notebooks', price: 799, mrp: 999, stockQuantity: 40, attributes: { Pack: 'Set of 5' } }
    ]
  },
  {
    sku: 'PROD-BKS-013',
    name: 'Uni-ball One Gel Pen 0.5mm (Pack of 8 Colors)',
    slug: 'uniball-one-gel-pen-0-5mm-8-pack',
    description: 'Japanese innovative gel pen formulated with bead pack pigment ink that stays on top of paper fibers for ultra-vivid dark lines.',
    brand: 'Uni-ball',
    categorySlug: 'books-stationery',
    subcategorySlug: 'pens-desk-supplies',
    modelNumber: 'UMN-S-05-8C',
    mrp: 1200,
    currentPrice: 960,
    originalPrice: 1200,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 6,
    rating: 4.8,
    reviewCount: 340,
    tags: ['uni ball', 'uni ball one', 'gel pen set', 'vivid gel pen', 'japanese pens'],
    specifications: { TipSize: '0.5mm', InkTech: 'One Pigment Ink', Pack: '8 Colors Assorted', Clip: 'Wire Pocket Clip' },
    images: [
      { url: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Uni-ball One 8-Color Pen Set Fan' },
      { url: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Uni-ball One Metal Wire Spring Clip' },
      { url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Uni-ball One Matte Off-White Barrel' },
      { url: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Uni-ball One High Contrast Color Swatches' },
    ],
    variants: [
      { sku: 'PROD-BKS-013-8P', name: '8 Color Assorted Set', price: 960, mrp: 1200, stockQuantity: 30, attributes: { Pack: '8 Colors' } }
    ]
  },
  {
    sku: 'PROD-BKS-014',
    name: 'Thinking, Fast and Slow by Daniel Kahneman',
    slug: 'thinking-fast-and-slow-daniel-kahneman',
    description: 'Nobel Prize winner Daniel Kahneman takes us on a groundbreaking tour of the mind explaining the two systems that drive the way we think (System 1 & System 2).',
    brand: 'Farrar, Straus and Giroux',
    categorySlug: 'books-stationery',
    subcategorySlug: 'fiction-non-fiction-books',
    modelNumber: 'ISBN-9780374533557',
    mrp: 699,
    currentPrice: 489,
    originalPrice: 699,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 35,
    lowStockThreshold: 7,
    rating: 4.7,
    reviewCount: 1120,
    tags: ['thinking fast and slow', 'kahneman', 'psychology book', 'nobel prize', 'bestseller'],
    specifications: { Format: 'Paperback', Pages: '512 Pages', Language: 'English' },
    images: [
      { url: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Thinking Fast and Slow Paperback Book Cover' },
      { url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Thinking Fast and Slow Open Text Page' },
      { url: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Thinking Fast and Slow Rear Reviews' },
      { url: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Thinking Fast and Slow Thick Book Spine' },
    ],
    variants: [
      { sku: 'PROD-BKS-014-PB', name: 'Paperback Edition', price: 489, mrp: 699, stockQuantity: 35, attributes: { Binding: 'Paperback' } }
    ]
  },
  {
    sku: 'PROD-BKS-015',
    name: 'Bostitch Executive Heavy Duty Desk Stapler Set',
    slug: 'bostitch-executive-heavy-duty-stapler-set',
    description: 'All-metal construction executive desk stapler with One-Finger spring powered easy stapling up to 28 sheets of paper, plus staple remover and 5,000 staples.',
    brand: 'Bostitch',
    categorySlug: 'books-stationery',
    subcategorySlug: 'pens-desk-supplies',
    modelNumber: 'BOS-EX-28',
    mrp: 1499,
    currentPrice: 1199,
    originalPrice: 1499,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 6,
    rating: 4.8,
    reviewCount: 390,
    tags: ['bostitch', 'stapler', 'desk stapler', 'heavy duty stapler', 'office supplies'],
    specifications: { Capacity: '28 Sheets Capacity', Mechanism: 'One-Finger Spring Powered', Material: 'Die-Cast Metal Alloy Body', Includes: 'Staple Remover + 5000 Standard Staples' },
    images: [
      { url: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Bostitch Executive Black Metal Stapler Side' },
      { url: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Bostitch Anvil Reversible Pin Clinch Plate' },
      { url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Bostitch Top Latch Quick Loading Channel' },
      { url: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Bostitch Staples Box & Remover Kit' },
    ],
    variants: [
      { sku: 'PROD-BKS-015-BLK', name: 'Black Metal Exec Kit', price: 1199, mrp: 1499, stockQuantity: 30, attributes: { Color: 'Black' } }
    ]
  }
];
