import { ProductStatus } from '@prisma/client';

export const fashionAccessoriesProducts = [
  {
    sku: 'PROD-FAC-001',
    name: 'Fossil Gen 6 Wellness Edition Touchscreen Smartwatch',
    slug: 'fossil-gen-6-wellness-smartwatch',
    description: 'Style meets performance with Wear OS by Google, Snapdragon Wear 4100+ platform, SpO2 sensor, continuous heart rate tracking, fast charging (80% in 30 mins), and 44mm stainless steel case.',
    brand: 'Fossil',
    categorySlug: 'fashion-accessories',
    subcategorySlug: 'watches',
    modelNumber: 'FTW4070',
    mrp: 24995,
    currentPrice: 19995,
    originalPrice: 24995,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 20,
    lowStockThreshold: 4,
    rating: 4.6,
    reviewCount: 185,
    tags: ['fossil', 'smartwatch', 'gen 6', 'wear os', 'stainless steel watch'],
    specifications: { CaseSize: '44mm', OS: 'Wear OS by Google', Processor: 'Snapdragon Wear 4100+', WaterResistance: '3 ATM' },
    images: [
      { url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Fossil Gen 6 Smartwatch Dial View' },
      { url: 'https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Fossil Gen 6 Wrist Profile' },
      { url: 'https://images.unsplash.com/photo-1508057198894-247b23fe5ade?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Fossil Gen 6 Crown & Push Buttons' },
      { url: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Fossil Gen 6 Heart Rate Sensors Back Case' },
    ],
    variants: [
      { sku: 'PROD-FAC-001-BLK', name: 'Black Silicone Strap', price: 19995, mrp: 24995, stockQuantity: 10, attributes: { Color: 'Black Silicone' } },
      { sku: 'PROD-FAC-001-SLV', name: 'Silver Stainless Steel Strap', price: 21995, mrp: 26995, stockQuantity: 10, attributes: { Color: 'Silver Stainless Steel' } },
    ]
  },
  {
    sku: 'PROD-FAC-002',
    name: 'Ray-Ban Classic Aviator Polarized Sunglasses',
    slug: 'ray-ban-classic-aviator-polarized',
    description: 'Iconic teardrop design created in 1937 featuring Arista Gold metal frame, G-15 Green polarized glass lenses providing 100% UV protection and high clarity.',
    brand: 'Ray-Ban',
    categorySlug: 'fashion-accessories',
    subcategorySlug: 'sunglasses',
    modelNumber: 'RB3025-001/58',
    mrp: 12590,
    currentPrice: 10690,
    originalPrice: 12590,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 25,
    lowStockThreshold: 5,
    rating: 4.9,
    reviewCount: 420,
    tags: ['ray-ban', 'aviator', 'sunglasses', 'polarized', 'gold frame'],
    specifications: { FrameMaterial: 'Metal Arista Gold', LensColor: 'G-15 Green Polarized', LensWidth: '58mm', Bridge: '14mm' },
    images: [
      { url: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Ray-Ban Aviator Gold Polarized Front View' },
      { url: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Ray-Ban Aviator Side Temple Arm Logo' },
      { url: 'https://images.unsplash.com/photo-1589782182703-2aaa69037b5b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Ray-Ban Glass Lens Etching Detail' },
      { url: 'https://images.unsplash.com/photo-1508296695146-257a814070b4?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Ray-Ban Leather Carrying Case' },
    ],
    variants: [
      { sku: 'PROD-FAC-002-58', name: 'Medium 58mm / Gold-Green', price: 10690, mrp: 12590, stockQuantity: 15, attributes: { Size: '58mm', Color: 'Gold/Green' } },
      { sku: 'PROD-FAC-002-62', name: 'Large 62mm / Gold-Green', price: 10690, mrp: 12590, stockQuantity: 10, attributes: { Size: '62mm', Color: 'Gold/Green' } },
    ]
  },
  {
    sku: 'PROD-FAC-003',
    name: 'Tommy Hilfiger Genuine Leather RFID Blocking Wallet',
    slug: 'tommy-hilfiger-leather-rfid-wallet',
    description: '100% genuine cowhide leather bifold wallet featuring classic red/navy stripe, 6 card slots, 2 bill compartments, removable passcase ID window, and built-in RFID blocking shield.',
    brand: 'Tommy Hilfiger',
    categorySlug: 'fashion-accessories',
    subcategorySlug: 'wallets-belts',
    modelNumber: '31TL22X062',
    mrp: 3499,
    currentPrice: 2449,
    originalPrice: 3499,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.7,
    reviewCount: 310,
    tags: ['tommy hilfiger', 'wallet', 'leather wallet', 'rfid blocking', 'bifold'],
    specifications: { Material: '100% Cowhide Leather', Protection: 'RFID Blocking Tech', Slots: '6 Card + 2 Currency', Closure: 'Bifold' },
    images: [
      { url: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Tommy Hilfiger Leather Bifold Wallet Opened' },
      { url: 'https://images.unsplash.com/photo-1606503153255-59d8b8b82176?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Tommy Hilfiger Wallet Closed Exterior Logo' },
      { url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Tommy Hilfiger Card Slots Detail' },
      { url: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Tommy Hilfiger Wallet Packaging Box' },
    ],
    variants: [
      { sku: 'PROD-FAC-003-BLK', name: 'Black Leather', price: 2449, mrp: 3499, stockQuantity: 20, attributes: { Color: 'Black' } },
      { sku: 'PROD-FAC-003-BRN', name: 'Tan Brown Leather', price: 2449, mrp: 3499, stockQuantity: 20, attributes: { Color: 'Tan Brown' } },
    ]
  },
  {
    sku: 'PROD-FAC-004',
    name: 'Casio G-Shock GA-2100 "CasiOak" Octagonal Watch',
    slug: 'casio-g-shock-ga-2100-casioak',
    description: 'Ultra-slim shock-resistant analog-digital watch featuring iconic octagonal bezel, carbon core guard structure, 200m water resistance, and double LED light.',
    brand: 'Casio G-Shock',
    categorySlug: 'fashion-accessories',
    subcategorySlug: 'watches',
    modelNumber: 'GA-2100-1A1',
    mrp: 9995,
    currentPrice: 8495,
    originalPrice: 9995,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 35,
    lowStockThreshold: 6,
    rating: 4.9,
    reviewCount: 510,
    tags: ['casio', 'g-shock', 'casioak', 'ga-2100', 'shock resistant', 'stealth black'],
    specifications: { Case: 'Carbon / Resin', WaterResistance: '20 bar / 200m', BatteryLife: '3 Years', Weight: '51g' },
    images: [
      { url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Casio G-Shock GA-2100 Octagonal Stealth Dial' },
      { url: 'https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Casio G-Shock GA-2100 Side Profile Case Thickness' },
      { url: 'https://images.unsplash.com/photo-1508057198894-247b23fe5ade?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Casio G-Shock Resin Strap & Buckle' },
      { url: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Casio G-Shock Stainless Steel Back Plate' },
    ],
    variants: [
      { sku: 'PROD-FAC-004-BLK', name: 'All Black Stealth', price: 8495, mrp: 9995, stockQuantity: 20, attributes: { Color: 'All Black' } },
      { sku: 'PROD-FAC-004-WHT', name: 'Black with White Indices', price: 8495, mrp: 9995, stockQuantity: 15, attributes: { Color: 'Black/White' } },
    ]
  },
  {
    sku: 'PROD-FAC-005',
    name: 'Wildcraft Workpacks 21L Everyday Laptop Backpack',
    slug: 'wildcraft-workpacks-21l-laptop-backpack',
    description: 'Ergonomic 21-liter laptop backpack crafted with durable water-repellent polyester, padded 15.6-inch laptop sleeve, organizer pockets, and breathable mesh back panel.',
    brand: 'Wildcraft',
    categorySlug: 'fashion-accessories',
    subcategorySlug: 'backpacks-bags',
    modelNumber: 'WCK-WP-21',
    mrp: 2499,
    currentPrice: 1749,
    originalPrice: 2499,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 45,
    lowStockThreshold: 10,
    rating: 4.6,
    reviewCount: 380,
    tags: ['wildcraft', 'backpack', 'laptop bag', 'office backpack', 'waterproof'],
    specifications: { Capacity: '21 Liters', LaptopCompatibility: 'Up to 15.6 inches', Material: '100% Polyester', Compartments: '3 Main + Bottle Holder' },
    images: [
      { url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Wildcraft Workpacks 21L Backpack Front View' },
      { url: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Wildcraft Padded Shoulder Straps & Back Panel' },
      { url: 'https://images.unsplash.com/photo-1581605405669-fcdf81165afa?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Wildcraft Laptop Sleeve Inner Pocket' },
      { url: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Wildcraft Side Water Bottle Mesh Pocket' },
    ],
    variants: [
      { sku: 'PROD-FAC-005-BLU', name: 'Navy Blue', price: 1749, mrp: 2499, stockQuantity: 25, attributes: { Color: 'Navy Blue' } },
      { sku: 'PROD-FAC-005-BLK', name: 'Charcoal Black', price: 1749, mrp: 2499, stockQuantity: 20, attributes: { Color: 'Charcoal Black' } },
    ]
  },
  {
    sku: 'PROD-FAC-006',
    name: 'Seiko 5 Sports Automatic Stainless Steel Watch',
    slug: 'seiko-5-sports-automatic-watch',
    description: 'Legendary Japanese automatic timepiece powered by Caliber 4R36 movement, 41-hour power reserve, day/date display, unidirectional rotating bezel, and 100m water resistance.',
    brand: 'Seiko',
    categorySlug: 'fashion-accessories',
    subcategorySlug: 'watches',
    modelNumber: 'SRPD55K1',
    mrp: 27500,
    currentPrice: 23375,
    originalPrice: 27500,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 15,
    lowStockThreshold: 3,
    rating: 4.9,
    reviewCount: 145,
    tags: ['seiko', 'seiko 5', 'automatic watch', 'diver watch', 'stainless steel'],
    specifications: { Movement: 'Caliber 4R36 Automatic', PowerReserve: '41 Hours', Crystal: 'Hardlex', WaterResistance: '10 bar / 100m' },
    images: [
      { url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Seiko 5 Sports Automatic Black Dial Watch' },
      { url: 'https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Seiko 5 Sports Rotary Bezel Profile' },
      { url: 'https://images.unsplash.com/photo-1508057198894-247b23fe5ade?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Seiko 5 Sports See-Through Exhibition Caseback' },
      { url: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Seiko 5 Sports Stainless Steel Bracelet Clasp' },
    ],
    variants: [
      { sku: 'PROD-FAC-006-BLK', name: 'Black Dial / Stainless Bracelet', price: 23375, mrp: 27500, stockQuantity: 8, attributes: { Color: 'Black Dial' } },
      { sku: 'PROD-FAC-006-BLU', name: 'Blue Sunray Dial / Stainless Bracelet', price: 23375, mrp: 27500, stockQuantity: 7, attributes: { Color: 'Blue Sunray Dial' } },
    ]
  },
  {
    sku: 'PROD-FAC-007',
    name: 'Oakley Holbrook Wayfarer Prizm Sunglasses',
    slug: 'oakley-holbrook-prizm-sunglasses',
    description: 'Classic American frame design featuring metal rivets and Oakley icons, lightweight O Matter frame material, and Prizm Sapphire lenses enhancing color contrast.',
    brand: 'Oakley',
    categorySlug: 'fashion-accessories',
    subcategorySlug: 'sunglasses',
    modelNumber: 'OO9102-E855',
    mrp: 13890,
    currentPrice: 11800,
    originalPrice: 13890,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 18,
    lowStockThreshold: 4,
    rating: 4.8,
    reviewCount: 210,
    tags: ['oakley', 'holbrook', 'prizm', 'sunglasses', 'sport fashion'],
    specifications: { FrameMaterial: 'O Matter Synthetic', LensTech: 'Prizm Sapphire Polarized', UVProtection: '100% Plutonite', Fit: 'Standard' },
    images: [
      { url: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Oakley Holbrook Prizm Matte Black Front' },
      { url: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Oakley Square O Metal Icon Temple' },
      { url: 'https://images.unsplash.com/photo-1589782182703-2aaa69037b5b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Oakley Prizm Lens Mirror Reflection' },
      { url: 'https://images.unsplash.com/photo-1508296695146-257a814070b4?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Oakley Microbag & Vault Case' },
    ],
    variants: [
      { sku: 'PROD-FAC-007-BLU', name: 'Matte Black / Prizm Sapphire', price: 11800, mrp: 13890, stockQuantity: 10, attributes: { Color: 'Prizm Sapphire' } },
      { sku: 'PROD-FAC-007-BLK', name: 'Matte Black / Prizm Black', price: 11800, mrp: 13890, stockQuantity: 8, attributes: { Color: 'Prizm Black' } },
    ]
  },
  {
    sku: 'PROD-FAC-008',
    name: 'Calvin Klein Genuine Reversible Leather Belt',
    slug: 'calvin-klein-reversible-leather-belt',
    description: 'Versatile 2-in-1 dress belt made with smooth genuine leather that easily flips from black to dark brown with a twistable brushed gunmetal roller buckle.',
    brand: 'Calvin Klein',
    categorySlug: 'fashion-accessories',
    subcategorySlug: 'wallets-belts',
    modelNumber: 'CK-79328',
    mrp: 4999,
    currentPrice: 3499,
    originalPrice: 4999,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 6,
    rating: 4.6,
    reviewCount: 175,
    tags: ['calvin klein', 'leather belt', 'reversible belt', 'black brown belt', 'formal belt'],
    specifications: { Material: '100% Genuine Leather', Width: '35mm', Mechanism: 'Twist Reversible Buckle', Style: 'Dress & Casual' },
    images: [
      { url: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Calvin Klein Reversible Leather Belt Coiled' },
      { url: 'https://images.unsplash.com/photo-1606503153255-59d8b8b82176?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Calvin Klein Brushed Gunmetal Buckle Detail' },
      { url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Calvin Klein Embossed Logo on Strap Tip' },
      { url: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Calvin Klein Belt Presentation Box' },
    ],
    variants: [
      { sku: 'PROD-FAC-008-32', name: 'Size 32 Waist', price: 3499, mrp: 4999, stockQuantity: 10, attributes: { WaistSize: '32 Inches' } },
      { sku: 'PROD-FAC-008-34', name: 'Size 34 Waist', price: 3499, mrp: 4999, stockQuantity: 10, attributes: { WaistSize: '34 Inches' } },
      { sku: 'PROD-FAC-008-36', name: 'Size 36 Waist', price: 3499, mrp: 4999, stockQuantity: 10, attributes: { WaistSize: '36 Inches' } },
    ]
  },
  {
    sku: 'PROD-FAC-009',
    name: 'Titan Karishma Analog Couple Watch Set',
    slug: 'titan-karishma-couple-watch-set',
    description: 'Elegant pair of complementary men’s and women’s gold-plated stainless steel dress watches with champagne sunray dials, quartz movements, and 30m water resistance.',
    brand: 'Titan',
    categorySlug: 'fashion-accessories',
    subcategorySlug: 'watches',
    modelNumber: '17752586YM01',
    mrp: 7995,
    currentPrice: 6395,
    originalPrice: 7995,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 20,
    lowStockThreshold: 4,
    rating: 4.8,
    reviewCount: 290,
    tags: ['titan', 'couple watch', 'gold watch', 'wedding gift', 'analog watch'],
    specifications: { Movement: 'High Precision Quartz', Plating: '22k Gold Ion Plated', DialColor: 'Champagne Gold', Pack: 'Pair (His & Hers)' },
    images: [
      { url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Titan Karishma Gold Couple Watches Pair' },
      { url: 'https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Titan Men Watch Dial Close' },
      { url: 'https://images.unsplash.com/photo-1508057198894-247b23fe5ade?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Titan Women Watch Slim Dial Close' },
      { url: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Titan Red Velvet Presentation Box' },
    ],
    variants: [
      { sku: 'PROD-FAC-009-SET', name: 'His & Hers Couple Set', price: 6395, mrp: 7995, stockQuantity: 20, attributes: { Pack: 'Set of 2 Watches' } }
    ]
  },
  {
    sku: 'PROD-FAC-010',
    name: 'American Tourister 32L Casual Travel Backpack',
    slug: 'american-tourister-32l-backpack',
    description: 'Spacious 32-liter multi-compartment casual backpack featuring rain cover, extra bottle pockets, padded shoulder straps, and durable ripstop fabric.',
    brand: 'American Tourister',
    categorySlug: 'fashion-accessories',
    subcategorySlug: 'backpacks-bags',
    modelNumber: 'AMT-RUBY-01',
    mrp: 3200,
    currentPrice: 1920,
    originalPrice: 3200,
    discount: 40.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 50,
    lowStockThreshold: 10,
    rating: 4.6,
    reviewCount: 410,
    tags: ['american tourister', 'backpack', 'college bag', 'travel bag', 'rain cover'],
    specifications: { Capacity: '32 Liters', RainCover: 'Included Integrated Rain Cover', Warranty: '1 Year Global', Weight: '480g' },
    images: [
      { url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'American Tourister 32L Backpack Front' },
      { url: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'American Tourister Shoulder Straps Cushion' },
      { url: 'https://images.unsplash.com/photo-1581605405669-fcdf81165afa?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'American Tourister Main Compartment Capacity' },
      { url: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'American Tourister Rain Cover Deployed' },
    ],
    variants: [
      { sku: 'PROD-FAC-010-RED', name: 'Black & Ruby Red', price: 1920, mrp: 3200, stockQuantity: 25, attributes: { Color: 'Ruby Red' } },
      { sku: 'PROD-FAC-010-BLU', name: 'Teal Blue', price: 1920, mrp: 3200, stockQuantity: 25, attributes: { Color: 'Teal Blue' } },
    ]
  },
  {
    sku: 'PROD-FAC-011',
    name: 'Police Black Square Polarized Men Sunglasses',
    slug: 'police-square-polarized-sunglasses',
    description: 'Italian luxury bold square sunglasses featuring lightweight matte acetate frame, dark grey polarized polycarbonate lenses, and signature wings metal temple hinges.',
    brand: 'Police',
    categorySlug: 'fashion-accessories',
    subcategorySlug: 'sunglasses',
    modelNumber: 'SPL872-0700',
    mrp: 11900,
    currentPrice: 8330,
    originalPrice: 11900,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 15,
    lowStockThreshold: 3,
    rating: 4.7,
    reviewCount: 95,
    tags: ['police', 'sunglasses', 'square sunglasses', 'polarized', 'italian design'],
    specifications: { FrameMaterial: 'High Grade Acetate', Lens: 'Polarized Dark Grey', LensWidth: '54mm', Bridge: '18mm' },
    images: [
      { url: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Police Black Square Polarized Sunglasses Front' },
      { url: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Police Eagle Wings Metal Temple Detail' },
      { url: 'https://images.unsplash.com/photo-1589782182703-2aaa69037b5b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Police Matte Black Frame Finish' },
      { url: 'https://images.unsplash.com/photo-1508296695146-257a814070b4?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Police Branded Leatherette Case' },
    ],
    variants: [
      { sku: 'PROD-FAC-011-BLK', name: 'Matte Black / Smoke Grey', price: 8330, mrp: 11900, stockQuantity: 15, attributes: { Color: 'Matte Black' } }
    ]
  },
  {
    sku: 'PROD-FAC-012',
    name: 'Hidesign Genuine Leather Crossbody Messenger Bag',
    slug: 'hidesign-leather-crossbody-messenger',
    description: 'Handcrafted vegetable-tanned full-grain leather messenger bag with magnetic flap closure, padded iPad/tablet compartment, brass hardware, and adjustable cotton web shoulder strap.',
    brand: 'Hidesign',
    categorySlug: 'fashion-accessories',
    subcategorySlug: 'backpacks-bags',
    modelNumber: 'HD-MES-09',
    mrp: 8995,
    currentPrice: 7195,
    originalPrice: 8995,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 18,
    lowStockThreshold: 4,
    rating: 4.8,
    reviewCount: 160,
    tags: ['hidesign', 'leather bag', 'messenger bag', 'crossbody bag', 'real leather'],
    specifications: { Material: 'Vegetable Tanned Leather', Fitting: 'Solid Brass Buckles', TabletSleeve: 'Fits 11 inch iPad', Closure: 'Magnetic Flap' },
    images: [
      { url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Hidesign Tan Leather Messenger Bag Front' },
      { url: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Hidesign Flap Opened Inner Lining' },
      { url: 'https://images.unsplash.com/photo-1581605405669-fcdf81165afa?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Hidesign Solid Brass Buckle Close' },
      { url: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Hidesign Adjustable Webbing Strap' },
    ],
    variants: [
      { sku: 'PROD-FAC-012-TAN', name: 'Tan Brown Leather', price: 7195, mrp: 8995, stockQuantity: 10, attributes: { Color: 'Tan Brown' } },
      { sku: 'PROD-FAC-012-BRN', name: 'Dark Mahogany Leather', price: 7195, mrp: 8995, stockQuantity: 8, attributes: { Color: 'Dark Mahogany' } },
    ]
  },
  {
    sku: 'PROD-FAC-013',
    name: 'Daniel Wellington Classic St Mawes Rose Gold Watch',
    slug: 'daniel-wellington-classic-st-mawes-rose-gold',
    description: 'Ultra-thin 6mm Japanese quartz minimalist dress watch featuring 40mm rose gold casing, eggshell white dial, and interchangeable genuine Italian brown leather strap.',
    brand: 'Daniel Wellington',
    categorySlug: 'fashion-accessories',
    subcategorySlug: 'watches',
    modelNumber: 'DW00100006',
    mrp: 14999,
    currentPrice: 11999,
    originalPrice: 14999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 22,
    lowStockThreshold: 4,
    rating: 4.7,
    reviewCount: 310,
    tags: ['daniel wellington', 'dw watch', 'rose gold watch', 'minimalist watch', 'leather watch'],
    specifications: { CaseThickness: '6mm', CaseSize: '40mm', StrapWidth: '20mm', Movement: 'Japanese Quartz' },
    images: [
      { url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Daniel Wellington Classic St Mawes Rose Gold Dial' },
      { url: 'https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Daniel Wellington Ultra-Thin Profile Case' },
      { url: 'https://images.unsplash.com/photo-1508057198894-247b23fe5ade?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Daniel Wellington Brown Leather Strap Texture' },
      { url: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Daniel Wellington Buckle & Caseback Engraving' },
    ],
    variants: [
      { sku: 'PROD-FAC-013-40', name: '40mm / Rose Gold / Brown Leather', price: 11999, mrp: 14999, stockQuantity: 12, attributes: { Size: '40mm', Color: 'Rose Gold/Brown' } },
      { sku: 'PROD-FAC-013-36', name: '36mm / Rose Gold / Brown Leather', price: 10999, mrp: 13999, stockQuantity: 10, attributes: { Size: '36mm', Color: 'Rose Gold/Brown' } },
    ]
  },
  {
    sku: 'PROD-FAC-014',
    name: 'Fastrack Polarized Wayfarer Unisex Sunglasses',
    slug: 'fastrack-polarized-wayfarer-sunglasses',
    description: 'Trendy lightweight plastic frame sunglasses with TAC polarized blue gradient lenses that reduce glare and block 100% of UV rays.',
    brand: 'Fastrack',
    categorySlug: 'fashion-accessories',
    subcategorySlug: 'sunglasses',
    modelNumber: 'P425BK1P',
    mrp: 2499,
    currentPrice: 1749,
    originalPrice: 2499,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.5,
    reviewCount: 240,
    tags: ['fastrack', 'sunglasses', 'wayfarer', 'polarized', 'blue gradient'],
    specifications: { FrameMaterial: 'Polycarbonate', LensType: 'Polarized TAC', FrameColor: 'Matte Black', UVProtection: 'UV400' },
    images: [
      { url: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Fastrack Polarized Wayfarer Blue Mirror Lens' },
      { url: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Fastrack Temple Arm Logo Detail' },
      { url: 'https://images.unsplash.com/photo-1589782182703-2aaa69037b5b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Fastrack Frame Angle View' },
      { url: 'https://images.unsplash.com/photo-1508296695146-257a814070b4?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Fastrack Soft Pouch Packaging' },
    ],
    variants: [
      { sku: 'PROD-FAC-014-BLU', name: 'Matte Black / Blue Mirror', price: 1749, mrp: 2499, stockQuantity: 20, attributes: { Color: 'Blue Mirror' } },
      { sku: 'PROD-FAC-014-GRN', name: 'Matte Black / Green Mirror', price: 1749, mrp: 2499, stockQuantity: 20, attributes: { Color: 'Green Mirror' } },
    ]
  },
  {
    sku: 'PROD-FAC-015',
    name: 'Titan Mens Leather Minimalist Slim Cardholder',
    slug: 'titan-leather-slim-cardholder',
    description: 'Sleek front pocket card wallet crafted from nappa genuine leather featuring 4 card slots, central cash compartment, and RFID blocking lining.',
    brand: 'Titan',
    categorySlug: 'fashion-accessories',
    subcategorySlug: 'wallets-belts',
    modelNumber: 'TW001CH',
    mrp: 1495,
    currentPrice: 1195,
    originalPrice: 1495,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 50,
    lowStockThreshold: 10,
    rating: 4.6,
    reviewCount: 190,
    tags: ['titan', 'cardholder', 'slim wallet', 'nappa leather', 'front pocket wallet'],
    specifications: { Material: 'Nappa Leather', Capacity: '4 Cards + Cash', Thickness: '5mm Ultra Thin', Protection: 'RFID Shield' },
    images: [
      { url: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Titan Slim Leather Cardholder Front View' },
      { url: 'https://images.unsplash.com/photo-1606503153255-59d8b8b82176?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Titan Card Slots with Cards Inserted' },
      { url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Titan Central Cash Pocket View' },
      { url: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Titan Cardholder Metal Badge' },
    ],
    variants: [
      { sku: 'PROD-FAC-015-BLK', name: 'Jet Black Nappa Leather', price: 1195, mrp: 1495, stockQuantity: 25, attributes: { Color: 'Jet Black' } },
      { sku: 'PROD-FAC-015-BRN', name: 'Chestnut Brown Nappa Leather', price: 1195, mrp: 1495, stockQuantity: 25, attributes: { Color: 'Chestnut Brown' } },
    ]
  }
];
