import { ProductStatus } from '@prisma/client';

export const footwearProducts = [
  {
    sku: 'PROD-FTW-001',
    name: 'Nike Air Force 1 07 Triple White',
    slug: 'nike-air-force-1-07-white',
    description: 'Iconic basketball-inspired lifestyle sneaker featuring pristine crisp leather upper, stitched overlays, micro-perforations for breathability, and full-length encapsulated Nike Air cushioning.',
    brand: 'Nike',
    categorySlug: 'footwear',
    subcategorySlug: 'sneakers-casual-shoes',
    modelNumber: 'CW2288-111',
    mrp: 9695,
    currentPrice: 8995,
    originalPrice: 9695,
    discount: 7.2,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 45,
    lowStockThreshold: 10,
    rating: 4.8,
    reviewCount: 520,
    tags: ['nike', 'air force 1', 'sneakers', 'white sneakers', 'lifestyle', 'iconic'],
    specifications: { Upper: 'Genuine Leather', Sole: 'Rubber with Air Unit', Color: 'Triple White', Closure: 'Lace-up' },
    images: [
      { url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Nike Air Force 1 07 White Side Profile' },
      { url: 'https://images.unsplash.com/photo-1600269452121-4f2416e55c28?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Nike Air Force 1 07 White Angle View' },
      { url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Nike Air Force 1 Toe Box Micro Perforations' },
      { url: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Nike Air Force 1 Heel Tab & Outsole Tread' },
    ],
    variants: [
      { sku: 'PROD-FTW-001-UK8', name: 'UK 8 / White', price: 8995, mrp: 9695, stockQuantity: 15, attributes: { Size: 'UK 8', Color: 'White' } },
      { sku: 'PROD-FTW-001-UK9', name: 'UK 9 / White', price: 8995, mrp: 9695, stockQuantity: 20, attributes: { Size: 'UK 9', Color: 'White' } },
      { sku: 'PROD-FTW-001-UK10', name: 'UK 10 / White', price: 8995, mrp: 9695, stockQuantity: 10, attributes: { Size: 'UK 10', Color: 'White' } },
    ]
  },
  {
    sku: 'PROD-FTW-002',
    name: 'Adidas Ultraboost Light Running Shoes',
    slug: 'adidas-ultraboost-light-running',
    description: 'Lightest Ultraboost ever made featuring 30% lighter Light BOOST material, Primeknit+ textile upper for precision foot wrapping, and Continental Rubber outsole.',
    brand: 'Adidas',
    categorySlug: 'footwear',
    subcategorySlug: 'sports-running-shoes',
    modelNumber: 'HQ6351',
    mrp: 18999,
    currentPrice: 15199,
    originalPrice: 18999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 5,
    rating: 4.7,
    reviewCount: 280,
    tags: ['adidas', 'ultraboost', 'running shoes', 'boost', 'marathon'],
    specifications: { Upper: 'Primeknit+ Eco Fabric', Midsole: 'Light BOOST', Outsole: 'Continental Rubber', Weight: '299g' },
    images: [
      { url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Adidas Ultraboost Light Running Shoes Lateral View' },
      { url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Adidas Ultraboost Light Red Accent Profile' },
      { url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Adidas Ultraboost Heel Counter & Boost Midsole' },
      { url: 'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Adidas Ultraboost Outsole Grip Pattern' },
    ],
    variants: [
      { sku: 'PROD-FTW-002-UK8', name: 'UK 8 / Core Black', price: 15199, mrp: 18999, stockQuantity: 15, attributes: { Size: 'UK 8', Color: 'Core Black' } },
      { sku: 'PROD-FTW-002-UK9', name: 'UK 9 / Core Black', price: 15199, mrp: 18999, stockQuantity: 15, attributes: { Size: 'UK 9', Color: 'Core Black' } },
    ]
  },
  {
    sku: 'PROD-FTW-003',
    name: 'Puma Suede Classic XXI Sneakers',
    slug: 'puma-suede-classic-xxi',
    description: 'Timeless retro street style featuring full suede upper, synthetic leather lining, Formstrip on lateral sides, and durable rubber midsole.',
    brand: 'Puma',
    categorySlug: 'footwear',
    subcategorySlug: 'sneakers-casual-shoes',
    modelNumber: '374915-01',
    mrp: 6999,
    currentPrice: 4899,
    originalPrice: 6999,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.6,
    reviewCount: 195,
    tags: ['puma', 'suede classic', 'retro sneakers', 'black suede'],
    specifications: { Upper: '100% Suede Leather', Lining: 'Synthetic', Sole: 'Non-marking Rubber', Fit: 'Regular' },
    images: [
      { url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Puma Suede Classic Black & White Profile' },
      { url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Puma Suede Classic Side Quarter View' },
      { url: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Puma Suede Classic Foil Gold Logo Detail' },
      { url: 'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Puma Suede Classic Rubber Sole Unit' },
    ],
    variants: [
      { sku: 'PROD-FTW-003-UK8', name: 'UK 8 / Black-White', price: 4899, mrp: 6999, stockQuantity: 20, attributes: { Size: 'UK 8', Color: 'Black-White' } },
      { sku: 'PROD-FTW-003-UK9', name: 'UK 9 / Black-White', price: 4899, mrp: 6999, stockQuantity: 20, attributes: { Size: 'UK 9', Color: 'Black-White' } },
    ]
  },
  {
    sku: 'PROD-FTW-004',
    name: 'Clarks Tilden Cap Leather Derby Shoes',
    slug: 'clarks-tilden-cap-derby-shoes',
    description: 'Refined men’s formal dress shoes crafted from full-grain dark brown leather, OrthoLite breathable footbed, discreet elastic gore panels, and flexible rubber traction sole.',
    brand: 'Clarks',
    categorySlug: 'footwear',
    subcategorySlug: 'formal-shoes-loafers',
    modelNumber: '26110309',
    mrp: 8999,
    currentPrice: 7199,
    originalPrice: 8999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 22,
    lowStockThreshold: 4,
    rating: 4.7,
    reviewCount: 140,
    tags: ['clarks', 'derby shoes', 'formal shoes', 'leather oxford', 'office footwear'],
    specifications: { Upper: 'Full Grain Leather', Insole: 'OrthoLite Cushioning', Closure: 'Lace-up', Toe: 'Cap Toe' },
    images: [
      { url: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Clarks Tilden Cap Leather Derby Pair' },
      { url: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Clarks Tilden Cap Leather Side Profile' },
      { url: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Clarks Tilden Stitching Detail & Cap Toe' },
      { url: 'https://images.unsplash.com/photo-1560343776-97e7d202ff0e?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Clarks Tilden Sole Traction Tread' },
    ],
    variants: [
      { sku: 'PROD-FTW-004-UK8', name: 'UK 8 / Dark Brown', price: 7199, mrp: 8999, stockQuantity: 10, attributes: { Size: 'UK 8', Color: 'Dark Brown' } },
      { sku: 'PROD-FTW-004-UK9', name: 'UK 9 / Dark Brown', price: 7199, mrp: 8999, stockQuantity: 12, attributes: { Size: 'UK 9', Color: 'Dark Brown' } },
    ]
  },
  {
    sku: 'PROD-FTW-005',
    name: 'Woodland Leather Casual Boots',
    slug: 'woodland-leather-casual-boots',
    description: 'Rugged outdoor leather boots with heavy-duty brass eyelets, oiled nubuck leather upper, deep lugs lugged rubber sole for extreme grip, and padded ankle collar.',
    brand: 'Woodland',
    categorySlug: 'footwear',
    subcategorySlug: 'sneakers-casual-shoes',
    modelNumber: 'GC0377107',
    mrp: 5495,
    currentPrice: 4670,
    originalPrice: 5495,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 35,
    lowStockThreshold: 6,
    rating: 4.6,
    reviewCount: 310,
    tags: ['woodland', 'boots', 'outdoor boots', 'leather boots', 'hiking'],
    specifications: { Upper: 'Oiled Nubuck Leather', Sole: 'High-Density Rubber', Lining: 'Textile', Height: 'Ankle High' },
    images: [
      { url: 'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Woodland Leather Casual Boots Front Profile' },
      { url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Woodland Boots Side Heel Profile' },
      { url: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Woodland Eyelets and Laces Texture' },
      { url: 'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Woodland Lugged Rubber Outsole' },
    ],
    variants: [
      { sku: 'PROD-FTW-005-UK8', name: 'UK 8 / Camel Tan', price: 4670, mrp: 5495, stockQuantity: 20, attributes: { Size: 'UK 8', Color: 'Camel Tan' } },
      { sku: 'PROD-FTW-005-UK9', name: 'UK 9 / Camel Tan', price: 4670, mrp: 5495, stockQuantity: 15, attributes: { Size: 'UK 9', Color: 'Camel Tan' } },
    ]
  },
  {
    sku: 'PROD-FTW-006',
    name: 'Asics Gel-Nimbus 26 Running Shoes',
    slug: 'asics-gel-nimbus-26',
    description: 'Maximum plush cushioning long-distance running shoe featuring PureGEL technology, FF BLAST PLUS ECO cushioning, and engineered stretch knit upper.',
    brand: 'Asics',
    categorySlug: 'footwear',
    subcategorySlug: 'sports-running-shoes',
    modelNumber: '1011B792',
    mrp: 15999,
    currentPrice: 13599,
    originalPrice: 15999,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 18,
    lowStockThreshold: 4,
    rating: 4.9,
    reviewCount: 165,
    tags: ['asics', 'gel nimbus', 'running shoes', 'marathon cushion', 'asics nimbus 26'],
    specifications: { Technology: 'PureGEL + FF BLAST PLUS ECO', 'Heel Drop': '8mm', Weight: '305g', Upper: 'Engineered Knit' },
    images: [
      { url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Asics Gel Nimbus 26 Running Shoe Side View' },
      { url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Asics Gel Nimbus 26 Angle View' },
      { url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Asics Gel Nimbus 26 Heel PureGel Insert' },
      { url: 'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Asics AHARPLUS Rubber Outsole' },
    ],
    variants: [
      { sku: 'PROD-FTW-006-UK8', name: 'UK 8 / Blue Expanse', price: 13599, mrp: 15999, stockQuantity: 8, attributes: { Size: 'UK 8', Color: 'Blue Expanse' } },
      { sku: 'PROD-FTW-006-UK9', name: 'UK 9 / Blue Expanse', price: 13599, mrp: 15999, stockQuantity: 10, attributes: { Size: 'UK 9', Color: 'Blue Expanse' } },
    ]
  },
  {
    sku: 'PROD-FTW-007',
    name: 'New Balance 574 Core Sneakers',
    slug: 'new-balance-574-core',
    description: 'Iconic heritage lifestyle sneaker with premium suede and mesh combination upper, ENCAP midsole cushioning with soft EVA foam, and durable rubber tread.',
    brand: 'New Balance',
    categorySlug: 'footwear',
    subcategorySlug: 'sneakers-casual-shoes',
    modelNumber: 'ML574EVG',
    mrp: 8999,
    currentPrice: 7199,
    originalPrice: 8999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 28,
    lowStockThreshold: 5,
    rating: 4.7,
    reviewCount: 230,
    tags: ['new balance', 'nb 574', 'retro sneakers', 'grey suede', 'lifestyle'],
    specifications: { Upper: 'Suede & Mesh', Midsole: 'ENCAP Polyurethane Rim with EVA Core', Outsole: 'Solid Rubber', Fit: 'Medium Width' },
    images: [
      { url: 'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'New Balance 574 Grey Suede Lateral View' },
      { url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'New Balance 574 Front Toe View' },
      { url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'New Balance 574 ENCAP Midsole & N Logo' },
      { url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'New Balance 574 Heel Collar & Outsole' },
    ],
    variants: [
      { sku: 'PROD-FTW-007-UK8', name: 'UK 8 / Grey', price: 7199, mrp: 8999, stockQuantity: 14, attributes: { Size: 'UK 8', Color: 'Grey' } },
      { sku: 'PROD-FTW-007-UK9', name: 'UK 9 / Grey', price: 7199, mrp: 8999, stockQuantity: 14, attributes: { Size: 'UK 9', Color: 'Grey' } },
    ]
  },
  {
    sku: 'PROD-FTW-008',
    name: 'Skechers Go Walk Max Men Walking Shoes',
    slug: 'skechers-go-walk-max',
    description: 'Ultra-lightweight laceless slip-on walking shoe featuring 5GEN responsive cushioning midsole, Goga Mat technology insole, and breathable woven mesh fabric upper.',
    brand: 'Skechers',
    categorySlug: 'footwear',
    subcategorySlug: 'sneakers-casual-shoes',
    modelNumber: '54601-BBK',
    mrp: 4999,
    currentPrice: 3999,
    originalPrice: 4999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 50,
    lowStockThreshold: 10,
    rating: 4.8,
    reviewCount: 410,
    tags: ['skechers', 'go walk', 'walking shoes', 'slip on', 'goga mat'],
    specifications: { Upper: 'Air Mesh Fabric', Insole: 'Goga Mat Rebound Cushioning', Midsole: '5GEN Polymer', Closure: 'Slip-on' },
    images: [
      { url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Skechers Go Walk Max Black Slip-On' },
      { url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Skechers Go Walk Mesh Heel Angle' },
      { url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Skechers Go Walk Flexible Cushion Midsole' },
      { url: 'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Skechers Go Walk Outsole Pods' },
    ],
    variants: [
      { sku: 'PROD-FTW-008-UK8', name: 'UK 8 / Black', price: 3999, mrp: 4999, stockQuantity: 25, attributes: { Size: 'UK 8', Color: 'Black' } },
      { sku: 'PROD-FTW-008-UK9', name: 'UK 9 / Black', price: 3999, mrp: 4999, stockQuantity: 25, attributes: { Size: 'UK 9', Color: 'Black' } },
    ]
  },
  {
    sku: 'PROD-FTW-009',
    name: 'Red Tape Genuine Leather Penny Loafers',
    slug: 'red-tape-leather-penny-loafers',
    description: 'Handcrafted slip-on formal penny loafers made with premium burnished tan leather upper, memory foam cushioned footbed, and flexible TPR slip-resistant sole.',
    brand: 'Red Tape',
    categorySlug: 'footwear',
    subcategorySlug: 'formal-shoes-loafers',
    modelNumber: 'RTE291A',
    mrp: 5999,
    currentPrice: 2399,
    originalPrice: 5999,
    discount: 60.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.5,
    reviewCount: 180,
    tags: ['red tape', 'loafers', 'penny loafers', 'tan leather', 'formal loafers'],
    specifications: { Upper: '100% Genuine Leather', Sole: 'TPR', Toe: 'Round Toe', Lining: 'Leatherette' },
    images: [
      { url: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Red Tape Tan Penny Loafers Front View' },
      { url: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Red Tape Penny Strap Detail' },
      { url: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Red Tape Leather Stitching Finish' },
      { url: 'https://images.unsplash.com/photo-1560343776-97e7d202ff0e?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Red Tape TPR Sole Profile' },
    ],
    variants: [
      { sku: 'PROD-FTW-009-UK8', name: 'UK 8 / Tan', price: 2399, mrp: 5999, stockQuantity: 20, attributes: { Size: 'UK 8', Color: 'Tan' } },
      { sku: 'PROD-FTW-009-UK9', name: 'UK 9 / Tan', price: 2399, mrp: 5999, stockQuantity: 20, attributes: { Size: 'UK 9', Color: 'Tan' } },
    ]
  },
  {
    sku: 'PROD-FTW-010',
    name: 'Vans Old Skool Unisex Canvas Sneakers',
    slug: 'vans-old-skool-sneakers',
    description: 'Classic skate shoe that first bared the iconic side stripe. Durable canvas and suede upper, reinforced toe caps, padded collars, and signature rubber waffle outsoles.',
    brand: 'Vans',
    categorySlug: 'footwear',
    subcategorySlug: 'sneakers-casual-shoes',
    modelNumber: 'VN000D3HY28',
    mrp: 5999,
    currentPrice: 4799,
    originalPrice: 5999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 35,
    lowStockThreshold: 6,
    rating: 4.8,
    reviewCount: 340,
    tags: ['vans', 'old skool', 'skate shoes', 'black canvas', 'sidestripe'],
    specifications: { Upper: 'Suede & Heavy Canvas', Pattern: 'Solid Black & White Stripe', Outsole: 'Rubber Waffle', Fit: 'Unisex' },
    images: [
      { url: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Vans Old Skool Black & White Profile' },
      { url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Vans Old Skool Sidestripe Detail' },
      { url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Vans Old Skool Heel Plate' },
      { url: 'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Vans Rubber Waffle Outsole' },
    ],
    variants: [
      { sku: 'PROD-FTW-010-UK8', name: 'UK 8 / Black-White', price: 4799, mrp: 5999, stockQuantity: 18, attributes: { Size: 'UK 8', Color: 'Black-White' } },
      { sku: 'PROD-FTW-010-UK9', name: 'UK 9 / Black-White', price: 4799, mrp: 5999, stockQuantity: 17, attributes: { Size: 'UK 9', Color: 'Black-White' } },
    ]
  },
  {
    sku: 'PROD-FTW-011',
    name: 'Converse Chuck Taylor All Star High Top',
    slug: 'converse-chuck-taylor-all-star-high',
    description: 'Timeless high-top canvas sneaker featuring iconic Star ankle patch, medial eyelets for airflow, vulcanized rubber sole with classic diamond pattern tread.',
    brand: 'Converse',
    categorySlug: 'footwear',
    subcategorySlug: 'sneakers-casual-shoes',
    modelNumber: 'M9160C',
    mrp: 4999,
    currentPrice: 4249,
    originalPrice: 4999,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.8,
    reviewCount: 490,
    tags: ['converse', 'chuck taylor', 'high top', 'black canvas', 'all star'],
    specifications: { Upper: '100% Cotton Canvas', Outsole: 'Vulcanized Rubber', Height: 'High Top', Toe: 'Rubber Toe Cap' },
    images: [
      { url: 'https://images.unsplash.com/photo-1607522370275-f14206abe5d3?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Converse Chuck Taylor High Top Lateral View' },
      { url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Converse All Star Ankle Patch Closeup' },
      { url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Converse Rubber Toe Cap & Lacing' },
      { url: 'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Converse Diamond Pattern Outsole' },
    ],
    variants: [
      { sku: 'PROD-FTW-011-UK8', name: 'UK 8 / Black Canvas', price: 4249, mrp: 4999, stockQuantity: 20, attributes: { Size: 'UK 8', Color: 'Black Canvas' } },
      { sku: 'PROD-FTW-011-UK9', name: 'UK 9 / Black Canvas', price: 4249, mrp: 4999, stockQuantity: 20, attributes: { Size: 'UK 9', Color: 'Black Canvas' } },
    ]
  },
  {
    sku: 'PROD-FTW-012',
    name: 'Crocs Classic Clog Slip-On Sandals',
    slug: 'crocs-classic-clog',
    description: 'World-renowned original clog made with Croslite foam material for cushion, ventilation ports for breathability and water drainage, and pivoting heel strap for secure fit.',
    brand: 'Crocs',
    categorySlug: 'footwear',
    subcategorySlug: 'sneakers-casual-shoes',
    modelNumber: '10001-001',
    mrp: 3495,
    currentPrice: 2795,
    originalPrice: 3495,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 60,
    lowStockThreshold: 12,
    rating: 4.7,
    reviewCount: 650,
    tags: ['crocs', 'classic clog', 'sandals', 'croslite', 'waterproof'],
    specifications: { Material: '100% Croslite Foam', Weight: 'Lightweight', WaterResistance: 'Waterproof & Buoyant', Care: 'Easy Clean' },
    images: [
      { url: 'https://images.unsplash.com/photo-1603808033192-082d6919d3e1?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Crocs Classic Black Clog Top View' },
      { url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Crocs Ventilation Holes & Pivoting Strap' },
      { url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Crocs Side Heel Footbed' },
      { url: 'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Crocs Non-marking Sole Texture' },
    ],
    variants: [
      { sku: 'PROD-FTW-012-UK8', name: 'UK 8 / Black', price: 2795, mrp: 3495, stockQuantity: 30, attributes: { Size: 'UK 8', Color: 'Black' } },
      { sku: 'PROD-FTW-012-UK9', name: 'UK 9 / Black', price: 2795, mrp: 3495, stockQuantity: 30, attributes: { Size: 'UK 9', Color: 'Black' } },
    ]
  },
  {
    sku: 'PROD-FTW-013',
    name: 'Birkenstock Arizona Birko-Flor Sandals',
    slug: 'birkenstock-arizona-sandals',
    description: 'Iconic double-strap sandal with anatomically shaped cork-latex footbed, suede lining, Birko-Flor synthetic upper, and lightweight EVA shock-absorbing outsole.',
    brand: 'Birkenstock',
    categorySlug: 'footwear',
    subcategorySlug: 'sneakers-casual-shoes',
    modelNumber: '51791',
    mrp: 8990,
    currentPrice: 7640,
    originalPrice: 8990,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 25,
    lowStockThreshold: 5,
    rating: 4.8,
    reviewCount: 290,
    tags: ['birkenstock', 'arizona', 'sandals', 'cork footbed', 'german orthopedic'],
    specifications: { Upper: 'Birko-Flor Synthetic Leather', Footbed: 'Natural Cork & Latex', Sole: 'EVA', Fit: 'Regular Fit' },
    images: [
      { url: 'https://images.unsplash.com/photo-1603808033192-082d6919d3e1?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Birkenstock Arizona Two-Strap Sandals' },
      { url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Birkenstock Cork Footbed Curve Detail' },
      { url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Birkenstock Metal Buckle Straps' },
      { url: 'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Birkenstock EVA Outsole Tread' },
    ],
    variants: [
      { sku: 'PROD-FTW-013-UK8', name: 'UK 8 / Black', price: 7640, mrp: 8990, stockQuantity: 12, attributes: { Size: 'UK 8', Color: 'Black' } },
      { sku: 'PROD-FTW-013-UK9', name: 'UK 9 / Black', price: 7640, mrp: 8990, stockQuantity: 13, attributes: { Size: 'UK 9', Color: 'Black' } },
    ]
  },
  {
    sku: 'PROD-FTW-014',
    name: 'Bata Premium Genuine Leather Monk Strap',
    slug: 'bata-premium-monk-strap-shoes',
    description: 'Double monk strap dress shoe with hand-burnished tan leather upper, metallic pin buckles, cushioned arch-support footbed, and durable resin rubber sole.',
    brand: 'Bata',
    categorySlug: 'footwear',
    subcategorySlug: 'formal-shoes-loafers',
    modelNumber: '854-4712',
    mrp: 3999,
    currentPrice: 2999,
    originalPrice: 3999,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 6,
    rating: 4.5,
    reviewCount: 160,
    tags: ['bata', 'monk strap', 'formal shoes', 'tan leather', 'dress shoes'],
    specifications: { Upper: 'Genuine Leather', Closure: 'Double Metal Buckle Straps', Sole: 'Resin Rubber', Toe: 'Almond Toe' },
    images: [
      { url: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Bata Monk Strap Tan Leather Shoes' },
      { url: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Bata Monk Buckle Detail Close' },
      { url: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Bata Almond Toe Burnish Finish' },
      { url: 'https://images.unsplash.com/photo-1560343776-97e7d202ff0e?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Bata Resin Sole Tread' },
    ],
    variants: [
      { sku: 'PROD-FTW-014-UK8', name: 'UK 8 / Tan', price: 2999, mrp: 3999, stockQuantity: 15, attributes: { Size: 'UK 8', Color: 'Tan' } },
      { sku: 'PROD-FTW-014-UK9', name: 'UK 9 / Tan', price: 2999, mrp: 3999, stockQuantity: 15, attributes: { Size: 'UK 9', Color: 'Tan' } },
    ]
  },
  {
    sku: 'PROD-FTW-015',
    name: 'Under Armour Charged Assert 10 Running Shoes',
    slug: 'under-armour-charged-assert-10',
    description: 'Neutral running shoes built to cushion impact with Charged Cushioning midsole, lightweight breathable mesh upper with durable leather overlays for locking in midfoot.',
    brand: 'Under Armour',
    categorySlug: 'footwear',
    subcategorySlug: 'sports-running-shoes',
    modelNumber: '3026998-001',
    mrp: 6999,
    currentPrice: 5599,
    originalPrice: 6999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 25,
    lowStockThreshold: 5,
    rating: 4.6,
    reviewCount: 140,
    tags: ['under armour', 'charged assert', 'running shoes', 'black sports shoes'],
    specifications: { Upper: 'Mesh with Leather Overlays', Midsole: 'Charged Cushioning', Sockliner: 'EVA Sockliner', HeelDrop: '10mm' },
    images: [
      { url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Under Armour Charged Assert 10 Profile' },
      { url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Under Armour Logo & Mesh Upper' },
      { url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Under Armour Charged Cushion Heel' },
      { url: 'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Under Armour Rubber Outsole Pods' },
    ],
    variants: [
      { sku: 'PROD-FTW-015-UK8', name: 'UK 8 / Black', price: 5599, mrp: 6999, stockQuantity: 12, attributes: { Size: 'UK 8', Color: 'Black' } },
      { sku: 'PROD-FTW-015-UK9', name: 'UK 9 / Black', price: 5599, mrp: 6999, stockQuantity: 13, attributes: { Size: 'UK 9', Color: 'Black' } },
    ]
  },
  {
    sku: 'PROD-FTW-016',
    name: 'Timberland 6-Inch Premium Waterproof Boots',
    slug: 'timberland-6-inch-waterproof-boots',
    description: 'The original yellow wheat waterproof boot crafted from premium full-grain leather, seam-sealed construction, 400g PrimaLoft insulation, and anti-fatigue footbed.',
    brand: 'Timberland',
    categorySlug: 'footwear',
    subcategorySlug: 'sneakers-casual-shoes',
    modelNumber: 'TB010061713',
    mrp: 19999,
    currentPrice: 16999,
    originalPrice: 19999,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 15,
    lowStockThreshold: 3,
    rating: 4.9,
    reviewCount: 320,
    tags: ['timberland', 'yellow boot', '6 inch boots', 'waterproof boots', 'nubuck'],
    specifications: { Upper: 'Waterproof Full Grain Nubuck', Insulation: '400g PrimaLoft', Outsole: 'Rubber Lug', Height: '6-Inch' },
    images: [
      { url: 'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Timberland 6-Inch Wheat Nubuck Boots' },
      { url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Timberland Side Padded Ankle Collar' },
      { url: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Timberland Brass Eyelets & Taslan Laces' },
      { url: 'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Timberland Deep Lug Rubber Outsole' },
    ],
    variants: [
      { sku: 'PROD-FTW-016-UK8', name: 'UK 8 / Wheat Yellow', price: 16999, mrp: 19999, stockQuantity: 7, attributes: { Size: 'UK 8', Color: 'Wheat Yellow' } },
      { sku: 'PROD-FTW-016-UK9', name: 'UK 9 / Wheat Yellow', price: 16999, mrp: 19999, stockQuantity: 8, attributes: { Size: 'UK 9', Color: 'Wheat Yellow' } },
    ]
  },
  {
    sku: 'PROD-FTW-017',
    name: 'Reebok Club C 85 Vintage Leather Sneakers',
    slug: 'reebok-club-c-85-vintage',
    description: 'Heritage court sneaker featuring soft garment leather upper, terry cloth towel lining, molded EVA midsole for lightweight cushioning, and high-abrasion rubber outsole.',
    brand: 'Reebok',
    categorySlug: 'footwear',
    subcategorySlug: 'sneakers-casual-shoes',
    modelNumber: 'AR0454',
    mrp: 7999,
    currentPrice: 5999,
    originalPrice: 7999,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 5,
    rating: 4.7,
    reviewCount: 210,
    tags: ['reebok', 'club c 85', 'vintage sneakers', 'chalk white', 'tennis shoe'],
    specifications: { Upper: 'Garment Leather', Lining: 'Terry Cloth', Midsole: 'Die-cut EVA', Style: 'Tennis Heritage' },
    images: [
      { url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Reebok Club C 85 Vintage Chalk White' },
      { url: 'https://images.unsplash.com/photo-1600269452121-4f2416e55c28?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Reebok Club C 85 Heel Profile' },
      { url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Reebok Window Box Logo Detail' },
      { url: 'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Reebok Rubber Outsole Tread' },
    ],
    variants: [
      { sku: 'PROD-FTW-017-UK8', name: 'UK 8 / Chalk White', price: 5999, mrp: 7999, stockQuantity: 15, attributes: { Size: 'UK 8', Color: 'Chalk White' } },
      { sku: 'PROD-FTW-017-UK9', name: 'UK 9 / Chalk White', price: 5999, mrp: 7999, stockQuantity: 15, attributes: { Size: 'UK 9', Color: 'Chalk White' } },
    ]
  },
  {
    sku: 'PROD-FTW-018',
    name: 'Hoka One One Clifton 9 Neutral Running Shoes',
    slug: 'hoka-clifton-9-running',
    description: 'Award-winning daily mileage runner with ultra-light compression-molded EVA midsole, early-stage Meta-Rocker geometry for smooth transitions, and breathable knit upper.',
    brand: 'Hoka',
    categorySlug: 'footwear',
    subcategorySlug: 'sports-running-shoes',
    modelNumber: '1127895',
    mrp: 14999,
    currentPrice: 12749,
    originalPrice: 14999,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 20,
    lowStockThreshold: 4,
    rating: 4.9,
    reviewCount: 310,
    tags: ['hoka', 'clifton 9', 'maximalist cushion', 'marathon running', 'hoka running'],
    specifications: { Midsole: 'CMEVA Foam', Technology: 'Early Stage Meta-Rocker', HeelDrop: '5mm', Weight: '248g' },
    images: [
      { url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Hoka Clifton 9 Running Shoe Lateral View' },
      { url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Hoka Clifton 9 Thick Midsole Profile' },
      { url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Hoka Clifton 9 Heel Collar & Tongue' },
      { url: 'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Hoka Durabrasion Rubber Outsole' },
    ],
    variants: [
      { sku: 'PROD-FTW-018-UK8', name: 'UK 8 / Black White', price: 12749, mrp: 14999, stockQuantity: 10, attributes: { Size: 'UK 8', Color: 'Black White' } },
      { sku: 'PROD-FTW-018-UK9', name: 'UK 9 / Black White', price: 12749, mrp: 14999, stockQuantity: 10, attributes: { Size: 'UK 9', Color: 'Black White' } },
    ]
  },
  {
    sku: 'PROD-FTW-019',
    name: 'Louis Philippe Leather Double Monk Strap Dress Shoes',
    slug: 'louis-philippe-double-monk-strap',
    description: 'Exquisite handcrafted formal dress shoes made with premium Italian calfskin leather, laser micro-perforated details, cushioned leather footbed, and polished leather-resin hybrid sole.',
    brand: 'Louis Philippe',
    categorySlug: 'footwear',
    subcategorySlug: 'formal-shoes-loafers',
    modelNumber: 'LPFGMS011',
    mrp: 8999,
    currentPrice: 7199,
    originalPrice: 8999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 16,
    lowStockThreshold: 3,
    rating: 4.8,
    reviewCount: 95,
    tags: ['louis philippe', 'monk strap', 'formal shoes', 'black leather', 'italian calfskin'],
    specifications: { Upper: 'Italian Calfskin Leather', Sole: 'Leather-Resin Hybrid', Buckles: 'Gunmetal Finish', Fit: 'Regular' },
    images: [
      { url: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Louis Philippe Black Double Monk Strap Pair' },
      { url: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Louis Philippe Gunmetal Buckles Closeup' },
      { url: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Louis Philippe Leather Polish Sheen' },
      { url: 'https://images.unsplash.com/photo-1560343776-97e7d202ff0e?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Louis Philippe Hybrid Leather Sole' },
    ],
    variants: [
      { sku: 'PROD-FTW-019-UK8', name: 'UK 8 / Black', price: 7199, mrp: 8999, stockQuantity: 8, attributes: { Size: 'UK 8', Color: 'Black' } },
      { sku: 'PROD-FTW-019-UK9', name: 'UK 9 / Black', price: 7199, mrp: 8999, stockQuantity: 8, attributes: { Size: 'UK 9', Color: 'Black' } },
    ]
  },
  {
    sku: 'PROD-FTW-020',
    name: 'Decathlon Kiprun KS900 Light Distance Running Shoes',
    slug: 'decathlon-kiprun-ks900-light',
    description: 'Engineered for half-marathon and marathon runners featuring MFOAM cushioning foam for maximum vibration damping, wide sole base for stability, and high-traction rubber outsole.',
    brand: 'Decathlon Kiprun',
    categorySlug: 'footwear',
    subcategorySlug: 'sports-running-shoes',
    modelNumber: '8644510',
    mrp: 6999,
    currentPrice: 5999,
    originalPrice: 6999,
    discount: 14.3,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 35,
    lowStockThreshold: 7,
    rating: 4.6,
    reviewCount: 175,
    tags: ['decathlon', 'kiprun', 'running shoes', 'mfoam', 'marathon'],
    specifications: { Midsole: 'MFOAM Cushioning', Drop: '6mm', Weight: '252g', Durability: '1000km guarantee' },
    images: [
      { url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Decathlon Kiprun KS900 Light Lateral Profile' },
      { url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Decathlon Kiprun Front Mesh Toe Box' },
      { url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Decathlon Kiprun MFOAM Cushion Layer' },
      { url: 'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Decathlon Kiprun Rubber Outsole Tread' },
    ],
    variants: [
      { sku: 'PROD-FTW-020-UK8', name: 'UK 8 / Blue Cyan', price: 5999, mrp: 6999, stockQuantity: 18, attributes: { Size: 'UK 8', Color: 'Blue Cyan' } },
      { sku: 'PROD-FTW-020-UK9', name: 'UK 9 / Blue Cyan', price: 5999, mrp: 6999, stockQuantity: 17, attributes: { Size: 'UK 9', Color: 'Blue Cyan' } },
    ]
  }
];
