import { ProductStatus } from '@prisma/client';

export const healthWellnessProducts = [
  {
    sku: 'PROD-HLT-001',
    name: 'Theragun PRO G5 Deep Tissue Percussive Massage Gun',
    slug: 'theragun-pro-g5-percussive-massage-gun',
    description: 'Professional-grade deep tissue percussive therapy device featuring QuietForce Technology, OLED screen, Bluetooth app integration, and 6 attachments.',
    brand: 'Therabody',
    categorySlug: 'health-wellness',
    subcategorySlug: 'recovery-massage-guns',
    modelNumber: 'TG-PRO-G5',
    mrp: 49999,
    currentPrice: 42499,
    originalPrice: 49999,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 10,
    lowStockThreshold: 2,
    rating: 4.9,
    reviewCount: 310,
    tags: ['theragun', 'therabody', 'massage gun', 'percussive therapy', 'muscle recovery'],
    specifications: { Amplitude: '16mm Deep Percussion', Speed: '5 Customizable Speeds (1750-2400 PPM)', StallForce: '60 lbs No Stall Force', Battery: '2 Swappable Lithium-Ion Batteries' },
    images: [
      { url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Theragun PRO G5 Black Triangle Ergonomic Handle' },
      { url: 'https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Theragun PRO OLED Display & Force Meter Meter' },
      { url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Theragun 6 Closed-Cell Foam Attachment Heads' },
      { url: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Theragun Hard Carrying Travel Case' },
    ],
    variants: [
      { sku: 'PROD-HLT-001-BLK', name: 'Black Professional G5 Kit', price: 42499, mrp: 49999, stockQuantity: 10, attributes: { Color: 'Black' } }
    ]
  },
  {
    sku: 'PROD-HLT-002',
    name: 'Withings Body Comp Wi-Fi Smart Body Composition Scale',
    slug: 'withings-body-comp-smart-scale',
    description: 'Precision smart scale offering clinical-grade body composition analysis (fat, muscle mass, water, bone mass), Visceral Fat assessment, and Vascular Age metric.',
    brand: 'Withings',
    categorySlug: 'health-wellness',
    subcategorySlug: 'smart-scales-monitors',
    modelNumber: 'WBS12-BLK',
    mrp: 19999,
    currentPrice: 16999,
    originalPrice: 19999,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 15,
    lowStockThreshold: 3,
    rating: 4.8,
    reviewCount: 220,
    tags: ['withings', 'smart scale', 'body fat scale', 'withings body comp', 'vascular age'],
    specifications: { Metrics: 'Body Fat %, Muscle, Water, Bone, Visceral Fat, Nerve Health', Accuracy: '50g Precision Position Control', Screen: 'High Res Color LCD Screen', Sync: 'Wi-Fi & Bluetooth Withings App' },
    images: [
      { url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Withings Body Comp Black Tempered Glass Surface' },
      { url: 'https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Withings Color Screen Metric Graph Display' },
      { url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Withings Electrodes Strip Alignment Line' },
      { url: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Withings Health Mate App Synchronization' },
    ],
    variants: [
      { sku: 'PROD-HLT-002-BLK', name: 'Black Tempered Glass', price: 16999, mrp: 19999, stockQuantity: 10, attributes: { Color: 'Black' } },
      { sku: 'PROD-HLT-002-WHT', name: 'White Tempered Glass', price: 16999, mrp: 19999, stockQuantity: 5, attributes: { Color: 'White' } },
    ]
  },
  {
    sku: 'PROD-HLT-003',
    name: 'Omron Evolv Wireless Upper Arm Blood Pressure Monitor',
    slug: 'omron-evolv-wireless-blood-pressure-monitor',
    description: 'All-in-one tubeless upper arm blood pressure monitor featuring Intelli Wrap Cuff technology for accurate 360-degree readings and Omron Connect app sync.',
    brand: 'Omron',
    categorySlug: 'health-wellness',
    subcategorySlug: 'smart-scales-monitors',
    modelNumber: 'BP7000',
    mrp: 9999,
    currentPrice: 7999,
    originalPrice: 9999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 25,
    lowStockThreshold: 5,
    rating: 4.9,
    reviewCount: 450,
    tags: ['omron', 'omron evolv', 'blood pressure monitor', 'bp monitor', 'wireless bp cuff'],
    specifications: { Design: 'Tubeless One-Piece Compact Design', Cuff: 'Intelli Wrap Cuff (22-42 cm)', Validation: 'Clinically Validated', Bluetooth: 'Omron Connect App' },
    images: [
      { url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Omron Evolv Tubeless BP Monitor Attached on Arm' },
      { url: 'https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Omron Evolv OLED Digital Systolic Reading Screen' },
      { url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Omron Intelli Wrap Pre-Formed Cuff Lining' },
      { url: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Omron Connect App History Graph' },
    ],
    variants: [
      { sku: 'PROD-HLT-003-BP', name: 'Evolv Tubeless BP Monitor', price: 7999, mrp: 9999, stockQuantity: 25, attributes: { Model: 'Evolv All-in-One' } }
    ]
  },
  {
    sku: 'PROD-HLT-004',
    name: 'Hyperice Hypervolt 2 Pro Percussive Massager',
    slug: 'hyperice-hypervolt-2-pro-massage-gun',
    description: 'High-torque 90W brushless motor percussive massage gun with 5 speed dial, Bluetooth connected Hyperice App guided routines, and QuietGlide technology.',
    brand: 'Hyperice',
    categorySlug: 'health-wellness',
    subcategorySlug: 'recovery-massage-guns',
    modelNumber: 'HYP-HV2-PRO',
    mrp: 38999,
    currentPrice: 33149,
    originalPrice: 38999,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 12,
    lowStockThreshold: 3,
    rating: 4.8,
    reviewCount: 260,
    tags: ['hyperice', 'hypervolt 2 pro', 'massage gun', 'athletic recovery', 'percussive massager'],
    specifications: { Motor: '90W High Torque Brushless Motor', Speeds: '5 Speed Dial', Attachments: '5 Head Attachments (Fork, Ball, Cushion, Flat, Bullet)', Weight: '1.18 kg' },
    images: [
      { url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Hyperice Hypervolt 2 Pro Matte Black Body' },
      { url: 'https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Hyperice Digital Speed Control Dial Ring' },
      { url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Hyperice 5 Interchangeable Head Nozzles' },
      { url: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Hyperice Battery Level LED Light Strip' },
    ],
    variants: [
      { sku: 'PROD-HLT-004-BLK', name: 'Matte Black Pro Kit', price: 33149, mrp: 38999, stockQuantity: 12, attributes: { Color: 'Matte Black' } }
    ]
  },
  {
    sku: 'PROD-HLT-005',
    name: 'Bauerfeind GenuTrain Knee Support Brace',
    slug: 'bauerfeind-genutrain-knee-support-brace',
    description: 'Medical-grade German anatomical knit knee brace featuring Omega pad visco-elastic insert to relieve knee joint pain, swelling, and patella tracking.',
    brand: 'Bauerfeind',
    categorySlug: 'health-wellness',
    subcategorySlug: 'supports-braces',
    modelNumber: 'BF-GT-KNEE-03',
    mrp: 9999,
    currentPrice: 8499,
    originalPrice: 9999,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 20,
    lowStockThreshold: 4,
    rating: 4.9,
    reviewCount: 380,
    tags: ['bauerfeind', 'genutrain', 'knee brace', 'knee support', 'german orthopedic'],
    specifications: { Material: 'Breathable 3D Train Knit Fabric', Insert: 'Visco-Elastic Omega Ring Pad', Origin: 'Made in Germany', Indications: 'Arthritis, Meniscus Tear, Patella Instability' },
    images: [
      { url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Bauerfeind GenuTrain Knee Sleeve Titanium Front' },
      { url: 'https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Bauerfeind Omega Visco-Elastic Silicone Ring' },
      { url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Bauerfeind 3D Compression Anatomical Knit Weave' },
      { url: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Bauerfeind Integrated Donning Handles Side' },
    ],
    variants: [
      { sku: 'PROD-HLT-005-SZ3', name: 'Size 3 (Thigh 44-47cm)', price: 8499, mrp: 9999, stockQuantity: 10, attributes: { Size: 'Size 3' } },
      { sku: 'PROD-HLT-005-SZ4', name: 'Size 4 (Thigh 47-50cm)', price: 8499, mrp: 9999, stockQuantity: 10, attributes: { Size: 'Size 4' } },
    ]
  },
  {
    sku: 'PROD-HLT-006',
    name: 'AGARO Supreme Foot & Calf Massager with Heat',
    slug: 'agaro-supreme-foot-and-calf-massager',
    description: 'Electrical leg massager providing kneading, rolling, reflexology Shiatsu massage, and vibration with thermal heating for calves, ankles, and feet.',
    brand: 'AGARO',
    categorySlug: 'health-wellness',
    subcategorySlug: 'recovery-massage-guns',
    modelNumber: 'AG-SUP-33157',
    mrp: 14999,
    currentPrice: 11249,
    originalPrice: 14999,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 15,
    lowStockThreshold: 3,
    rating: 4.6,
    reviewCount: 310,
    tags: ['agaro', 'foot massager', 'calf massager', 'shiatsu leg massager', 'heating massager'],
    specifications: { Modes: '4 Automatic Programs + 3 Custom Speed Modes', Heating: 'Infrared Warm Heat Therapy', Covers: 'Removable Washable Fabric Sleeves', Tilt: 'Adjustable Incline Bar' },
    images: [
      { url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'AGARO Supreme Foot Calf Massager Unit Front' },
      { url: 'https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'AGARO Touch Control Button Panel Top' },
      { url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'AGARO Dual Calf Kneading Rollers Chamber' },
      { url: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'AGARO Bottom Tilt Stand Bracket' },
    ],
    variants: [
      { sku: 'PROD-HLT-006-BLK', name: 'Black & Metallic Silver', price: 11249, mrp: 14999, stockQuantity: 15, attributes: { Color: 'Black/Silver' } }
    ]
  },
  {
    sku: 'PROD-HLT-007',
    name: 'Accu-Chek Guide Wireless Blood Glucose Meter Kit',
    slug: 'accu-chek-guide-blood-glucose-meter-kit',
    description: 'Spill-resistant SmartPack vial diabetes monitoring kit with Bluetooth sync to Mysugr app, backlit display, and fast under 4 second test result time.',
    brand: 'Accu-Chek',
    categorySlug: 'health-wellness',
    subcategorySlug: 'smart-scales-monitors',
    modelNumber: 'ACC-GUIDE-KIT',
    mrp: 2499,
    currentPrice: 1999,
    originalPrice: 2499,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.8,
    reviewCount: 650,
    tags: ['accu-chek', 'accu chek guide', 'glucometer', 'blood sugar monitor', 'diabetes monitor'],
    specifications: { Includes: 'Guide Meter + FastClix Lancing Device + 50 Test Strips', TestTime: 'Less than 4 Seconds', SampleSize: '0.6 microliters', Connectivity: 'Bluetooth Mysugr App' },
    images: [
      { url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Accu-Chek Guide Glucose Meter & Test Strip Vial' },
      { url: 'https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Accu-Chek Guide Backlit LCD Screen Value Reading' },
      { url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Accu-Chek FastClix Lancing Pen Drum Cartridge' },
      { url: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Accu-Chek Zippered Travel Case Set' },
    ],
    variants: [
      { sku: 'PROD-HLT-007-KIT', name: 'Guide Meter + 50 Strips Kit', price: 1999, mrp: 2499, stockQuantity: 40, attributes: { Pack: 'Complete Kit' } }
    ]
  },
  {
    sku: 'PROD-HLT-008',
    name: 'Dr Trust USA Smart Pulse Oximeter Fingertip Monitor',
    slug: 'dr-trust-usa-smart-pulse-oximeter-fingertip',
    description: 'Fingertip pulse oximeter with OLED display measuring SpO2 oxygen saturation, Pulse Rate, Perfusion Index (PI), and respiratory rate with audio alarm.',
    brand: 'Dr Trust',
    categorySlug: 'health-wellness',
    subcategorySlug: 'smart-scales-monitors',
    modelNumber: 'DRT-OXI-509',
    mrp: 1999,
    currentPrice: 1199,
    originalPrice: 1999,
    discount: 40.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 50,
    lowStockThreshold: 10,
    rating: 4.7,
    reviewCount: 920,
    tags: ['dr trust', 'pulse oximeter', 'spo2 monitor', 'oxygen level monitor', 'fingertip oximeter'],
    specifications: { Screen: 'Dual Color OLED Display', Measurements: 'SpO2 + Pulse Rate + PI Index', Sensor: 'High Precision Photoelectric Sensor', AutoOff: 'Auto Power Off in 8 Seconds' },
    images: [
      { url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Dr Trust Fingertip Pulse Oximeter Clip Profile' },
      { url: 'https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Dr Trust OLED SpO2 Percentage Reading Screen' },
      { url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Dr Trust Soft Silicone Finger Chamber' },
      { url: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Dr Trust Lanyard & AAA Batteries Included' },
    ],
    variants: [
      { sku: 'PROD-HLT-008-BLK', name: 'Black OLED Oximeter', price: 1199, mrp: 1999, stockQuantity: 30, attributes: { Color: 'Black' } },
      { sku: 'PROD-HLT-008-BLU', name: 'Blue OLED Oximeter', price: 1199, mrp: 1999, stockQuantity: 20, attributes: { Color: 'Blue' } },
    ]
  },
  {
    sku: 'PROD-HLT-009',
    name: 'Tynor Posture Corrector Belt Adjustable Lumbar Support',
    slug: 'tynor-posture-corrector-belt',
    description: 'Ergonomic back brace with rigid aluminum stays pulling shoulders back to correct slouching, relieve upper back pain, and align spine.',
    brand: 'Tynor',
    categorySlug: 'health-wellness',
    subcategorySlug: 'supports-braces',
    modelNumber: 'TYN-A-33-L',
    mrp: 1499,
    currentPrice: 1049,
    originalPrice: 1499,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.5,
    reviewCount: 510,
    tags: ['tynor', 'posture corrector', 'back belt', 'spine support', 'shoulder brace'],
    specifications: { Stays: 'Customizable Malleable Aluminum Stays', Straps: 'Padded Underarm Straps', Closure: 'Hook and Loop Fasteners', Fabric: 'Porous Breathable Elastic' },
    images: [
      { url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Tynor Posture Corrector Belt Front & Back View' },
      { url: 'https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Tynor Shoulder Straps & Buckle Tensioner' },
      { url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Tynor Malleable Aluminum Splint Stays' },
      { url: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Tynor Breathable Porous Webbing Mesh' },
    ],
    variants: [
      { sku: 'PROD-HLT-009-M', name: 'Medium (Chest 34-40 in)', price: 1049, mrp: 1499, stockQuantity: 20, attributes: { Size: 'Medium' } },
      { sku: 'PROD-HLT-009-L', name: 'Large (Chest 40-46 in)', price: 1049, mrp: 1499, stockQuantity: 20, attributes: { Size: 'Large' } },
    ]
  },
  {
    sku: 'PROD-HLT-010',
    name: 'Beurer FT90 Non-Contact Infrared Clinical Thermometer',
    slug: 'beurer-ft90-non-contact-infrared-thermometer',
    description: 'Medical-grade German non-contact forehead thermometer measuring body, ambient, and surface temperature in seconds with fever alarm.',
    brand: 'Beurer',
    categorySlug: 'health-wellness',
    subcategorySlug: 'smart-scales-monitors',
    modelNumber: 'FT-90',
    mrp: 4999,
    currentPrice: 3749,
    originalPrice: 4999,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 25,
    lowStockThreshold: 5,
    rating: 4.8,
    reviewCount: 340,
    tags: ['beurer', 'infrared thermometer', 'non contact thermometer', 'forehead thermometer', 'fever alarm'],
    specifications: { Distance: '2 to 3 cm Distance Measurement', Speed: '1 Second Measurement', Memory: '60 Temperature Memory Spaces', Display: 'XL Blue Backlit Screen' },
    images: [
      { url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Beurer FT90 White Infrared Thermometer Handheld' },
      { url: 'https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Beurer Blue Backlit LCD Screen Temperature Value' },
      { url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Beurer Front Infrared Sensor Lens' },
      { url: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Beurer Protective Storage Case' },
    ],
    variants: [
      { sku: 'PROD-HLT-010-FT90', name: 'FT90 Infrared Model', price: 3749, mrp: 4999, stockQuantity: 25, attributes: { Model: 'FT90' } }
    ]
  },
  {
    sku: 'PROD-HLT-011',
    name: 'Caresmith Wave Rechargeable Body Massager',
    slug: 'caresmith-wave-rechargeable-body-massager',
    description: 'Cordless handheld percussion full body massager featuring 6 interchangeable massage heads, 5 vibration modes, and high-torque copper motor.',
    brand: 'Caresmith',
    categorySlug: 'health-wellness',
    subcategorySlug: 'recovery-massage-guns',
    modelNumber: 'CS-WAVE-01',
    mrp: 2999,
    currentPrice: 1799,
    originalPrice: 2999,
    discount: 40.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 6,
    rating: 4.6,
    reviewCount: 380,
    tags: ['caresmith', 'body massager', 'handheld massager', 'percussion massager', 'back massager'],
    specifications: { Motor: '24W Pure Copper Motor (3200 RPM)', Battery: '2000 mAh Li-ion (140 mins run time)', Heads: '6 Distinct Attachment Heads', Modes: '5 Intensity Levels' },
    images: [
      { url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Caresmith Wave Handheld Massager Long Handle' },
      { url: 'https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Caresmith 6 Massage Attachment Heads Array' },
      { url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Caresmith Soft Rubber Handle Grip' },
      { url: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Caresmith USB Charging Cable' },
    ],
    variants: [
      { sku: 'PROD-HLT-011-WAVE', name: 'White & Grey Wave Kit', price: 1799, mrp: 2999, stockQuantity: 30, attributes: { Color: 'White/Grey' } }
    ]
  },
  {
    sku: 'PROD-HLT-012',
    name: 'Mueller Sports Medicine Adjustable Wrist Support Brace',
    slug: 'mueller-sports-medicine-wrist-brace',
    description: 'Neoprene blend wrist support brace featuring adjustable hook and loop straps, perforated fabric for heat release, and firm wrist compression.',
    brand: 'Mueller',
    categorySlug: 'health-wellness',
    subcategorySlug: 'supports-braces',
    modelNumber: 'MUE-WRST-01',
    mrp: 1499,
    currentPrice: 1049,
    originalPrice: 1499,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 35,
    lowStockThreshold: 7,
    rating: 4.7,
    reviewCount: 290,
    tags: ['mueller', 'wrist brace', 'wrist support', 'carpal tunnel brace', 'sports wrist wrap'],
    specifications: { Fit: 'Universal Fits Left or Right Wrist', Material: 'Perforated Neoprene Blend', Indications: 'Carpal Tunnel, Sprains, Tendonitis', Strap: 'Dual Adjustable Compression Straps' },
    images: [
      { url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Mueller Black Adjustable Wrist Brace Wrapped' },
      { url: 'https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Mueller Thumb Loop Hole Passage' },
      { url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Mueller Velcro Fastener Straps Close' },
      { url: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Mueller Perforated Neoprene Fabric Texture' },
    ],
    variants: [
      { sku: 'PROD-HLT-012-BLK', name: 'Universal Black Size', price: 1049, mrp: 1499, stockQuantity: 35, attributes: { Size: 'Universal' } }
    ]
  },
  {
    sku: 'PROD-HLT-013',
    name: 'Eufy Smart Scale P2 Pro Body Composition Analyzer',
    slug: 'eufy-smart-scale-p2-pro',
    description: 'Wi-Fi & Bluetooth body fat scale analyzing 16 health metrics including 3D virtual body model, heart rate, muscle mass, body fat, and visceral fat.',
    brand: 'Eufy by Anker',
    categorySlug: 'health-wellness',
    subcategorySlug: 'smart-scales-monitors',
    modelNumber: 'T9149',
    mrp: 5999,
    currentPrice: 4499,
    originalPrice: 5999,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 25,
    lowStockThreshold: 5,
    rating: 4.8,
    reviewCount: 390,
    tags: ['eufy', 'smart scale p2 pro', 'body fat scale', 'eufy scale', '3d body model'],
    specifications: { Metrics: '16 Body Metrics', Technology: 'High-Precision ITO Coating Sensors', IPXRating: 'IPX5 Waterproof Rating', App: 'EufyLife App + Apple Health / Fitbit' },
    images: [
      { url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Eufy Smart Scale P2 Pro Black Glass Surface' },
      { url: 'https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Eufy Full Surface ITO Coating Glass' },
      { url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Eufy Bright LED Weight Display' },
      { url: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Eufy 3D Avatar Body Model App Screen' },
    ],
    variants: [
      { sku: 'PROD-HLT-013-BLK', name: 'Black P2 Pro', price: 4499, mrp: 5999, stockQuantity: 15, attributes: { Color: 'Black' } },
      { sku: 'PROD-HLT-013-WHT', name: 'White P2 Pro', price: 4499, mrp: 5999, stockQuantity: 10, attributes: { Color: 'White' } },
    ]
  },
  {
    sku: 'PROD-HLT-014',
    name: 'FormFit Ankle Stirrup Brace for Sprains and Recovery',
    slug: 'formfit-ankle-stirrup-brace-sprain-support',
    description: 'Rigid semi-shell ankle support brace with gel/air padding system to immobilize inversion/eversion movement while allowing normal walking.',
    brand: 'FormFit',
    categorySlug: 'health-wellness',
    subcategorySlug: 'supports-braces',
    modelNumber: 'FF-ANK-ST',
    mrp: 2999,
    currentPrice: 2249,
    originalPrice: 2999,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 20,
    lowStockThreshold: 4,
    rating: 4.7,
    reviewCount: 180,
    tags: ['formfit', 'ankle brace', 'ankle support', 'stirrup brace', 'ankle sprain support'],
    specifications: { Shell: 'Anatomical Rigid Plastic Shells', Padding: 'Cold Therapy Gel Pads', Fit: 'Universal Fit (Fits Inside Most Shoes)', Straps: 'Dual Hook and Loop Straps' },
    images: [
      { url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'FormFit Ankle Stirrup Brace White Shell Profile' },
      { url: 'https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'FormFit Gel Air Cushion Lining Insert' },
      { url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'FormFit Heel Stirrup Width Strap Adjustment' },
      { url: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'FormFit Ankle Brace Worn Inside Athletic Shoe' },
    ],
    variants: [
      { sku: 'PROD-HLT-014-UNI', name: 'Universal Size (White/Blue)', price: 2249, mrp: 2999, stockQuantity: 20, attributes: { Size: 'Universal' } }
    ]
  },
  {
    sku: 'PROD-HLT-015',
    name: 'Lifelong LLM99 Foot Spa Pedicure Massager with Bubbles and Heat',
    slug: 'lifelong-llm99-foot-spa-pedicure-massager',
    description: 'Electric foot bath spa massager featuring automatic temperature control heating, bubbling oxygen jets, infrared light, and 8 manual massage rollers.',
    brand: 'Lifelong',
    categorySlug: 'health-wellness',
    subcategorySlug: 'recovery-massage-guns',
    modelNumber: 'LLM99',
    mrp: 3999,
    currentPrice: 2399,
    originalPrice: 3999,
    discount: 40.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 25,
    lowStockThreshold: 5,
    rating: 4.6,
    reviewCount: 420,
    tags: ['lifelong', 'foot spa', 'pedicure massager', 'foot bath', 'bubble massager'],
    specifications: { Functions: 'Heat Water + Bubble Jet Spa + Infrared Light', Temperature: 'Maintains Water up to 45 deg C', Rollers: '8 Removable Massage Rollers', Safety: 'Water-Electricity Separation Protection' },
    images: [
      { url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Lifelong Foot Spa Tub Water Bubbling Top' },
      { url: 'https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Lifelong Digital Touch Control Buttons & Temperature Display' },
      { url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Lifelong Bottom Massage Rollers Grid' },
      { url: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Lifelong Drain Pipe & Anti-Splash Guard' },
    ],
    variants: [
      { sku: 'PROD-HLT-015-WHT', name: 'White & Blue Foot Spa', price: 2399, mrp: 3999, stockQuantity: 25, attributes: { Color: 'White/Blue' } }
    ]
  }
];
