import { ProductStatus } from '@prisma/client';

export const homeAppliancesProducts = [
  {
    sku: 'PROD-HAP-001',
    name: 'Dyson V15 Detect Cordless Vacuum Cleaner',
    slug: 'dyson-v15-detect-cordless-vacuum',
    description: 'Most powerful intelligent cordless vacuum cleaner with laser illumination revealing microscopic dust, piezo sensor counting dust particles, and Hyperdymium motor.',
    brand: 'Dyson',
    categorySlug: 'home-appliances',
    subcategorySlug: 'vacuum-cleaners',
    modelNumber: '368340-01',
    mrp: 65900,
    currentPrice: 59900,
    originalPrice: 65900,
    discount: 9.1,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 15,
    lowStockThreshold: 3,
    rating: 4.9,
    reviewCount: 420,
    tags: ['dyson', 'v15 detect', 'cordless vacuum', 'laser dust', 'hepa vacuum'],
    specifications: { SuctionPower: '240 AW', RunTime: 'Up to 60 Minutes', Filtration: '99.99% down to 0.3 microns', Weight: '3.0 kg' },
    images: [
      { url: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Dyson V15 Detect Cordless Vacuum Cleaner Stand' },
      { url: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Dyson Fluffy Optic Cleaner Head Green Laser Light' },
      { url: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Dyson LCD Screen Particle Count Graph' },
      { url: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Dyson Quick Release Attachments Dock' },
    ],
    variants: [
      { sku: 'PROD-HAP-001-GOLD', name: 'Yellow / Nickel', price: 59900, mrp: 65900, stockQuantity: 10, attributes: { Color: 'Yellow/Nickel' } },
      { sku: 'PROD-HAP-001-BLU', name: 'Prussian Blue / Gold', price: 62900, mrp: 68900, stockQuantity: 5, attributes: { Color: 'Prussian Blue/Gold' } },
    ]
  },
  {
    sku: 'PROD-HAP-002',
    name: 'Samsung Bespoke AI 653L French Door Refrigerator',
    slug: 'samsung-bespoke-ai-653l-refrigerator',
    description: 'AI Energy Mode smart refrigerator with customizable glass door panels, Beverage Center with AutoFill Water Pitcher, Dual Auto Ice Maker, and Twin Cooling Plus.',
    brand: 'Samsung',
    categorySlug: 'home-appliances',
    subcategorySlug: 'cooling-heating',
    modelNumber: 'RF65DB9000',
    mrp: 185000,
    currentPrice: 157250,
    originalPrice: 185000,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 6,
    lowStockThreshold: 1,
    rating: 4.8,
    reviewCount: 95,
    tags: ['samsung', 'bespoke AI', 'french door refrigerator', 'smart fridge', 'beverage center'],
    specifications: { Capacity: '653 Liters', EnergyRating: '5 Star Inverter', Compressors: 'Digital Inverter 20 Yrs Warranty', SmartFeatures: 'SmartThings AI Energy' },
    images: [
      { url: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Samsung Bespoke AI French Door Refrigerator Front' },
      { url: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Samsung Beverage Center Door-in-Door Access' },
      { url: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Samsung Interior LED Shelving Space' },
      { url: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Samsung Dual Ice Maker Cubes Drawer' },
    ],
    variants: [
      { sku: 'PROD-HAP-002-WHT', name: 'Clean White Glass Panels', price: 157250, mrp: 185000, stockQuantity: 3, attributes: { Finish: 'Clean White Glass' } },
      { sku: 'PROD-HAP-002-NVY', name: 'Navy & Cotta Glass Panels', price: 157250, mrp: 185000, stockQuantity: 3, attributes: { Finish: 'Navy/Cotta Glass' } },
    ]
  },
  {
    sku: 'PROD-HAP-003',
    name: 'Philips AC3259/20 High Performance Smart Air Purifier',
    slug: 'philips-ac3259-20-smart-air-purifier',
    description: 'AeraSense technology air purifier covering rooms up to 102 sq m, removing 99.97% of airborne allergens, PM2.5, viruses, and gases with NanoProtect HEPA filter.',
    brand: 'Philips',
    categorySlug: 'home-appliances',
    subcategorySlug: 'air-purifiers',
    modelNumber: 'AC3259/20',
    mrp: 37995,
    currentPrice: 28496,
    originalPrice: 37995,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 20,
    lowStockThreshold: 4,
    rating: 4.7,
    reviewCount: 310,
    tags: ['philips', 'air purifier', 'hepa purifier', 'pm2.5 filter', 'allergen filter'],
    specifications: { CADR: '393 m3/h', CoverageArea: 'Up to 102 sq m (1097 sq ft)', FilterType: 'NanoProtect HEPA + Active Carbon', Noise: '33 dB Silent Mode' },
    images: [
      { url: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Philips High Performance Air Purifier White Column' },
      { url: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Philips AeraSense Numerical PM2.5 LED Ring Display' },
      { url: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Philips NanoProtect HEPA Filter Layer Removed' },
      { url: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Philips Air Vent Grille Top Panel' },
    ],
    variants: [
      { sku: 'PROD-HAP-003-WHT', name: 'White High Capacity', price: 28496, mrp: 37995, stockQuantity: 20, attributes: { Color: 'White' } }
    ]
  },
  {
    sku: 'PROD-HAP-004',
    name: 'LG 9kg AI Direct Drive Front Load Washing Machine',
    slug: 'lg-9kg-ai-direct-drive-washing-machine',
    description: 'AI DD motor detects fabric weight and softness to choose optimal wash motion. Steam+ allergy care cycle removes 99.9% dust mites, with Wi-Fi ThinQ remote access.',
    brand: 'LG',
    categorySlug: 'home-appliances',
    subcategorySlug: 'cooling-heating',
    modelNumber: 'FHP1409Z9B',
    mrp: 52990,
    currentPrice: 42392,
    originalPrice: 52990,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 12,
    lowStockThreshold: 3,
    rating: 4.8,
    reviewCount: 380,
    tags: ['lg', 'washing machine', 'front load washer', 'ai direct drive', 'steam wash'],
    specifications: { Capacity: '9.0 kg', SpinSpeed: '1400 RPM', Motor: 'Inverter Direct Drive 10 Yrs Warranty', Steam: 'Steam+ Hygiene Care' },
    images: [
      { url: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'LG AI Direct Drive Front Load Washing Machine Black Steel' },
      { url: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'LG Chrome Dial Switch & Touch LED Screen' },
      { url: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'LG Tempered Glass Door Opened Stainless Lifters' },
      { url: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'LG Detergent Dispenser Drawer Opened' },
    ],
    variants: [
      { sku: 'PROD-HAP-004-STL', name: 'Middle Black Steel', price: 42392, mrp: 52990, stockQuantity: 8, attributes: { Color: 'Middle Black Steel' } },
      { sku: 'PROD-HAP-004-WHT', name: 'White', price: 39990, mrp: 49990, stockQuantity: 4, attributes: { Color: 'White' } },
    ]
  },
  {
    sku: 'PROD-HAP-005',
    name: 'iRobot Roomba j7+ Self-Emptying Robot Vacuum Cleaner',
    slug: 'irobot-roomba-j7-plus-robot-vacuum',
    description: 'Intelligent robot vacuum using PrecisionVision Navigation to avoid pet waste and cords, automatically emptying its dust bin into Clean Base for 60 days.',
    brand: 'iRobot',
    categorySlug: 'home-appliances',
    subcategorySlug: 'vacuum-cleaners',
    modelNumber: 'j755020',
    mrp: 74900,
    currentPrice: 59920,
    originalPrice: 74900,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 10,
    lowStockThreshold: 2,
    rating: 4.8,
    reviewCount: 290,
    tags: ['irobot', 'roomba j7+', 'robot vacuum', 'self emptying vacuum', 'smart robot vacuum'],
    specifications: { Navigation: 'PrecisionVision Obstacle Avoidance', Base: 'Clean Base Automatic Dirt Disposal', Suction: '10x Power-Lifting Suction', Map: 'Imprint Smart Mapping' },
    images: [
      { url: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'iRobot Roomba j7+ Robot & Clean Base Station' },
      { url: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'iRobot Roomba Front Facing Camera Sensor' },
      { url: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'iRobot Dual Multi-Surface Rubber Brushes Underside' },
      { url: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'iRobot Clean Base Dust Bag Replacement Compartment' },
    ],
    variants: [
      { sku: 'PROD-HAP-005-BLK', name: 'Graphite Metal & Black Base', price: 59920, mrp: 74900, stockQuantity: 10, attributes: { Color: 'Graphite Black' } }
    ]
  },
  {
    sku: 'PROD-HAP-006',
    name: 'Daikin 1.5 Ton 5 Star Inverter Split AC with PM2.5 Filter',
    slug: 'daikin-1-5-ton-5-star-inverter-split-ac',
    description: 'Energy-efficient inverter split air conditioner featuring Dew Clean Technology, PM2.5 filter, Triple Display, 3D Airflow, and 100% copper condenser coil.',
    brand: 'Daikin',
    categorySlug: 'home-appliances',
    subcategorySlug: 'cooling-heating',
    modelNumber: 'MTKM50U',
    mrp: 58400,
    currentPrice: 46720,
    originalPrice: 58400,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 15,
    lowStockThreshold: 3,
    rating: 4.8,
    reviewCount: 520,
    tags: ['daikin', 'split ac', '1.5 ton ac', '5 star ac', 'inverter ac', 'dew clean'],
    specifications: { Capacity: '1.5 Ton (5200W)', EnergyRating: '5 Star ISEER 5.2', Condenser: '100% Copper Coil', Refrigerant: 'R32 Eco Friendly' },
    images: [
      { url: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Daikin 1.5 Ton Split AC Indoor Unit Mounted' },
      { url: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Daikin Triple Digital Display Panel Close' },
      { url: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Daikin Outdoor Compressor Unit Copper Fins' },
      { url: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Daikin Wireless Remote Control' },
    ],
    variants: [
      { sku: 'PROD-HAP-006-15T', name: '1.5 Ton / 5 Star', price: 46720, mrp: 58400, stockQuantity: 15, attributes: { Capacity: '1.5 Ton' } }
    ]
  },
  {
    sku: 'PROD-HAP-007',
    name: 'Eureka Forbes Forbes Vacuum Cleaner Trendy Nano 1000W',
    slug: 'eureka-forbes-trendy-nano-vacuum-cleaner',
    description: 'Compact handheld canister vacuum cleaner with powerful 1000W suction motor, dust bag full indicator, thermal overload cut-off protection, and 5 accessories.',
    brand: 'Eureka Forbes',
    categorySlug: 'home-appliances',
    subcategorySlug: 'vacuum-cleaners',
    modelNumber: 'GFK-TN-1000',
    mrp: 4999,
    currentPrice: 3499,
    originalPrice: 4999,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.5,
    reviewCount: 680,
    tags: ['eureka forbes', 'trendy nano', 'vacuum cleaner', 'canister vacuum', '1000w vacuum'],
    specifications: { Motor: '1000 Watts Suction', Weight: '2.5 kg Portable', DustCapacity: '1.0 Liter', Accessories: 'Floor Brush, Crevice Nozzle, Hose Pipe' },
    images: [
      { url: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Eureka Forbes Trendy Nano Red Vacuum Body' },
      { url: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Eureka Forbes Hose Pipe Attached Floor Brush' },
      { url: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Eureka Forbes Cord Retractor Winding Button' },
      { url: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Eureka Forbes Dust Bag Chamber Opened' },
    ],
    variants: [
      { sku: 'PROD-HAP-007-RED', name: 'Cherry Red & Black', price: 3499, mrp: 4999, stockQuantity: 40, attributes: { Color: 'Cherry Red' } }
    ]
  },
  {
    sku: 'PROD-HAP-008',
    name: 'Xiaomi Smart Air Purifier 4 Pro with HEPA Filter',
    slug: 'xiaomi-smart-air-purifier-4-pro',
    description: 'High-efficiency smart air purifier featuring 500m³/h CADR, dual PM2.5/PM10 sensor, OLED touch display, negative air ionization, and low noise 33.7dB(A) night mode.',
    brand: 'Xiaomi',
    categorySlug: 'home-appliances',
    subcategorySlug: 'air-purifiers',
    modelNumber: 'BHR5056EN',
    mrp: 24999,
    currentPrice: 19999,
    originalPrice: 24999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 25,
    lowStockThreshold: 5,
    rating: 4.8,
    reviewCount: 410,
    tags: ['xiaomi', 'mi air purifier 4 pro', 'hepa purifier', 'smart air purifier', 'pm2.5 sensor'],
    specifications: { CADR: '500 m3/h', Coverage: 'Up to 60 sq m (645 sq ft)', FilterLife: '6 to 12 Months', App: 'Mi Home / Xiaomi Home' },
    images: [
      { url: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Xiaomi Smart Air Purifier 4 Pro Front Tower' },
      { url: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Xiaomi Circular OLED Touch Display Panel' },
      { url: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Xiaomi 3-in-1 Filter Cylinder Extracted' },
      { url: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Xiaomi Detachable Top Air Outlet Grille' },
    ],
    variants: [
      { sku: 'PROD-HAP-008-WHT', name: 'Matte White Pro', price: 19999, mrp: 24999, stockQuantity: 25, attributes: { Color: 'Matte White' } }
    ]
  },
  {
    sku: 'PROD-HAP-009',
    name: 'Bosch Series 6 8kg Inverter Fully Automatic Front Load Washer',
    slug: 'bosch-series-6-8kg-front-load-washing-machine',
    description: 'EcoSilence Drive brushless motor washing machine with AntiTangle feature, VarioDrum wave droplet design, SpeedPerfect (65% faster wash), and 16 wash programs.',
    brand: 'Bosch',
    categorySlug: 'home-appliances',
    subcategorySlug: 'cooling-heating',
    modelNumber: 'WAJ2846WIN',
    mrp: 48990,
    currentPrice: 39192,
    originalPrice: 48990,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 15,
    lowStockThreshold: 3,
    rating: 4.8,
    reviewCount: 310,
    tags: ['bosch', 'series 6', 'front load washer', 'ecosilence drive', 'variodrum'],
    specifications: { Capacity: '8.0 kg', SpinSpeed: '1400 RPM', Motor: 'EcoSilence Drive 10 Yrs Warranty', NoiseLevel: '49 dB Wash' },
    images: [
      { url: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Bosch Series 6 Front Load Washer Silver' },
      { url: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Bosch Touch Control LED Display Dial' },
      { url: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Bosch VarioDrum Droplet Pattern Inside' },
      { url: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Bosch AntiVibration Side Wall Design' },
    ],
    variants: [
      { sku: 'PROD-HAP-009-SLV', name: 'Silver Inox', price: 39192, mrp: 48990, stockQuantity: 10, attributes: { Color: 'Silver Inox' } },
      { sku: 'PROD-HAP-009-WHT', name: 'Polar White', price: 36990, mrp: 45990, stockQuantity: 5, attributes: { Color: 'Polar White' } },
    ]
  },
  {
    sku: 'PROD-HAP-010',
    name: 'Haier 325L 3 Star Frost Free Inverter Double Door Refrigerator',
    slug: 'haier-325l-3-star-double-door-refrigerator',
    description: 'Bottom Mounted Refrigerator with 14-in-1 convertible modes, 1-hour icing technology, 2x bigger vegetable box, and 3-star energy efficiency rating.',
    brand: 'Haier',
    categorySlug: 'home-appliances',
    subcategorySlug: 'cooling-heating',
    modelNumber: 'HEB-333S-P',
    mrp: 44990,
    currentPrice: 33742,
    originalPrice: 44990,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 18,
    lowStockThreshold: 4,
    rating: 4.6,
    reviewCount: 280,
    tags: ['haier', 'double door fridge', 'bottom freezer', 'convertible refrigerator', '1 hour icing'],
    specifications: { Capacity: '325 Liters', Type: 'Bottom Mounted Refrigerator', Modes: '14-in-1 Convertible', Compressor: 'Twin Inverter' },
    images: [
      { url: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Haier Bottom Mounted Refrigerator Steel Front' },
      { url: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Haier Top Refrigerator Compartment Shelves' },
      { url: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Haier Bottom Freezer Drawers Space' },
      { url: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Haier External Digital Temperature Panel' },
    ],
    variants: [
      { sku: 'PROD-HAP-010-STL', name: 'Inox Steel', price: 33742, mrp: 44990, stockQuantity: 10, attributes: { Finish: 'Inox Steel' } },
      { sku: 'PROD-HAP-010-BLK', name: 'Black Steel', price: 34990, mrp: 46990, stockQuantity: 8, attributes: { Finish: 'Black Steel' } },
    ]
  },
  {
    sku: 'PROD-HAP-011',
    name: 'Kärcher WD 3 Multi-Purpose Wet & Dry Vacuum Cleaner',
    slug: 'karcher-wd3-wet-and-dry-vacuum',
    description: 'German engineered 1000W wet and dry canister vacuum cleaner with robust 17L impact-resistant plastic container, cartridge filter, and blower function.',
    brand: 'Kärcher',
    categorySlug: 'home-appliances',
    subcategorySlug: 'vacuum-cleaners',
    modelNumber: 'WD 3 *EU-I',
    mrp: 9999,
    currentPrice: 7999,
    originalPrice: 9999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 25,
    lowStockThreshold: 5,
    rating: 4.8,
    reviewCount: 540,
    tags: ['karcher', 'wd3', 'wet dry vacuum', 'industrial vacuum', 'blower function'],
    specifications: { Power: '1000W High Efficiency', Container: '17 Liters Yellow Plastic', Function: 'Vacuuming Wet/Dry Liquids + Blower', HoseLength: '2.0 Meters' },
    images: [
      { url: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Kärcher WD 3 Yellow Canister Vacuum Cleaner Front' },
      { url: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Kärcher Suction Hose Floor Nozzle Attached' },
      { url: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Kärcher Cartridge Filter Inspected Top' },
      { url: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Kärcher Blower Port Air Discharge' },
    ],
    variants: [
      { sku: 'PROD-HAP-011-YEL', name: 'Kärcher Yellow 17L Container', price: 7999, mrp: 9999, stockQuantity: 25, attributes: { Color: 'Yellow' } }
    ]
  },
  {
    sku: 'PROD-HAP-012',
    name: 'Honeywell Air Touch i8 Smart Room Air Purifier',
    slug: 'honeywell-air-touch-i8-purifier',
    description: 'Real-time PM2.5 CADR 300m³/h air purifier with anti-bacterial filter and HiSiv filter removing formaldehyde and toxic volatile organic compounds (VOCs).',
    brand: 'Honeywell',
    categorySlug: 'home-appliances',
    subcategorySlug: 'air-purifiers',
    modelNumber: 'HC000018/AP',
    mrp: 22990,
    currentPrice: 16093,
    originalPrice: 22990,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 18,
    lowStockThreshold: 4,
    rating: 4.6,
    reviewCount: 190,
    tags: ['honeywell', 'air touch i8', 'hisiv filter', 'hepa purifier', 'formaldehyde filter'],
    specifications: { CADR: '300 m3/h', Coverage: 'Up to 36 sq m (387 sq ft)', Filter: 'Pre-filter + HEPA + HiSiv VOC Filter', ChildLock: 'Yes' },
    images: [
      { url: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Honeywell Air Touch i8 Champagne Gold Unit' },
      { url: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Honeywell Top Touch Control Panel Numerical AQI' },
      { url: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Honeywell Patented HiSiv Filter Layer' },
      { url: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Honeywell Side Air Intake Mesh' },
    ],
    variants: [
      { sku: 'PROD-HAP-012-GLD', name: 'Champagne Gold', price: 16093, mrp: 22990, stockQuantity: 18, attributes: { Color: 'Champagne Gold' } }
    ]
  },
  {
    sku: 'PROD-HAP-013',
    name: 'Havells Solace 15-Litre 5 Star Vertical Storage Water Heater (Geyser)',
    slug: 'havells-solace-15l-storage-water-heater',
    description: 'Feroglas tech ultra-thick steel inner tank storage geyser with Incoloy 800 heating element, IPX4 waterproof body, and adjustable temperature knob.',
    brand: 'Havells',
    categorySlug: 'home-appliances',
    subcategorySlug: 'cooling-heating',
    modelNumber: 'GHWABSVK015',
    mrp: 12490,
    currentPrice: 8743,
    originalPrice: 12490,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 20,
    lowStockThreshold: 4,
    rating: 4.7,
    reviewCount: 340,
    tags: ['havells', 'solace', 'water heater', 'geyser 15l', 'feroglas tank', '5 star geyser'],
    specifications: { Capacity: '15 Liters', StarRating: '5 Star Energy Rating', Pressure: '8 Bar Suitable for High Rise', Tank: 'Feroglas Coated Steel' },
    images: [
      { url: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Havells Solace 15L White Vertical Water Heater Geyser' },
      { url: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Havells LED Temperature Indicator Light Panel' },
      { url: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Havells Temperature Dial Knob Bottom View' },
      { url: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Havells Safety Valve Pipe Connection' },
    ],
    variants: [
      { sku: 'PROD-HAP-013-15L', name: '15 Liters White', price: 8743, mrp: 12490, stockQuantity: 12, attributes: { Capacity: '15 Liters' } },
      { sku: 'PROD-HAP-013-25L', name: '25 Liters White', price: 10200, mrp: 14500, stockQuantity: 8, attributes: { Capacity: '25 Liters' } },
    ]
  },
  {
    sku: 'PROD-HAP-014',
    name: 'Voltas 24 Liter Personal Air Cooler with Honeycomb Pads',
    slug: 'voltas-24l-personal-air-cooler',
    description: 'Compact room personal air cooler featuring 24L water tank capacity, high-efficiency honeycomb cooling pads, 3-speed fan control, and castor wheels.',
    brand: 'Voltas',
    categorySlug: 'home-appliances',
    subcategorySlug: 'cooling-heating',
    modelNumber: 'VA-P24H',
    mrp: 7990,
    currentPrice: 5992,
    originalPrice: 7990,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 6,
    rating: 4.5,
    reviewCount: 390,
    tags: ['voltas', 'air cooler', 'personal cooler', 'honeycomb pad', 'room cooler'],
    specifications: { TankCapacity: '24 Liters', AirDelivery: '1200 m3/h', CoolingPads: 'Anti-Bacterial Honeycomb', Power: '130W' },
    images: [
      { url: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Voltas 24L Personal Air Cooler White Front' },
      { url: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Voltas Oscillating Louvers & Control Knobs' },
      { url: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Voltas Water Level Indicator & Ice Chamber Top' },
      { url: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Voltas Rear Honeycomb Pad Grid' },
    ],
    variants: [
      { sku: 'PROD-HAP-014-WHT', name: 'White & Blue 24L', price: 5992, mrp: 7990, stockQuantity: 30, attributes: { Color: 'White/Blue' } }
    ]
  },
  {
    sku: 'PROD-HAP-015',
    name: 'Black+Decker 2000W Garment Steamer for Clothes',
    slug: 'black-decker-2000w-garment-steamer',
    description: 'Standing clothes steamer featuring 2000W heating element, 2.4L removable water tank, 3 levels of continuous steam, dual pole aluminum hanger, and fabric brush.',
    brand: 'Black+Decker',
    categorySlug: 'home-appliances',
    subcategorySlug: 'vacuum-cleaners',
    modelNumber: 'GST2000-B5',
    mrp: 9999,
    currentPrice: 7499,
    originalPrice: 9999,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 20,
    lowStockThreshold: 4,
    rating: 4.6,
    reviewCount: 220,
    tags: ['black decker', 'garment steamer', 'clothes steamer', 'fabric steamer', 'vertical iron'],
    specifications: { Power: '2000 Watts', Tank: '2.4 Liters Removable Tank', HeatUpTime: '45 Seconds', SteamRate: '35 g/min' },
    images: [
      { url: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Black+Decker Garment Steamer Standing Setup' },
      { url: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Black+Decker Steam Nozzle Head & Fabric Brush' },
      { url: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Black+Decker 2.4L Water Tank Release Button' },
      { url: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Black+Decker Telescopic Dual Pole Hanger' },
    ],
    variants: [
      { sku: 'PROD-HAP-015-BLK', name: 'Black & Gold', price: 7499, mrp: 9999, stockQuantity: 20, attributes: { Color: 'Black/Gold' } }
    ]
  }
];
