import { ProductStatus } from '@prisma/client';

export const homeFurnitureProducts = [
  {
    sku: 'PROD-HMF-001',
    name: 'Herman Miller Aeron Ergonomic Office Chair',
    slug: 'herman-miller-aeron-chair',
    description: 'The benchmark for ergonomic seating featuring Pellicle 8Z breathable suspension mesh, PostureFit SL adjustable sacral and lumbar support, and fully adjustable armrests.',
    brand: 'Herman Miller',
    categorySlug: 'home-furniture',
    subcategorySlug: 'seating-sofas',
    modelNumber: 'AER1B23DW',
    mrp: 145000,
    currentPrice: 123250,
    originalPrice: 145000,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 12,
    lowStockThreshold: 2,
    rating: 4.9,
    reviewCount: 310,
    tags: ['herman miller', 'aeron chair', 'ergonomic chair', 'mesh chair', 'office chair'],
    specifications: { Mesh: '8Z Pellicle Elastomeric', Frame: 'Mineral Aluminum Base', Tilt: 'Harmonic 2 Tilt Mechanism', Warranty: '12 Years Official' },
    images: [
      { url: 'https://images.unsplash.com/photo-1580481072645-022f9a6d83d0?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Herman Miller Aeron Mineral Mesh Chair Front' },
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Herman Miller Aeron Side Lumbar Pad Support' },
      { url: 'https://images.unsplash.com/photo-1505797149-43b0069ec26b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Herman Miller 3D Armrest Adjustment' },
      { url: 'https://images.unsplash.com/photo-1519947486511-46149fa0a254?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Herman Miller Polished Aluminum Caster Base' },
    ],
    variants: [
      { sku: 'PROD-HMF-001-B', name: 'Size B (Medium) / Mineral', price: 123250, mrp: 145000, stockQuantity: 7, attributes: { Size: 'Medium (Size B)' } },
      { sku: 'PROD-HMF-001-C', name: 'Size C (Large) / Mineral', price: 128000, mrp: 150000, stockQuantity: 5, attributes: { Size: 'Large (Size C)' } },
    ]
  },
  {
    sku: 'PROD-HMF-002',
    name: 'IKEA BEKANT Motorized Electric Standing Desk 160x80cm',
    slug: 'ikea-bekant-standing-desk-160x80',
    description: 'Electric height-adjustable desk featuring dual motors for smooth transition between 65cm and 125cm, stain-resistant oak veneer tabletop, and heavy-duty steel underframe.',
    brand: 'IKEA',
    categorySlug: 'home-furniture',
    subcategorySlug: 'desks-tables',
    modelNumber: 'BEKANT-160',
    mrp: 45000,
    currentPrice: 38250,
    originalPrice: 45000,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 15,
    lowStockThreshold: 3,
    rating: 4.7,
    reviewCount: 220,
    tags: ['ikea', 'bekant', 'standing desk', 'motorized desk', 'adjustable desk'],
    specifications: { Dimensions: '160cm x 80cm', HeightRange: '65cm to 125cm', MaxLoad: '70 kg', TopMaterial: 'Oak Veneer' },
    images: [
      { url: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'IKEA BEKANT Oak Top Standing Desk Setup' },
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'IKEA BEKANT Height Control Switch Button' },
      { url: 'https://images.unsplash.com/photo-1505797149-43b0069ec26b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'IKEA BEKANT Steel Leg Telescopic Column' },
      { url: 'https://images.unsplash.com/photo-1519947486511-46149fa0a254?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'IKEA BEKANT Underdesk Cable Management Net' },
    ],
    variants: [
      { sku: 'PROD-HMF-002-OAK', name: 'Oak Veneer / White Legs', price: 38250, mrp: 45000, stockQuantity: 8, attributes: { Color: 'Oak/White' } },
      { sku: 'PROD-HMF-002-BLK', name: 'Black Stained / Black Legs', price: 38250, mrp: 45000, stockQuantity: 7, attributes: { Color: 'Black/Black' } },
    ]
  },
  {
    sku: 'PROD-HMF-003',
    name: 'West Elm Harmony 3-Piece L-Shape Sectional Sofa',
    slug: 'west-elm-harmony-sectional-sofa',
    description: 'Ultra-plush cloud-like L-shape sectional sofa featuring down-blend cushions, deep 41-inch seating, engineered hardwood frame, and stain-resistant performance velvet fabric.',
    brand: 'West Elm',
    categorySlug: 'home-furniture',
    subcategorySlug: 'seating-sofas',
    modelNumber: 'WE-HARM-SEC',
    mrp: 220000,
    currentPrice: 187000,
    originalPrice: 220000,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 6,
    lowStockThreshold: 1,
    rating: 4.8,
    reviewCount: 95,
    tags: ['west elm', 'harmony sofa', 'sectional sofa', 'l shape sofa', 'velvet sofa'],
    specifications: { Dimensions: '112 in W x 68 in D x 34 in H', Cushioning: '50% Down Feather + 50% Poly Fiber', Fabric: 'Performance Velvet', Orientation: 'Right Arm Chaise' },
    images: [
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'West Elm Harmony Sectional Sofa Light Grey Front' },
      { url: 'https://images.unsplash.com/photo-1580481072645-022f9a6d83d0?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'West Elm Deep Seat Cushion Texture' },
      { url: 'https://images.unsplash.com/photo-1505797149-43b0069ec26b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'West Elm Chaise Lounge Angle Profile' },
      { url: 'https://images.unsplash.com/photo-1519947486511-46149fa0a254?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'West Elm Solid Wood Tapered Legs' },
    ],
    variants: [
      { sku: 'PROD-HMF-003-GRY', name: 'Performance Velvet Light Grey', price: 187000, mrp: 220000, stockQuantity: 3, attributes: { Color: 'Light Grey' } },
      { sku: 'PROD-HMF-003-BEI', name: 'Performance Boucle Warm Beige', price: 195000, mrp: 230000, stockQuantity: 3, attributes: { Color: 'Warm Beige' } },
    ]
  },
  {
    sku: 'PROD-HMF-004',
    name: 'BenQ WiT e-Reading LED Desk Lamp with Auto-Dimming',
    slug: 'benq-wit-e-reading-led-desk-lamp',
    description: 'Pioneering curved LED desk lamp designed for monitor screens with zero glare, smart ambient light sensor auto-dimming, and adjustable dual-color temperature (2700K-5700K).',
    brand: 'BenQ',
    categorySlug: 'home-furniture',
    subcategorySlug: 'lamps-lighting',
    modelNumber: 'AR15_D',
    mrp: 18990,
    currentPrice: 15192,
    originalPrice: 18990,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 20,
    lowStockThreshold: 4,
    rating: 4.8,
    reviewCount: 180,
    tags: ['benq', 'wit lamp', 'led desk lamp', 'reading lamp', 'monitor bar light'],
    specifications: { Illumination: '1800 Lux at 45cm', ColorTemp: '2700K to 5700K', Material: 'Aluminum Alloy & Zinc', Power: '18W LED' },
    images: [
      { url: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'BenQ WiT Curved LED Desk Lamp Illuminated' },
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'BenQ Metallic Dial Control Knob Close' },
      { url: 'https://images.unsplash.com/photo-1505797149-43b0069ec26b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'BenQ Ball Joint Arm Rotation Angle' },
      { url: 'https://images.unsplash.com/photo-1519947486511-46149fa0a254?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'BenQ Weighted Base Plate Stability' },
    ],
    variants: [
      { sku: 'PROD-HMF-004-SLV', name: 'Silver Metallic', price: 15192, mrp: 18990, stockQuantity: 10, attributes: { Color: 'Silver Metallic' } },
      { sku: 'PROD-HMF-004-BLU', name: 'Sky Blue Metallic', price: 15192, mrp: 18990, stockQuantity: 10, attributes: { Color: 'Sky Blue' } },
    ]
  },
  {
    sku: 'PROD-HMF-005',
    name: 'Urban Ladder Genoa Solid Sheesham Wood Dining Table 6-Seater',
    slug: 'urban-ladder-genoa-sheesham-dining-table',
    description: 'Handcrafted 6-seater dining table made from 100% solid Indian Sheesham wood (Rosewood) with teak finish, melamine coat, and reinforced corner joints.',
    brand: 'Urban Ladder',
    categorySlug: 'home-furniture',
    subcategorySlug: 'desks-tables',
    modelNumber: 'UL-GEN-DT-6',
    mrp: 38999,
    currentPrice: 31199,
    originalPrice: 38999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 10,
    lowStockThreshold: 2,
    rating: 4.7,
    reviewCount: 165,
    tags: ['urban ladder', 'sheesham wood', 'dining table', '6 seater dining', 'solid wood table'],
    specifications: { Dimensions: '152cm L x 91cm W x 76cm H', WoodType: '100% Solid Sheesham Wood', Finish: 'Teak Polish', SeatingCapacity: '6 Persons' },
    images: [
      { url: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Urban Ladder Sheesham Dining Table Top Angle' },
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Urban Ladder Sheesham Wood Grain Pattern' },
      { url: 'https://images.unsplash.com/photo-1505797149-43b0069ec26b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Urban Ladder Thick Square Legs Joinery' },
      { url: 'https://images.unsplash.com/photo-1519947486511-46149fa0a254?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Urban Ladder Dining Table Set with Chairs' },
    ],
    variants: [
      { sku: 'PROD-HMF-005-TEAK', name: 'Teak Finish', price: 31199, mrp: 38999, stockQuantity: 6, attributes: { Finish: 'Teak Polish' } },
      { sku: 'PROD-HMF-005-WAL', name: 'Walnut Finish', price: 31199, mrp: 38999, stockQuantity: 4, attributes: { Finish: 'Walnut Polish' } },
    ]
  },
  {
    sku: 'PROD-HMF-006',
    name: 'Pepperfry Wooden Street Felt Fabric Recliner Chair',
    slug: 'pepperfry-felt-fabric-single-recliner-chair',
    description: 'Single-seater manual push-back recliner chair upholstered in high-density foam and plush suede fabric, with 3-position backrest recline.',
    brand: 'WoodenStreet',
    categorySlug: 'home-furniture',
    subcategorySlug: 'seating-sofas',
    modelNumber: 'WS-REC-01',
    mrp: 24999,
    currentPrice: 17499,
    originalPrice: 24999,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 15,
    lowStockThreshold: 3,
    rating: 4.6,
    reviewCount: 140,
    tags: ['woodenstreet', 'recliner chair', 'push back recliner', 'single sofa', 'pepperfry'],
    specifications: { ReclineMechanism: 'Manual Push Back 160 deg', Cushion: '32-Density Foam', Frame: 'Solid Pine Wood + Heavy Steel Mechanism', MaxWeight: '130kg' },
    images: [
      { url: 'https://images.unsplash.com/photo-1580481072645-022f9a6d83d0?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'WoodenStreet Recliner Chair Upright Front' },
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'WoodenStreet Footrest Extended Recline Angle' },
      { url: 'https://images.unsplash.com/photo-1505797149-43b0069ec26b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'WoodenStreet Armrest Soft Cushioning' },
      { url: 'https://images.unsplash.com/photo-1519947486511-46149fa0a254?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'WoodenStreet Steel Base Mechanism' },
    ],
    variants: [
      { sku: 'PROD-HMF-006-BRN', name: 'Mocha Brown Suede', price: 17499, mrp: 24999, stockQuantity: 8, attributes: { Color: 'Mocha Brown' } },
      { sku: 'PROD-HMF-006-GRY', name: 'Charcoal Grey Suede', price: 17499, mrp: 24999, stockQuantity: 7, attributes: { Color: 'Charcoal Grey' } },
    ]
  },
  {
    sku: 'PROD-HMF-007',
    name: 'Philips Hue White & Color Ambiance Gradient Floor Lamp',
    slug: 'philips-hue-gradient-floor-lamp',
    description: 'Smart LED floor standing light tube capable of seamlessly blending 16 million colors simultaneously, integrated with Apple HomeKit, Alexa, and Google Home.',
    brand: 'Philips Hue',
    categorySlug: 'home-furniture',
    subcategorySlug: 'lamps-lighting',
    modelNumber: 'HUE-FLR-GRAD',
    mrp: 34999,
    currentPrice: 29749,
    originalPrice: 34999,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 10,
    lowStockThreshold: 2,
    rating: 4.9,
    reviewCount: 110,
    tags: ['philips hue', 'smart lamp', 'floor lamp', 'rgb lighting', 'gradient light'],
    specifications: { LightOutput: '2500 Lumens', Colors: '16 Million + Dynamic Gradients', Connectivity: 'Zigbee + Bluetooth', Height: '145cm' },
    images: [
      { url: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Philips Hue Gradient Floor Lamp Glowing Multicolor' },
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Philips Hue Aluminum Pole Base Finish' },
      { url: 'https://images.unsplash.com/photo-1505797149-43b0069ec26b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Philips Hue Corner Wall Reflection Effect' },
      { url: 'https://images.unsplash.com/photo-1519947486511-46149fa0a254?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Philips Hue Mobile App Controller Screen' },
    ],
    variants: [
      { sku: 'PROD-HMF-007-BLK', name: 'Black Anodized Aluminum', price: 29749, mrp: 34999, stockQuantity: 6, attributes: { Color: 'Black' } },
      { sku: 'PROD-HMF-007-WHT', name: 'White Powder Coated Aluminum', price: 29749, mrp: 34999, stockQuantity: 4, attributes: { Color: 'White' } },
    ]
  },
  {
    sku: 'PROD-HMF-008',
    name: 'Wakefit Orthopedic Memory Foam King Size Mattress (78x72x8 in)',
    slug: 'wakefit-orthopedic-memory-foam-mattress-king',
    description: '7-zone orthopedic memory foam mattress with high resilience support foam, breathable cotton fabric cover, and zero motion transfer tech for posture alignment.',
    brand: 'Wakefit',
    categorySlug: 'home-furniture',
    subcategorySlug: 'seating-sofas',
    modelNumber: 'WF-ORTH-K8',
    mrp: 21999,
    currentPrice: 15399,
    originalPrice: 21999,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 25,
    lowStockThreshold: 5,
    rating: 4.8,
    reviewCount: 920,
    tags: ['wakefit', 'mattress', 'memory foam', 'orthopedic mattress', 'king size mattress'],
    specifications: { Dimensions: '78 x 72 x 8 Inches (King Size)', Core: '7-Zone Memory Foam', Cover: 'GSM Premium Zippered Cover', Warranty: '10 Years Warranty' },
    images: [
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Wakefit Orthopedic King Mattress on Bedframe' },
      { url: 'https://images.unsplash.com/photo-1580481072645-022f9a6d83d0?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Wakefit Zipper Cover & Quilted Fabric Detail' },
      { url: 'https://images.unsplash.com/photo-1505797149-43b0069ec26b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Wakefit 7-Zone Memory Foam Layer Cutaway' },
      { url: 'https://images.unsplash.com/photo-1519947486511-46149fa0a254?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Wakefit Roll Pack Delivery Box' },
    ],
    variants: [
      { sku: 'PROD-HMF-008-K8', name: 'King (78x72x8 in)', price: 15399, mrp: 21999, stockQuantity: 15, attributes: { Size: 'King Size 8-Inch' } },
      { sku: 'PROD-HMF-008-Q8', name: 'Queen (78x60x8 in)', price: 12999, mrp: 18999, stockQuantity: 10, attributes: { Size: 'Queen Size 8-Inch' } },
    ]
  },
  {
    sku: 'PROD-HMF-009',
    name: 'Godrej Interio Slimline 3-Door Steel Almirah Wardrobe',
    slug: 'godrej-interio-slimline-3-door-almirah',
    description: 'Heavy gauge corrosion-resistant CRCA steel 3-door wardrobe featuring full length mirror, ultra-secure 3-way locking system, adjustable shelves, and hanging rod.',
    brand: 'Godrej Interio',
    categorySlug: 'home-furniture',
    subcategorySlug: 'desks-tables',
    modelNumber: 'SLIMLINE-3D-M',
    mrp: 42000,
    currentPrice: 35700,
    originalPrice: 42000,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 8,
    lowStockThreshold: 2,
    rating: 4.7,
    reviewCount: 145,
    tags: ['godrej interio', 'almirah', 'steel wardrobe', 'godrej wardrobe', '3 door almirah'],
    specifications: { Dimensions: '195cm H x 135cm W x 50cm D', Material: 'CRCA Steel (0.9mm)', Lock: 'Dual Control 3-Way Lock', Mirror: 'High Definition Glass' },
    images: [
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Godrej Interio 3-Door Steel Almirah Front' },
      { url: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Godrej Almirah Doors Opened Shelves Arrangement' },
      { url: 'https://images.unsplash.com/photo-1505797149-43b0069ec26b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Godrej Dual Control Keyhole Mechanism' },
      { url: 'https://images.unsplash.com/photo-1519947486511-46149fa0a254?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Godrej Full Length Dressing Mirror Door' },
    ],
    variants: [
      { sku: 'PROD-HMF-009-SLV', name: 'Pacific Blue & Silver', price: 35700, mrp: 42000, stockQuantity: 5, attributes: { Color: 'Pacific Blue' } },
      { sku: 'PROD-HMF-009-BRN', name: 'Texture Brown Maroon', price: 35700, mrp: 42000, stockQuantity: 3, attributes: { Color: 'Texture Brown' } },
    ]
  },
  {
    sku: 'PROD-HMF-010',
    name: 'Wipro Garnet 12W Smart RGB B22 LED Smart Bulb',
    slug: 'wipro-garnet-12w-smart-led-bulb',
    description: 'WiFi connected B22 LED bulb offering 16 million colors, music sync feature, schedules, and voice control with Amazon Alexa and Google Assistant.',
    brand: 'Wipro',
    categorySlug: 'home-furniture',
    subcategorySlug: 'lamps-lighting',
    modelNumber: 'NS1200',
    mrp: 1499,
    currentPrice: 749,
    originalPrice: 1499,
    discount: 50.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 50,
    lowStockThreshold: 10,
    rating: 4.5,
    reviewCount: 480,
    tags: ['wipro', 'smart bulb', 'b22 bulb', 'rgb light', 'alexa bulb'],
    specifications: { Wattage: '12 Watts', Lumens: '1100 Lumens', CapType: 'B22 Indian Socket', App: 'Wipro Next Smart Home' },
    images: [
      { url: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Wipro Smart LED Bulb Glowing Violet' },
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Wipro B22 Metal Base & Polycarbonate Dome' },
      { url: 'https://images.unsplash.com/photo-1505797149-43b0069ec26b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Wipro Mobile App Color Wheel Control' },
      { url: 'https://images.unsplash.com/photo-1519947486511-46149fa0a254?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Wipro Retail Packaging Box' },
    ],
    variants: [
      { sku: 'PROD-HMF-010-B22', name: 'B22 Pin Cap Socket', price: 749, mrp: 1499, stockQuantity: 30, attributes: { Socket: 'B22 Pin' } },
      { sku: 'PROD-HMF-010-E27', name: 'E27 Screw Socket', price: 749, mrp: 1499, stockQuantity: 20, attributes: { Socket: 'E27 Screw' } },
    ]
  },
  {
    sku: 'PROD-HMF-011',
    name: 'Featherlite Astro Mesh Ergonomic Task Chair',
    slug: 'featherlite-astro-mesh-ergonomic-chair',
    description: 'High-back office task chair featuring self-weight adjusting synchro-tilt mechanism, 2D lumbar height adjustment, and breathable mesh backrest.',
    brand: 'Featherlite',
    categorySlug: 'home-furniture',
    subcategorySlug: 'seating-sofas',
    modelNumber: 'FL-ASTRO-HB',
    mrp: 15999,
    currentPrice: 12799,
    originalPrice: 15999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 20,
    lowStockThreshold: 4,
    rating: 4.6,
    reviewCount: 230,
    tags: ['featherlite', 'astro chair', 'mesh chair', 'ergonomic task chair', 'computer chair'],
    specifications: { Mechanism: 'Self-Weight Synchro-Tilt', GasLift: 'Class 4 BIFMA Certified', Base: 'Nylon 5-Star Base', Warranty: '3 Years Warranty' },
    images: [
      { url: 'https://images.unsplash.com/photo-1580481072645-022f9a6d83d0?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Featherlite Astro High Back Mesh Chair Front' },
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Featherlite Astro Lumbar Support Cushion Close' },
      { url: 'https://images.unsplash.com/photo-1505797149-43b0069ec26b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Featherlite Astro Adjustable Headrest' },
      { url: 'https://images.unsplash.com/photo-1519947486511-46149fa0a254?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Featherlite Astro Nylon Base Wheels' },
    ],
    variants: [
      { sku: 'PROD-HMF-011-BLK', name: 'Black Mesh / Black Frame', price: 12799, mrp: 15999, stockQuantity: 12, attributes: { Color: 'Black' } },
      { sku: 'PROD-HMF-011-GRY', name: 'Grey Mesh / White Frame', price: 13499, mrp: 16999, stockQuantity: 8, attributes: { Color: 'Grey/White' } },
    ]
  },
  {
    sku: 'PROD-HMF-012',
    name: 'IKEA KALLAX Shelf Unit 4x4 Square Bookcase',
    slug: 'ikea-kallax-shelf-unit-4x4-white',
    description: 'Versatile 147x147 cm square cube shelving unit that can be placed vertically or horizontally, compatible with KALLAX fabric boxes and inserts.',
    brand: 'IKEA',
    categorySlug: 'home-furniture',
    subcategorySlug: 'desks-tables',
    modelNumber: 'KALLAX-147',
    mrp: 12990,
    currentPrice: 11041,
    originalPrice: 12990,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 18,
    lowStockThreshold: 4,
    rating: 4.8,
    reviewCount: 390,
    tags: ['ikea', 'kallax', 'bookshelf', 'cube shelf', 'storage unit'],
    specifications: { Dimensions: '147 cm x 147 cm x 39 cm', MaxLoadPerShelf: '13 kg', Material: 'Particleboard & Honeycomb Paper Filling', Cubes: '16 Compartments' },
    images: [
      { url: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'IKEA KALLAX White 4x4 Bookcase Unit Front' },
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'IKEA KALLAX Cube Compartment with Storage Boxes' },
      { url: 'https://images.unsplash.com/photo-1505797149-43b0069ec26b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'IKEA KALLAX Laminated Outer Surface Detail' },
      { url: 'https://images.unsplash.com/photo-1519947486511-46149fa0a254?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'IKEA KALLAX Room Divider Horizontal Layout' },
    ],
    variants: [
      { sku: 'PROD-HMF-012-WHT', name: 'White Gloss', price: 11041, mrp: 12990, stockQuantity: 10, attributes: { Color: 'White' } },
      { sku: 'PROD-HMF-012-BLK', name: 'Black-Brown Wood Effect', price: 11041, mrp: 12990, stockQuantity: 8, attributes: { Color: 'Black-Brown' } },
    ]
  },
  {
    sku: 'PROD-HMF-013',
    name: 'Green Soul Monster Ultimate Series T Gaming Chair',
    slug: 'green-soul-monster-ultimate-gaming-chair',
    description: 'Heavy-duty gaming chair with breathable spandex fabric upholstery, integrated adjustable lumbar support knob, 4D armrests, and 180-degree recline.',
    brand: 'Green Soul',
    categorySlug: 'home-furniture',
    subcategorySlug: 'seating-sofas',
    modelNumber: 'GS-MONSTER-T',
    mrp: 24990,
    currentPrice: 18742,
    originalPrice: 24990,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 15,
    lowStockThreshold: 3,
    rating: 4.7,
    reviewCount: 380,
    tags: ['green soul', 'gaming chair', 'monster ultimate', 'reclining chair', 'ergonomic gaming'],
    specifications: { Recline: '90 to 180 degrees', Armrests: '4D Adjustable', Material: 'Breathable Spandex Fabric + PU Leather', WeightCapacity: '135 kg' },
    images: [
      { url: 'https://images.unsplash.com/photo-1580481072645-022f9a6d83d0?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Green Soul Monster Ultimate Gaming Chair Front' },
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Green Soul 180-Degree Full Flat Recline Angle' },
      { url: 'https://images.unsplash.com/photo-1505797149-43b0069ec26b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Green Soul 4D Armrest Movement Controls' },
      { url: 'https://images.unsplash.com/photo-1519947486511-46149fa0a254?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Green Soul Heavy Duty Class 4 Gas Lift' },
    ],
    variants: [
      { sku: 'PROD-HMF-013-BLK', name: 'Black & Cyan Spandex', price: 18742, mrp: 24990, stockQuantity: 8, attributes: { Color: 'Black/Cyan' } },
      { sku: 'PROD-HMF-013-RED', name: 'Black & Crimson Red Spandex', price: 18742, mrp: 24990, stockQuantity: 7, attributes: { Color: 'Black/Red' } },
    ]
  },
  {
    sku: 'PROD-HMF-014',
    name: 'Home Centre Solid Wood Coffee Table with Glass Top',
    slug: 'home-centre-solid-wood-coffee-table',
    description: 'Contemporary living room center coffee table featuring tempered glass top shelf, solid rubberwood legs, and bottom magazine storage lattice.',
    brand: 'Home Centre',
    categorySlug: 'home-furniture',
    subcategorySlug: 'desks-tables',
    modelNumber: 'HC-CFT-08',
    mrp: 14999,
    currentPrice: 10499,
    originalPrice: 14999,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 15,
    lowStockThreshold: 3,
    rating: 4.6,
    reviewCount: 120,
    tags: ['home centre', 'coffee table', 'center table', 'glass top table', 'wooden coffee table'],
    specifications: { Dimensions: '110cm L x 60cm W x 45cm H', Top: '8mm Toughened Tempered Glass', Frame: 'Solid Malaysian Rubberwood', Storage: 'Bottom Newspaper Shelf' },
    images: [
      { url: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Home Centre Glass Top Coffee Table Living Room Setup' },
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Home Centre Tempered Glass Beveled Edge' },
      { url: 'https://images.unsplash.com/photo-1505797149-43b0069ec26b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Home Centre Bottom Slatted Storage Shelf' },
      { url: 'https://images.unsplash.com/photo-1519947486511-46149fa0a254?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Home Centre Rubberwood Leg Joint Detail' },
    ],
    variants: [
      { sku: 'PROD-HMF-014-WAL', name: 'Walnut Dark Brown', price: 10499, mrp: 14999, stockQuantity: 15, attributes: { Color: 'Walnut' } }
    ]
  },
  {
    sku: 'PROD-HMF-015',
    name: 'Mi Smart LED Desk Lamp 1S with Apple HomeKit Support',
    slug: 'mi-smart-led-desk-lamp-1s',
    description: 'Minimalist folding desk lamp with Ra90 high color rendering index, flicker-free optical lens, dial knob brightness control, and Xiaomi Home app connectivity.',
    brand: 'Xiaomi',
    categorySlug: 'home-furniture',
    subcategorySlug: 'lamps-lighting',
    modelNumber: 'MJTD01SY',
    mrp: 3499,
    currentPrice: 2799,
    originalPrice: 3499,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 6,
    rating: 4.8,
    reviewCount: 290,
    tags: ['xiaomi', 'mi smart lamp', 'desk lamp', 'led lamp', 'apple homekit'],
    specifications: { ColorRendering: 'Ra90', Brightness: '520 Lumens', FoldAngle: '135 Degrees', SmartControls: 'Mi Home, Apple HomeKit, Alexa' },
    images: [
      { url: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Mi Smart LED Desk Lamp 1S White Arm Profile' },
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Mi Lamp Orange Cord Accent & Metal Hinge' },
      { url: 'https://images.unsplash.com/photo-1505797149-43b0069ec26b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Mi Lamp Single Dial Knob Switch Base' },
      { url: 'https://images.unsplash.com/photo-1519947486511-46149fa0a254?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Mi Lamp Flat Folded Storage State' },
    ],
    variants: [
      { sku: 'PROD-HMF-015-WHT', name: 'Pure White', price: 2799, mrp: 3499, stockQuantity: 30, attributes: { Color: 'Pure White' } }
    ]
  }
];
