import { ProductStatus } from '@prisma/client';

export const jewelleryProducts = [
  {
    sku: 'PROD-JWL-001',
    name: 'Tanishq 18k Yellow Gold Diamond Solitaire Ring',
    slug: 'tanishq-18k-gold-diamond-solitaire-ring',
    description: 'Certified 0.50 Carat VVS1 Clarity Round Brilliant Cut Diamond mounted on a hallmarked 18 Karat Yellow Gold polished band with prong setting.',
    brand: 'Tanishq',
    categorySlug: 'jewellery',
    subcategorySlug: 'rings',
    modelNumber: '502919RCAAAA02',
    mrp: 85000,
    currentPrice: 76500,
    originalPrice: 85000,
    discount: 10.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 10,
    lowStockThreshold: 2,
    rating: 4.9,
    reviewCount: 92,
    tags: ['tanishq', 'diamond ring', 'solitaire', '18k gold', 'engagement ring'],
    specifications: { GoldPurity: '18K (750)', DiamondWeight: '0.50 Carat', DiamondClarity: 'VVS1', Certification: 'IGI Certified' },
    images: [
      { url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Tanishq 18k Gold Diamond Solitaire Ring Top Angle' },
      { url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Tanishq Diamond Sparkle Prism Closeup' },
      { url: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Tanishq Gold Band Hallmark Engraving' },
      { url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Tanishq Luxury Velvet Ring Box' },
    ],
    variants: [
      { sku: 'PROD-JWL-001-SZ12', name: 'Ring Size 12', price: 76500, mrp: 85000, stockQuantity: 5, attributes: { RingSize: '12 Indian' } },
      { sku: 'PROD-JWL-001-SZ14', name: 'Ring Size 14', price: 76500, mrp: 85000, stockQuantity: 5, attributes: { RingSize: '14 Indian' } },
    ]
  },
  {
    sku: 'PROD-JWL-002',
    name: 'Swarovski Sparkling Dance Clover Pendant Necklace',
    slug: 'swarovski-sparkling-dance-clover-necklace',
    description: 'Rhodium-plated pendant necklace featuring a floating clear crystal inside a clover-shaped cage that catches light with every move.',
    brand: 'Swarovski',
    categorySlug: 'jewellery',
    subcategorySlug: 'necklaces-chains',
    modelNumber: '5514488',
    mrp: 14500,
    currentPrice: 12325,
    originalPrice: 14500,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 20,
    lowStockThreshold: 4,
    rating: 4.8,
    reviewCount: 175,
    tags: ['swarovski', 'crystal necklace', 'pendant', 'rhodium plated', 'clover necklace'],
    specifications: { Material: 'Rhodium Plated Metal', Crystal: 'Swarovski Clear Crystal', ChainLength: '38 cm', Extender: '5 cm' },
    images: [
      { url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Swarovski Sparkling Dance Clover Pendant Front' },
      { url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Swarovski Crystal Refraction Sparkle' },
      { url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Swarovski Chain Clasp Swan Emblem' },
      { url: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Swarovski Blue Gift Box' },
    ],
    variants: [
      { sku: 'PROD-JWL-002-SIL', name: 'Rhodium Silver', price: 12325, mrp: 14500, stockQuantity: 10, attributes: { Color: 'Rhodium Silver' } },
      { sku: 'PROD-JWL-002-ROSE', name: 'Rose Gold Plated', price: 12325, mrp: 14500, stockQuantity: 10, attributes: { Color: 'Rose Gold' } },
    ]
  },
  {
    sku: 'PROD-JWL-003',
    name: 'GIVA 925 Sterling Silver Cubic Zirconia Drop Earrings',
    slug: 'giva-925-silver-cz-drop-earrings',
    description: 'Pure 925 sterling silver drop earrings studded with AAA+ quality Cubic Zirconia stones and anti-tarnish e-coating for long-lasting sheen.',
    brand: 'GIVA',
    categorySlug: 'jewellery',
    subcategorySlug: 'earrings',
    modelNumber: 'ER0198',
    mrp: 3299,
    currentPrice: 1979,
    originalPrice: 3299,
    discount: 40.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.7,
    reviewCount: 310,
    tags: ['giva', 'silver earrings', '925 sterling silver', 'drop earrings', 'cz stones'],
    specifications: { Metal: '925 Sterling Silver', Stone: 'AAA+ Cubic Zirconia', Coating: 'Rhodium E-Coated Anti-Tarnish', Stamp: '925 Hallmarked' },
    images: [
      { url: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'GIVA 925 Sterling Silver Drop Earrings Pair' },
      { url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'GIVA Cubic Zirconia Stone Cut Sparkle' },
      { url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'GIVA Earring Back Push Lever' },
      { url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'GIVA Authenticity Certificate & Velvet Box' },
    ],
    variants: [
      { sku: 'PROD-JWL-003-SIL', name: 'Silver CZ', price: 1979, mrp: 3299, stockQuantity: 20, attributes: { Color: 'Silver' } },
      { sku: 'PROD-JWL-003-ROSE', name: 'Rose Gold CZ', price: 1979, mrp: 3299, stockQuantity: 20, attributes: { Color: 'Rose Gold' } },
    ]
  },
  {
    sku: 'PROD-JWL-004',
    name: 'Pandora Moments Snake Chain Charm Bracelet',
    slug: 'pandora-moments-snake-chain-bracelet',
    description: 'Iconic hand-finished sterling silver snake chain bracelet featuring threaders and Pandora barrel clasp designed to hold your personal charm collection.',
    brand: 'Pandora',
    categorySlug: 'jewellery',
    subcategorySlug: 'rings',
    modelNumber: '590702HV',
    mrp: 6990,
    currentPrice: 5941,
    originalPrice: 6990,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 25,
    lowStockThreshold: 5,
    rating: 4.8,
    reviewCount: 260,
    tags: ['pandora', 'charm bracelet', 'snake chain', '925 silver', 'pandora moments'],
    specifications: { Metal: '925 Sterling Silver', Clasp: 'Barrel Crown Clasp', Compatibility: 'Pandora Moments Charms', Finish: 'Polished Silver' },
    images: [
      { url: 'https://images.unsplash.com/photo-1611591475281-6d9819885c31?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Pandora Snake Chain Charm Bracelet Coiled' },
      { url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Pandora Barrel Clasp Crown Logo Detail' },
      { url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Pandora Threaders & Snake Weave Pattern' },
      { url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Pandora White Gift Box & Polishing Cloth' },
    ],
    variants: [
      { sku: 'PROD-JWL-004-18', name: '18 cm Wrist Size', price: 5941, mrp: 6990, stockQuantity: 12, attributes: { Length: '18 cm' } },
      { sku: 'PROD-JWL-004-20', name: '20 cm Wrist Size', price: 5941, mrp: 6990, stockQuantity: 13, attributes: { Length: '20 cm' } },
    ]
  },
  {
    sku: 'PROD-JWL-005',
    name: 'Kalyan Jewellers 22k Yellow Gold Mangalsutra Chain',
    slug: 'kalyan-jewellers-22k-gold-mangalsutra',
    description: 'Traditional yet modern 22k gold mangalsutra featuring handcrafted black onyx beads woven into double gold strands with a delicate flower diamond-accented pendant.',
    brand: 'Kalyan Jewellers',
    categorySlug: 'jewellery',
    subcategorySlug: 'necklaces-chains',
    modelNumber: 'KJ-MS-22K-09',
    mrp: 48000,
    currentPrice: 43200,
    originalPrice: 48000,
    discount: 10.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 12,
    lowStockThreshold: 3,
    rating: 4.9,
    reviewCount: 140,
    tags: ['kalyan jewellers', 'mangalsutra', '22k gold', 'black beads', 'traditional jewellery'],
    specifications: { Purity: '22K BIS Hallmarked', Length: '18 inches', Beads: 'Genuine Black Onyx', Weight: '8.5 grams' },
    images: [
      { url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Kalyan Jewellers 22k Gold Mangalsutra Pendant View' },
      { url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Kalyan Jewellers Black Onyx Bead Strand Closeup' },
      { url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Kalyan Jewellers BIS Hallmarked Stamp' },
      { url: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Kalyan Jewellers Red Silk Gift Box' },
    ],
    variants: [
      { sku: 'PROD-JWL-005-18', name: '18 Inch Length', price: 43200, mrp: 48000, stockQuantity: 6, attributes: { Length: '18 Inch' } },
      { sku: 'PROD-JWL-005-20', name: '20 Inch Length', price: 43200, mrp: 48000, stockQuantity: 6, attributes: { Length: '20 Inch' } },
    ]
  },
  {
    sku: 'PROD-JWL-006',
    name: 'CaratLane 14k Rose Gold Diamond Stud Earrings',
    slug: 'caratlane-14k-rose-gold-diamond-studs',
    description: 'Classic daily-wear solitaire stud earrings set in 14k rose gold featuring 0.20ct GH Color SI Clarity round diamonds with secure screw-back posts.',
    brand: 'CaratLane',
    categorySlug: 'jewellery',
    subcategorySlug: 'earrings',
    modelNumber: 'JE03841-1RP900',
    mrp: 26000,
    currentPrice: 22100,
    originalPrice: 26000,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 15,
    lowStockThreshold: 3,
    rating: 4.8,
    reviewCount: 180,
    tags: ['caratlane', 'diamond studs', 'rose gold studs', '14k gold', 'solitaire studs'],
    specifications: { GoldPurity: '14K Rose Gold', TotalDiamondWeight: '0.20 Carat', DiamondClarity: 'SI GH', Closure: 'Screw Back' },
    images: [
      { url: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'CaratLane Rose Gold Diamond Stud Earrings Pair' },
      { url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'CaratLane Diamond Setting & Prism Sparkle' },
      { url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'CaratLane Threaded Screw Back Post' },
      { url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'CaratLane Purple Gift Pouch & SGL Certificate' },
    ],
    variants: [
      { sku: 'PROD-JWL-006-PAIR', name: '14k Rose Gold Pair', price: 22100, mrp: 26000, stockQuantity: 15, attributes: { Metal: '14k Rose Gold' } }
    ]
  },
  {
    sku: 'PROD-JWL-007',
    name: 'Mia by Tanishq 14k Yellow Gold Geometric Band Ring',
    slug: 'mia-tanishq-14k-gold-geometric-ring',
    description: 'Modern office-wear stackable ring crafted in 14k hallmarked yellow gold featuring a faceted geometric design with subtle diamond accents.',
    brand: 'Mia by Tanishq',
    categorySlug: 'jewellery',
    subcategorySlug: 'rings',
    modelNumber: '552818RBAAA00',
    mrp: 18500,
    currentPrice: 15725,
    originalPrice: 18500,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 18,
    lowStockThreshold: 4,
    rating: 4.7,
    reviewCount: 110,
    tags: ['mia by tanishq', 'gold ring', 'stackable ring', '14k gold', 'geometric ring'],
    specifications: { Metal: '14K Yellow Gold', Style: 'Faceted Geometric Band', Accent: 'Natural Diamonds (0.04 ct)', Weight: '2.4 grams' },
    images: [
      { url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Mia by Tanishq Geometric Gold Band Ring' },
      { url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Mia Faceted Gold Surface Reflection' },
      { url: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Mia Diamond Accent Closeup' },
      { url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Mia Teal Ring Box & Authenticity Tag' },
    ],
    variants: [
      { sku: 'PROD-JWL-007-SZ12', name: 'Ring Size 12', price: 15725, mrp: 18500, stockQuantity: 9, attributes: { RingSize: '12 Indian' } },
      { sku: 'PROD-JWL-007-SZ14', name: 'Ring Size 14', price: 15725, mrp: 18500, stockQuantity: 9, attributes: { RingSize: '14 Indian' } },
    ]
  },
  {
    sku: 'PROD-JWL-008',
    name: 'Joyalukkas 22k Yellow Gold Rope Chain Necklace',
    slug: 'joyalukkas-22k-gold-rope-chain',
    description: 'Sturdy 22 karat yellow gold diamond-cut rope chain featuring interlocking spiral loops and heavy lobster claw clasp.',
    brand: 'Joyalukkas',
    categorySlug: 'jewellery',
    subcategorySlug: 'necklaces-chains',
    modelNumber: 'JYL-CH-22K-15',
    mrp: 62000,
    currentPrice: 55800,
    originalPrice: 62000,
    discount: 10.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 10,
    lowStockThreshold: 2,
    rating: 4.9,
    reviewCount: 155,
    tags: ['joyalukkas', 'gold chain', '22k gold chain', 'rope chain', 'bis hallmarked'],
    specifications: { Purity: '22K (916) BIS Hallmarked', Weight: '10.2 grams', Width: '3mm', Length: '20 inches' },
    images: [
      { url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Joyalukkas 22k Gold Rope Chain Coiled' },
      { url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Joyalukkas Diamond Cut Spiral Loops Closeup' },
      { url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Joyalukkas Lobster Clasp 916 Hallmark' },
      { url: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Joyalukkas Leatherette Jewel Box' },
    ],
    variants: [
      { sku: 'PROD-JWL-008-20', name: '20 Inch Length (10.2g)', price: 55800, mrp: 62000, stockQuantity: 5, attributes: { Length: '20 Inch' } },
      { sku: 'PROD-JWL-008-22', name: '22 Inch Length (11.5g)', price: 62800, mrp: 69000, stockQuantity: 5, attributes: { Length: '22 Inch' } },
    ]
  },
  {
    sku: 'PROD-JWL-009',
    name: 'Zaveri Pearls Traditional Gold Plated Kundan Jhumka',
    slug: 'zaveri-pearls-kundan-jhumka-earrings',
    description: 'Grand festive bell jhumki earrings richly decorated with hand-set Kundan stones, green enamel meenakari work, and dangling pearl drops.',
    brand: 'Zaveri Pearls',
    categorySlug: 'jewellery',
    subcategorySlug: 'earrings',
    modelNumber: 'ZPFK9182',
    mrp: 2999,
    currentPrice: 899,
    originalPrice: 2999,
    discount: 70.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 50,
    lowStockThreshold: 10,
    rating: 4.6,
    reviewCount: 420,
    tags: ['zaveri pearls', 'jhumka', 'kundan earrings', 'traditional jewellery', 'pearl jhumki'],
    specifications: { BaseMaterial: 'Brass Alloy', Plating: '24k Gold Micro Plating', Stones: 'Kundan & Faux Pearls', Weight: '35g' },
    images: [
      { url: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Zaveri Pearls Kundan Jhumka Pair Front' },
      { url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Zaveri Pearls Meenakari & Pearl Drops Detail' },
      { url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Zaveri Pearls Earring Post & Silicone Stopper' },
      { url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Zaveri Pearls Signature Box' },
    ],
    variants: [
      { sku: 'PROD-JWL-009-GRN', name: 'Emerald Green Kundan', price: 899, mrp: 2999, stockQuantity: 25, attributes: { Color: 'Emerald Green' } },
      { sku: 'PROD-JWL-009-RED', name: 'Ruby Red Kundan', price: 899, mrp: 2999, stockQuantity: 25, attributes: { Color: 'Ruby Red' } },
    ]
  },
  {
    sku: 'PROD-JWL-010',
    name: 'Malabar Gold & Diamonds 22k Gold Bangles Set',
    slug: 'malabar-22k-gold-bangles-set-of-2',
    description: 'Set of two exquisitely carved 22 karat gold bangles featuring intricately etched floral filigree designs with semi-gloss polish.',
    brand: 'Malabar Gold & Diamonds',
    categorySlug: 'jewellery',
    subcategorySlug: 'rings',
    modelNumber: 'MGB-22K-004',
    mrp: 95000,
    currentPrice: 85500,
    originalPrice: 95000,
    discount: 10.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 8,
    lowStockThreshold: 2,
    rating: 4.9,
    reviewCount: 88,
    tags: ['malabar gold', 'gold bangles', '22k gold', 'filigree bangles', 'bridal jewellery'],
    specifications: { Purity: '22K (916) BIS Hallmarked', Pack: 'Set of 2 Bangles', TotalWeight: '15.8 grams', Finish: 'Carved Filigree' },
    images: [
      { url: 'https://images.unsplash.com/photo-1611591475281-6d9819885c31?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Malabar 22k Gold Filigree Bangles Pair' },
      { url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Malabar Gold Carving Filigree Pattern' },
      { url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Malabar BIS Hallmark Stamp Interior' },
      { url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Malabar Gold Luxury Bangle Box' },
    ],
    variants: [
      { sku: 'PROD-JWL-010-24', name: 'Size 2-4 (2.25 in)', price: 85500, mrp: 95000, stockQuantity: 4, attributes: { BangleSize: '2-4' } },
      { sku: 'PROD-JWL-010-26', name: 'Size 2-6 (2.37 in)', price: 85500, mrp: 95000, stockQuantity: 4, attributes: { BangleSize: '2-6' } },
    ]
  },
  {
    sku: 'PROD-JWL-011',
    name: 'BlueStone 18k White Gold Sapphire & Diamond Pendant',
    slug: 'bluestone-18k-white-gold-sapphire-pendant',
    description: 'Royal teardrop blue sapphire gemstone surrounded by a halo of 16 sparkling natural diamonds set in 18k white gold.',
    brand: 'BlueStone',
    categorySlug: 'jewellery',
    subcategorySlug: 'necklaces-chains',
    modelNumber: 'BOSP0391P01',
    mrp: 38000,
    currentPrice: 32300,
    originalPrice: 38000,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 12,
    lowStockThreshold: 3,
    rating: 4.8,
    reviewCount: 105,
    tags: ['bluestone', 'sapphire pendant', 'white gold', 'halo pendant', 'diamond pendant'],
    specifications: { Metal: '18K White Gold', Gemstone: 'Natural Blue Sapphire (0.75 ct)', HaloDiamonds: '0.12 ct GH-VS', Certification: 'SGL Certified' },
    images: [
      { url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'BlueStone Blue Sapphire Diamond Halo Pendant' },
      { url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Blue Sapphire Facet Refraction Detail' },
      { url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'BlueStone White Gold Loop & Chain Pass' },
      { url: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'BlueStone Navy Presentation Box' },
    ],
    variants: [
      { sku: 'PROD-JWL-011-PENDANT', name: '18k White Gold Pendant Only', price: 32300, mrp: 38000, stockQuantity: 12, attributes: { Pack: 'Pendant Only' } }
    ]
  },
  {
    sku: 'PROD-JWL-012',
    name: 'Clara 925 Sterling Silver Solitaire Studs for Men',
    slug: 'clara-925-silver-solitaire-studs-men',
    description: 'Sleek masculine 925 sterling silver square solitaire ear studs set with Swiss Zirconia stone and secure screw post.',
    brand: 'Clara',
    categorySlug: 'jewellery',
    subcategorySlug: 'earrings',
    modelNumber: 'CL-MN-STD-01',
    mrp: 1999,
    currentPrice: 1399,
    originalPrice: 1999,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 35,
    lowStockThreshold: 7,
    rating: 4.6,
    reviewCount: 165,
    tags: ['clara', 'men studs', 'silver studs', '925 silver', 'single ear stud'],
    specifications: { Metal: '925 Sterling Silver', Stone: 'Swiss Zirconia 5mm', Finish: 'High Polish Silver', Post: 'Screw Post' },
    images: [
      { url: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Clara Men Square Silver Solitaire Stud Pair' },
      { url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Clara Swiss Zirconia Square Prong Setting' },
      { url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Clara 925 Silver Stamp & Screw Post' },
      { url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Clara Silver Care Cloth Box' },
    ],
    variants: [
      { sku: 'PROD-JWL-012-PAIR', name: 'Pair (2 Studs)', price: 1399, mrp: 1999, stockQuantity: 20, attributes: { Pack: 'Pair' } },
      { sku: 'PROD-JWL-012-SINGLE', name: 'Single Stud', price: 799, mrp: 1199, stockQuantity: 15, attributes: { Pack: 'Single Stud' } },
    ]
  },
  {
    sku: 'PROD-JWL-013',
    name: 'Senco Gold 22k Yellow Gold Choker Necklace Set',
    slug: 'senco-gold-22k-choker-necklace-set',
    description: 'Heritage Bengali craftsmanship 22k gold choker necklace with elaborate die-cut mesh design, matching dangling earrings, and adjustable gold thread cord.',
    brand: 'Senco Gold',
    categorySlug: 'jewellery',
    subcategorySlug: 'necklaces-chains',
    modelNumber: 'SG-CHK-22K-02',
    mrp: 145000,
    currentPrice: 130500,
    originalPrice: 145000,
    discount: 10.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 5,
    lowStockThreshold: 1,
    rating: 4.9,
    reviewCount: 62,
    tags: ['senco gold', 'choker necklace', '22k gold set', 'bridal choker', 'bengali gold craftsmanship'],
    specifications: { Purity: '22K (916) BIS Hallmarked', TotalWeight: '22.4 grams', Pack: 'Choker + Matching Earrings', Closure: 'Adjustable Tar (Cord)' },
    images: [
      { url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Senco Gold 22k Gold Choker & Earrings Set' },
      { url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Senco Gold Mesh & Granule Work Detail' },
      { url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Senco Gold Hallmark & Cord Loop' },
      { url: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Senco Royal Velvet Necklace Case' },
    ],
    variants: [
      { sku: 'PROD-JWL-013-SET', name: 'Choker + Earrings Set', price: 130500, mrp: 145000, stockQuantity: 5, attributes: { Set: 'Necklace + Earrings' } }
    ]
  },
  {
    sku: 'PROD-JWL-014',
    name: 'Shining Diva 18k Rose Gold Plated Crystal Hoops',
    slug: 'shining-diva-rose-gold-crystal-hoop-earrings',
    description: 'Chic everyday huggie hoop earrings plated in 18k rose gold studded with micro-pave Swiss crystal accents.',
    brand: 'Shining Diva',
    categorySlug: 'jewellery',
    subcategorySlug: 'earrings',
    modelNumber: 'SD-HGP-102',
    mrp: 1499,
    currentPrice: 499,
    originalPrice: 1499,
    discount: 66.7,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 60,
    lowStockThreshold: 12,
    rating: 4.5,
    reviewCount: 390,
    tags: ['shining diva', 'hoop earrings', 'rose gold hoops', 'huggie hoops', 'crystal hoops'],
    specifications: { Plating: '18k Rose Gold Plated', Diameter: '15mm', Stones: 'Swiss Micro-Pave Crystal', Clasp: 'Hinged Snap Closure' },
    images: [
      { url: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Shining Diva Rose Gold Huggie Hoop Pair' },
      { url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Shining Diva Micro Pave Crystal Row Sparkle' },
      { url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Shining Diva Hinged Latch Mechanism' },
      { url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Shining Diva Card Packaging' },
    ],
    variants: [
      { sku: 'PROD-JWL-014-ROSE', name: 'Rose Gold Plated', price: 499, mrp: 1499, stockQuantity: 30, attributes: { Color: 'Rose Gold' } },
      { sku: 'PROD-JWL-014-SIL', name: 'Silver Plated', price: 499, mrp: 1499, stockQuantity: 30, attributes: { Color: 'Silver' } },
    ]
  },
  {
    sku: 'PROD-JWL-015',
    name: 'Orra 18k Yellow Gold Diamond Platinum Couple Bands',
    slug: 'orra-18k-gold-platinum-couple-bands',
    description: 'Matching dual-tone couple wedding bands combining 950 Platinum and 18k Yellow Gold accented with solitaire diamonds.',
    brand: 'Orra',
    categorySlug: 'jewellery',
    subcategorySlug: 'rings',
    modelNumber: 'OR-CB-950-01',
    mrp: 98000,
    currentPrice: 88200,
    originalPrice: 98000,
    discount: 10.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 10,
    lowStockThreshold: 2,
    rating: 4.9,
    reviewCount: 75,
    tags: ['orra', 'platinum bands', 'couple rings', 'wedding bands', 'diamond couple bands'],
    specifications: { Metal: 'Pt950 Platinum + 18k Yellow Gold', Diamonds: 'Natural VS GH Solitaires', Pack: 'Pair of 2 Rings', Certificate: 'IGI Certified' },
    images: [
      { url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Orra Platinum & Gold Couple Bands Pair' },
      { url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Orra Platinum Brushed Polish Finish' },
      { url: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Orra Diamond Flush Mount Detail' },
      { url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Orra Luxury Wooden Presentation Box' },
    ],
    variants: [
      { sku: 'PROD-JWL-015-SET', name: 'His & Hers Couple Bands Pair', price: 88200, mrp: 98000, stockQuantity: 10, attributes: { Pack: 'Set of 2 Rings' } }
    ]
  }
];
