import { ProductStatus } from '@prisma/client';

export const kitchenAppliancesProducts = [
  {
    sku: 'PROD-KAP-001',
    name: 'Philips HD9252/90 Digital Air Fryer 4.1L',
    slug: 'philips-hd9252-90-digital-air-fryer',
    description: 'Rapid Air technology with unique starfish design for up to 90% less fat. Touchscreen panel with 7 presets, keep warm mode, and NutriU app recipe connection.',
    brand: 'Philips',
    categorySlug: 'kitchen-appliances-utensils',
    subcategorySlug: 'small-kitchen-appliances',
    modelNumber: 'HD9252/90',
    mrp: 11995,
    currentPrice: 8995,
    originalPrice: 11995,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 25,
    lowStockThreshold: 5,
    rating: 4.8,
    reviewCount: 610,
    tags: ['philips', 'air fryer', 'digital air fryer', 'rapid air', 'healthy cooking'],
    specifications: { Capacity: '4.1 Liters', Power: '1400W', PresetPrograms: '7 Touchscreen Presets', PanMaterial: 'Non-Stick Dishwasher Safe' },
    images: [
      { url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Philips Digital Air Fryer Black Glossy Body' },
      { url: 'https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Philips Air Fryer Touchscreen Digital Display presets' },
      { url: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Philips Non-Stick Air Fryer Basket Opened' },
      { url: 'https://images.unsplash.com/photo-1507048685967-837c71e7829f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Philips Starfish Base Air Flow Mechanism' },
    ],
    variants: [
      { sku: 'PROD-KAP-001-BLK', name: 'Black 4.1L', price: 8995, mrp: 11995, stockQuantity: 15, attributes: { Color: 'Black' } },
      { sku: 'PROD-KAP-001-WHT', name: 'White 4.1L', price: 8995, mrp: 11995, stockQuantity: 10, attributes: { Color: 'White' } },
    ]
  },
  {
    sku: 'PROD-KAP-002',
    name: 'Nespresso Vertuo Pop Espresso Coffee Machine',
    slug: 'nespresso-vertuo-pop-coffee-machine',
    description: 'Compact pod coffee maker powered by Centrifusion extraction technology reading barcode on capsules to brew 5 cup sizes with thick velvet crema.',
    brand: 'Nespresso',
    categorySlug: 'kitchen-appliances-utensils',
    subcategorySlug: 'small-kitchen-appliances',
    modelNumber: 'ENV90.B',
    mrp: 16900,
    currentPrice: 14365,
    originalPrice: 16900,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 18,
    lowStockThreshold: 4,
    rating: 4.7,
    reviewCount: 290,
    tags: ['nespresso', 'vertuo pop', 'coffee machine', 'espresso maker', 'coffee pods'],
    specifications: { Technology: 'Centrifusion Extraction', HeatUpTime: '30 Seconds', WaterTank: '600ml', AutoOff: 'After 2 Minutes' },
    images: [
      { url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Nespresso Vertuo Pop Liquorice Black Front' },
      { url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Nespresso Barcode Reader Capsule Head Opened' },
      { url: 'https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Nespresso Espresso Crema Pouring into Glass' },
      { url: 'https://images.unsplash.com/photo-1507048685967-837c71e7829f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Nespresso Removable Water Tank & Drip Tray' },
    ],
    variants: [
      { sku: 'PROD-KAP-002-BLK', name: 'Liquorice Black', price: 14365, mrp: 16900, stockQuantity: 10, attributes: { Color: 'Liquorice Black' } },
      { sku: 'PROD-KAP-002-YEL', name: 'Mango Yellow', price: 14365, mrp: 16900, stockQuantity: 8, attributes: { Color: 'Mango Yellow' } },
    ]
  },
  {
    sku: 'PROD-KAP-003',
    name: 'Vitamix E310 Explorian Professional Blender',
    slug: 'vitamix-e310-explorian-blender',
    description: 'Commercial-grade kitchen blender featuring 2.0 HP motor, ten variable speed controls, pulse feature, laser-cut hardened stainless steel blades, and 1.4L container.',
    brand: 'Vitamix',
    categorySlug: 'kitchen-appliances-utensils',
    subcategorySlug: 'small-kitchen-appliances',
    modelNumber: 'E310-065884',
    mrp: 39900,
    currentPrice: 33915,
    originalPrice: 39900,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 10,
    lowStockThreshold: 2,
    rating: 4.9,
    reviewCount: 380,
    tags: ['vitamix', 'e310', 'blender', 'commercial blender', 'smoothie maker'],
    specifications: { Motor: '2.0 Peak Horsepower', Container: '1.4 Liter BPA-Free Eastman Tritan', Blades: '3-Inch Laser-Cut Stainless Steel', Warranty: '5 Years' },
    images: [
      { url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Vitamix E310 Explorian Blender Black Base' },
      { url: 'https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Vitamix Variable Speed Dial & Pulse Switch' },
      { url: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Vitamix Laser Cut Stainless Steel Blades Bottom' },
      { url: 'https://images.unsplash.com/photo-1507048685967-837c71e7829f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Vitamix Tamper Tool & 1.4L Tritan Pitcher' },
    ],
    variants: [
      { sku: 'PROD-KAP-003-BLK', name: 'Black 1.4L Container', price: 33915, mrp: 39900, stockQuantity: 10, attributes: { Color: 'Black' } }
    ]
  },
  {
    sku: 'PROD-KAP-004',
    name: 'Prestige Tri-Ply Stainless Steel Cookware Set (3 Pieces)',
    slug: 'prestige-tri-ply-stainless-steel-cookware-set',
    description: '3-layer stainless steel cookware set (Fry Pan, Kadai with Glass Lid, Saucepan) with aluminum core between two stainless steel layers for zero hot spots.',
    brand: 'Prestige',
    categorySlug: 'kitchen-appliances-utensils',
    subcategorySlug: 'cookware-pans',
    modelNumber: 'PR-TRIPLY-03',
    mrp: 6995,
    currentPrice: 4896,
    originalPrice: 6995,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 6,
    rating: 4.7,
    reviewCount: 420,
    tags: ['prestige', 'cookware set', 'triply stainless steel', 'kadai', 'fry pan'],
    specifications: { Layers: '3-Ply (SS304 + Aluminum + SS430)', InductionCompatible: 'Yes All Stovetops', Handles: 'Riveted Cool Touch', Pack: '3 Pieces' },
    images: [
      { url: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Prestige Tri-Ply Stainless Steel Cookware Set Array' },
      { url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Prestige Tri-Ply Kadai Mirror Finish Close' },
      { url: 'https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Prestige Toughened Glass Lid Steam Vent' },
      { url: 'https://images.unsplash.com/photo-1507048685967-837c71e7829f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Prestige Heavy Induction Bottom Base' },
    ],
    variants: [
      { sku: 'PROD-KAP-004-SET', name: '3-Piece Set with Glass Lid', price: 4896, mrp: 6995, stockQuantity: 30, attributes: { Pack: 'Set of 3' } }
    ]
  },
  {
    sku: 'PROD-KAP-005',
    name: 'Instant Pot Duo 7-in-1 Electric Pressure Cooker 5.7L',
    slug: 'instant-pot-duo-7-in-1-electric-cooker',
    description: 'Smart 7-in-1 electric cooker functioning as pressure cooker, slow cooker, rice cooker, steamer, sauté pan, yogurt maker, and food warmer.',
    brand: 'Instant Pot',
    categorySlug: 'kitchen-appliances-utensils',
    subcategorySlug: 'small-kitchen-appliances',
    modelNumber: 'DUO-60-V5',
    mrp: 14990,
    currentPrice: 10493,
    originalPrice: 14990,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 20,
    lowStockThreshold: 4,
    rating: 4.8,
    reviewCount: 750,
    tags: ['instant pot', 'electric pressure cooker', 'duo 7-in-1', 'slow cooker', 'rice cooker'],
    specifications: { Capacity: '5.7 Liters (6 Quart)', InnerPot: 'Food-Grade 18/8 Stainless Steel', Safety: '10 Proven Safety Mechanisms', Power: '1000W' },
    images: [
      { url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Instant Pot Duo 7-in-1 Brushed Stainless Body' },
      { url: 'https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Instant Pot Digital Control Panel One Touch Buttons' },
      { url: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Instant Pot Stainless Steel Inner Pot Removed' },
      { url: 'https://images.unsplash.com/photo-1507048685967-837c71e7829f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Instant Pot Pressure Release Valve Top Lid' },
    ],
    variants: [
      { sku: 'PROD-KAP-005-57L', name: '5.7 Liter (6-Quart)', price: 10493, mrp: 14990, stockQuantity: 20, attributes: { Capacity: '5.7 Liters' } }
    ]
  },
  {
    sku: 'PROD-KAP-006',
    name: 'Borosil Glass Lunch Box Set with Insulated Bag (4 Containers)',
    slug: 'borosil-glass-lunch-box-set-4-containers',
    description: '100% borosilicate glass containers that are microwave, oven, freezer and dishwasher safe with air-tight leakproof silicone seal lids and thermal bag.',
    brand: 'Borosil',
    categorySlug: 'kitchen-appliances-utensils',
    subcategorySlug: 'cutlery-containers',
    modelNumber: 'HP-GLB-04',
    mrp: 1990,
    currentPrice: 1492,
    originalPrice: 1990,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.7,
    reviewCount: 510,
    tags: ['borosil', 'glass lunch box', 'borosilicate glass', 'tiffin box', 'microwave safe'],
    specifications: { Material: '100% Borosilicate Glass', TemperatureRange: 'Up to 400 deg C in Oven', Pack: '4 Containers (320ml x 2 + 400ml x 2)', Bag: 'Thermal Insulated Fabric' },
    images: [
      { url: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Borosil Glass Lunch Box 4 Containers with Blue Bag' },
      { url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Borosil Air-Tight Clip Lock Lid Close' },
      { url: 'https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Borosil Glass Clarity & Silicone Gasket' },
      { url: 'https://images.unsplash.com/photo-1507048685967-837c71e7829f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Borosil Insulated Carry Bag Zipper' },
    ],
    variants: [
      { sku: 'PROD-KAP-006-4P', name: '4 Container Set with Blue Bag', price: 1492, mrp: 1990, stockQuantity: 25, attributes: { Pack: '4 Containers' } },
      { sku: 'PROD-KAP-006-4G', name: '4 Container Set with Grey Bag', price: 1492, mrp: 1990, stockQuantity: 15, attributes: { Pack: '4 Containers' } },
    ]
  },
  {
    sku: 'PROD-KAP-007',
    name: 'Morphy Richards 24L Convection Microwave Oven',
    slug: 'morphy-richards-24l-convection-microwave',
    description: '24-liter multi-function convection microwave oven featuring 250 auto-cook menus, stainless steel cavity, motorized rotisserie, and combination cooking modes.',
    brand: 'Morphy Richards',
    categorySlug: 'kitchen-appliances-utensils',
    subcategorySlug: 'small-kitchen-appliances',
    modelNumber: '24CG-DIGI',
    mrp: 15990,
    currentPrice: 12792,
    originalPrice: 15990,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 15,
    lowStockThreshold: 3,
    rating: 4.6,
    reviewCount: 220,
    tags: ['morphy richards', 'microwave oven', 'convection microwave', 'rotisserie', 'baking oven'],
    specifications: { Capacity: '24 Liters', Cavity: 'Stainless Steel Scratch Resistant', AutoMenus: '250 Pre-programmed Menus', Features: 'Child Lock + Deodorizer' },
    images: [
      { url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Morphy Richards Convection Microwave Front Mirror Door' },
      { url: 'https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Morphy Richards Digital Touchpad Control Knob' },
      { url: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Morphy Richards Stainless Steel Cavity Rotisserie Spit' },
      { url: 'https://images.unsplash.com/photo-1507048685967-837c71e7829f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Morphy Richards Glass Turntable & Wire Rack' },
    ],
    variants: [
      { sku: 'PROD-KAP-007-SLV', name: 'Silver & Black Mirror', price: 12792, mrp: 15990, stockQuantity: 15, attributes: { Color: 'Silver/Black' } }
    ]
  },
  {
    sku: 'PROD-KAP-008',
    name: 'Sujata Dynamix DX 900-Watt Mixer Grinder',
    slug: 'sujata-dynamix-dx-900w-mixer-grinder',
    description: 'Heavy-duty 900W commercial motor mixer grinder with double ball bearings, 90 minutes continuous rating, and 3 stainless steel dome jars.',
    brand: 'Sujata',
    categorySlug: 'kitchen-appliances-utensils',
    subcategorySlug: 'small-kitchen-appliances',
    modelNumber: 'DYNAMIX-DX',
    mrp: 7500,
    currentPrice: 6375,
    originalPrice: 7500,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 6,
    rating: 4.9,
    reviewCount: 890,
    tags: ['sujata', 'mixer grinder', '900w mixer', 'sujata dynamix', 'heavy duty mixer'],
    specifications: { Motor: '900 Watts Heavy Duty', Speed: '22,000 RPM', ContinuousRating: '90 Minutes', Jars: '3 Stainless Steel Jars' },
    images: [
      { url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Sujata Dynamix 900W Mixer Grinder Base & Jar' },
      { url: 'https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Sujata Rotary 3-Speed Switch Knob Close' },
      { url: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Sujata Stainless Steel Blades Assembly' },
      { url: 'https://images.unsplash.com/photo-1507048685967-837c71e7829f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Sujata Polycarbonate Dome Lids & Gaskets' },
    ],
    variants: [
      { sku: 'PROD-KAP-008-WHT', name: 'White 3 Jar Set', price: 6375, mrp: 7500, stockQuantity: 30, attributes: { Color: 'White' } }
    ]
  },
  {
    sku: 'PROD-KAP-009',
    name: 'Pigeon by Stovekraft 1.8L Stainless Steel Electric Kettle',
    slug: 'pigeon-1-8l-electric-kettle',
    description: 'Cordless 1500W rapid boiling electric kettle with 100% food-grade stainless steel body, auto shut-off safety protection, and 360-degree swivel base.',
    brand: 'Pigeon',
    categorySlug: 'kitchen-appliances-utensils',
    subcategorySlug: 'small-kitchen-appliances',
    modelNumber: 'PIG-KTL-18',
    mrp: 1245,
    currentPrice: 699,
    originalPrice: 1245,
    discount: 43.8,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 60,
    lowStockThreshold: 12,
    rating: 4.5,
    reviewCount: 1200,
    tags: ['pigeon', 'electric kettle', 'water kettle', 'stainless steel kettle', 'boiling water'],
    specifications: { Capacity: '1.8 Liters', Power: '1500W', Material: 'SUS304 Stainless Steel', Safety: 'Boil Dry Protection' },
    images: [
      { url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Pigeon 1.8L Stainless Steel Electric Kettle Profile' },
      { url: 'https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Pigeon Handle Power Switch LED Indicator' },
      { url: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Pigeon Wide Mouth Opened Lid Top View' },
      { url: 'https://images.unsplash.com/photo-1507048685967-837c71e7829f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Pigeon 360 Degree Cordless Power Base' },
    ],
    variants: [
      { sku: 'PROD-KAP-009-SLV', name: 'Stainless Steel Silver', price: 699, mrp: 1245, stockQuantity: 60, attributes: { Color: 'Silver' } }
    ]
  },
  {
    sku: 'PROD-KAP-010',
    name: 'Hawkins Contura Hard Anodized Pressure Cooker 3L',
    slug: 'hawkins-contura-hard-anodized-pressure-cooker-3l',
    description: 'Black hard anodized 3-liter pressure cooker with inner-fitting safety lid, non-tarnishing body, precision pressure regulator, and stay-cool handles.',
    brand: 'Hawkins',
    categorySlug: 'kitchen-appliances-utensils',
    subcategorySlug: 'cookware-pans',
    modelNumber: 'CB30',
    mrp: 2350,
    currentPrice: 1997,
    originalPrice: 2350,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.8,
    reviewCount: 840,
    tags: ['hawkins', 'pressure cooker', 'contura', 'hard anodized', '3l cooker'],
    specifications: { Capacity: '3 Liters', Material: 'Hard Anodized Aluminum (3.25mm)', BaseThickness: '3.25mm', Lid: 'Inside Fitting Safety Lid' },
    images: [
      { url: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Hawkins Contura Black Pressure Cooker 3L Front' },
      { url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Hawkins Pressure Regulator Whistle Valve Close' },
      { url: 'https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Hawkins Inside Fitting Curved Lid Gasket' },
      { url: 'https://images.unsplash.com/photo-1507048685967-837c71e7829f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Hawkins Bakelite Stay-Cool Handle Grip' },
    ],
    variants: [
      { sku: 'PROD-KAP-010-3L', name: '3 Liter Black', price: 1997, mrp: 2350, stockQuantity: 25, attributes: { Capacity: '3 Liters' } },
      { sku: 'PROD-KAP-010-5L', name: '5 Liter Black', price: 2750, mrp: 3200, stockQuantity: 15, attributes: { Capacity: '5 Liters' } },
    ]
  },
  {
    sku: 'PROD-KAP-011',
    name: 'Wonderchef Nutri-Blend 22000 RPM Mixer Smoothie Maker',
    slug: 'wonderchef-nutri-blend-22000-rpm-mixer',
    description: 'Compact super-fast blender with 400W 22000 RPM copper motor, surgical-grade stainless steel blades, and two transparent unbreakable polycarbonate jars.',
    brand: 'Wonderchef',
    categorySlug: 'kitchen-appliances-utensils',
    subcategorySlug: 'small-kitchen-appliances',
    modelNumber: '63152504',
    mrp: 5000,
    currentPrice: 2799,
    originalPrice: 5000,
    discount: 44.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 35,
    lowStockThreshold: 7,
    rating: 4.6,
    reviewCount: 610,
    tags: ['wonderchef', 'nutri-blend', 'smoothie maker', 'bullet blender', 'sanjeev kapoor'],
    specifications: { Motor: '400W 100% Copper', RPM: '22,000 RPM', Jars: '500ml + 300ml Polycarbonate', Blades: 'Grinding & Blending Dual Blades' },
    images: [
      { url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Wonderchef Nutri-Blend Black Motor Base with Jar' },
      { url: 'https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Wonderchef Surgical Steel Blade Attachment' },
      { url: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Wonderchef Sipper Lid & Storage Cap' },
      { url: 'https://images.unsplash.com/photo-1507048685967-837c71e7829f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Wonderchef Recipe Book by Sanjeev Kapoor' },
    ],
    variants: [
      { sku: 'PROD-KAP-011-BLK', name: 'Black 2 Jars Set', price: 2799, mrp: 5000, stockQuantity: 20, attributes: { Color: 'Black' } },
      { sku: 'PROD-KAP-011-RED', name: 'Crimson Red 2 Jars Set', price: 2799, mrp: 5000, stockQuantity: 15, attributes: { Color: 'Crimson Red' } },
    ]
  },
  {
    sku: 'PROD-KAP-012',
    name: 'Milton Thermosteel Flip Lid Vacuum Insulated Flask 1000ml',
    slug: 'milton-thermosteel-flask-1000ml',
    description: 'Double-walled vacuum insulated SUS304 stainless steel flask keeping beverages hot or cold for 24 hours, with leakproof flip lid cap cup.',
    brand: 'Milton',
    categorySlug: 'kitchen-appliances-utensils',
    subcategorySlug: 'cutlery-containers',
    modelNumber: 'TS-FL-1000',
    mrp: 1190,
    currentPrice: 952,
    originalPrice: 1190,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 50,
    lowStockThreshold: 10,
    rating: 4.8,
    reviewCount: 950,
    tags: ['milton', 'thermosteel', 'vacuum flask', 'hot cold bottle', 'insulated flask'],
    specifications: { Capacity: '1000ml (1 Liter)', Material: '18/8 Stainless Steel Inner & Outer', Insulation: '24 Hours Hot / Cold', Cap: 'Serves as Drinking Cup' },
    images: [
      { url: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Milton Thermosteel Silver 1000ml Flask Front' },
      { url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Milton Push Button Flip Spout Pouring' },
      { url: 'https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Milton Stainless Steel Cup Cap Unscrewed' },
      { url: 'https://images.unsplash.com/photo-1507048685967-837c71e7829f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Milton Thermosteel Outer Fabric Jacket Pouch' },
    ],
    variants: [
      { sku: 'PROD-KAP-012-1000', name: '1000ml Stainless Silver', price: 952, mrp: 1190, stockQuantity: 30, attributes: { Volume: '1000ml' } },
      { sku: 'PROD-KAP-012-750', name: '750ml Stainless Silver', price: 820, mrp: 1020, stockQuantity: 20, attributes: { Volume: '750ml' } },
    ]
  },
  {
    sku: 'PROD-KAP-013',
    name: 'Agaro Imperial Slow Juicer Cold Press 240W',
    slug: 'agaro-imperial-slow-juicer-cold-press',
    description: 'Cold press slow masticating juicer operating at 60 RPM to retain maximum nutrients and enzymes, featuring 74mm wide feeding chute and reverse function.',
    brand: 'AGARO',
    categorySlug: 'kitchen-appliances-utensils',
    subcategorySlug: 'small-kitchen-appliances',
    modelNumber: 'AG-IMP-33537',
    mrp: 18999,
    currentPrice: 13299,
    originalPrice: 18999,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 12,
    lowStockThreshold: 3,
    rating: 4.7,
    reviewCount: 310,
    tags: ['agaro', 'cold press juicer', 'slow juicer', 'masticating juicer', 'nutrient juicer'],
    specifications: { Speed: '60 RPM Low Speed Masticating', Power: '240W AC Motor', Chute: '74mm Wide Mouth', Strainers: 'Juice & Sorbet Strainers' },
    images: [
      { url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Agaro Imperial Slow Juicer Gunmetal Body' },
      { url: 'https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Agaro 74mm Wide Feeding Chute Top Angle' },
      { url: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Agaro Masticating Heavy Screw Auger' },
      { url: 'https://images.unsplash.com/photo-1507048685967-837c71e7829f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Agaro Pulp & Juice Jug Containers' },
    ],
    variants: [
      { sku: 'PROD-KAP-013-SLV', name: 'Gunmetal Grey', price: 13299, mrp: 18999, stockQuantity: 12, attributes: { Color: 'Gunmetal Grey' } }
    ]
  },
  {
    sku: 'PROD-KAP-014',
    name: 'Cello Checkers PET Plastic Air Tight Container Set (18 Pieces)',
    slug: 'cello-checkers-pet-container-set-18-pieces',
    description: 'BPA-free food grade clear PET plastic storage container jar set with checkered textured grip and 100% airtight screw cap lids for pantry organization.',
    brand: 'Cello',
    categorySlug: 'kitchen-appliances-utensils',
    subcategorySlug: 'cutlery-containers',
    modelNumber: 'CHK-SET-18',
    mrp: 1599,
    currentPrice: 959,
    originalPrice: 1599,
    discount: 40.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.6,
    reviewCount: 480,
    tags: ['cello', 'container set', 'pet jars', 'pantry storage', 'airtight jars'],
    specifications: { Material: 'BPA-Free Food Grade PET', Pack: '18 Jars (300ml x 6, 650ml x 6, 1200ml x 6)', Feature: 'Unbreakable Shatterproof' },
    images: [
      { url: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Cello Checkers 18 Piece Container Set Pantry Array' },
      { url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Cello Checkers Textured Surface Pattern Close' },
      { url: 'https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Cello Black Airtight Screw Cap Lid' },
      { url: 'https://images.unsplash.com/photo-1507048685967-837c71e7829f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Cello Stacked Containers Nesting Design' },
    ],
    variants: [
      { sku: 'PROD-KAP-014-BLK', name: '18 Jars Set / Black Lids', price: 959, mrp: 1599, stockQuantity: 25, attributes: { Color: 'Black Lids' } },
      { sku: 'PROD-KAP-014-RED', name: '18 Jars Set / Red Lids', price: 959, mrp: 1599, stockQuantity: 15, attributes: { Color: 'Red Lids' } },
    ]
  },
  {
    sku: 'PROD-KAP-015',
    name: 'Victorinox Swiss Classic 6-Piece Steak & Kitchen Knife Set',
    slug: 'victorinox-swiss-classic-knife-set-6-piece',
    description: 'Swiss-made kitchen knife set featuring ultrasharp wavy-edge stainless steel blades and ergonomic non-slip Fibrox polypropylene handles.',
    brand: 'Victorinox',
    categorySlug: 'kitchen-appliances-utensils',
    subcategorySlug: 'cutlery-containers',
    modelNumber: '6.7833.6',
    mrp: 3499,
    currentPrice: 2974,
    originalPrice: 3499,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 25,
    lowStockThreshold: 5,
    rating: 4.9,
    reviewCount: 310,
    tags: ['victorinox', 'swiss knife', 'kitchen knives', 'steak knives', 'serrated knife'],
    specifications: { BladeMaterial: 'Martensitic Stainless Steel', Handle: 'Polypropylene (PP)', Edge: '11cm Serrated Wavy Edge', Origin: 'Made in Switzerland' },
    images: [
      { url: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Victorinox Swiss Classic 6-Piece Knife Set Front' },
      { url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Victorinox Serrated Stainless Blade Edge Detail' },
      { url: 'https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Victorinox Swiss Cross Logo on Handle' },
      { url: 'https://images.unsplash.com/photo-1507048685967-837c71e7829f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Victorinox Gift Box Presentation' },
    ],
    variants: [
      { sku: 'PROD-KAP-015-BLK', name: 'Black Handles (Set of 6)', price: 2974, mrp: 3499, stockQuantity: 15, attributes: { Color: 'Black' } },
      { sku: 'PROD-KAP-015-RED', name: 'Swiss Red Handles (Set of 6)', price: 2974, mrp: 3499, stockQuantity: 10, attributes: { Color: 'Swiss Red' } },
    ]
  }
];
