import { ProductStatus } from '@prisma/client';

export const mensClothingProducts = [
  {
    sku: 'PROD-MCL-001',
    name: "Levi's 501 Original Fit Denim Jeans",
    slug: 'levis-501-original-fit-jeans',
    description: 'The iconic straight-leg denim jeans since 1873. Crafted with 100% premium heavy cotton denim and classic button fly.',
    brand: "Levi's",
    categorySlug: 'mens-clothing',
    subcategorySlug: 'mens-jeans-trousers',
    modelNumber: '00501-0114',
    mrp: 4599,
    currentPrice: 3499,
    originalPrice: 4599,
    discount: 23.9,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 45,
    lowStockThreshold: 8,
    rating: 4.8,
    reviewCount: 420,
    tags: ['levis', '501 jeans', 'denim', 'straight fit', 'mens fashion'],
    specifications: { Fit: 'Original Straight Fit', Fly: 'Button Fly', Fabric: '100% Cotton 12.5oz Denim' },
    images: [
      { url: 'https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: "Levi's 501 Original Blue Jeans Front" },
      { url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: "Levi's 501 Red Tab Back Pocket Detail" },
      { url: 'https://images.unsplash.com/photo-1490578474895-699bc4e2cf59?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: "Levi's 501 Denim Stitching" },
      { url: 'https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: "Levi's 501 Full Length Fit View" },
    ],
    variants: [
      { sku: 'PROD-MCL-001-32-32', name: 'Waist 32 / Length 32', price: 3499, mrp: 4599, stockQuantity: 20, attributes: { Waist: '32', Length: '32' } },
      { sku: 'PROD-MCL-001-34-32', name: 'Waist 34 / Length 32', price: 3499, mrp: 4599, stockQuantity: 15, attributes: { Waist: '34', Length: '32' } }
    ]
  },
  {
    sku: 'PROD-MCL-002',
    name: 'Nike Sportswear Tech Fleece Full-Zip Hoodie',
    slug: 'nike-sportswear-tech-fleece-hoodie',
    description: 'Premium lightweight fleece hoodie offering warmth without bulk. Features taped zippered arm pocket and 4-panel hood design.',
    brand: 'Nike',
    categorySlug: 'mens-clothing',
    subcategorySlug: 'mens-jackets',
    modelNumber: 'FB7921-010',
    mrp: 8995,
    currentPrice: 7495,
    originalPrice: 8995,
    discount: 16.6,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 5,
    rating: 4.9,
    reviewCount: 310,
    tags: ['nike', 'tech fleece', 'hoodie', 'sportswear', 'black hoodie'],
    specifications: { Material: '53% Cotton, 47% Polyester', Fit: 'Standard Relaxed Fit', Pocket: 'Zippered Sleeve Pocket' },
    images: [
      { url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Nike Tech Fleece Black Hoodie Front' },
      { url: 'https://images.unsplash.com/photo-1490578474895-699bc4e2cf59?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Nike Tech Fleece Sleeve Zipper Pocket' },
      { url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Nike Tech Fleece Hood Profile' },
      { url: 'https://images.unsplash.com/photo-1490578474895-699bc4e2cf59?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Nike Tech Fleece Chest Logo Detail' },
    ]
  },
  {
    sku: 'PROD-MCL-003',
    name: 'Tommy Hilfiger Classic Regular Fit Oxford Shirt',
    slug: 'tommy-hilfiger-classic-oxford-shirt',
    description: 'Pure cotton woven Oxford shirt featuring button-down collar, chest patch pocket with iconic flag embroidery, and curved hem.',
    brand: 'Tommy Hilfiger',
    categorySlug: 'mens-clothing',
    subcategorySlug: 'mens-shirts-tshirts',
    modelNumber: 'MW0MW17604',
    mrp: 5999,
    currentPrice: 4499,
    originalPrice: 5999,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 35,
    lowStockThreshold: 6,
    rating: 4.7,
    reviewCount: 230,
    tags: ['tommy hilfiger', 'oxford shirt', 'cotton shirt', 'mens shirt', 'formal casual'],
    specifications: { Fabric: '100% Organic Cotton', Collar: 'Button-Down Collar', Fit: 'Regular Fit' },
    images: [
      { url: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Tommy Hilfiger Blue Oxford Shirt Front' },
      { url: 'https://images.unsplash.com/photo-1490578474895-699bc4e2cf59?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Tommy Hilfiger Chest Flag Embroidery' },
      { url: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Tommy Hilfiger Button Collar Detail' },
      { url: 'https://images.unsplash.com/photo-1490578474895-699bc4e2cf59?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Tommy Hilfiger Cuff Buttons' },
    ]
  },
  {
    sku: 'PROD-MCL-004',
    name: 'U.S. Polo Assn. Men Solid Pique Polo T-Shirt',
    slug: 'us-polo-assn-pique-polo-tshirt',
    description: 'Signature breathable cotton pique polo with double horsemen embroidered logo on chest, ribbed collar, and two-button placket.',
    brand: 'U.S. Polo Assn.',
    categorySlug: 'mens-clothing',
    subcategorySlug: 'mens-shirts-tshirts',
    modelNumber: 'USTSH1024',
    mrp: 2299,
    currentPrice: 1599,
    originalPrice: 2299,
    discount: 30.4,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 50,
    lowStockThreshold: 10,
    rating: 4.6,
    reviewCount: 510,
    tags: ['us polo', 'polo shirt', 'pique tshirt', 'casual tshirt'],
    specifications: { Fabric: '100% Combed Cotton Pique', Fit: 'Slim Fit', Neck: 'Polo Collar with Placket' },
    images: [
      { url: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'U.S. Polo Assn. Navy Blue Polo Shirt' },
      { url: 'https://images.unsplash.com/photo-1490578474895-699bc4e2cf59?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'U.S. Polo Assn. Chest Horse Logo' },
      { url: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'U.S. Polo Assn. Ribbed Sleeves' },
      { url: 'https://images.unsplash.com/photo-1490578474895-699bc4e2cf59?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'U.S. Polo Assn. Side Slit Hem' },
    ]
  },
  {
    sku: 'PROD-MCL-005',
    name: 'Adidas Tiro 24 Training Track Jacket',
    slug: 'adidas-tiro-24-track-jacket',
    description: 'AEROREADY moisture-absorbing track jacket with iconic 3-Stripes along the sleeves and zippered side pockets.',
    brand: 'Adidas',
    categorySlug: 'mens-clothing',
    subcategorySlug: 'mens-jackets',
    modelNumber: 'IR9498',
    mrp: 4999,
    currentPrice: 3999,
    originalPrice: 4999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.8,
    reviewCount: 190,
    tags: ['adidas', 'tiro 24', 'track jacket', 'aeroready', 'sportswear'],
    specifications: { Material: '100% Recycled Polyester Doubleknit', Technology: 'AEROREADY Moisture Wicking', Fit: 'Regular Fit' },
    images: [
      { url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Adidas Tiro 24 Black Track Jacket Front' },
      { url: 'https://images.unsplash.com/photo-1490578474895-699bc4e2cf59?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Adidas 3-Stripes Shoulder Detail' },
      { url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Adidas Full Zip Collar Up' },
      { url: 'https://images.unsplash.com/photo-1490578474895-699bc4e2cf59?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Adidas Zippered Side Pockets' },
    ]
  },
  {
    sku: 'PROD-MCL-006',
    name: 'Allen Solly Men Textured Single-Breasted Slim Fit Blazer',
    slug: 'allen-solly-textured-slim-fit-blazer',
    description: 'Sharp two-button formal blazer tailored from poly-viscose blend with notch lapels, flap pockets, and double-vented back.',
    brand: 'Allen Solly',
    categorySlug: 'mens-clothing',
    subcategorySlug: 'mens-jackets',
    modelNumber: 'ASBZ10293',
    mrp: 8999,
    currentPrice: 6299,
    originalPrice: 8999,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 20,
    lowStockThreshold: 4,
    rating: 4.7,
    reviewCount: 160,
    tags: ['allen solly', 'blazer', 'formal jacket', 'slim fit blazer'],
    specifications: { Fabric: '65% Polyester, 35% Viscose', Closure: '2-Button Single Breasted', Vents: 'Double Back Vents' },
    images: [
      { url: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Allen Solly Navy Blue Slim Fit Blazer' },
      { url: 'https://images.unsplash.com/photo-1490578474895-699bc4e2cf59?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Allen Solly Lapel & Pocket Detail' },
      { url: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Allen Solly Interior Lining Pockets' },
      { url: 'https://images.unsplash.com/photo-1490578474895-699bc4e2cf59?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Allen Solly Sleeve Cuff Buttons' },
    ]
  },
  {
    sku: 'PROD-MCL-007',
    name: 'Puma Essentials Small Logo Men Fleece Hoodie',
    slug: 'puma-essentials-fleece-hoodie',
    description: 'Cozy fleece-lined pullover hoodie with kangaroo pocket, drawstring hood, and subtle Cat Logo chest print.',
    brand: 'Puma',
    categorySlug: 'mens-clothing',
    subcategorySlug: 'mens-jackets',
    modelNumber: '58668801',
    mrp: 3499,
    currentPrice: 2499,
    originalPrice: 3499,
    discount: 28.5,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 45,
    lowStockThreshold: 8,
    rating: 4.6,
    reviewCount: 280,
    tags: ['puma', 'essentials hoodie', 'fleece pullover', 'casual hoodie'],
    specifications: { Material: '66% Cotton, 34% Polyester Fleece', Fit: 'Regular Fit', Pocket: 'Front Kangaroo Pocket' },
    images: [
      { url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Puma Essentials Black Fleece Hoodie' },
      { url: 'https://images.unsplash.com/photo-1490578474895-699bc4e2cf59?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Puma Cat Logo Chest Embroidery' },
      { url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Puma Hoodie Kangaroo Pocket' },
      { url: 'https://images.unsplash.com/photo-1490578474895-699bc4e2cf59?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Puma Ribbed Cuffs Detail' },
    ]
  },
  {
    sku: 'PROD-MCL-008',
    name: 'Superdry Real Leather Biker Jacket',
    slug: 'superdry-real-leather-biker-jacket',
    description: 'Crafted from 100% genuine supple lambskin leather with asymmetric zip closure, zippered pockets, and quilted shoulder padding.',
    brand: 'Superdry',
    categorySlug: 'mens-clothing',
    subcategorySlug: 'mens-jackets',
    modelNumber: 'M5010041A',
    mrp: 24999,
    currentPrice: 19999,
    originalPrice: 24999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 12,
    lowStockThreshold: 2,
    rating: 4.9,
    reviewCount: 85,
    tags: ['superdry', 'leather jacket', 'biker jacket', 'lambskin', 'mens leather'],
    specifications: { Shell: '100% Genuine Lambskin Leather', Lining: '100% Polyester Satin', Closure: 'Asymmetric Heavy Zip' },
    images: [
      { url: 'https://images.unsplash.com/photo-1521223890158-f9f7c3d5d504?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Superdry Black Leather Biker Jacket Front' },
      { url: 'https://images.unsplash.com/photo-1490578474895-699bc4e2cf59?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Superdry Quilted Shoulder Padding' },
      { url: 'https://images.unsplash.com/photo-1521223890158-f9f7c3d5d504?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Superdry Zippered Sleeve Cuffs' },
      { url: 'https://images.unsplash.com/photo-1490578474895-699bc4e2cf59?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Superdry Heavyweight Zippers' },
    ]
  },
  {
    sku: 'PROD-MCL-009',
    name: 'Wrangler Authentics Men Long Sleeve Corduroy Shirt',
    slug: 'wrangler-authentics-corduroy-shirt',
    description: 'Durable 100% cotton fine-wale corduroy shirt featuring dual flap chest pockets and comfortable regular fit for layering.',
    brand: 'Wrangler',
    categorySlug: 'mens-clothing',
    subcategorySlug: 'mens-shirts-tshirts',
    modelNumber: 'ZM605TN',
    mrp: 3299,
    currentPrice: 2499,
    originalPrice: 3299,
    discount: 24.2,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 35,
    lowStockThreshold: 6,
    rating: 4.6,
    reviewCount: 140,
    tags: ['wrangler', 'corduroy shirt', 'cotton shirt', 'mens casual'],
    specifications: { Fabric: '100% Fine-Wale Cotton Corduroy', Fit: 'Relaxed Fit', Pockets: 'Twin Chest Flap Pockets' },
    images: [
      { url: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Wrangler Tan Corduroy Shirt Front' },
      { url: 'https://images.unsplash.com/photo-1490578474895-699bc4e2cf59?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Wrangler Corduroy Texture Close-up' },
      { url: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Wrangler Buttoned Chest Pocket' },
      { url: 'https://images.unsplash.com/photo-1490578474895-699bc4e2cf59?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Wrangler Cuff Stitching' },
    ]
  },
  {
    sku: 'PROD-MCL-010',
    name: 'Van Heusen World Wear Formal Trousers',
    slug: 'van-heusen-world-wear-formal-trousers',
    description: 'Flat-front formal trousers woven from premium wrinkle-resistant poly-wool blend with custom grip waistband.',
    brand: 'Van Heusen',
    categorySlug: 'mens-clothing',
    subcategorySlug: 'mens-jeans-trousers',
    modelNumber: 'VHTR1094',
    mrp: 3499,
    currentPrice: 2699,
    originalPrice: 3499,
    discount: 22.8,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.7,
    reviewCount: 310,
    tags: ['van heusen', 'formal trousers', 'flat front', 'office trousers'],
    specifications: { Fabric: 'Poly-Wool Blend', Front: 'Flat Front', Waistband: 'Shirt-Grip Rubberized Waistband' },
    images: [
      { url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Van Heusen Charcoal Formal Trousers' },
      { url: 'https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Van Heusen Waistband Button Detail' },
      { url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Van Heusen Rear Pocket Crease' },
      { url: 'https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Van Heusen Ankle Hem Crease' },
    ]
  },
  {
    sku: 'PROD-MCL-011',
    name: 'Calvin Klein Liquid Touch Cotton Crew Neck T-Shirt 3-Pack',
    slug: 'calvin-klein-liquid-touch-tshirt-3pack',
    description: 'Ultra-soft liquid touch spun cotton crew neck tees engineered with stretch for supreme softness and fit retention.',
    brand: 'Calvin Klein',
    categorySlug: 'mens-clothing',
    subcategorySlug: 'mens-shirts-tshirts',
    modelNumber: 'NB2218-001',
    mrp: 4999,
    currentPrice: 3999,
    originalPrice: 4999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 5,
    rating: 4.8,
    reviewCount: 220,
    tags: ['calvin klein', 't-shirt 3-pack', 'crew neck', 'liquid touch cotton'],
    specifications: { Fabric: '95% Liquid Touch Cotton, 5% Elastane', Pack: '3 Pack (Black, Grey, White)', Neck: 'Crew Neck' },
    images: [
      { url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Calvin Klein Crew Neck T-Shirt Front' },
      { url: 'https://images.unsplash.com/photo-1490578474895-699bc4e2cf59?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Calvin Klein Lower Hem Monogram Logo' },
      { url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Calvin Klein Neck Tag Print' },
      { url: 'https://images.unsplash.com/photo-1490578474895-699bc4e2cf59?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Calvin Klein 3 Pack Folded Stack' },
    ]
  },
  {
    sku: 'PROD-MCL-012',
    name: 'Jack & Jones Men Slim Fit Chino Trousers',
    slug: 'jack-jones-slim-fit-chino-trousers',
    description: 'Stretch cotton twill chinos styled with slant front pockets, buttoned welt rear pockets, and comfortable low rise.',
    brand: 'Jack & Jones',
    categorySlug: 'mens-clothing',
    subcategorySlug: 'mens-jeans-trousers',
    modelNumber: '12182901',
    mrp: 3299,
    currentPrice: 2299,
    originalPrice: 3299,
    discount: 30.3,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.6,
    reviewCount: 195,
    tags: ['jack jones', 'chinos', 'slim fit trousers', 'cotton chinos'],
    specifications: { Material: '98% Cotton, 2% Elastane Twill', Fit: 'Slim Fit', Pockets: '2 Front Slant + 2 Back Welt' },
    images: [
      { url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Jack & Jones Beige Chino Trousers Front' },
      { url: 'https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Jack & Jones Waistband Loop Detail' },
      { url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Jack & Jones Back Pocket Button' },
      { url: 'https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Jack & Jones Ankle Cuff Turnup' },
    ]
  },
  {
    sku: 'PROD-MCL-013',
    name: 'Under Armour Tech 2.0 Short Sleeve T-Shirt',
    slug: 'under-armour-tech-20-tshirt',
    description: 'UA Tech fabric is quick-drying, ultra-soft & has a natural feel. Anti-odor technology prevents growth of odor-causing microbes.',
    brand: 'Under Armour',
    categorySlug: 'mens-clothing',
    subcategorySlug: 'mens-shirts-tshirts',
    modelNumber: '1326413-001',
    mrp: 1999,
    currentPrice: 1499,
    originalPrice: 1999,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 60,
    lowStockThreshold: 12,
    rating: 4.8,
    reviewCount: 390,
    tags: ['under armour', 'tech 2.0', 'gym tshirt', 'workout shirt', 'quick dry'],
    specifications: { Fabric: '100% UA Tech Polyester', Feature: 'Anti-Odor & Quick Dry', Fit: 'Loose Streamlined Fit' },
    images: [
      { url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Under Armour Tech 2.0 Black T-Shirt' },
      { url: 'https://images.unsplash.com/photo-1490578474895-699bc4e2cf59?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Under Armour Chest Logo Print' },
      { url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Under Armour Moisture Wicking Fabric' },
      { url: 'https://images.unsplash.com/photo-1490578474895-699bc4e2cf59?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Under Armour Back Neck Logo' },
    ]
  },
  {
    sku: 'PROD-MCL-014',
    name: 'Pepe Jeans London Men Regular Fit Denim Jacket',
    slug: 'pepe-jeans-regular-fit-denim-jacket',
    description: 'Rugged classic trucker denim jacket featuring buttoned chest flap pockets, button closure, and adjustable waist tabs.',
    brand: 'Pepe Jeans',
    categorySlug: 'mens-clothing',
    subcategorySlug: 'mens-jackets',
    modelNumber: 'PM402194',
    mrp: 5999,
    currentPrice: 4199,
    originalPrice: 5999,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 25,
    lowStockThreshold: 5,
    rating: 4.7,
    reviewCount: 175,
    tags: ['pepe jeans', 'denim jacket', 'trucker jacket', 'mens jacket'],
    specifications: { Fabric: '100% Rigid Cotton Denim', Style: 'Trucker Denim Jacket', Pockets: '4 Pocket Styling' },
    images: [
      { url: 'https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Pepe Jeans Blue Denim Trucker Jacket' },
      { url: 'https://images.unsplash.com/photo-1490578474895-699bc4e2cf59?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Pepe Jeans Metallic Buttons' },
      { url: 'https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Pepe Jeans Chest Pocket Leather Patch' },
      { url: 'https://images.unsplash.com/photo-1490578474895-699bc4e2cf59?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Pepe Jeans Back Hem Waist Adjustment' },
    ]
  },
  {
    sku: 'PROD-MCL-015',
    name: 'Celio Men Solid Cotton Cargo Joggers',
    slug: 'celio-cotton-cargo-joggers',
    description: 'Utility urban cargo pants featuring elasticated drawstring waist, 6 utility flap pockets, and cuffed ankles.',
    brand: 'Celio',
    categorySlug: 'mens-clothing',
    subcategorySlug: 'mens-jeans-trousers',
    modelNumber: 'CEL-CARGO-771',
    mrp: 3999,
    currentPrice: 2799,
    originalPrice: 3999,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 6,
    rating: 4.6,
    reviewCount: 140,
    tags: ['celio', 'cargo joggers', 'cargo pants', 'utility joggers'],
    specifications: { Material: '98% Cotton, 2% Elastane', Waist: 'Elastic Drawstring', Pockets: '6 Pocket Utility Storage' },
    images: [
      { url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Celio Olive Green Cargo Joggers Front' },
      { url: 'https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Celio Side Flap Cargo Pocket' },
      { url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Celio Drawstring Elastic Waistband' },
      { url: 'https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Celio Elastic Ribbed Ankle Cuffs' },
    ]
  }
];
