import { ProductStatus } from '@prisma/client';

export const mobileAccessoriesProducts = [
  {
    sku: 'PROD-ACC-001',
    name: 'Anker Prime 20,000mAh Power Bank 200W',
    slug: 'anker-prime-20000mah-power-bank',
    description: 'Ultra-fast 200W output power bank with smart digital display, dual USB-C PD fast charging ports, and 100W rapid recharging.',
    brand: 'Anker',
    categorySlug: 'mobile-accessories',
    subcategorySlug: 'chargers-power-banks',
    modelNumber: 'A1336',
    mrp: 14999,
    currentPrice: 11999,
    originalPrice: 14999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.8,
    reviewCount: 310,
    tags: ['anker', 'power bank', '200w', 'fast charging', 'usb-c pd'],
    specifications: { Capacity: '20,000mAh', Output: '200W Max', Display: 'Smart OLED Color Display', Weight: '540g' },
    images: [
      { url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Anker Prime Power Bank Front Display' },
      { url: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Anker Prime Power Bank USB-C Ports' },
      { url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Anker Prime Power Bank Charging Laptop' },
      { url: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Anker Prime Compact Profile' },
    ]
  },
  {
    sku: 'PROD-ACC-002',
    name: 'Spigen Tough Armor MagSafe Case for iPhone 18 Pro Max',
    slug: 'spigen-tough-armor-magsafe-iphone-18-pro-max',
    description: 'Dual-layer military-grade drop protection with air cushion technology, integrated MagSafe magnetic ring, and pop-out kickstand.',
    brand: 'Spigen',
    categorySlug: 'mobile-accessories',
    subcategorySlug: 'phone-cases-covers',
    modelNumber: 'ACS07650',
    mrp: 3499,
    currentPrice: 2499,
    originalPrice: 3499,
    discount: 28.5,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 60,
    lowStockThreshold: 10,
    rating: 4.7,
    reviewCount: 450,
    tags: ['spigen', 'magsafe case', 'iphone 18 pro max', 'tough armor', 'kickstand'],
    specifications: { Material: 'TPU + Polycarbonate', Protection: 'MIL-STD 810G-516.6', Feature: 'MagSafe Compatible & Built-in Kickstand' },
    images: [
      { url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Spigen Tough Armor Black MagSafe Case' },
      { url: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Spigen Tough Armor Rear Kickstand Open' },
      { url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Spigen Tough Armor Camera Ring Protection' },
      { url: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Spigen Tough Armor Internal Air Cushion' },
    ]
  },
  {
    sku: 'PROD-ACC-003',
    name: 'Belkin BoostCharge Pro 3-in-1 MagSafe Charger 15W',
    slug: 'belkin-boostcharge-pro-3-in-1-magsafe',
    description: 'Official Made for MagSafe 15W fast wireless charging stand for iPhone, Apple Watch Ultra fast charging, and AirPods charging pad.',
    brand: 'Belkin',
    categorySlug: 'mobile-accessories',
    subcategorySlug: 'chargers-power-banks',
    modelNumber: 'WIZ017ttBK',
    mrp: 14999,
    currentPrice: 12499,
    originalPrice: 14999,
    discount: 16.6,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 25,
    lowStockThreshold: 5,
    rating: 4.8,
    reviewCount: 220,
    tags: ['belkin', 'magsafe charger', '3-in-1', 'wireless charger', 'apple accessory'],
    specifications: { iPhoneCharging: '15W MagSafe', WatchCharging: 'Apple Watch Fast Charger', PowerSupply: '40W AC Adapter Included' },
    images: [
      { url: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Belkin 3-in-1 MagSafe Charging Stand' },
      { url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Belkin MagSafe Stand iPhone Angle' },
      { url: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Belkin Watch Charging Puck' },
      { url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Belkin Base AirPod Charging Pad' },
    ]
  },
  {
    sku: 'PROD-ACC-004',
    name: 'Peak Design Mobile Tripod MagSafe Mount',
    slug: 'peak-design-mobile-tripod-magsafe',
    description: 'Precision-machined anodized aluminum ultra-portable micro tripod with SlimLink magnetic lock for video recording and photography.',
    brand: 'Peak Design',
    categorySlug: 'mobile-accessories',
    subcategorySlug: 'mounts-stands',
    modelNumber: 'M-TR-AA-BK-1',
    mrp: 7999,
    currentPrice: 6499,
    originalPrice: 7999,
    discount: 18.7,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 6,
    rating: 4.9,
    reviewCount: 180,
    tags: ['peak design', 'mobile tripod', 'magsafe stand', 'aluminum', 'vlogging'],
    specifications: { Material: 'Machined Anodized Aluminum', Compatibility: 'MagSafe & SlimLink', FoldedThickness: '0.5cm' },
    images: [
      { url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Peak Design Mobile Tripod Deployed' },
      { url: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Peak Design Mobile Tripod Folded Flat' },
      { url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Peak Design Ball Head Tilt Angle' },
      { url: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Peak Design Magnetic Ring Backing' },
    ]
  },
  {
    sku: 'PROD-ACC-005',
    name: 'ESR HaloLock Wireless Car Charger MagSafe Mount',
    slug: 'esr-halolock-wireless-car-charger',
    description: 'Strong 1,500g magnetic hold air-vent car phone mount with 15W CryoBoost cooling fan for fast wireless charging during navigation.',
    brand: 'ESR',
    categorySlug: 'mobile-accessories',
    subcategorySlug: 'mounts-stands',
    modelNumber: '2C542',
    mrp: 4299,
    currentPrice: 2999,
    originalPrice: 4299,
    discount: 30.2,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 45,
    lowStockThreshold: 8,
    rating: 4.6,
    reviewCount: 290,
    tags: ['esr', 'car mount', 'magsafe car charger', 'cryoboost', '15w'],
    specifications: { HoldingForce: '1,500g Magnetic Strength', Cooling: 'CryoBoost Fan Built-in', MountType: 'Air Vent Clamp' },
    images: [
      { url: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'ESR HaloLock Car Charger Mount Front' },
      { url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'ESR HaloLock Air Vent Clamp Detail' },
      { url: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'ESR HaloLock Magnetic Ring Light' },
      { url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'ESR HaloLock Car Dash View' },
    ]
  },
  {
    sku: 'PROD-ACC-006',
    name: 'Samsung 45W Super Fast Charging 2.0 Power Adapter',
    slug: 'samsung-45w-super-fast-charger',
    description: 'Official USB-C PPS 45W Super Fast Charging wall charger bundle with 5A braided 1.8m USB-C to USB-C cable for Galaxy devices.',
    brand: 'Samsung',
    categorySlug: 'mobile-accessories',
    subcategorySlug: 'chargers-power-banks',
    modelNumber: 'EP-T4510NBEGWW',
    mrp: 3499,
    currentPrice: 2499,
    originalPrice: 3499,
    discount: 28.5,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 50,
    lowStockThreshold: 10,
    rating: 4.8,
    reviewCount: 380,
    tags: ['samsung', '45w charger', 'super fast charging', 'usb-c pps', 'galaxy charger'],
    specifications: { Output: '45W Max (PDO/PPS)', CableIncluded: '1.8m 5A USB-C Cable', Technology: 'GaN Tech' },
    images: [
      { url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Samsung 45W Adapter & USB-C Cable' },
      { url: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Samsung 45W Adapter USB-C Port' },
      { url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Samsung 45W Wall Plug Prongs' },
      { url: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Samsung 45W Cable Connector' },
    ]
  },
  {
    sku: 'PROD-ACC-007',
    name: 'Native Union Belt Cable Pro USB-C to USB-C 240W 2.4m',
    slug: 'native-union-belt-cable-pro-240w',
    description: 'Ultra-durable Kevlar-reinforced braided 2.4m charging cable supporting EPR 240W Power Delivery and integrated leather strap.',
    brand: 'Native Union',
    categorySlug: 'mobile-accessories',
    subcategorySlug: 'cables-adapters',
    modelNumber: 'BELT-PRO-CC-2.4M',
    mrp: 4999,
    currentPrice: 3899,
    originalPrice: 4999,
    discount: 22.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 35,
    lowStockThreshold: 5,
    rating: 4.7,
    reviewCount: 140,
    tags: ['native union', 'usb-c cable', '240w pd', 'braided cable', 'kevlar'],
    specifications: { PowerDelivery: '240W EPR Support', Length: '2.4 meters (8ft)', Material: 'Recycled PET Braided Sleeve & Kevlar Core' },
    images: [
      { url: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Native Union Belt Cable Pro Coiled with Leather Strap' },
      { url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Native Union Cable Metal Connectors' },
      { url: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Native Union Braided Pattern Detail' },
      { url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Native Union Leather Strap Button' },
    ]
  },
  {
    sku: 'PROD-ACC-008',
    name: 'UGREEN 100W 20,000mAh Laptop Power Bank',
    slug: 'ugreen-100w-20000mah-power-bank',
    description: 'High-speed 100W PD 3.0 power bank capable of fast charging MacBooks, iPhones, and Galaxy devices simultaneously.',
    brand: 'UGREEN',
    categorySlug: 'mobile-accessories',
    subcategorySlug: 'chargers-power-banks',
    modelNumber: 'PB720',
    mrp: 9999,
    currentPrice: 7499,
    originalPrice: 9999,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 6,
    rating: 4.8,
    reviewCount: 260,
    tags: ['ugreen', 'power bank', '100w pd', '20000mah', 'laptop charger'],
    specifications: { Capacity: '20,000mAh', Output: '100W Max USB-C1', Ports: '2x USB-C + 1x USB-A' },
    images: [
      { url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'UGREEN 100W Power Bank Front Panel' },
      { url: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'UGREEN 100W Power Bank Port Hub' },
      { url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'UGREEN Power Bank Screen Percentage' },
      { url: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'UGREEN Power Bank Matte Finish' },
    ]
  },
  {
    sku: 'PROD-ACC-009',
    name: 'Spigen EZ Fit Tempered Glass Screen Protector for iPhone 18 Pro Max',
    slug: 'spigen-ez-fit-screen-protector-iphone-18-pro-max',
    description: 'Pack of 2 9H hardness tempered glass screen protectors with auto-alignment installation tray and oleophobic coating.',
    brand: 'Spigen',
    categorySlug: 'mobile-accessories',
    subcategorySlug: 'phone-cases-covers',
    modelNumber: 'AGL07660',
    mrp: 2499,
    currentPrice: 1699,
    originalPrice: 2499,
    discount: 32.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 70,
    lowStockThreshold: 15,
    rating: 4.8,
    reviewCount: 520,
    tags: ['spigen', 'screen protector', 'tempered glass', 'ez fit', 'iphone 18 pro max'],
    specifications: { Quantity: 'Pack of 2', Hardness: '9H Tempered Glass', Feature: 'Auto-Alignment Tray Included' },
    images: [
      { url: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Spigen EZ Fit Installation Tray Box' },
      { url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Spigen Tempered Glass Application' },
      { url: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Spigen Oleophobic Coating Test' },
      { url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Spigen EZ Fit Pack Contents' },
    ]
  },
  {
    sku: 'PROD-ACC-010',
    name: 'Anker MagGo Wireless Power Bank 10,000mAh',
    slug: 'anker-maggo-10000mah-wireless-power-bank',
    description: 'Qi2-certified 15W wireless charging power bank with MagSafe magnet, built-in kickstand, and smart LCD battery indicator.',
    brand: 'Anker',
    categorySlug: 'mobile-accessories',
    subcategorySlug: 'chargers-power-banks',
    modelNumber: 'A1654',
    mrp: 7999,
    currentPrice: 5999,
    originalPrice: 7999,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.8,
    reviewCount: 340,
    tags: ['anker', 'maggo', 'qi2 wireless', 'magsafe power bank', '10000mah'],
    specifications: { WirelessOutput: '15W Qi2 Certified', WiredOutput: '27W USB-C', Display: 'Smart Screen Indicator' },
    images: [
      { url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Anker MagGo Power Bank Attached to Phone' },
      { url: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Anker MagGo Kickstand Mode' },
      { url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Anker MagGo LCD Screen Percentage' },
      { url: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Anker MagGo Compact Size' },
    ]
  },
  {
    sku: 'PROD-ACC-011',
    name: 'Apple MagSafe FineWoven Wallet for iPhone',
    slug: 'apple-magsafe-finewoven-wallet',
    description: 'Crafted from durable microtwill material with built-in magnets that snap onto the back of your iPhone, with Find My support.',
    brand: 'Apple',
    categorySlug: 'mobile-accessories',
    subcategorySlug: 'phone-cases-covers',
    modelNumber: 'MT033ZM/A',
    mrp: 5900,
    currentPrice: 4990,
    originalPrice: 5900,
    discount: 15.4,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 28,
    lowStockThreshold: 5,
    rating: 4.4,
    reviewCount: 190,
    tags: ['apple', 'finewoven wallet', 'magsafe wallet', 'find my', 'card holder'],
    specifications: { Material: 'Microtwill FineWoven', Capacity: '3 Credit Cards', Feature: 'Find My Tracking Support' },
    images: [
      { url: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Apple FineWoven MagSafe Wallet Taupe' },
      { url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Apple FineWoven Wallet Card Slot' },
      { url: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Apple FineWoven Wallet Rear Magnets' },
      { url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Apple FineWoven Wallet iPhone Snapped' },
    ]
  },
  {
    sku: 'PROD-ACC-012',
    name: 'Satechi Aluminum Magnetic Desktop Stand for MagSafe',
    slug: 'satechi-aluminum-magnetic-desktop-stand',
    description: 'Sleek aluminum desktop stand with 360-degree rotation ball mount and MagSafe magnetic docking head.',
    brand: 'Satechi',
    categorySlug: 'mobile-accessories',
    subcategorySlug: 'mounts-stands',
    modelNumber: 'ST-MDSKM',
    mrp: 5499,
    currentPrice: 4299,
    originalPrice: 5499,
    discount: 21.8,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 20,
    lowStockThreshold: 4,
    rating: 4.7,
    reviewCount: 110,
    tags: ['satechi', 'desktop stand', 'aluminum stand', 'magsafe mount'],
    specifications: { Material: 'Space Gray Aluminum', Rotation: '360-Degree Ball Joint', Base: 'Weighted Anti-Slip Base' },
    images: [
      { url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Satechi Desktop Stand Space Gray Front' },
      { url: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Satechi Desktop Stand Magnetic Head' },
      { url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Satechi Desktop Stand Base Rubber Ring' },
      { url: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Satechi Desktop Stand Phone Docked' },
    ]
  },
  {
    sku: 'PROD-ACC-013',
    name: 'Anker 511 Charger Nano 30W GaN Wall Charger',
    slug: 'anker-511-charger-nano-30w',
    description: 'Ultra-compact 30W GaN II fast charger capable of high-speed charging iPhones, iPads, and MacBook Air.',
    brand: 'Anker',
    categorySlug: 'mobile-accessories',
    subcategorySlug: 'chargers-power-banks',
    modelNumber: 'A2147',
    mrp: 2499,
    currentPrice: 1799,
    originalPrice: 2499,
    discount: 28.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 60,
    lowStockThreshold: 12,
    rating: 4.9,
    reviewCount: 410,
    tags: ['anker', 'nano 30w', 'gan charger', 'fast charger', 'mini charger'],
    specifications: { Output: '30W Max USB-C PD', Technology: 'GaN II Tech', Size: '70% Smaller than standard 30W' },
    images: [
      { url: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Anker Nano 30W Charger Cube' },
      { url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Anker Nano 30W USB-C Port' },
      { url: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Anker Nano 30W Plug Prongs' },
      { url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Anker Nano 30W Next to Coin Size Comparison' },
    ]
  },
  {
    sku: 'PROD-ACC-014',
    name: 'Belkin BoostCharge Braided USB-C to Lightning Cable 2m',
    slug: 'belkin-boostcharge-braided-lightning-cable-2m',
    description: 'MFi-certified double-braided nylon charging cable tested to withstand 10,000+ bends for fast charging iPhones.',
    brand: 'Belkin',
    categorySlug: 'mobile-accessories',
    subcategorySlug: 'cables-adapters',
    modelNumber: 'CAA004bt2MBK',
    mrp: 2499,
    currentPrice: 1799,
    originalPrice: 2499,
    discount: 28.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 45,
    lowStockThreshold: 8,
    rating: 4.7,
    reviewCount: 230,
    tags: ['belkin', 'lightning cable', 'braided cable', 'mfi certified', '2m cable'],
    specifications: { Length: '2 Meters (6.6ft)', Certification: 'MFi Certified', Material: 'Double-Braided Nylon' },
    images: [
      { url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Belkin Braided Lightning Cable Black' },
      { url: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Belkin Cable Lightning Connector Tip' },
      { url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Belkin Cable Strain Relief Joints' },
      { url: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Belkin Cable Strap Wrap' },
    ]
  },
  {
    sku: 'PROD-ACC-015',
    name: 'Spigen Ultra Hybrid MagSafe Clear Case for Galaxy S26 Ultra',
    slug: 'spigen-ultra-hybrid-magsafe-galaxy-s26-ultra',
    description: 'Crystal-clear transparent hybrid case with anti-yellowing technology and integrated MagSafe ring for S26 Ultra.',
    brand: 'Spigen',
    categorySlug: 'mobile-accessories',
    subcategorySlug: 'phone-cases-covers',
    modelNumber: 'ACS07680',
    mrp: 2999,
    currentPrice: 2199,
    originalPrice: 2999,
    discount: 26.6,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.8,
    reviewCount: 310,
    tags: ['spigen', 'ultra hybrid', 'clear case', 'galaxy s26 ultra', 'magsafe'],
    specifications: { Material: 'Clear Polycarbonate Back + TPU Bumper', AntiYellowing: 'DuraClear Tech', AirCushion: '4 Corners Air Cushion' },
    images: [
      { url: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Spigen Ultra Hybrid Clear Case S26 Ultra' },
      { url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Spigen Clear Case Camera Cutouts' },
      { url: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Spigen Clear Case Corner Air Bumper' },
      { url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Spigen Clear Case Back Ring' },
    ]
  }
];
