import { ProductStatus } from '@prisma/client';

export const officeAccessoriesProducts = [
  {
    sku: 'PROD-OFC-001',
    name: 'Logitech MX Master 3S Performance Wireless Mouse',
    slug: 'logitech-mx-master-3s-wireless-mouse',
    description: 'Iconic ergonomic performance mouse with 8K DPI Quiet Clicks, MagSpeed Electromagnetic Scrolling wheel, Logi Options+ software customization, and USB-C fast charging.',
    brand: 'Logitech',
    categorySlug: 'office-computer-accessories',
    subcategorySlug: 'webcams-usb-hubs',
    modelNumber: '910-006561',
    mrp: 10995,
    currentPrice: 8796,
    originalPrice: 10995,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.9,
    reviewCount: 950,
    tags: ['logitech', 'mx master 3s', 'wireless mouse', 'ergonomic mouse', 'magspeed scroll'],
    specifications: { Sensor: '8,000 DPI Darkfield Laser Sensor', Clicks: 'Quiet Clicks (90% Noise Reduction)', Connectivity: 'Bluetooth LE + Logi Bolt USB Receiver', Battery: '70 Days Full Charge' },
    images: [
      { url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Logitech MX Master 3S Graphite Ergonomic Profile' },
      { url: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Logitech MagSpeed Machined Steel Scroll Wheel' },
      { url: 'https://images.unsplash.com/photo-1586105251261-72a756497a11?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Logitech Side Thumb Wheel & Gesture Button' },
      { url: 'https://images.unsplash.com/photo-1547394765-185e1e68f34e?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Logitech USB-C Fast Charging Port Front' },
    ],
    variants: [
      { sku: 'PROD-OFC-001-GRP', name: 'Graphite Black', price: 8796, mrp: 10995, stockQuantity: 25, attributes: { Color: 'Graphite' } },
      { sku: 'PROD-OFC-001-PL', name: 'Pale Grey', price: 8796, mrp: 10995, stockQuantity: 15, attributes: { Color: 'Pale Grey' } },
    ]
  },
  {
    sku: 'PROD-OFC-002',
    name: 'Keychron K2 Pro QMK/VIA Wireless Mechanical Keyboard',
    slug: 'keychron-k2-pro-mechanical-keyboard',
    description: '75% compact wireless custom mechanical keyboard with QMK/VIA programmable keys, hot-swappable Keychron K Pro switches, PBT double-shot keycaps, and RGB backlight.',
    brand: 'Keychron',
    categorySlug: 'office-computer-accessories',
    subcategorySlug: 'webcams-usb-hubs',
    modelNumber: 'K2P-J3',
    mrp: 11999,
    currentPrice: 9599,
    originalPrice: 11999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 25,
    lowStockThreshold: 5,
    rating: 4.8,
    reviewCount: 420,
    tags: ['keychron', 'keychron k2 pro', 'mechanical keyboard', 'hot swappable', 'mac windows keyboard'],
    specifications: { Layout: '75% Compact (84 Keys)', Switches: 'Hot-Swappable Keychron K Pro Red (Linear)', Keycaps: 'OSA Profile Double-Shot PBT', Battery: '4000 mAh (up to 300 hrs)' },
    images: [
      { url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Keychron K2 Pro Mechanical Keyboard RGB Light' },
      { url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Keychron PBT Double Shot Keycaps Texture Close' },
      { url: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Keychron Mac Windows System Toggle Switch' },
      { url: 'https://images.unsplash.com/photo-1586105251261-72a756497a11?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Keychron Hot-Swap Socket & Red Switch Pull' },
    ],
    variants: [
      { sku: 'PROD-OFC-002-RED', name: 'Keychron K Pro Red Switch (Linear)', price: 9599, mrp: 11999, stockQuantity: 15, attributes: { Switch: 'Red Linear' } },
      { sku: 'PROD-OFC-002-BRN', name: 'Keychron K Pro Brown Switch (Tactile)', price: 9599, mrp: 11999, stockQuantity: 10, attributes: { Switch: 'Brown Tactile' } },
    ]
  },
  {
    sku: 'PROD-OFC-003',
    name: 'CalDigit TS4 Thunderbolt 4 Dock 18-in-1 Expansion',
    slug: 'caldigit-ts4-thunderbolt-4-dock',
    description: 'Ultimate 18-port Thunderbolt 4 dock delivering 98W laptop charging, 2.5Gb Ethernet, 3x Thunderbolt 4 ports, 5x USB-A, 3x USB-C, UHS-II SD card reader, and 8K display support.',
    brand: 'CalDigit',
    categorySlug: 'office-computer-accessories',
    subcategorySlug: 'webcams-usb-hubs',
    modelNumber: 'TS4-US',
    mrp: 45000,
    currentPrice: 38250,
    originalPrice: 45000,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 10,
    lowStockThreshold: 2,
    rating: 4.9,
    reviewCount: 180,
    tags: ['caldigit', 'ts4 dock', 'thunderbolt 4 dock', 'usb hub', 'macbook dock'],
    specifications: { PowerDelivery: '98W Laptop Charging', TotalPorts: '18 Ports (3x TB4, 5x USB-A, 3x USB-C 10Gbps, 2.5GbE, DisplayPort 1.4, SD 4.0)', Video: 'Dual 4K 60Hz or Single 8K 60Hz' },
    images: [
      { url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'CalDigit TS4 Thunderbolt 4 Dock Space Grey Standing' },
      { url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'CalDigit TS4 Front SD Reader & USB-C 20W Port' },
      { url: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'CalDigit TS4 Rear Ports 2.5G Ethernet & DisplayPort' },
      { url: 'https://images.unsplash.com/photo-1586105251261-72a756497a11?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'CalDigit Heat-Dissipating Aluminum Ridge Casing' },
    ],
    variants: [
      { sku: 'PROD-OFC-003-SLV', name: 'Space Grey Aluminum', price: 38250, mrp: 45000, stockQuantity: 10, attributes: { Color: 'Space Grey' } }
    ]
  },
  {
    sku: 'PROD-OFC-004',
    name: 'Logitech Brio 4K Ultra HD Webcam with RightLight 3',
    slug: 'logitech-brio-4k-webcam',
    description: 'Premier 4K Ultra HD webcam with HDR, dual omni-directional noise-canceling microphones, Windows Hello facial recognition, and adjustable 65°/78°/90° field of view.',
    brand: 'Logitech',
    categorySlug: 'office-computer-accessories',
    subcategorySlug: 'webcams-usb-hubs',
    modelNumber: '960-001105',
    mrp: 24995,
    currentPrice: 19996,
    originalPrice: 24995,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 20,
    lowStockThreshold: 4,
    rating: 4.8,
    reviewCount: 510,
    tags: ['logitech', 'logitech brio', '4k webcam', 'streaming camera', 'windows hello camera'],
    specifications: { Resolution: '4K Ultra HD 30fps / 1080P 60fps', Zoom: '5x Digital Zoom', Lighting: 'RightLight 3 with HDR', Microphones: 'Dual Omni-Directional' },
    images: [
      { url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Logitech Brio 4K Webcam Mounted on Monitor' },
      { url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Logitech Brio Glass Lens & IR Sensor Array' },
      { url: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Logitech Brio Detachable Privacy Shade Cover' },
      { url: 'https://images.unsplash.com/photo-1586105251261-72a756497a11?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Logitech Brio Adjustable Universal Mounting Clip' },
    ],
    variants: [
      { sku: 'PROD-OFC-004-BLK', name: 'Black 4K Webcam', price: 19996, mrp: 24995, stockQuantity: 20, attributes: { Color: 'Black' } }
    ]
  },
  {
    sku: 'PROD-OFC-005',
    name: 'Satechi Aluminum Universal Ergonomic Laptop Stand Riser',
    slug: 'satechi-aluminum-laptop-stand-riser',
    description: 'Sleek premium aluminum laptop riser elevating laptop screen by 6 inches to eye level to improve posture and promote air airflow dissipation.',
    brand: 'Satechi',
    categorySlug: 'office-computer-accessories',
    subcategorySlug: 'laptop-stands-risers',
    modelNumber: 'ST-ALM-LS',
    mrp: 4999,
    currentPrice: 3999,
    originalPrice: 4999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 6,
    rating: 4.8,
    reviewCount: 340,
    tags: ['satechi', 'laptop stand', 'macbook stand', 'aluminum riser', 'desk setup'],
    specifications: { Height: '6 Inches Elevation', Material: 'Anodized Aluminum Alloy', Grip: 'Rubberized Anti-Slip Padding', Compatibility: 'Fits all 12 to 17 inch Laptops' },
    images: [
      { url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Satechi Space Grey Aluminum Laptop Stand Front' },
      { url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Satechi Rubberized Lip Hold & Cable Hole' },
      { url: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Satechi MacBook Pro Seated on Riser Side View' },
      { url: 'https://images.unsplash.com/photo-1586105251261-72a756497a11?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Satechi Base Anti-Scratch Rubber Pads' },
    ],
    variants: [
      { sku: 'PROD-OFC-005-SPG', name: 'Space Grey Aluminum', price: 3999, mrp: 4999, stockQuantity: 18, attributes: { Color: 'Space Grey' } },
      { sku: 'PROD-OFC-005-SLV', name: 'Silver Aluminum', price: 3999, mrp: 4999, stockQuantity: 12, attributes: { Color: 'Silver' } },
    ]
  },
  {
    sku: 'PROD-OFC-006',
    name: 'Anker PowerExpand 8-in-1 USB-C PD Media Hub',
    slug: 'anker-powerexpand-8-in-1-usb-c-hub',
    description: 'Pass-through 85W charging USB-C hub featuring 4K 60Hz HDMI, 1Gbps Ethernet, SD & MicroSD card readers, and 2x 10Gbps USB-A data ports.',
    brand: 'Anker',
    categorySlug: 'office-computer-accessories',
    subcategorySlug: 'webcams-usb-hubs',
    modelNumber: 'A8383',
    mrp: 7999,
    currentPrice: 5999,
    originalPrice: 7999,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 35,
    lowStockThreshold: 7,
    rating: 4.8,
    reviewCount: 490,
    tags: ['anker', 'usb-c hub', 'powerexpand', 'macbook hub', 'hdmi hub'],
    specifications: { Power: '100W Input (85W Pass-Through Charging)', Video: 'HDMI 4K at 60Hz', Ethernet: '1 Gbps RJ45', Data: '2x USB-A 10Gbps + 1x USB-C 10Gbps' },
    images: [
      { url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Anker PowerExpand 8-in-1 USB-C Hub Metallic Body' },
      { url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Anker 4K 60Hz HDMI & Ethernet Port Side' },
      { url: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Anker SD & MicroSD UHS-I Card Slots' },
      { url: 'https://images.unsplash.com/photo-1586105251261-72a756497a11?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Anker Braided Nylon USB-C Cable Connector' },
    ],
    variants: [
      { sku: 'PROD-OFC-006-GRY', name: 'Dark Grey Aluminum', price: 5999, mrp: 7999, stockQuantity: 35, attributes: { Color: 'Dark Grey' } }
    ]
  },
  {
    sku: 'PROD-OFC-007',
    name: 'Elgato Stream Deck MK.2 15 Customizable Macro Keys',
    slug: 'elgato-stream-deck-mk2',
    description: 'Essential controller for streamers and professionals featuring 15 customizable LCD keys to trigger unlimited actions, apps, audio, and smart lighting.',
    brand: 'Elgato',
    categorySlug: 'office-computer-accessories',
    subcategorySlug: 'webcams-usb-hubs',
    modelNumber: '10GBA9901',
    mrp: 15999,
    currentPrice: 13599,
    originalPrice: 15999,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 15,
    lowStockThreshold: 3,
    rating: 4.9,
    reviewCount: 390,
    tags: ['elgato', 'stream deck', 'macro pad', 'lcd keys', 'obs controller'],
    specifications: { Keys: '15 Customizable LCD Keys', Interface: 'USB 2.0 Cable', Stand: '45-Degree Fixed Desktop Stand', App: 'Elgato Stream Deck Store' },
    images: [
      { url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Elgato Stream Deck MK.2 Illuminated LCD Keys' },
      { url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Elgato Custom Icon Graphics Displayed on Key' },
      { url: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Elgato Detachable Faceplate Snap Off' },
      { url: 'https://images.unsplash.com/photo-1586105251261-72a756497a11?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Elgato Desktop Stand Angle Profile' },
    ],
    variants: [
      { sku: 'PROD-OFC-007-BLK', name: 'Black Frame MK.2', price: 13599, mrp: 15999, stockQuantity: 10, attributes: { Color: 'Black' } },
      { sku: 'PROD-OFC-007-WHT', name: 'White Frame MK.2', price: 13599, mrp: 15999, stockQuantity: 5, attributes: { Color: 'White' } },
    ]
  },
  {
    sku: 'PROD-OFC-008',
    name: 'Logitech Desk Mat Studio Series Anti-Fray Mouse Pad',
    slug: 'logitech-desk-mat-studio-series',
    description: 'Spacious 70cm x 30cm water-repellent fabric desk mat with non-slip rubber base, anti-fraying stitched edges, and fine weave tracking surface.',
    brand: 'Logitech',
    categorySlug: 'office-computer-accessories',
    subcategorySlug: 'webcams-usb-hubs',
    modelNumber: '956-000037',
    mrp: 2495,
    currentPrice: 1996,
    originalPrice: 2495,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.8,
    reviewCount: 420,
    tags: ['logitech', 'desk mat', 'mouse pad', 'large mouse pad', 'waterproof desk pad'],
    specifications: { Dimensions: '700 mm x 300 mm x 2 mm', Surface: '100% Recycled Polyester', Base: '72% Natural Rubber Non-Skid', Coating: 'Spill-Resistant Water Repellent' },
    images: [
      { url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Logitech Desk Mat Lavender Purple Unrolled' },
      { url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Logitech Anti-Fray Stitched Edge Detail' },
      { url: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Logitech Water Droplet Beading on Surface' },
      { url: 'https://images.unsplash.com/photo-1586105251261-72a756497a11?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Logitech Rubber Anti-Slip Bottom Weave' },
    ],
    variants: [
      { sku: 'PROD-OFC-008-LAV', name: 'Lavender Purple', price: 1996, mrp: 2495, stockQuantity: 15, attributes: { Color: 'Lavender' } },
      { sku: 'PROD-OFC-008-GRY', name: 'Mid Grey', price: 1996, mrp: 2495, stockQuantity: 25, attributes: { Color: 'Mid Grey' } },
    ]
  },
  {
    sku: 'PROD-OFC-009',
    name: 'BenQ ScreenBar Halo LED Monitor Light Bar with Wireless Controller',
    slug: 'benq-screenbar-halo-monitor-light-bar',
    description: 'Flagship automatic dimming monitor light bar featuring patented asymmetrical optical design, front & back dual lighting, and smart wireless rotary controller.',
    brand: 'BenQ',
    categorySlug: 'office-computer-accessories',
    subcategorySlug: 'webcams-usb-hubs',
    modelNumber: 'SCREENBAR-HALO',
    mrp: 19990,
    currentPrice: 16991,
    originalPrice: 19990,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 15,
    lowStockThreshold: 3,
    rating: 4.9,
    reviewCount: 290,
    tags: ['benq', 'screenbar halo', 'monitor light', 'screen light bar', 'eye care lamp'],
    specifications: { Illumination: '800 Lux at 45cm', Control: 'Wireless Touch Dial Controller', Fitting: 'Patented Counterweight Clamp Fits Curved Monitors', AmbientLight: 'Back Backlight Ring Included' },
    images: [
      { url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'BenQ ScreenBar Halo Mounted on Curved Monitor' },
      { url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'BenQ Wireless Rotary Touch Controller Dial' },
      { url: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'BenQ Backlight Ambient Light Diffuser' },
      { url: 'https://images.unsplash.com/photo-1586105251261-72a756497a11?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'BenQ Asymmetrical Optical Light Path' },
    ],
    variants: [
      { sku: 'PROD-OFC-009-HALO', name: 'Metallic Grey ScreenBar Halo Set', price: 16991, mrp: 19990, stockQuantity: 15, attributes: { Model: 'ScreenBar Halo' } }
    ]
  },
  {
    sku: 'PROD-OFC-010',
    name: 'Anker Work PowerConf S500 USB/Bluetooth Speakerphone',
    slug: 'anker-powerconf-s500-speakerphone',
    description: 'Conference room speakerphone with 4 VoiceRadar beamforming microphones, Hi-Fi 10W speaker, VoiceSpot technology, and Zoom Rooms certification.',
    brand: 'Anker Work',
    categorySlug: 'office-computer-accessories',
    subcategorySlug: 'webcams-usb-hubs',
    modelNumber: 'A3305',
    mrp: 19999,
    currentPrice: 15999,
    originalPrice: 19999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 12,
    lowStockThreshold: 3,
    rating: 4.8,
    reviewCount: 160,
    tags: ['anker', 'powerconf s500', 'speakerphone', 'conference microphone', 'zoom speakerphone'],
    specifications: { Microphones: '4 VoiceRadar Microphones (360 Deg Pickup)', Speaker: '10W Acoustic Clarity Speaker', Battery: 'up to 16 Hours Talk Time', Certifications: 'Zoom Rooms & Microsoft Teams' },
    images: [
      { url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Anker PowerConf S500 Speakerphone Top Face' },
      { url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Anker PowerConf LED Indicator Status Ring' },
      { url: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Anker Touch Sensitive Controls Mute Button' },
      { url: 'https://images.unsplash.com/photo-1586105251261-72a756497a11?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Anker Travel Case & USB-C Cable' },
    ],
    variants: [
      { sku: 'PROD-OFC-010-BLK', name: 'Black Metallic', price: 15999, mrp: 19999, stockQuantity: 12, attributes: { Color: 'Black' } }
    ]
  },
  {
    sku: 'PROD-OFC-011',
    name: 'Rain Design mStand Aluminum Laptop Stand',
    slug: 'rain-design-mstand-aluminum-laptop-stand',
    description: 'Single piece sturdy anodized aluminum desktop stand matching MacBook finish, elevating screen by 5.9 inches while acting as a heat sink.',
    brand: 'Rain Design',
    categorySlug: 'office-computer-accessories',
    subcategorySlug: 'laptop-stands-risers',
    modelNumber: 'RD-10032',
    mrp: 5999,
    currentPrice: 4799,
    originalPrice: 5999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 25,
    lowStockThreshold: 5,
    rating: 4.9,
    reviewCount: 520,
    tags: ['rain design', 'mstand', 'macbook stand', 'laptop riser', 'aluminum stand'],
    specifications: { Height: '5.9 Inches Elevation', Weight: '1.36 kg Solid Aluminum', Hole: '2 Inch Rear Cable Outlet', Fit: 'All MacBooks & Laptops' },
    images: [
      { url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Rain Design mStand Silver Aluminum Front' },
      { url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Rain Design Rear Circular Cable Organizer Pass' },
      { url: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Rain Design Rubber Pads Cushioning MacBook' },
      { url: 'https://images.unsplash.com/photo-1586105251261-72a756497a11?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Rain Design mStand Side Angle Profile' },
    ],
    variants: [
      { sku: 'PROD-OFC-011-SLV', name: 'Silver Anodized Aluminum', price: 4799, mrp: 5999, stockQuantity: 15, attributes: { Color: 'Silver' } },
      { sku: 'PROD-OFC-011-SPG', name: 'Space Grey Anodized Aluminum', price: 4799, mrp: 5999, stockQuantity: 10, attributes: { Color: 'Space Grey' } },
    ]
  },
  {
    sku: 'PROD-OFC-012',
    name: 'SanDisk Extreme PRO 1TB Portable External SSD V2 2000MB/s',
    slug: 'sandisk-extreme-pro-1tb-portable-ssd-v2',
    description: 'Ultra-fast NVMe portable solid state drive delivering up to 2000MB/s read/write speeds, IP65 water/dust resistance, and forged aluminum chassis.',
    brand: 'SanDisk',
    categorySlug: 'office-computer-accessories',
    subcategorySlug: 'webcams-usb-hubs',
    modelNumber: 'SDSSDE81-1T00',
    mrp: 18999,
    currentPrice: 14249,
    originalPrice: 18999,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 6,
    rating: 4.8,
    reviewCount: 680,
    tags: ['sandisk', 'extreme pro ssd', 'portable ssd', 'external ssd 1tb', 'fast ssd'],
    specifications: { Capacity: '1TB (1000 GB)', Interface: 'USB 3.2 Gen 2x2 Type-C', Speed: 'Up to 2000 MB/s Read & Write', Durability: 'IP65 Water & Dust Resistant + 3M Drop Proof' },
    images: [
      { url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'SanDisk Extreme Pro 1TB Portable SSD Front' },
      { url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'SanDisk Orange Carabiner Loop Hole Corner' },
      { url: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'SanDisk Rubberized Grippy Back Shell' },
      { url: 'https://images.unsplash.com/photo-1586105251261-72a756497a11?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'SanDisk USB-C to USB-C High Speed Cable' },
    ],
    variants: [
      { sku: 'PROD-OFC-012-1TB', name: '1TB Capacity / 2000MB/s', price: 14249, mrp: 18999, stockQuantity: 20, attributes: { Capacity: '1TB' } },
      { sku: 'PROD-OFC-012-2TB', name: '2TB Capacity / 2000MB/s', price: 23999, mrp: 29999, stockQuantity: 10, attributes: { Capacity: '2TB' } },
    ]
  },
  {
    sku: 'PROD-OFC-013',
    name: 'UGREEN 100W GaN Fast Wall Charger 4-Port',
    slug: 'ugreen-100w-gan-fast-wall-charger',
    description: 'Compact Nexode GaN wall charger with 3x USB-C PD and 1x USB-A ports capable of fast charging a MacBook Pro 16", iPad Pro, and iPhone simultaneously.',
    brand: 'UGREEN',
    categorySlug: 'office-computer-accessories',
    subcategorySlug: 'webcams-usb-hubs',
    modelNumber: 'UG-CD226',
    mrp: 6999,
    currentPrice: 4899,
    originalPrice: 6999,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 35,
    lowStockThreshold: 7,
    rating: 4.8,
    reviewCount: 450,
    tags: ['ugreen', 'gan charger', '100w charger', 'macbook charger', 'multi port charger'],
    specifications: { Power: '100W Max Total Output', Ports: '3x USB-C (100W PD) + 1x USB-A (22.5W)', Tech: 'GaNFast II Technology', Safety: 'Over-Temperature Protection' },
    images: [
      { url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'UGREEN 100W GaN 4-Port Wall Charger Body' },
      { url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'UGREEN 3 Type-C & 1 Type-A Port Layout' },
      { url: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'UGREEN Foldable AC Wall Prongs' },
      { url: 'https://images.unsplash.com/photo-1586105251261-72a756497a11?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'UGREEN Matte Black Metal Finish' },
    ],
    variants: [
      { sku: 'PROD-OFC-013-100W', name: '100W 4-Port Nexode Charger', price: 4899, mrp: 6999, stockQuantity: 35, attributes: { Power: '100W' } }
    ]
  },
  {
    sku: 'PROD-OFC-014',
    name: 'MOFT Invisible Slim Adhesive Folding Laptop Stand',
    slug: 'moft-invisible-slim-folding-laptop-stand',
    description: 'Ultra-thin 3mm paper-thin adhesive folding laptop stand providing two height angles (15° and 25°) constructed from vegan leather and fiberglass.',
    brand: 'MOFT',
    categorySlug: 'office-computer-accessories',
    subcategorySlug: 'laptop-stands-risers',
    modelNumber: 'MOFT-LS-SLM',
    mrp: 2499,
    currentPrice: 1999,
    originalPrice: 2499,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.6,
    reviewCount: 380,
    tags: ['moft', 'moft stand', 'adhesive laptop stand', 'slim laptop stand', 'portable stand'],
    specifications: { Thickness: '3mm (0.11 inch)', Weight: '85 grams', Angles: 'Dual 15 Deg & 25 Deg Adjustments', MaxWeight: '8 kg (18 lbs)' },
    images: [
      { url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'MOFT Invisible Laptop Stand Folded Flat on Laptop Base' },
      { url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'MOFT Origami Folded Triangle Elevation 25 Deg' },
      { url: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'MOFT Removable Reusable Adhesive Strip' },
      { url: 'https://images.unsplash.com/photo-1586105251261-72a756497a11?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'MOFT Vegan Leather Texture Surface' },
    ],
    variants: [
      { sku: 'PROD-OFC-014-GRY', name: 'Space Grey Vegan Leather', price: 1999, mrp: 2499, stockQuantity: 20, attributes: { Color: 'Space Grey' } },
      { sku: 'PROD-OFC-014-SLV', name: 'Silver Vegan Leather', price: 1999, mrp: 2499, stockQuantity: 20, attributes: { Color: 'Silver' } },
    ]
  },
  {
    sku: 'PROD-OFC-015',
    name: 'Twelve South BookArc Vertical Aluminum Stand for MacBook',
    slug: 'twelve-south-bookarc-vertical-macbook-stand',
    description: 'Sleek vertical desktop space-saving arch stand for MacBooks operating in clamshell mode with external monitor and keyboard setup.',
    brand: 'Twelve South',
    categorySlug: 'office-computer-accessories',
    subcategorySlug: 'laptop-stands-risers',
    modelNumber: '12-2005',
    mrp: 5999,
    currentPrice: 4799,
    originalPrice: 5999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 20,
    lowStockThreshold: 4,
    rating: 4.8,
    reviewCount: 220,
    tags: ['twelve south', 'bookarc', 'vertical macbook stand', 'clamshell stand', 'macbook accessory'],
    specifications: { Material: 'Sandblasted Anodized Aluminum', Inserts: 'Includes 3 Interchangeable Silicone Inserts', CableCatch: 'Integrated Cable Catch Slots' },
    images: [
      { url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Twelve South BookArc Silver Stand Holding MacBook Vertically' },
      { url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Twelve South Silicone Insert Cushioning MacBook' },
      { url: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Twelve South Integrated Cable Loop Underside' },
      { url: 'https://images.unsplash.com/photo-1586105251261-72a756497a11?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Twelve South Sandblasted Aluminum Arch Profile' },
    ],
    variants: [
      { sku: 'PROD-OFC-015-SLV', name: 'Silver Aluminum', price: 4799, mrp: 5999, stockQuantity: 12, attributes: { Color: 'Silver' } },
      { sku: 'PROD-OFC-015-SPG', name: 'Space Grey Aluminum', price: 4799, mrp: 5999, stockQuantity: 8, attributes: { Color: 'Space Grey' } },
    ]
  }
];
