import { ProductStatus } from '@prisma/client';

export const petSuppliesProducts = [
  {
    sku: 'PROD-PET-001',
    name: 'Bedsure Orthopedic Memory Foam Large Dog Bed',
    slug: 'bedsure-orthopedic-memory-foam-dog-bed',
    description: 'High-density egg crate orthopedic memory foam dog bed with removable washable micro-suede cover, water-resistant liner, and non-skid bottom.',
    brand: 'Bedsure',
    categorySlug: 'pet-supplies',
    subcategorySlug: 'pet-beds-furniture',
    modelNumber: 'BS-DGB-L',
    mrp: 4999,
    currentPrice: 3999,
    originalPrice: 4999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 6,
    rating: 4.8,
    reviewCount: 520,
    tags: ['bedsure', 'dog bed', 'orthopedic dog bed', 'memory foam dog bed', 'pet bed', 'non-food'],
    specifications: { Dimensions: '89cm x 63cm x 7.5cm (Large)', Foam: 'Egg Crate High-Density Orthopedic Foam', Cover: 'Micro-Suede Removable Zippered', Base: 'Non-Slip Rubber Dots' },
    images: [
      { url: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Bedsure Orthopedic Grey Dog Bed Cushion' },
      { url: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Bedsure Micro-Suede Plush Cover Zipper Detail' },
      { url: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Bedsure Egg Crate Foam Density Layer' },
      { url: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Bedsure Non-Slip Bottom Rubber Tread' },
    ],
    variants: [
      { sku: 'PROD-PET-001-L', name: 'Large (89x63cm) / Slate Grey', price: 3999, mrp: 4999, stockQuantity: 20, attributes: { Size: 'Large' } },
      { sku: 'PROD-PET-001-XL', name: 'XL (112x81cm) / Slate Grey', price: 4999, mrp: 5999, stockQuantity: 10, attributes: { Size: 'XL' } },
    ]
  },
  {
    sku: 'PROD-PET-002',
    name: 'PETKIT Pura X Automated Self-Cleaning Cat Litter Box',
    slug: 'petkit-pura-x-self-cleaning-litter-box',
    description: 'Smart automatic self-cleaning cat litter box with xSecure 12 safety sensors, auto-deodorization spray, real-time app tracking for cat weight and usage.',
    brand: 'PETKIT',
    categorySlug: 'pet-supplies',
    subcategorySlug: 'pet-beds-furniture',
    modelNumber: 'PET-PURA-X',
    mrp: 49990,
    currentPrice: 42491,
    originalPrice: 49990,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 10,
    lowStockThreshold: 2,
    rating: 4.9,
    reviewCount: 180,
    tags: ['petkit', 'pura x', 'self cleaning litter box', 'automatic cat litter box', 'smart pet furniture'],
    specifications: { Capacity: '60L Inner Cylinder', Safety: '12 Thermal & Infrared Sensors', Deodorizer: 'Purifying Liquid Spray Module', App: 'PETKIT App WiFi' },
    images: [
      { url: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'PETKIT Pura X Automatic Cat Litter Box Unit' },
      { url: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'PETKIT OLED Display Screen & Control Buttons' },
      { url: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'PETKIT Inner Sifting Drum & Waste Bin Drawer' },
      { url: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'PETKIT Smart Spray Liquid Refill Slot' },
    ],
    variants: [
      { sku: 'PROD-PET-002-WHT', name: 'White & Grey Smart Litter Box', price: 42491, mrp: 49990, stockQuantity: 10, attributes: { Color: 'White' } }
    ]
  },
  {
    sku: 'PROD-PET-003',
    name: 'FURminator Undercoat DeShedding Tool for Dogs',
    slug: 'furminator-undercoat-deshedding-tool-dogs',
    description: 'Stainless steel deShedding edge reaches through topcoat to safely and easily remove loose undercoat hair without damaging topcoat or cutting skin.',
    brand: 'FURminator',
    categorySlug: 'pet-supplies',
    subcategorySlug: 'grooming-toys',
    modelNumber: 'FUR-L-DL',
    mrp: 2999,
    currentPrice: 2399,
    originalPrice: 2999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 35,
    lowStockThreshold: 7,
    rating: 4.8,
    reviewCount: 680,
    tags: ['furminator', 'deshedding tool', 'dog brush', 'grooming brush', 'undercoat tool'],
    specifications: { Blade: 'Stainless Steel Undercoat Edge', Ejector: 'FURejector Button for Easy Hair Release', Handle: 'Ergonomic Rubber Grip', Size: 'Large Long Hair' },
    images: [
      { url: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'FURminator Undercoat Tool Orange Handle Front' },
      { url: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'FURminator Stainless Steel Teeth Edge Closeup' },
      { url: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'FURminator FURejector Hair Ejection Button' },
      { url: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'FURminator Ergonomic Rubberized Grip Handle' },
    ],
    variants: [
      { sku: 'PROD-PET-003-L-LNG', name: 'Large Dog / Long Hair', price: 2399, mrp: 2999, stockQuantity: 20, attributes: { Size: 'Large Long Hair' } },
      { sku: 'PROD-PET-003-M-SHT', name: 'Medium Dog / Short Hair', price: 2199, mrp: 2799, stockQuantity: 15, attributes: { Size: 'Medium Short Hair' } },
    ]
  },
  {
    sku: 'PROD-PET-004',
    name: 'KONG Classic Durable Natural Rubber Dog Toy',
    slug: 'kong-classic-durable-rubber-dog-toy',
    description: 'World-famous ultra-durable red natural rubber chew toy featuring unpredictable bounce and hollow center designed for mental stimulation and fetching.',
    brand: 'KONG',
    categorySlug: 'pet-supplies',
    subcategorySlug: 'grooming-toys',
    modelNumber: 'KONG-RED-L',
    mrp: 1299,
    currentPrice: 1039,
    originalPrice: 1299,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 50,
    lowStockThreshold: 10,
    rating: 4.9,
    reviewCount: 920,
    tags: ['kong', 'kong classic', 'dog chew toy', 'rubber dog toy', 'fetch toy', 'non-food'],
    specifications: { Material: '100% Natural Durable Red Rubber', Size: 'Large (for dogs 13-30 kg)', Feature: 'Erratic Bounce & Dishwasher Safe', Origin: 'Made in USA' },
    images: [
      { url: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'KONG Classic Red Rubber Toy Profile' },
      { url: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'KONG Hollow Interior Chamber Opening' },
      { url: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'KONG Embossed Logo & Rubber Ridge Texture' },
      { url: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'KONG Retail Header Card Packaging' },
    ],
    variants: [
      { sku: 'PROD-PET-004-L', name: 'Large Red Rubber', price: 1039, mrp: 1299, stockQuantity: 30, attributes: { Size: 'Large' } },
      { sku: 'PROD-PET-004-XL', name: 'XL Extreme Black Rubber', price: 1399, mrp: 1699, stockQuantity: 20, attributes: { Size: 'XL Extreme' } },
    ]
  },
  {
    sku: 'PROD-PET-005',
    name: 'Ruffwear Front Range No-Pull Dog Harness',
    slug: 'ruffwear-front-range-no-pull-dog-harness',
    description: 'Padded everyday dog harness with two leash attachment points (aluminum V-ring on back and reinforced webbing loop on chest to stop pulling).',
    brand: 'Ruffwear',
    categorySlug: 'pet-supplies',
    subcategorySlug: 'collars-leashes-harnesses',
    modelNumber: 'RF-FR-HAR-M',
    mrp: 4999,
    currentPrice: 4249,
    originalPrice: 4999,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 25,
    lowStockThreshold: 5,
    rating: 4.9,
    reviewCount: 410,
    tags: ['ruffwear', 'front range', 'dog harness', 'no pull harness', 'padded harness'],
    specifications: { Attachments: 'Anodized Aluminum V-Ring + Front Chest Webbing', Adjustment: '4 Points of Adjustment', Trim: '3M Reflective Trim', GirthSize: 'Medium (69-81cm / 27-32 in)' },
    images: [
      { url: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Ruffwear Front Range Blue Harness Top View' },
      { url: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Ruffwear Aluminum Back V-Ring Attachment' },
      { url: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Ruffwear Padded Chest Panel & Reflective Piping' },
      { url: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Ruffwear Side Release Buckles Close' },
    ],
    variants: [
      { sku: 'PROD-PET-005-M-BLU', name: 'Medium / Blue Moon', price: 4249, mrp: 4999, stockQuantity: 15, attributes: { Size: 'Medium', Color: 'Blue Moon' } },
      { sku: 'PROD-PET-005-L-ORG', name: 'Large / Campfire Orange', price: 4249, mrp: 4999, stockQuantity: 10, attributes: { Size: 'Large', Color: 'Campfire Orange' } },
    ]
  },
  {
    sku: 'PROD-PET-006',
    name: 'Flexi New Comfort Retractable Dog Tape Leash 5m',
    slug: 'flexi-new-comfort-retractable-tape-leash-5m',
    description: 'German engineered 5-meter heavy duty retractable tape leash with short-stroke single-hand braking system and soft grip handle.',
    brand: 'Flexi',
    categorySlug: 'pet-supplies',
    subcategorySlug: 'collars-leashes-harnesses',
    modelNumber: 'FLX-NC-5M-L',
    mrp: 3499,
    currentPrice: 2799,
    originalPrice: 3499,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 6,
    rating: 4.8,
    reviewCount: 480,
    tags: ['flexi', 'retractable leash', 'dog leash', '5m tape leash', 'german flexi'],
    specifications: { Length: '5 Meters (16 feet)', TapeType: 'High-Durability Nylon Tape', DogWeight: 'Up to 50 kg (Large)', Brake: 'One-Hand Short-Stroke Brake' },
    images: [
      { url: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Flexi New Comfort Black Retractable Leash Profile' },
      { url: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Flexi One-Hand Thumb Lock Brake Button' },
      { url: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Flexi Chrome Plated Swivel Snap Hook' },
      { url: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Flexi Soft Adjustable Grip Handle' },
    ],
    variants: [
      { sku: 'PROD-PET-006-L-BLK', name: 'Large 5m Tape / Black', price: 2799, mrp: 3499, stockQuantity: 20, attributes: { Size: 'Large 5m' } },
      { sku: 'PROD-PET-006-M-RED', name: 'Medium 5m Tape / Red', price: 2399, mrp: 2999, stockQuantity: 10, attributes: { Size: 'Medium 5m' } },
    ]
  },
  {
    sku: 'PROD-PET-007',
    name: 'Petmate Two-Door Top-Load Pet Kennel Carrier',
    slug: 'petmate-two-door-top-load-kennel-carrier',
    description: 'Durable travel pet carrier with steel wire top and front doors for easy loading, steel wingnut fasteners, and 360-degree ventilation.',
    brand: 'Petmate',
    categorySlug: 'pet-supplies',
    subcategorySlug: 'pet-beds-furniture',
    modelNumber: '21085',
    mrp: 6999,
    currentPrice: 5599,
    originalPrice: 6999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 15,
    lowStockThreshold: 3,
    rating: 4.7,
    reviewCount: 290,
    tags: ['petmate', 'pet carrier', 'dog kennel', 'cat carrier', 'travel kennel'],
    specifications: { Dimensions: '61cm L x 42cm W x 37cm H (24 Inch)', Doors: 'Dual Top & Front Steel Wire Doors', Latch: 'Squeeze Latch Mechanism', Airline: 'Meets Air Travel Guidelines' },
    images: [
      { url: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Petmate Two Door Carrier Kennel Front' },
      { url: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Petmate Steel Wire Top Door Opened' },
      { url: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Petmate Heavy Duty Carrying Handle Top' },
      { url: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Petmate Side Ventilation Grille Holes' },
    ],
    variants: [
      { sku: 'PROD-PET-007-24', name: '24-Inch / Honey Brown', price: 5599, mrp: 6999, stockQuantity: 10, attributes: { Size: '24 Inch' } },
      { sku: 'PROD-PET-007-19', name: '19-Inch / Metallic White', price: 4499, mrp: 5499, stockQuantity: 5, attributes: { Size: '19 Inch' } },
    ]
  },
  {
    sku: 'PROD-PET-008',
    name: 'WaterRower Cat Scratching Post Tree Tower 90cm',
    slug: 'cat-scratching-post-tree-tower-90cm',
    description: 'Multi-level cat scratching tree wrapped in natural durable sisal rope with plush perch bed, dangling plush ball, and sturdy anti-tipping base.',
    brand: 'MeowTown',
    categorySlug: 'pet-supplies',
    subcategorySlug: 'pet-beds-furniture',
    modelNumber: 'MT-CAT-TREE',
    mrp: 3999,
    currentPrice: 2999,
    originalPrice: 3999,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 20,
    lowStockThreshold: 4,
    rating: 4.6,
    reviewCount: 340,
    tags: ['cat tree', 'cat scratching post', 'sisal rope post', 'cat furniture', 'cat condo'],
    specifications: { Height: '90 cm (35 inches)', PostMaterial: '100% Natural Jute Sisal Fiber', Fabric: 'Soft Faux Fur Fabric', Base: 'Reinforced 40x40cm Baseboard' },
    images: [
      { url: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Cat Scratching Post Tree Tower Beige Front' },
      { url: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Natural Sisal Rope Wrapped Pillar Closeup' },
      { url: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Top Plush Perch Bed Cushion Rim' },
      { url: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Dangling Toy Ball Elastic Cord' },
    ],
    variants: [
      { sku: 'PROD-PET-008-BEI', name: 'Warm Cream Beige', price: 2999, mrp: 3999, stockQuantity: 12, attributes: { Color: 'Cream Beige' } },
      { sku: 'PROD-PET-008-GRY', name: 'Dark Smoke Grey', price: 2999, mrp: 3999, stockQuantity: 8, attributes: { Color: 'Smoke Grey' } },
    ]
  },
  {
    sku: 'PROD-PET-009',
    name: 'PetSafe Drinkwell Multi-Tier Stainless Steel Pet Fountain 3.8L',
    slug: 'petsafe-drinkwell-stainless-steel-pet-fountain',
    description: 'Circulating 3.8-liter stainless steel water fountain with free-falling stream, dual filtration (carbon filter + foam filter) for continuous fresh water.',
    brand: 'PetSafe',
    categorySlug: 'pet-supplies',
    subcategorySlug: 'pet-beds-furniture',
    modelNumber: 'PWW00-16468',
    mrp: 8990,
    currentPrice: 7192,
    originalPrice: 8990,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 15,
    lowStockThreshold: 3,
    rating: 4.8,
    reviewCount: 220,
    tags: ['petsafe', 'drinkwell', 'pet water fountain', 'stainless steel water bowl', 'dog fountain'],
    specifications: { Capacity: '3.8 Liters (128 oz)', Material: 'Hygienic Dishwasher Safe Stainless Steel', Filter: 'Activated Carbon + Foam Pump Filter', Pump: 'Submersible Low Voltage Pump' },
    images: [
      { url: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'PetSafe Drinkwell Stainless Fountain Overview' },
      { url: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'PetSafe Free Falling Water Stream Spout' },
      { url: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'PetSafe Submersible Low Noise Motor Unit' },
      { url: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'PetSafe Carbon Filter Replacement Pad' },
    ],
    variants: [
      { sku: 'PROD-PET-009-38L', name: '3.8 Liter Stainless Steel', price: 7192, mrp: 8990, stockQuantity: 15, attributes: { Capacity: '3.8 Liters' } }
    ]
  },
  {
    sku: 'PROD-PET-010',
    name: 'Loving Pets Stainless Steel No-Tip Rubber Base Dog Bowl 900ml',
    slug: 'loving-pets-stainless-steel-no-tip-dog-bowl',
    description: 'Heavy gauge polished stainless steel pet dish with wide tip-proof rubber base ring preventing spills and sliding during feeding time.',
    brand: 'Loving Pets',
    categorySlug: 'pet-supplies',
    subcategorySlug: 'pet-beds-furniture',
    modelNumber: 'LP-NTB-900',
    mrp: 999,
    currentPrice: 699,
    originalPrice: 999,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 50,
    lowStockThreshold: 10,
    rating: 4.7,
    reviewCount: 610,
    tags: ['loving pets', 'dog bowl', 'stainless steel bowl', 'no tip bowl', 'rubber base bowl', 'non-food'],
    specifications: { Capacity: '900 ml (approx 4 Cups)', Material: 'Bacteria-Resistant Stainless Steel', Base: 'Permanently Attached Non-Skid Rubber Ring', Care: 'Dishwasher Safe (Remove Rubber Ring)' },
    images: [
      { url: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Loving Pets Stainless Steel Dog Bowl Top View' },
      { url: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Loving Pets Wide Flare Rubber Base Ring' },
      { url: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Loving Pets Polished Mirror Interior Finish' },
      { url: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Loving Pets Staked Bowls Pair' },
    ],
    variants: [
      { sku: 'PROD-PET-010-900', name: '900ml Medium Bowl', price: 699, mrp: 999, stockQuantity: 30, attributes: { Capacity: '900ml' } },
      { sku: 'PROD-PET-010-1500', name: '1500ml Large Bowl', price: 899, mrp: 1299, stockQuantity: 20, attributes: { Capacity: '1500ml' } },
    ]
  },
  {
    sku: 'PROD-PET-011',
    name: 'Andis AGC2 2-Speed Professional Animal Clipper',
    slug: 'andis-agc2-2-speed-professional-pet-clipper',
    description: 'Professional 2-speed rotary motor pet grooming clipper running cool without fans, featuring UltraEdge size 10 detachable carbon steel blade.',
    brand: 'Andis',
    categorySlug: 'pet-supplies',
    subcategorySlug: 'grooming-toys',
    modelNumber: '22360',
    mrp: 14990,
    currentPrice: 12741,
    originalPrice: 14990,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 12,
    lowStockThreshold: 2,
    rating: 4.9,
    reviewCount: 190,
    tags: ['andis', 'pet clipper', 'dog grooming clipper', 'professional trimmer', 'agc2'],
    specifications: { Motor: '2-Speed Rotary (3,400 / 4,400 SPM)', Blade: 'UltraEdge Detachable Size 10 Blade', Housing: 'Shatterproof Sealed Housing', Cord: '4.2m Heavy Duty Cord' },
    images: [
      { url: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Andis AGC2 Black Pet Clipper Body' },
      { url: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Andis UltraEdge Carbon Steel Size 10 Blade' },
      { url: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Andis 2-Speed Power Toggle Switch' },
      { url: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Andis Clipper Oil & Replacement Drive Cap' },
    ],
    variants: [
      { sku: 'PROD-PET-011-BLK', name: 'Black 2-Speed Pro Kit', price: 12741, mrp: 14990, stockQuantity: 12, attributes: { Color: 'Black' } }
    ]
  },
  {
    sku: 'PROD-PET-012',
    name: 'Chuckit! Ultra Ball Rubber Fetch Toy 2-Pack',
    slug: 'chuckit-ultra-ball-rubber-fetch-toy-2pack',
    description: 'High-bounce durable natural rubber fetch balls with extra-thick rubber core, high-visibility orange and blue colors, and water flotation capability.',
    brand: 'Chuckit!',
    categorySlug: 'pet-supplies',
    subcategorySlug: 'grooming-toys',
    modelNumber: 'CH-UB-M2',
    mrp: 1499,
    currentPrice: 1199,
    originalPrice: 1499,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.9,
    reviewCount: 820,
    tags: ['chuckit', 'ultra ball', 'dog fetch ball', 'rubber dog ball', 'floating dog toy', 'non-food'],
    specifications: { Size: 'Medium (6.5cm diameter)', Pack: '2 Balls', Feature: 'Floats on Water + Launcher Compatible', Material: 'Natural Rubber Core' },
    images: [
      { url: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Chuckit! Ultra Ball Orange Blue Pair' },
      { url: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Chuckit High Bounce Thick Rubber Wall' },
      { url: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Chuckit Embossed Textured Grooves' },
      { url: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Chuckit Retail Card Package' },
    ],
    variants: [
      { sku: 'PROD-PET-012-M2', name: 'Medium (Pack of 2)', price: 1199, mrp: 1499, stockQuantity: 40, attributes: { Pack: '2 Balls' } }
    ]
  },
  {
    sku: 'PROD-PET-013',
    name: 'Outward Hound Fun Feeder Slo Bowl Slow Feeder (Non-Food Dish)',
    slug: 'outward-hound-fun-feeder-slow-bowl',
    description: 'Veterinarian recommended slow feeder dog bowl featuring maze ridges that slow down eating time up to 10x to improve digestion and prevent bloat.',
    brand: 'Outward Hound',
    categorySlug: 'pet-supplies',
    subcategorySlug: 'pet-beds-furniture',
    modelNumber: 'OH-51001',
    mrp: 1499,
    currentPrice: 1124,
    originalPrice: 1499,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 35,
    lowStockThreshold: 7,
    rating: 4.8,
    reviewCount: 710,
    tags: ['outward hound', 'slow feeder bowl', 'maze bowl', 'dog dish', 'bloat stop bowl', 'non-food'],
    specifications: { Material: 'BPA, PVC & Phthalate Free Food-Grade ABS', Size: 'Large (Holds up to 4 cups)', Base: 'Non-Slip Rubber Base', Care: 'Top Rack Dishwasher Safe' },
    images: [
      { url: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Outward Hound Teal Spiral Slow Feeder Bowl Top' },
      { url: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Outward Hound Deep Maze Ridge Channels' },
      { url: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Outward Hound Rubber Feet Non Slip Base' },
      { url: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Outward Hound Dishwasher Safe Icon' },
    ],
    variants: [
      { sku: 'PROD-PET-013-TEL', name: 'Teal Spiral (Large)', price: 1124, mrp: 1499, stockQuantity: 20, attributes: { Color: 'Teal Spiral' } },
      { sku: 'PROD-PET-013-PUR', name: 'Purple Flower (Large)', price: 1124, mrp: 1499, stockQuantity: 15, attributes: { Color: 'Purple Flower' } },
    ]
  },
  {
    sku: 'PROD-PET-014',
    name: 'Nylabone Power Chew Textured Durable Ring Dog Toy',
    slug: 'nylabone-power-chew-textured-ring-toy',
    description: 'Ultra-tough nylon chew toy ring built for extreme chewers with raised nubs that help clean teeth and control plaque and tartar during chew sessions.',
    brand: 'Nylabone',
    categorySlug: 'pet-supplies',
    subcategorySlug: 'grooming-toys',
    modelNumber: 'NYL-PWR-RNG',
    mrp: 1299,
    currentPrice: 974,
    originalPrice: 1299,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.7,
    reviewCount: 490,
    tags: ['nylabone', 'power chew', 'dog chew ring', 'nylon dog toy', 'dental chew toy', 'non-food'],
    specifications: { Material: 'Heavy Duty Tough Nylon', Size: 'Souper (for dogs 23kg+)', Dental: 'Raised Massage Dental Nubs', Origin: 'Made in USA' },
    images: [
      { url: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Nylabone Power Chew White Textured Ring' },
      { url: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Nylabone Raised Dental Nubs Surface' },
      { url: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Nylabone Tough Nylon Material Density' },
      { url: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Nylabone Header Card Package' },
    ],
    variants: [
      { sku: 'PROD-PET-014-SUP', name: 'Souper Size Ring', price: 974, mrp: 1299, stockQuantity: 40, attributes: { Size: 'Souper' } }
    ]
  },
  {
    sku: 'PROD-PET-015',
    name: 'Bergan Stainless Steel Double Elevated Dog Diner Feeder',
    slug: 'bergan-elevated-stainless-steel-double-diner',
    description: 'Elevated pet diner featuring sturdy black powder-coated steel frame and two removable stainless steel food and water bowls for comfortable posture.',
    brand: 'Bergan',
    categorySlug: 'pet-supplies',
    subcategorySlug: 'pet-beds-furniture',
    modelNumber: 'BER-ELD-L',
    mrp: 3499,
    currentPrice: 2624,
    originalPrice: 3499,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 20,
    lowStockThreshold: 4,
    rating: 4.8,
    reviewCount: 310,
    tags: ['bergan', 'elevated diner', 'raised dog bowls', 'double diner', 'stainless steel bowls', 'non-food'],
    specifications: { Height: '30 cm Elevated Frame', Bowls: '2 x 1800ml Stainless Steel Bowls', Frame: 'Wrought Iron Powder-Coated Metal', RubberFeet: 'Non-Marring Rubber Feet' },
    images: [
      { url: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Bergan Double Elevated Steel Diner Frame & Bowls' },
      { url: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Bergan Removable Stainless Steel Bowl Inset' },
      { url: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Bergan Wrought Iron Scroll Leg Base' },
      { url: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Bergan Rubber Feet Caps Base' },
    ],
    variants: [
      { sku: 'PROD-PET-015-L', name: 'Large 30cm Height (2x 1800ml)', price: 2624, mrp: 3499, stockQuantity: 20, attributes: { Size: 'Large Elevated' } }
    ]
  }
];
