import { ProductStatus } from '@prisma/client';

export const sportsFitnessProducts = [
  {
    sku: 'PROD-SPF-001',
    name: 'Yonex Astrox 99 Pro Badminton Racket 4U G5',
    slug: 'yonex-astrox-99-pro-badminton-racket',
    description: 'Professional head-heavy badminton racket engineered with Namd graphite technology, Energy Boost Cap Plus, and Volume Cut Resin for steep crushing smashes.',
    brand: 'Yonex',
    categorySlug: 'sports-fitness',
    subcategorySlug: 'racquet-outdoor-sports',
    modelNumber: 'AX99-P-4UG5',
    mrp: 19990,
    currentPrice: 15992,
    originalPrice: 19990,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 20,
    lowStockThreshold: 4,
    rating: 4.9,
    reviewCount: 380,
    tags: ['yonex', 'astrox 99 pro', 'badminton racket', 'professional racket', 'japan made'],
    specifications: { Flex: 'Stiff', Frame: 'HM Graphite + Namd', WeightSize: '4U (Ave 83g) G5', MadeIn: 'Japan' },
    images: [
      { url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Yonex Astrox 99 Pro Cherry Sunburst Frame' },
      { url: 'https://images.unsplash.com/photo-1526676037777-05a232554f77?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Yonex Isometric Head & Grommet Strip' },
      { url: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Yonex Energy Boost Cap & Shaft Branding' },
      { url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Yonex Full Length Thermal Racket Cover' },
    ],
    variants: [
      { sku: 'PROD-SPF-001-4U5', name: '4U G5 / Cherry Sunburst', price: 15992, mrp: 19990, stockQuantity: 12, attributes: { WeightGrip: '4U G5' } },
      { sku: 'PROD-SPF-001-3U4', name: '3U G4 / White Tiger', price: 16990, mrp: 20990, stockQuantity: 8, attributes: { WeightGrip: '3U G4' } },
    ]
  },
  {
    sku: 'PROD-SPF-002',
    name: 'Bowflex SelectTech 552 Adjustable Dumbbell Pair',
    slug: 'bowflex-selecttech-552-adjustable-dumbbells',
    description: 'Space-saving adjustable dumbbell set replacing 15 pairs of weights. Easily adjusts from 2kg to 24kg (5 to 52.5 lbs) with turn of a dial.',
    brand: 'Bowflex',
    categorySlug: 'sports-fitness',
    subcategorySlug: 'fitness-dumbbells',
    modelNumber: 'ST-552-PAIR',
    mrp: 49999,
    currentPrice: 42499,
    originalPrice: 49999,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 10,
    lowStockThreshold: 2,
    rating: 4.9,
    reviewCount: 420,
    tags: ['bowflex', 'selecttech 552', 'adjustable dumbbells', 'home gym', 'strength training'],
    specifications: { WeightRange: '2 to 24 kg per dumbbell', Settings: '15 Weight Increments', PlateCoating: 'Durable Molded Metal', Trays: 'Includes Heavy Duty Trays' },
    images: [
      { url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Bowflex SelectTech 552 Dumbbell Pair on Storage Trays' },
      { url: 'https://images.unsplash.com/photo-1526676037777-05a232554f77?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Bowflex Weight Selector Dial Mechanism' },
      { url: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Bowflex Ergonomic Rubber Grip Handle' },
      { url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Bowflex Molded Steel Weight Plates Alignment' },
    ],
    variants: [
      { sku: 'PROD-SPF-002-PAIR', name: 'Pair (2 Dumbbells with Trays)', price: 42499, mrp: 49999, stockQuantity: 10, attributes: { Pack: 'Pair' } }
    ]
  },
  {
    sku: 'PROD-SPF-003',
    name: 'Lululemon Reversible Yoga Mat 5mm Non-Slip Premium',
    slug: 'lululemon-reversible-yoga-mat-5mm',
    description: 'Dual-texture 5mm thick yoga mat featuring smooth polyurethane top layer for grip during sweaty practices and cushioned natural rubber base for joint support.',
    brand: 'Lululemon',
    categorySlug: 'sports-fitness',
    subcategorySlug: 'yoga-mats',
    modelNumber: 'LU-YOG-5MM',
    mrp: 7800,
    currentPrice: 6630,
    originalPrice: 7800,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 25,
    lowStockThreshold: 5,
    rating: 4.9,
    reviewCount: 310,
    tags: ['lululemon', 'yoga mat', '5mm mat', 'non slip yoga mat', 'natural rubber mat'],
    specifications: { Thickness: '5 mm', Dimensions: '66cm x 180cm', Weight: '2.38 kg', Material: 'Polyurethane + Sustainably Sourced Natural Rubber' },
    images: [
      { url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Lululemon 5mm Reversible Yoga Mat Unrolled' },
      { url: 'https://images.unsplash.com/photo-1526676037777-05a232554f77?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Lululemon Matte Polyurethane Grippy Surface Close' },
      { url: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Lululemon Embossed Logo Detail' },
      { url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Lululemon Rolled Mat with Carrying Strap' },
    ],
    variants: [
      { sku: 'PROD-SPF-003-BLK', name: 'Black & White Marble', price: 6630, mrp: 7800, stockQuantity: 15, attributes: { Color: 'Black Marble' } },
      { sku: 'PROD-SPF-003-GRN', name: 'Sage Green', price: 6630, mrp: 7800, stockQuantity: 10, attributes: { Color: 'Sage Green' } },
    ]
  },
  {
    sku: 'PROD-SPF-004',
    name: 'Wilson Pro Staff 97 v14 Tennis Racket',
    slug: 'wilson-pro-staff-97-v14-tennis-racket',
    description: 'Legendary precision tennis racket featuring Braid 45 construction for enhanced feel, Paradigm Bending technology, and rich copper/bronze iridescent finish.',
    brand: 'Wilson',
    categorySlug: 'sports-fitness',
    subcategorySlug: 'racquet-outdoor-sports',
    modelNumber: 'WR125711U',
    mrp: 24999,
    currentPrice: 21249,
    originalPrice: 24999,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 12,
    lowStockThreshold: 3,
    rating: 4.8,
    reviewCount: 190,
    tags: ['wilson', 'pro staff 97', 'tennis racket', 'federer racket', 'pro tennis'],
    specifications: { HeadSize: '97 sq in (626 sq cm)', WeightUnstrung: '315g', StringPattern: '16x19', Balance: '31 cm / 10 pts HL' },
    images: [
      { url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Wilson Pro Staff 97 v14 Metallic Bronze Frame' },
      { url: 'https://images.unsplash.com/photo-1526676037777-05a232554f77?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Wilson Braid 45 Carbon Fiber Texture' },
      { url: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Wilson Pro Staff Leather Grip Base' },
      { url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Wilson String Bed 16x19 Pattern' },
    ],
    variants: [
      { sku: 'PROD-SPF-004-G3', name: 'Grip Size 4 3/8 (G3)', price: 21249, mrp: 24999, stockQuantity: 7, attributes: { GripSize: '4 3/8 (G3)' } },
      { sku: 'PROD-SPF-004-G2', name: 'Grip Size 4 1/4 (G2)', price: 21249, mrp: 24999, stockQuantity: 5, attributes: { GripSize: '4 1/4 (G2)' } },
    ]
  },
  {
    sku: 'PROD-SPF-005',
    name: 'Decathlon Nyamba 500 Rubber Hex Dumbbells 10kg Pair',
    slug: 'decathlon-nyamba-hex-dumbbells-10kg-pair',
    description: 'Commercial hex dumbbells with durable non-marking rubber coating to prevent floor damage and knurled ergonomic chrome steel handles.',
    brand: 'Decathlon',
    categorySlug: 'sports-fitness',
    subcategorySlug: 'fitness-dumbbells',
    modelNumber: '8529552',
    mrp: 4999,
    currentPrice: 4249,
    originalPrice: 4999,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 6,
    rating: 4.7,
    reviewCount: 520,
    tags: ['decathlon', 'hex dumbbells', '10kg dumbbells', 'rubber dumbbells', 'gym weights'],
    specifications: { Weight: '10 kg per dumbbell', Shape: 'Anti-roll Hexagonal', Material: 'Solid Cast Iron with Natural Rubber Coating', Handle: 'Chrome Knurled' },
    images: [
      { url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Decathlon 10kg Hex Dumbbells Pair Rubber Heads' },
      { url: 'https://images.unsplash.com/photo-1526676037777-05a232554f77?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Decathlon Chrome Knurled Steel Handle Texture' },
      { url: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Decathlon Embossed 10KG Weight Number' },
      { url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Decathlon Hex Shape Anti-Roll Floor Placement' },
    ],
    variants: [
      { sku: 'PROD-SPF-005-10KG', name: '10kg Pair (Total 20kg)', price: 4249, mrp: 4999, stockQuantity: 30, attributes: { Weight: '10kg x 2' } }
    ]
  },
  {
    sku: 'PROD-SPF-006',
    name: 'Nike Premium 4mm Printed Fitness Yoga Mat',
    slug: 'nike-premium-4mm-printed-yoga-mat',
    description: 'Lightweight high-density TPE yoga mat featuring micro-textured non-slip surface traction for stability and integrated carry strap.',
    brand: 'Nike',
    categorySlug: 'sports-fitness',
    subcategorySlug: 'yoga-mats',
    modelNumber: 'N0002381',
    mrp: 3995,
    currentPrice: 3196,
    originalPrice: 3995,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 35,
    lowStockThreshold: 7,
    rating: 4.6,
    reviewCount: 240,
    tags: ['nike', 'yoga mat', 'nike mat', 'tpe yoga mat', 'fitness mat'],
    specifications: { Thickness: '4 mm', Material: '95% TPE / 5% Polyester', Dimensions: '61cm x 173cm', Features: 'Non-Toxic PVC Free' },
    images: [
      { url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Nike 4mm Printed Yoga Mat Black Swoosh' },
      { url: 'https://images.unsplash.com/photo-1526676037777-05a232554f77?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Nike Micro Textured Grip Pattern Close' },
      { url: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Nike Printed Swoosh Logo Graphic' },
      { url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Nike Carrying Harness Strap Attached' },
    ],
    variants: [
      { sku: 'PROD-SPF-006-BLK', name: 'Black / Anthracite', price: 3196, mrp: 3995, stockQuantity: 20, attributes: { Color: 'Black/Anthracite' } },
      { sku: 'PROD-SPF-006-BLU', name: 'Obsidian Blue', price: 3196, mrp: 3995, stockQuantity: 15, attributes: { Color: 'Obsidian Blue' } },
    ]
  },
  {
    sku: 'PROD-SPF-007',
    name: 'Cosco FIFA Approved Size 5 Match Football',
    slug: 'cosco-fifa-approved-size-5-football',
    description: 'Official match size 5 football featuring thermal bonded micro-texture PU synthetic leather, butyl bladder for air retention, and FIFA Quality Pro certification.',
    brand: 'Cosco',
    categorySlug: 'sports-fitness',
    subcategorySlug: 'racquet-outdoor-sports',
    modelNumber: 'COS-FB-M5',
    mrp: 2999,
    currentPrice: 2249,
    originalPrice: 2999,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.7,
    reviewCount: 390,
    tags: ['cosco', 'football', 'soccer ball', 'size 5 football', 'fifa approved'],
    specifications: { Size: 'Official Size 5', Construction: 'Seamless Thermally Bonded', Bladder: 'High Retention Butyl', Certification: 'FIFA Quality Pro' },
    images: [
      { url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Cosco Size 5 Match Football Tricolor Panels' },
      { url: 'https://images.unsplash.com/photo-1526676037777-05a232554f77?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Cosco Micro-Textured PU Surface Grip' },
      { url: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Cosco FIFA Quality Pro Stamp Logo' },
      { url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Cosco Air Valve Inflation Port' },
    ],
    variants: [
      { sku: 'PROD-SPF-007-SZ5', name: 'Official Size 5', price: 2249, mrp: 2999, stockQuantity: 40, attributes: { Size: 'Size 5' } }
    ]
  },
  {
    sku: 'PROD-SPF-008',
    name: 'Kore PVC 20kg Adjustable Home Gym Dumbbell Kit',
    slug: 'kore-pvc-20kg-home-gym-dumbbell-kit',
    description: 'Complete home workout weight plate set including 20kg PVC weights, 2 dumbbell rods with star nuts, and 1 connecting rod for barbell conversion.',
    brand: 'Kore',
    categorySlug: 'sports-fitness',
    subcategorySlug: 'fitness-dumbbells',
    modelNumber: 'KORE-20KG-SET',
    mrp: 3499,
    currentPrice: 1399,
    originalPrice: 3499,
    discount: 60.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 50,
    lowStockThreshold: 10,
    rating: 4.4,
    reviewCount: 1100,
    tags: ['kore', 'home gym', 'dumbbell set', '20kg dumbbell', 'barbell combo'],
    specifications: { TotalWeight: '20 kg', Plates: '2kg x 4 + 3kg x 4 PVC Plates', Rods: '2 x 14 in Dumbbell Rods + 1 x Barbell Connector', Collars: '4 Star Locks' },
    images: [
      { url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Kore 20kg Home Gym Dumbbell Kit Array' },
      { url: 'https://images.unsplash.com/photo-1526676037777-05a232554f77?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Kore PVC Weight Plates Black Finish' },
      { url: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Kore Barbell Extension Connecting Rod' },
      { url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Kore Star Lock Nut Threading' },
    ],
    variants: [
      { sku: 'PROD-SPF-008-20KG', name: '20kg Kit with Barbell Converter', price: 1399, mrp: 3499, stockQuantity: 50, attributes: { Pack: '20kg Complete Set' } }
    ]
  },
  {
    sku: 'PROD-SPF-009',
    name: 'Boldfit Heavy Duty Resistance Bands Set for Home Workout',
    slug: 'boldfit-heavy-duty-resistance-bands-set',
    description: 'Set of 5 stackable latex exercise resistance bands with door anchor, padded handles, ankle straps, and waterproof carrying pouch up to 150 lbs resistance.',
    brand: 'Boldfit',
    categorySlug: 'sports-fitness',
    subcategorySlug: 'fitness-dumbbells',
    modelNumber: 'BF-RST-5',
    mrp: 1999,
    currentPrice: 999,
    originalPrice: 1999,
    discount: 50.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 60,
    lowStockThreshold: 12,
    rating: 4.6,
    reviewCount: 850,
    tags: ['boldfit', 'resistance bands', 'workout bands', 'home gym bands', 'latex tube bands'],
    specifications: { ResistanceLevel: '10 lbs to 150 lbs Combined', Material: '100% Natural Malaysian Latex', Accessories: '2 Handles + 2 Ankle Straps + Door Anchor', Includes: 'Travel Pouch' },
    images: [
      { url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Boldfit 5 Color Coded Resistance Bands Array' },
      { url: 'https://images.unsplash.com/photo-1526676037777-05a232554f77?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Boldfit Heavy Metal Carabiner Clip Attachments' },
      { url: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Boldfit Foam Padded Grip Handles' },
      { url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Boldfit Door Anchor Foam Stopper' },
    ],
    variants: [
      { sku: 'PROD-SPF-009-SET', name: '150 lbs Resistance 11-Pcs Set', price: 999, mrp: 1999, stockQuantity: 60, attributes: { Pack: 'Set of 11 Pieces' } }
    ]
  },
  {
    sku: 'PROD-SPF-010',
    name: 'Nivia Heavy Duty Pro Skipping Rope with Ball Bearings',
    slug: 'nivia-heavy-duty-pro-skipping-rope',
    description: 'Speed jump rope featuring 360-degree smooth ball bearing steel swivel system, adjustable 3m PVC coated steel cable, and non-slip foam handles.',
    brand: 'Nivia',
    categorySlug: 'sports-fitness',
    subcategorySlug: 'fitness-dumbbells',
    modelNumber: 'NIV-SR-PRO',
    mrp: 599,
    currentPrice: 399,
    originalPrice: 599,
    discount: 33.4,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 70,
    lowStockThreshold: 15,
    rating: 4.7,
    reviewCount: 920,
    tags: ['nivia', 'skipping rope', 'speed rope', 'jump rope', 'cardio exercise'],
    specifications: { CableLength: '3.0 Meters Adjustable', CableMaterial: 'Steel Wire with PVC Sheath', Bearing: 'Dual 360 Deg Ball Bearings', Handles: 'Soft Memory Foam' },
    images: [
      { url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Nivia Speed Jump Rope Black Foam Handles' },
      { url: 'https://images.unsplash.com/photo-1526676037777-05a232554f77?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Nivia 360 Degree Ball Bearing Head Detail' },
      { url: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Nivia Cable Length Adjustment Screw Lock' },
      { url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Nivia Coiled Steel Cable Sheath' },
    ],
    variants: [
      { sku: 'PROD-SPF-010-BLK', name: 'Black Memory Foam', price: 399, mrp: 599, stockQuantity: 40, attributes: { Color: 'Black' } },
      { sku: 'PROD-SPF-010-RED', name: 'Red Memory Foam', price: 399, mrp: 599, stockQuantity: 30, attributes: { Color: 'Red' } },
    ]
  },
  {
    sku: 'PROD-SPF-011',
    name: 'Spalding NBA Zi/O Excel Indoor Outdoor Basketball Size 7',
    slug: 'spalding-nba-zio-excel-basketball-size-7',
    description: 'Official size 7 composite leather basketball with foam backing for soft tack feel, deep channels for shooting grip, and full ball pebbling.',
    brand: 'Spalding',
    categorySlug: 'sports-fitness',
    subcategorySlug: 'racquet-outdoor-sports',
    modelNumber: '74872Z',
    mrp: 4999,
    currentPrice: 3999,
    originalPrice: 4999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 25,
    lowStockThreshold: 5,
    rating: 4.8,
    reviewCount: 310,
    tags: ['spalding', 'basketball', 'nba basketball', 'size 7 basketball', 'composite leather'],
    specifications: { Size: 'Official Size 7 (29.5 inches)', Material: 'Zi/O Composite Leather', Usage: 'Indoor & Outdoor Courts', Inflation: '8 psi' },
    images: [
      { url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Spalding NBA Zi/O Excel Leather Basketball Front' },
      { url: 'https://images.unsplash.com/photo-1526676037777-05a232554f77?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Spalding Pebbled Composite Leather Texture' },
      { url: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Spalding Gold Foil NBA Logo Stamp' },
      { url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Spalding Black Channel Grooves Close' },
    ],
    variants: [
      { sku: 'PROD-SPF-011-SZ7', name: 'Official Size 7', price: 3999, mrp: 4999, stockQuantity: 25, attributes: { Size: 'Size 7' } }
    ]
  },
  {
    sku: 'PROD-SPF-012',
    name: 'Stiga Pro Carbon 7-Ply Table Tennis Racket',
    slug: 'stiga-pro-carbon-table-tennis-racket',
    description: 'Tournament performance ping pong paddle built with 7-ply ultra-light blade incorporating carbon technology, S5 ITTF approved rubber, and 2.0mm sponge.',
    brand: 'Stiga',
    categorySlug: 'sports-fitness',
    subcategorySlug: 'racquet-outdoor-sports',
    modelNumber: 'T1206',
    mrp: 12999,
    currentPrice: 9749,
    originalPrice: 12999,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 15,
    lowStockThreshold: 3,
    rating: 4.8,
    reviewCount: 260,
    tags: ['stiga', 'table tennis racket', 'ping pong paddle', 'carbon racket', 'ittf approved'],
    specifications: { Speed: '99', Spin: '100', Control: '80', Blade: '7-Ply Carbon & Balsa Wood', Rubber: 'Stiga S5 ITTF Approved' },
    images: [
      { url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Stiga Pro Carbon Table Tennis Paddle Red Rubber' },
      { url: 'https://images.unsplash.com/photo-1526676037777-05a232554f77?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Stiga Black Backside ITTF Approved Rubber Stamp' },
      { url: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Stiga Concave Handle Carbon Lens Emblem' },
      { url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Stiga 7-Ply Wood & Carbon Layer Edge' },
    ],
    variants: [
      { sku: 'PROD-SPF-012-PAD', name: 'Pro Carbon Paddle', price: 9749, mrp: 12999, stockQuantity: 15, attributes: { Type: 'Pro Carbon' } }
    ]
  },
  {
    sku: 'PROD-SPF-013',
    name: 'Manduka PRO Yoga Mat 6mm Lifetime Guarantee',
    slug: 'manduka-pro-yoga-mat-6mm',
    description: 'Ultra-dense 6mm thick professional yoga mat designed to last a lifetime. Closed-cell surface blocks moisture and sweat from seeping into mat core.',
    brand: 'Manduka',
    categorySlug: 'sports-fitness',
    subcategorySlug: 'yoga-mats',
    modelNumber: 'MAN-PRO-6MM',
    mrp: 14900,
    currentPrice: 12665,
    originalPrice: 14900,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 12,
    lowStockThreshold: 2,
    rating: 4.9,
    reviewCount: 180,
    tags: ['manduka', 'manduka pro', '6mm yoga mat', 'lifetime guarantee mat', 'dense mat'],
    specifications: { Thickness: '6.0 mm', Dimensions: '66cm x 180cm', Weight: '3.4 kg', Warranty: 'Lifetime Manufacturer Guarantee' },
    images: [
      { url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Manduka PRO 6mm Black Mat Unrolled' },
      { url: 'https://images.unsplash.com/photo-1526676037777-05a232554f77?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Manduka Frog Logo Metallic Button Detail' },
      { url: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Manduka Fabric-Like Slip Resistant Top Finish' },
      { url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Manduka Dot Pattern Cushion Base' },
    ],
    variants: [
      { sku: 'PROD-SPF-013-BLK', name: 'Black Sage', price: 12665, mrp: 14900, stockQuantity: 7, attributes: { Color: 'Black Sage' } },
      { sku: 'PROD-SPF-013-BLU', name: 'Indi Blue', price: 12665, mrp: 14900, stockQuantity: 5, attributes: { Color: 'Indi Blue' } },
    ]
  },
  {
    sku: 'PROD-SPF-014',
    name: 'SG English Willow Cricket Bat Full Size (Real Wood)',
    slug: 'sg-english-willow-cricket-bat',
    description: 'Handcrafted Grade 2 English Willow cricket bat with big sweet spot, thick edges, cane handle with rubber grip, and toe guard.',
    brand: 'SG',
    categorySlug: 'sports-fitness',
    subcategorySlug: 'racquet-outdoor-sports',
    modelNumber: 'SG-RP-EW',
    mrp: 18999,
    currentPrice: 15199,
    originalPrice: 18999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 15,
    lowStockThreshold: 3,
    rating: 4.8,
    reviewCount: 290,
    tags: ['sg', 'cricket bat', 'english willow', 'sg cricket', 'full size bat'],
    specifications: { Willow: 'Grade 2 English Willow', Weight: '1180 - 1220 grams', Grains: '6 to 9 Straight Grains', Handle: '9-Piece Singapore Cane' },
    images: [
      { url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'SG English Willow Cricket Bat Profile' },
      { url: 'https://images.unsplash.com/photo-1526676037777-05a232554f77?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'SG Straight Grain English Willow Face' },
      { url: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'SG Chevron Rubber Handle Grip' },
      { url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'SG Padded Full Pouch Carry Bag' },
    ],
    variants: [
      { sku: 'PROD-SPF-014-SH', name: 'Short Handle (1190g)', price: 15199, mrp: 18999, stockQuantity: 10, attributes: { Handle: 'Short Handle' } },
      { sku: 'PROD-SPF-014-LH', name: 'Long Handle (1220g)', price: 15999, mrp: 19999, stockQuantity: 5, attributes: { Handle: 'Long Handle' } },
    ]
  },
  {
    sku: 'PROD-SPF-015',
    name: 'Flexnest Flexbike Smart Bluetooth Stationary Exercise Bike',
    slug: 'flexnest-flexbike-smart-exercise-bike',
    description: 'Smart magnetic resistance exercise bike with Bluetooth sensor sync, iPad mount, virtual scenic rides in Flexnest App, and quiet magnetic flywheel.',
    brand: 'Flexnest',
    categorySlug: 'sports-fitness',
    subcategorySlug: 'fitness-dumbbells',
    modelNumber: 'FLX-BK-01',
    mrp: 39999,
    currentPrice: 29999,
    originalPrice: 39999,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 10,
    lowStockThreshold: 2,
    rating: 4.7,
    reviewCount: 210,
    tags: ['flexnest', 'flexbike', 'exercise bike', 'stationary bike', 'spin bike'],
    specifications: { Resistance: 'Stepless Silent Magnetic Resistance', Flywheel: '7.5 kg Heavy Steel Flywheel', App: 'Flexnest App Virtual Workouts', MaxUserWeight: '120 kg' },
    images: [
      { url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Flexnest Flexbike Smart Exercise Bike Matte Black' },
      { url: 'https://images.unsplash.com/photo-1526676037777-05a232554f77?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Flexnest Resistance Knob & Emergency Brake' },
      { url: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Flexnest Tablet Mount Holder Bracket' },
      { url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Flexnest Cushioned Seat Adjustment Column' },
    ],
    variants: [
      { sku: 'PROD-SPF-015-BLK', name: 'Matte Black', price: 29999, mrp: 39999, stockQuantity: 10, attributes: { Color: 'Matte Black' } }
    ]
  }
];
