import { ProductStatus } from '@prisma/client';

export const toysGamesProducts = [
  {
    sku: 'PROD-TOY-001',
    name: 'LEGO Technic Porsche 911 GT3 RS (1,580 Pieces)',
    slug: 'lego-technic-porsche-911-gt3-rs',
    description: 'Detailed LEGO Technic replica featuring aerodynamic bodywork, adjustable rear spoiler, working flat 6 engine with moving pistons, steering wheel, and paddle shifters.',
    brand: 'LEGO',
    categorySlug: 'toys-games',
    subcategorySlug: 'building-blocks-lego',
    modelNumber: '42056',
    mrp: 29999,
    currentPrice: 25499,
    originalPrice: 29999,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 12,
    lowStockThreshold: 2,
    rating: 4.9,
    reviewCount: 410,
    tags: ['lego', 'technic', 'porsche 911', 'lego supercar', 'building blocks'],
    specifications: { Pieces: '1,580 Pieces', AgeGroup: '18+ Years', Dimensions: '57cm L x 25cm W x 17cm H', Scale: '1:8 Scale' },
    images: [
      { url: 'https://images.unsplash.com/photo-1566576721346-d4a3b4eaeb55?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'LEGO Technic Porsche 911 GT3 RS Assembled Model' },
      { url: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'LEGO Technic Working Flat 6 Engine Pistons' },
      { url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'LEGO Technic Orange Aerodynamic Body Curved Panels' },
      { url: 'https://images.unsplash.com/photo-1560169897-fc0cdbdfa4d5?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'LEGO Technic Cockpit Dashboard & Paddle Gearbox' },
    ],
    variants: [
      { sku: 'PROD-TOY-001-ORG', name: 'Lava Orange 1:8 Scale', price: 25499, mrp: 29999, stockQuantity: 12, attributes: { Color: 'Lava Orange' } }
    ]
  },
  {
    sku: 'PROD-TOY-002',
    name: 'Catan Board Game 5th Edition Strategy Board Game',
    slug: 'catan-strategy-board-game-5th-edition',
    description: 'The award-winning game of island resource trading, settlement building, and tactical development for 3-4 players.',
    brand: 'Catan Studio',
    categorySlug: 'toys-games',
    subcategorySlug: 'board-games-puzzles',
    modelNumber: 'CN3071',
    mrp: 3999,
    currentPrice: 3399,
    originalPrice: 3999,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 6,
    rating: 4.9,
    reviewCount: 950,
    tags: ['catan', 'board game', 'settlers of catan', 'strategy game', 'family game'],
    specifications: { Players: '3 to 4 Players', Age: '10+ Years', PlayTime: '60 Minutes', Contents: '19 Hex Tiles + 95 Resource Cards + 60 Wooden Settlements' },
    images: [
      { url: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Catan Hexagonal Island Board Layout Set Up' },
      { url: 'https://images.unsplash.com/photo-1566576721346-d4a3b4eaeb55?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Catan Wooden Settlements Roads & Dice' },
      { url: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Catan Resource Cards Ore Wheat Brick Lumber Sheep' },
      { url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Catan Box Art Front' },
    ],
    variants: [
      { sku: 'PROD-TOY-002-BASE', name: 'Base Game (3-4 Players)', price: 3399, mrp: 3999, stockQuantity: 30, attributes: { Version: 'Base Game' } }
    ]
  },
  {
    sku: 'PROD-TOY-003',
    name: 'DJI Neo Motion Fly More Combo Mini RC Drone',
    slug: 'dji-neo-motion-fly-more-combo-drone',
    description: 'Ultra-compact 135g palm-takeoff 4K UHD video drone featuring AI subject tracking, QuickShots, full propeller guards, and RC Motion 3 controller.',
    brand: 'DJI',
    categorySlug: 'toys-games',
    subcategorySlug: 'action-figures-rc-toys',
    modelNumber: 'DJI-NEO-FMC',
    mrp: 34900,
    currentPrice: 29665,
    originalPrice: 34900,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 15,
    lowStockThreshold: 3,
    rating: 4.8,
    reviewCount: 180,
    tags: ['dji', 'dji neo', 'drone', '4k drone', 'mini drone', 'rc aircraft'],
    specifications: { TakeoffWeight: '135g No License Needed', Camera: '4K Ultra HD 30fps / 12MP', MaxFlightTime: '18 Minutes per battery', FlightControl: 'Palm Control / App / Motion Controller' },
    images: [
      { url: 'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'DJI Neo Mini Drone Hovering Front View' },
      { url: 'https://images.unsplash.com/photo-1566576721346-d4a3b4eaeb55?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'DJI Neo 4K Camera Lens & Propeller Guards' },
      { url: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'DJI RC Motion 3 Controller & Goggles N3' },
      { url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'DJI Two-Way Charging Hub with 3 Batteries' },
    ],
    variants: [
      { sku: 'PROD-TOY-003-FMC', name: 'Fly More Combo (3 Batteries)', price: 29665, mrp: 34900, stockQuantity: 15, attributes: { Pack: 'Fly More Combo' } }
    ]
  },
  {
    sku: 'PROD-TOY-004',
    name: 'Monopoly Ultimate Banking Electronic Board Game',
    slug: 'monopoly-ultimate-banking-electronic',
    description: 'Fast-paced cashless Monopoly edition featuring touch-screen Ultimate Banking tap-and-scan card reader for automatic money and property management.',
    brand: 'Hasbro Gaming',
    categorySlug: 'toys-games',
    subcategorySlug: 'board-games-puzzles',
    modelNumber: 'B6677',
    mrp: 2999,
    currentPrice: 2249,
    originalPrice: 2999,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 35,
    lowStockThreshold: 7,
    rating: 4.7,
    reviewCount: 620,
    tags: ['monopoly', 'hasbro', 'ultimate banking', 'electronic monopoly', 'cashless game'],
    specifications: { Players: '2 to 4 Players', Battery: '3 x AAA (Not Included)', Feature: 'Tap & Scan Bank Cards', Age: '8+ Years' },
    images: [
      { url: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Monopoly Ultimate Banking Board Game Setup' },
      { url: 'https://images.unsplash.com/photo-1566576721346-d4a3b4eaeb55?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Monopoly Electronic Bank Card Scanner Unit' },
      { url: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Monopoly Barcode Property Cards & Tokens' },
      { url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Monopoly Board Game Box Front' },
    ],
    variants: [
      { sku: 'PROD-TOY-004-ELEC', name: 'Ultimate Banking Edition', price: 2249, mrp: 2999, stockQuantity: 35, attributes: { Edition: 'Ultimate Banking' } }
    ]
  },
  {
    sku: 'PROD-TOY-005',
    name: 'Hot Wheels 20-Car Gift Pack Assortment',
    slug: 'hot-wheels-20-car-gift-pack',
    description: 'Collection of 20 die-cast 1:64 scale classic, sports, muscle, and concept vehicles with authentic detailing and smooth rolling wheels.',
    brand: 'Hot Wheels',
    categorySlug: 'toys-games',
    subcategorySlug: 'action-figures-rc-toys',
    modelNumber: 'H7045',
    mrp: 2999,
    currentPrice: 2399,
    originalPrice: 2999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.8,
    reviewCount: 890,
    tags: ['hot wheels', 'die cast cars', 'toy cars', 'hot wheels 20 pack', 'mattel'],
    specifications: { Scale: '1:64 Die-Cast Scale', Quantity: '20 Unique Cars', Material: 'Zinc Metal & Polycarbonate', Age: '3+ Years' },
    images: [
      { url: 'https://images.unsplash.com/photo-1566576721346-d4a3b4eaeb55?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Hot Wheels 20-Car Window Box Gift Pack' },
      { url: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Hot Wheels Die-Cast Muscle Cars Row' },
      { url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Hot Wheels Metallic Paint Detailing' },
      { url: 'https://images.unsplash.com/photo-1560169897-fc0cdbdfa4d5?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Hot Wheels Track Compatible Wheel Hubs' },
    ],
    variants: [
      { sku: 'PROD-TOY-005-20P', name: '20-Car Gift Pack Box', price: 2399, mrp: 2999, stockQuantity: 40, attributes: { Pack: '20 Cars' } }
    ]
  },
  {
    sku: 'PROD-TOY-006',
    name: 'LEGO Star Wars Millennium Falcon (1,351 Pieces)',
    slug: 'lego-star-wars-millennium-falcon',
    description: 'Iconic LEGO Star Wars starship model with rotating top/bottom gun turrets, 2 spring-loaded shooters, lowering ramp, opening cockpit, and 7 minifigures.',
    brand: 'LEGO',
    categorySlug: 'toys-games',
    subcategorySlug: 'building-blocks-lego',
    modelNumber: '75257',
    mrp: 16999,
    currentPrice: 14449,
    originalPrice: 16999,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 15,
    lowStockThreshold: 3,
    rating: 4.9,
    reviewCount: 540,
    tags: ['lego', 'star wars', 'millennium falcon', 'chewbacca minifig', 'lego spaceship'],
    specifications: { Pieces: '1,351 Pieces', Minifigures: '7 Minifigures (Finn, Chewbacca, Lando, etc.)', Dimensions: '44cm L x 32cm W x 14cm H', Age: '9+ Years' },
    images: [
      { url: 'https://images.unsplash.com/photo-1566576721346-d4a3b4eaeb55?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'LEGO Star Wars Millennium Falcon Completed Ship' },
      { url: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'LEGO Millennium Falcon Interior Dejarik Hologram Table' },
      { url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'LEGO Star Wars Minifigures Chewbacca & Lando' },
      { url: 'https://images.unsplash.com/photo-1560169897-fc0cdbdfa4d5?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'LEGO Radar Dish & Spring Loaded Shooters' },
    ],
    variants: [
      { sku: 'PROD-TOY-006-SET', name: '75257 Millennium Falcon Set', price: 14449, mrp: 16999, stockQuantity: 15, attributes: { Version: '75257 Edition' } }
    ]
  },
  {
    sku: 'PROD-TOY-007',
    name: 'Stuka 4WD High-Speed Remote Control Off-Road RC Monster Truck',
    slug: 'stuka-4wd-rc-monster-truck-45kmh',
    description: '1:16 scale 4WD high-speed hobby-grade RC truck reaching 45 km/h with 2.4GHz proportional transmitter, oil-filled shocks, and 2 rechargeable Li-ion batteries.',
    brand: 'Stuka RC',
    categorySlug: 'toys-games',
    subcategorySlug: 'action-figures-rc-toys',
    modelNumber: 'RC-9200',
    mrp: 6999,
    currentPrice: 4899,
    originalPrice: 6999,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 20,
    lowStockThreshold: 4,
    rating: 4.7,
    reviewCount: 310,
    tags: ['rc truck', 'rc car', 'monster truck', '4wd rc car', 'remote control car'],
    specifications: { Speed: 'Up to 45 km/h', Motor: '390 High-Speed Carbon Brushed Motor', Range: '80 Meters 2.4GHz', RunTime: '40 Mins (2 Batteries Included)' },
    images: [
      { url: 'https://images.unsplash.com/photo-1566576721346-d4a3b4eaeb55?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Stuka 4WD Red RC Monster Truck Front' },
      { url: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Stuka RC Metal Oil Filled Shock Absorbers' },
      { url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Stuka 2.4GHz Pistol Grip Transmitter Remote' },
      { url: 'https://images.unsplash.com/photo-1560169897-fc0cdbdfa4d5?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Stuka High-Traction Rubber Off-Road Tires' },
    ],
    variants: [
      { sku: 'PROD-TOY-007-RED', name: 'Flame Red Monster Truck', price: 4899, mrp: 6999, stockQuantity: 10, attributes: { Color: 'Flame Red' } },
      { sku: 'PROD-TOY-007-BLU', name: 'Electric Blue Monster Truck', price: 4899, mrp: 6999, stockQuantity: 10, attributes: { Color: 'Electric Blue' } },
    ]
  },
  {
    sku: 'PROD-TOY-008',
    name: 'Stonemaier Games Wingspan Board Game with Engine Building',
    slug: 'stonemaier-wingspan-board-game',
    description: 'A competitive, medium-weight, card-driven, engine-building board game about bird enthusiasts seeking to discover and attract the best birds.',
    brand: 'Stonemaier Games',
    categorySlug: 'toys-games',
    subcategorySlug: 'board-games-puzzles',
    modelNumber: 'STM900',
    mrp: 5999,
    currentPrice: 5099,
    originalPrice: 5999,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 20,
    lowStockThreshold: 4,
    rating: 4.9,
    reviewCount: 680,
    tags: ['wingspan', 'stonemaier games', 'engine building game', 'board game', 'bird game'],
    specifications: { Players: '1 to 5 Players', Age: '10+ Years', Duration: '40 to 70 Mins', Includes: '170 Unique Bird Cards + Dice Tower + 5 Wooden Dice' },
    images: [
      { url: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Wingspan Board Game Component Layout' },
      { url: 'https://images.unsplash.com/photo-1566576721346-d4a3b4eaeb55?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Wingspan Pastel Wooden Egg Tokens & Dice Tower' },
      { url: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Wingspan Illustrated Bird Cards Detail' },
      { url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Wingspan Player Mat Habitat Tracker' },
    ],
    variants: [
      { sku: 'PROD-TOY-008-ENG', name: 'English 1st Edition', price: 5099, mrp: 5999, stockQuantity: 20, attributes: { Language: 'English' } }
    ]
  },
  {
    sku: 'PROD-TOY-009',
    name: 'Marvel Legends Series Spider-Man 6-Inch Action Figure',
    slug: 'marvel-legends-spider-man-6-inch-action-figure',
    description: 'Premium 6-inch scale Marvel Legends Spider-Man figure featuring movie-inspired design, over 20 points of articulation, and 4 alternate web-shooting hands.',
    brand: 'Hasbro Marvel Legends',
    categorySlug: 'toys-games',
    subcategorySlug: 'action-figures-rc-toys',
    modelNumber: 'F3698',
    mrp: 2499,
    currentPrice: 1999,
    originalPrice: 2499,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 6,
    rating: 4.8,
    reviewCount: 450,
    tags: ['marvel legends', 'spider man', 'action figure', 'hasbro marvel', 'superhero toy'],
    specifications: { FigureHeight: '6 Inches (15 cm)', Articulation: '20+ Articulated Joints', Accessories: '4 Extra Interchangeable Hands + Web Effect', Age: '4+ Years' },
    images: [
      { url: 'https://images.unsplash.com/photo-1566576721346-d4a3b4eaeb55?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Marvel Legends Spider-Man Action Figure Posed' },
      { url: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Marvel Legends Spider Suit Web Pattern Sculpt' },
      { url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Marvel Legends Alternate Thwip Hands' },
      { url: 'https://images.unsplash.com/photo-1560169897-fc0cdbdfa4d5?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Marvel Legends Window Box Package' },
    ],
    variants: [
      { sku: 'PROD-TOY-009-CLASSIC', name: 'Classic Red & Blue Suit', price: 1999, mrp: 2499, stockQuantity: 20, attributes: { Suit: 'Classic Red/Blue' } },
      { sku: 'PROD-TOY-009-SYM', name: 'Symbiote Black Suit', price: 2199, mrp: 2699, stockQuantity: 10, attributes: { Suit: 'Symbiote Black' } },
    ]
  },
  {
    sku: 'PROD-TOY-010',
    name: 'Ravensburger 1000-Piece Bestseller Jigsaw Puzzle',
    slug: 'ravensburger-1000-piece-landscape-jigsaw-puzzle',
    description: 'Premium German 1000-piece jigsaw puzzle featuring Softclick Technology, glare-free linen finish paper, and extra-thick recycled cardboard.',
    brand: 'Ravensburger',
    categorySlug: 'toys-games',
    subcategorySlug: 'board-games-puzzles',
    modelNumber: 'RAV-1000-08',
    mrp: 1999,
    currentPrice: 1599,
    originalPrice: 1999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 6,
    rating: 4.8,
    reviewCount: 520,
    tags: ['ravensburger', 'jigsaw puzzle', '1000 piece puzzle', 'puzzle for adults', 'german puzzle'],
    specifications: { PieceCount: '1000 Pieces', FinishedSize: '70cm x 50cm', Technology: 'Softclick Precision Cut', Origin: 'Made in Germany' },
    images: [
      { url: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Ravensburger 1000 Piece Completed Landscape Puzzle' },
      { url: 'https://images.unsplash.com/photo-1566576721346-d4a3b4eaeb55?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Ravensburger Softclick Interlocking Pieces Close' },
      { url: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Ravensburger Glare-Free Matte Linen Texture' },
      { url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Ravensburger Blue Triangle Box Front' },
    ],
    variants: [
      { sku: 'PROD-TOY-010-ALP', name: 'Alpine Village Landscape', price: 1599, mrp: 1999, stockQuantity: 15, attributes: { Theme: 'Alpine Village' } },
      { sku: 'PROD-TOY-010-MAP', name: 'World Map Vintage', price: 1599, mrp: 1999, stockQuantity: 15, attributes: { Theme: 'Vintage World Map' } },
    ]
  },
  {
    sku: 'PROD-TOY-011',
    name: 'Barbie Signature 65th Anniversary Collector Doll',
    slug: 'barbie-signature-65th-anniversary-collector-doll',
    description: 'Glamorous celebration collector doll wearing a black-and-white couture gown honoring the original 1959 Barbie swimsuit with cat-eye sunglasses and doll stand.',
    brand: 'Barbie',
    categorySlug: 'toys-games',
    subcategorySlug: 'action-figures-rc-toys',
    modelNumber: 'HRM84',
    mrp: 6999,
    currentPrice: 5599,
    originalPrice: 6999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 15,
    lowStockThreshold: 3,
    rating: 4.9,
    reviewCount: 210,
    tags: ['barbie', 'barbie collector', '65th anniversary barbie', 'fashion doll', 'mattel'],
    specifications: { Edition: 'Black Label Collector', Sculpt: 'Original Vintage Face Sculpt', Includes: 'Certificate of Authenticity + Doll Stand', Age: '6+ Years' },
    images: [
      { url: 'https://images.unsplash.com/photo-1566576721346-d4a3b4eaeb55?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Barbie 65th Anniversary Couture Black Gown Doll' },
      { url: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Barbie Cat-Eye Sunglasses & Pearl Earrings Detail' },
      { url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Barbie Black & White Striped Gown Train' },
      { url: 'https://images.unsplash.com/photo-1560169897-fc0cdbdfa4d5?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Barbie Signature Collector Display Box' },
    ],
    variants: [
      { sku: 'PROD-TOY-011-BLND', name: 'Blonde Ponytail', price: 5599, mrp: 6999, stockQuantity: 10, attributes: { Hair: 'Blonde' } },
      { sku: 'PROD-TOY-011-BRN', name: 'Brunette Waves', price: 5599, mrp: 6999, stockQuantity: 5, attributes: { Hair: 'Brunette' } },
    ]
  },
  {
    sku: 'PROD-TOY-012',
    name: 'BeyBlade Burst QuadDrive Cosmic Vector Battle Set',
    slug: 'beyblade-burst-quaddrive-cosmic-vector-set',
    description: '4-in-1 QuadDrive technology stadium set featuring Beystadium, 2 right/left-spin launchers, and 2 customized competitive spinning tops.',
    brand: 'Beyblade',
    categorySlug: 'toys-games',
    subcategorySlug: 'action-figures-rc-toys',
    modelNumber: 'F3962',
    mrp: 4999,
    currentPrice: 3999,
    originalPrice: 4999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 25,
    lowStockThreshold: 5,
    rating: 4.7,
    reviewCount: 380,
    tags: ['beyblade', 'quaddrive', 'beystadium', 'beyblade burst', 'spinning tops'],
    specifications: { Includes: 'Cosmic Vector Beystadium + 2 Tops + 2 Launchers', Tech: '4-in-1 QuadDrive Configs', Age: '8+ Years' },
    images: [
      { url: 'https://images.unsplash.com/photo-1566576721346-d4a3b4eaeb55?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'BeyBlade Burst QuadDrive Beystadium Arena Set' },
      { url: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'BeyBlade Metal Armor Tip & Performance Driver' },
      { url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'BeyBlade Dual Ripcord Launchers' },
      { url: 'https://images.unsplash.com/photo-1560169897-fc0cdbdfa4d5?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'BeyBlade QuadDrive Packaging Box' },
    ],
    variants: [
      { sku: 'PROD-TOY-012-SET', name: 'Cosmic Vector Battle Set', price: 3999, mrp: 4999, stockQuantity: 25, attributes: { Set: 'Battle Set' } }
    ]
  },
  {
    sku: 'PROD-TOY-013',
    name: 'Nerf Elite 2.0 Commander RD-6 Motorized Blaster',
    slug: 'nerf-elite-2-0-commander-rd-6-blaster',
    description: 'Rotating 6-dart drum blaster featuring rapid slam-fire action, tactical rails, barrel and stock attachment points, and 12 official Nerf Elite darts.',
    brand: 'Nerf',
    categorySlug: 'toys-games',
    subcategorySlug: 'action-figures-rc-toys',
    modelNumber: 'E9485',
    mrp: 1799,
    currentPrice: 1349,
    originalPrice: 1799,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.7,
    reviewCount: 710,
    tags: ['nerf', 'nerf blaster', 'elite 2.0', 'commander rd-6', 'foam dart blaster'],
    specifications: { Range: 'Up to 27 Meters (90 Feet)', Capacity: '6-Dart Rotating Drum', Includes: '12 Official Nerf Darts', TacticalRails: '2 Tactical Rails' },
    images: [
      { url: 'https://images.unsplash.com/photo-1566576721346-d4a3b4eaeb55?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Nerf Elite 2.0 Commander RD-6 Blaster Profile' },
      { url: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Nerf 6-Dart Rotating Drum Barrel Loaded' },
      { url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Nerf Elite 2.0 Teal & Orange Foam Darts' },
      { url: 'https://images.unsplash.com/photo-1560169897-fc0cdbdfa4d5?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Nerf Priming Slide & Tactical Rail Top' },
    ],
    variants: [
      { sku: 'PROD-TOY-013-RD6', name: 'Commander RD-6 with 12 Darts', price: 1349, mrp: 1799, stockQuantity: 40, attributes: { Model: 'RD-6' } }
    ]
  },
  {
    sku: 'PROD-TOY-014',
    name: 'Ticket to Ride Europe Board Game by Days of Wonder',
    slug: 'ticket-to-ride-europe-board-game',
    description: 'Cross-country train adventure game across Europe. Players collect train cards to claim railway routes connecting iconic European cities.',
    brand: 'Days of Wonder',
    categorySlug: 'toys-games',
    subcategorySlug: 'board-games-puzzles',
    modelNumber: 'DOW7202',
    mrp: 4499,
    currentPrice: 3824,
    originalPrice: 4499,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 20,
    lowStockThreshold: 4,
    rating: 4.9,
    reviewCount: 820,
    tags: ['ticket to ride', 'days of wonder', 'europe board game', 'train game', 'family strategy'],
    specifications: { Players: '2 to 5 Players', PlayTime: '30 to 60 Minutes', Age: '8+ Years', Components: '1 Board Map + 240 Colored Train Cars + 158 Cards' },
    images: [
      { url: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Ticket to Ride Europe Map Board Setup' },
      { url: 'https://images.unsplash.com/photo-1566576721346-d4a3b4eaeb55?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Ticket to Ride Plastic Colored Train Cars' },
      { url: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Ticket to Ride Destination Tickets Cards' },
      { url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Ticket to Ride Game Box Front Cover' },
    ],
    variants: [
      { sku: 'PROD-TOY-014-EUR', name: 'Europe Edition', price: 3824, mrp: 4499, stockQuantity: 20, attributes: { Edition: 'Europe' } }
    ]
  },
  {
    sku: 'PROD-TOY-015',
    name: 'Rubik’s Speed Cube 3x3 Magnetic Official Puzzle',
    slug: 'rubiks-speed-cube-3x3-magnetic',
    description: 'Frictionless magnetic speed cube featuring internal magnets for alignment precision, anti-pop mechanism, and stickerless tiled surface.',
    brand: 'Rubiks',
    categorySlug: 'toys-games',
    subcategorySlug: 'board-games-puzzles',
    modelNumber: 'RUB-3X3-MAG',
    mrp: 1499,
    currentPrice: 1199,
    originalPrice: 1499,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 50,
    lowStockThreshold: 10,
    rating: 4.8,
    reviewCount: 940,
    tags: ['rubiks cube', 'speed cube', 'magnetic cube', '3x3 puzzle', 'brain teaser'],
    specifications: { Dimensions: '5.6cm x 5.6cm x 5.6cm', Type: '3x3x3 Speed Cube', Magnetics: '48 Positioned Magnets', Surface: 'Stickerless Tiled' },
    images: [
      { url: 'https://images.unsplash.com/photo-1566576721346-d4a3b4eaeb55?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Rubik’s Speed Cube 3x3 Solved State Angle' },
      { url: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Rubik’s Cube Internal Magnetic Core View' },
      { url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Rubik’s Stickerless Matte Plastic Tiles' },
      { url: 'https://images.unsplash.com/photo-1560169897-fc0cdbdfa4d5?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Rubik’s Speed Cube Stand Holder' },
    ],
    variants: [
      { sku: 'PROD-TOY-015-3X3', name: '3x3 Magnetic Speed Cube', price: 1199, mrp: 1499, stockQuantity: 50, attributes: { Size: '3x3' } }
    ]
  }
];
