import { ProductStatus } from '@prisma/client';

export const travelLuggageProducts = [
  {
    sku: 'PROD-TRV-001',
    name: 'Samsonite Omni 2 Hardside Expandable Luggage 28-Inch',
    slug: 'samsonite-omni-2-hardside-spinner-28-inch',
    description: '100% polycarbonate micro-diamond textured scratch-resistant hardshell suitcase with 360-degree dual spinner wheels and TSA combination lock.',
    brand: 'Samsonite',
    categorySlug: 'travel-luggage',
    subcategorySlug: 'trolley-suitcases',
    modelNumber: 'SAM-OMNI2-28',
    mrp: 18999,
    currentPrice: 15199,
    originalPrice: 18999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 20,
    lowStockThreshold: 4,
    rating: 4.8,
    reviewCount: 450,
    tags: ['samsonite', 'hardside luggage', 'trolley suitcase', 'spinner suitcase', 'tsa lock'],
    specifications: { Dimensions: '71cm x 50cm x 32cm (28 Inch Check-In)', Material: '100% Polycarbonate', Wheels: '4 Dual 360 Deg Spinner Wheels', Lock: 'Integrated TSA Combination Lock' },
    images: [
      { url: 'https://images.unsplash.com/photo-1565026057447-b88e3f29042b?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Samsonite Omni 2 Hardside Suitcase Teal Front' },
      { url: 'https://images.unsplash.com/photo-1581605405669-fcdf81165afa?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Samsonite Micro Diamond Polycarbonate Shell Texture' },
      { url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Samsonite Integrated Flush Mounted TSA Lock' },
      { url: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Samsonite Dual Spinner Wheels Close' },
    ],
    variants: [
      { sku: 'PROD-TRV-001-28-TEL', name: '28-Inch Check-In / Teal', price: 15199, mrp: 18999, stockQuantity: 10, attributes: { Size: '28 Inch', Color: 'Teal' } },
      { sku: 'PROD-TRV-001-20-BLK', name: '20-Inch Cabin Carry-On / Black', price: 11999, mrp: 14999, stockQuantity: 10, attributes: { Size: '20 Inch', Color: 'Black' } },
    ]
  },
  {
    sku: 'PROD-TRV-002',
    name: 'The North Face Base Camp Duffel Bag Medium 71L',
    slug: 'the-north-face-base-camp-duffel-medium',
    description: 'Legendary expedition duffel made from recycled phthalate-free TPE laminate material with water-repellent finish, removable ergonomic shoulder straps, and 71L capacity.',
    brand: 'The North Face',
    categorySlug: 'travel-luggage',
    subcategorySlug: 'duffel-travel-bags',
    modelNumber: 'TNF-BC-M',
    mrp: 14999,
    currentPrice: 12749,
    originalPrice: 14999,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 25,
    lowStockThreshold: 5,
    rating: 4.9,
    reviewCount: 380,
    tags: ['the north face', 'base camp duffel', 'travel duffel', 'waterproof duffel', 'expedition bag'],
    specifications: { Volume: '71 Liters', Weight: '1.62 kg', Material: '1000D Recycled TPE Fabric Laminate', Handles: 'Padded Alpine-Cut Shoulder Straps' },
    images: [
      { url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'The North Face Base Camp Duffel Yellow Front' },
      { url: 'https://images.unsplash.com/photo-1565026057447-b88e3f29042b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'The North Face Heavy Duty D-Zip Opening' },
      { url: 'https://images.unsplash.com/photo-1581605405669-fcdf81165afa?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'The North Face Alpine Cut Shoulder Straps' },
      { url: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'The North Face Side Zippered Pocket' },
    ],
    variants: [
      { sku: 'PROD-TRV-002-YEL', name: '71L Medium / Summit Gold', price: 12749, mrp: 14999, stockQuantity: 15, attributes: { Color: 'Summit Gold' } },
      { sku: 'PROD-TRV-002-BLK', name: '71L Medium / TNF Black', price: 12749, mrp: 14999, stockQuantity: 10, attributes: { Color: 'TNF Black' } },
    ]
  },
  {
    sku: 'PROD-TRV-003',
    name: 'Travelon Compression Packing Cubes 4-Piece Set',
    slug: 'travelon-compression-packing-cubes-4-pack',
    description: 'Double zipper compression packing cubes made with lightweight ripstop honeycomb nylon that compresses clothes up to 60% extra luggage space.',
    brand: 'Travelon',
    categorySlug: 'travel-luggage',
    subcategorySlug: 'travel-organizers',
    modelNumber: 'TVL-CUB-04',
    mrp: 2999,
    currentPrice: 2099,
    originalPrice: 2999,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.7,
    reviewCount: 420,
    tags: ['travelon', 'packing cubes', 'compression cubes', 'luggage organizer', 'travel pouch'],
    specifications: { Pack: '4 Cubes (1 Large, 2 Medium, 1 Small)', Material: '210D Honeycomb Ripstop Nylon', Zipper: 'Reinforced Dual Compression Zippers', Mesh: 'Breathable Mesh Window' },
    images: [
      { url: 'https://images.unsplash.com/photo-1581605405669-fcdf81165afa?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Travelon Compression Packing Cubes 4 Set Array' },
      { url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Travelon Compression Zipper Action Close' },
      { url: 'https://images.unsplash.com/photo-1565026057447-b88e3f29042b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Travelon Mesh Top Panel Breathability' },
      { url: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Travelon Packed Cubes Inside Suitcase' },
    ],
    variants: [
      { sku: 'PROD-TRV-003-GRY', name: 'Charcoal Grey 4-Pack', price: 2099, mrp: 2999, stockQuantity: 25, attributes: { Color: 'Charcoal Grey' } },
      { sku: 'PROD-TRV-003-BLU', name: 'Ocean Blue 4-Pack', price: 2099, mrp: 2999, stockQuantity: 15, attributes: { Color: 'Ocean Blue' } },
    ]
  },
  {
    sku: 'PROD-TRV-004',
    name: 'American Tourister Jamaica 3-Piece Softside Spinner Set',
    slug: 'american-tourister-jamaica-softside-luggage-set',
    description: 'Ultra-lightweight polyester 3-piece trolley suitcase set (Cabin, Medium, Large) with corner guards, front pocket access, and 360-degree dual wheels.',
    brand: 'American Tourister',
    categorySlug: 'travel-luggage',
    subcategorySlug: 'trolley-suitcases',
    modelNumber: 'AMT-JAM-SET3',
    mrp: 24999,
    currentPrice: 17499,
    originalPrice: 24999,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 15,
    lowStockThreshold: 3,
    rating: 4.7,
    reviewCount: 510,
    tags: ['american tourister', 'softside luggage', 'trolley set', 'luggage set of 3', 'cabin checkin set'],
    specifications: { SetIncludes: '55cm Cabin + 68cm Medium + 80cm Large', Material: '600D Dobby Polyester', Lock: 'Combi Dial Lock', Wheels: '4 Multi-Directional Wheels' },
    images: [
      { url: 'https://images.unsplash.com/photo-1565026057447-b88e3f29042b?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'American Tourister 3 Piece Softside Trolley Nesting Set' },
      { url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'American Tourister Front Pocket Quick Access' },
      { url: 'https://images.unsplash.com/photo-1581605405669-fcdf81165afa?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'American Tourister Push Button Telescopic Handle' },
      { url: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'American Tourister Corner Protection Guard' },
    ],
    variants: [
      { sku: 'PROD-TRV-004-BLK', name: 'Black 3-Piece Set', price: 17499, mrp: 24999, stockQuantity: 10, attributes: { Color: 'Black' } },
      { sku: 'PROD-TRV-004-RED', name: 'Wine Red 3-Piece Set', price: 17499, mrp: 24999, stockQuantity: 5, attributes: { Color: 'Wine Red' } },
    ]
  },
  {
    sku: 'PROD-TRV-005',
    name: 'Muji Hanging Toiletry Travel Pouch Box',
    slug: 'muji-hanging-toiletry-travel-pouch',
    description: 'Japanese minimalist hanging wash bag made with water-resistant nylon, built-in swivel hook, clear TPU zip pockets, and elastic bottle loops.',
    brand: 'Muji',
    categorySlug: 'travel-luggage',
    subcategorySlug: 'travel-organizers',
    modelNumber: 'MUJ-TOIL-HG',
    mrp: 2490,
    currentPrice: 1992,
    originalPrice: 2490,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 6,
    rating: 4.8,
    reviewCount: 260,
    tags: ['muji', 'toiletry bag', 'hanging wash bag', 'japanese travel organizer', 'cosmetic pouch'],
    specifications: { Material: 'Polyester & TPU Transparent Film', Dimensions: '16cm x 19cm x 6cm (Unfolded 40cm)', Feature: 'Stowable Swivel Hanging Hook' },
    images: [
      { url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Muji Hanging Toiletry Pouch Black Opened' },
      { url: 'https://images.unsplash.com/photo-1581605405669-fcdf81165afa?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Muji Built-in Swivel Plastic Hook' },
      { url: 'https://images.unsplash.com/photo-1565026057447-b88e3f29042b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Muji Transparent TPU Zipper Compartment' },
      { url: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Muji Compact Closed Pouch Profile' },
    ],
    variants: [
      { sku: 'PROD-TRV-005-BLK', name: 'Black Polyester', price: 1992, mrp: 2490, stockQuantity: 20, attributes: { Color: 'Black' } },
      { sku: 'PROD-TRV-005-NVY', name: 'Navy Polyester', price: 1992, mrp: 2490, stockQuantity: 10, attributes: { Color: 'Navy' } },
    ]
  },
  {
    sku: 'PROD-TRV-006',
    name: 'Rimowa Original Cabin Aluminum Hardside Spinner',
    slug: 'rimowa-original-cabin-aluminum-suitcase',
    description: 'Iconic German high-end aluminum suitcase with grooved design, anodized aluminum construction, TSA-approved locks, and Flex Divider system.',
    brand: 'Rimowa',
    categorySlug: 'travel-luggage',
    subcategorySlug: 'trolley-suitcases',
    modelNumber: '92553004',
    mrp: 125000,
    currentPrice: 112500,
    originalPrice: 125000,
    discount: 10.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 5,
    lowStockThreshold: 1,
    rating: 4.9,
    reviewCount: 140,
    tags: ['rimowa', 'rimowa cabin', 'aluminum suitcase', 'luxury luggage', 'rimowa original'],
    specifications: { Dimensions: '55 x 40 x 23 cm (Cabin Approved)', Material: 'High-Grade Anodized Aluminum', Wheels: 'Multiwheel System', Weight: '4.3 kg' },
    images: [
      { url: 'https://images.unsplash.com/photo-1565026057447-b88e3f29042b?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Rimowa Original Silver Aluminum Cabin Suitcase' },
      { url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Rimowa Grooved Aluminum Surface Texture' },
      { url: 'https://images.unsplash.com/photo-1581605405669-fcdf81165afa?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Rimowa Dual Latch Lock Mechanism' },
      { url: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Rimowa Flex Divider Height Adjustable System' },
    ],
    variants: [
      { sku: 'PROD-TRV-006-SLV', name: 'Silver Anodized Aluminum', price: 112500, mrp: 125000, stockQuantity: 3, attributes: { Finish: 'Silver Aluminum' } },
      { sku: 'PROD-TRV-006-BLK', name: 'Black Anodized Aluminum', price: 112500, mrp: 125000, stockQuantity: 2, attributes: { Finish: 'Black Aluminum' } },
    ]
  },
  {
    sku: 'PROD-TRV-007',
    name: 'Wildcraft Wheel Duffel Bag 55L',
    slug: 'wildcraft-wheel-duffel-bag-55l',
    description: 'Rugged 55-liter rolling duffel bag combining spacious duffel volume with smooth inline skate wheels and padded haul handles.',
    brand: 'Wildcraft',
    categorySlug: 'travel-luggage',
    subcategorySlug: 'duffel-travel-bags',
    modelNumber: 'WCK-WDUF-55',
    mrp: 3999,
    currentPrice: 2799,
    originalPrice: 3999,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 6,
    rating: 4.6,
    reviewCount: 390,
    tags: ['wildcraft', 'wheel duffel', 'rolling duffel', 'travel duffel', 'duffel trolley'],
    specifications: { Capacity: '55 Liters', Material: 'High-Density Ripstop Polyester', Wheels: 'Heavy Duty Inline Skate Wheels', Handle: 'Retractable Trolley Handle' },
    images: [
      { url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Wildcraft 55L Rolling Wheel Duffel Bag Front' },
      { url: 'https://images.unsplash.com/photo-1565026057447-b88e3f29042b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Wildcraft Inline Skate Wheels Base Guard' },
      { url: 'https://images.unsplash.com/photo-1581605405669-fcdf81165afa?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Wildcraft U-Shaped Main Compartment Opening' },
      { url: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Wildcraft Telescopic Pull Handle' },
    ],
    variants: [
      { sku: 'PROD-TRV-007-BLK', name: 'Black & Orange', price: 2799, mrp: 3999, stockQuantity: 20, attributes: { Color: 'Black/Orange' } },
      { sku: 'PROD-TRV-007-NVY', name: 'Navy & Yellow', price: 2799, mrp: 3999, stockQuantity: 10, attributes: { Color: 'Navy/Yellow' } },
    ]
  },
  {
    sku: 'PROD-TRV-008',
    name: 'Bellroy Leather Passport Sleeve & Micro Pen Holder',
    slug: 'bellroy-leather-passport-sleeve',
    description: 'Ultra-slim premium environmentally certified leather passport cover with quick-access card slots, cash pocket, and micro travel pen.',
    brand: 'Bellroy',
    categorySlug: 'travel-luggage',
    subcategorySlug: 'travel-organizers',
    modelNumber: 'APSA-BRN',
    mrp: 5999,
    currentPrice: 4799,
    originalPrice: 5999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 25,
    lowStockThreshold: 5,
    rating: 4.8,
    reviewCount: 190,
    tags: ['bellroy', 'passport sleeve', 'leather passport holder', 'travel wallet', 'slim passport case'],
    specifications: { Material: 'Environmentally Certified LWG Leather', Fits: '1 Passport + 4 Cards + Tickets', Pen: 'Includes Refillable Micro Pen', Warranty: '3 Years Warranty' },
    images: [
      { url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Bellroy Leather Passport Sleeve Caramel Opened' },
      { url: 'https://images.unsplash.com/photo-1565026057447-b88e3f29042b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Bellroy Micro Pen Insert Slot Close' },
      { url: 'https://images.unsplash.com/photo-1581605405669-fcdf81165afa?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Bellroy Quick Access Card Pull Tab' },
      { url: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Bellroy Embossed Owl Logo Stamp' },
    ],
    variants: [
      { sku: 'PROD-TRV-008-CRM', name: 'Caramel Tan Leather', price: 4799, mrp: 5999, stockQuantity: 15, attributes: { Color: 'Caramel Tan' } },
      { sku: 'PROD-TRV-008-BLK', name: 'Black Leather', price: 4799, mrp: 5999, stockQuantity: 10, attributes: { Color: 'Black' } },
    ]
  },
  {
    sku: 'PROD-TRV-009',
    name: 'Safari Pentagon 3-Piece Hardside Polypropylene Trolley Set',
    slug: 'safari-pentagon-3-piece-hardside-trolley-set',
    description: 'Unbreakable 100% polypropylene scratch-resistant suitcase set (55cm, 65cm, 75cm) with 3-digit fixed combination lock and dual wheels.',
    brand: 'Safari',
    categorySlug: 'travel-luggage',
    subcategorySlug: 'trolley-suitcases',
    modelNumber: 'SAF-PENT-3P',
    mrp: 18999,
    currentPrice: 11399,
    originalPrice: 18999,
    discount: 40.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 20,
    lowStockThreshold: 4,
    rating: 4.6,
    reviewCount: 680,
    tags: ['safari', 'pentagon', 'polypropylene suitcase', 'hardside luggage set', 'unbreakable suitcase'],
    specifications: { SetIncludes: 'Small (55cm) + Medium (65cm) + Large (75cm)', Material: '100% Impact Resistant Polypropylene', Lock: 'Fixed 3-Digit Dial Lock', Wheels: '4 Dual 360 Deg Spinners' },
    images: [
      { url: 'https://images.unsplash.com/photo-1565026057447-b88e3f29042b?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Safari Pentagon 3 Piece Cyan Trolley Set Nesting' },
      { url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Safari Pentagon Geometric Shell Texture' },
      { url: 'https://images.unsplash.com/photo-1581605405669-fcdf81165afa?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Safari Integrated Combination Lock' },
      { url: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Safari Multi-Stage Aluminum Trolley Rod' },
    ],
    variants: [
      { sku: 'PROD-TRV-009-CYN', name: 'Cyan Blue (Set of 3)', price: 11399, mrp: 18999, stockQuantity: 12, attributes: { Color: 'Cyan Blue' } },
      { sku: 'PROD-TRV-009-RED', name: 'Crimson Red (Set of 3)', price: 11399, mrp: 18999, stockQuantity: 8, attributes: { Color: 'Crimson Red' } },
    ]
  },
  {
    sku: 'PROD-TRV-010',
    name: 'Peak Design Travel Backpack 45L Modular Carry-On',
    slug: 'peak-design-travel-backpack-45l',
    description: 'Versatile 45-liter weatherproof carry-on travel backpack featuring dual side access, top & front opening, stowable shoulder straps, and modular packing compatibility.',
    brand: 'Peak Design',
    categorySlug: 'travel-luggage',
    subcategorySlug: 'duffel-travel-bags',
    modelNumber: 'BTR-45-BK-1',
    mrp: 34999,
    currentPrice: 29749,
    originalPrice: 34999,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 10,
    lowStockThreshold: 2,
    rating: 4.9,
    reviewCount: 310,
    tags: ['peak design', 'travel backpack', '45l backpack', 'carry on backpack', 'modular bag'],
    specifications: { Volume: '35L Standard (Expands to 45L / Compresses to 30L)', Material: 'Weatherproof 400D Recycled Nylon Canvas', Laptop: 'Fits up to 16 inch MacBook Pro', CarryOn: 'International Carry-On Approved' },
    images: [
      { url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Peak Design 45L Travel Backpack Black Front' },
      { url: 'https://images.unsplash.com/photo-1565026057447-b88e3f29042b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Peak Design Rear Stowable Magnetic Shoulder Straps' },
      { url: 'https://images.unsplash.com/photo-1581605405669-fcdf81165afa?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Peak Design Full Rear Hatch Opening Interior' },
      { url: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Peak Design Expansion Zippers Extended' },
    ],
    variants: [
      { sku: 'PROD-TRV-010-BLK', name: 'Black Weatherproof', price: 29749, mrp: 34999, stockQuantity: 6, attributes: { Color: 'Black' } },
      { sku: 'PROD-TRV-010-SGE', name: 'Sage Green Weatherproof', price: 29749, mrp: 34999, stockQuantity: 4, attributes: { Color: 'Sage Green' } },
    ]
  },
  {
    sku: 'PROD-TRV-011',
    name: 'Anker Universal All-in-One International Travel Adapter 65W',
    slug: 'anker-universal-international-travel-adapter-65w',
    description: 'Global travel plug adapter working in over 150 countries (US/EU/UK/AU) featuring 65W GaN USB-C fast charging port for laptops and phones.',
    brand: 'Anker',
    categorySlug: 'travel-luggage',
    subcategorySlug: 'travel-organizers',
    modelNumber: 'A9212',
    mrp: 4999,
    currentPrice: 3749,
    originalPrice: 4999,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 6,
    rating: 4.8,
    reviewCount: 540,
    tags: ['anker', 'travel adapter', 'universal plug adapter', '65w gan charger', 'international adapter'],
    specifications: { Compatibility: 'US / UK / EU / AU / JP (150+ Countries)', USBPorts: '1x 65W USB-C + 2x USB-A', Fuse: 'Integrated 8A Safety Fuse', ACVoltage: '100V - 250V Max 2000W' },
    images: [
      { url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Anker Universal Travel Adapter Plug Slider Front' },
      { url: 'https://images.unsplash.com/photo-1565026057447-b88e3f29042b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Anker Retractable US UK EU AU Pin Slider Mechanism' },
      { url: 'https://images.unsplash.com/photo-1581605405669-fcdf81165afa?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Anker 65W USB-C Port & Dual USB-A Output' },
      { url: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Anker Zippered Hard Case Included' },
    ],
    variants: [
      { sku: 'PROD-TRV-011-65W', name: '65W GaN Travel Adapter Kit', price: 3749, mrp: 4999, stockQuantity: 30, attributes: { Power: '65W' } }
    ]
  },
  {
    sku: 'PROD-TRV-012',
    name: 'Victorinox Spectra 3.0 Expandable Global Carry-On 20-Inch',
    slug: 'victorinox-spectra-3-expandable-carry-on',
    description: 'Swiss-engineered expandable hardside carry-on crafted from SORPLAS recycled high-performance polycarbonate with front opening organizer compartment.',
    brand: 'Victorinox',
    categorySlug: 'travel-luggage',
    subcategorySlug: 'trolley-suitcases',
    modelNumber: '611752',
    mrp: 38000,
    currentPrice: 32300,
    originalPrice: 38000,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 12,
    lowStockThreshold: 3,
    rating: 4.9,
    reviewCount: 160,
    tags: ['victorinox', 'spectra 3.0', 'carry on suitcase', 'swiss luggage', 'expandable hardside'],
    specifications: { Dimensions: '55cm x 40cm x 20cm (Expandable +20%)', Material: 'SORPLAS Recycled Polycarbonate', Feature: 'Quick Access Front Tech Door', Lock: 'Travel Sentry Approved Lock' },
    images: [
      { url: 'https://images.unsplash.com/photo-1565026057447-b88e3f29042b?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Victorinox Spectra 3.0 Black Carry-On Front' },
      { url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Victorinox Front Door 15.6 Inch Laptop Sleeve Opened' },
      { url: 'https://images.unsplash.com/photo-1581605405669-fcdf81165afa?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Victorinox Dual Caster Hinomoto Wheels' },
      { url: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Victorinox Swiss Cross Metal Badge Logo' },
    ],
    variants: [
      { sku: 'PROD-TRV-012-BLK', name: '20-Inch Global Carry-On / Black', price: 32300, mrp: 38000, stockQuantity: 12, attributes: { Size: '20 Inch' } }
    ]
  },
  {
    sku: 'PROD-TRV-013',
    name: 'Sea to Summit Hydraulic Waterproof Dry Duffel Bag 90L',
    slug: 'sea-to-summit-hydraulic-waterproof-dry-duffel-90l',
    description: 'Heavy duty IPX7 fully submersible waterproof expedition duffel made with TPU laminated 840D nylon, pressure-tested YKK waterproof zipper.',
    brand: 'Sea to Summit',
    categorySlug: 'travel-luggage',
    subcategorySlug: 'duffel-travel-bags',
    modelNumber: 'STS-HYD-90L',
    mrp: 24999,
    currentPrice: 21249,
    originalPrice: 24999,
    discount: 15.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 10,
    lowStockThreshold: 2,
    rating: 4.8,
    reviewCount: 140,
    tags: ['sea to summit', 'dry duffel', 'waterproof duffel', 'ipx7 dry bag', 'expedition gear'],
    specifications: { Rating: 'IPX7 Waterproof (Submersible to 1 meter)', Volume: '90 Liters', Fabric: '840D Heavy Duty TPU Laminated Nylon', Zipper: 'YKK Waterproof Tooth Zipper' },
    images: [
      { url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Sea to Summit Hydraulic Dry Duffel Yellow Body' },
      { url: 'https://images.unsplash.com/photo-1565026057447-b88e3f29042b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Sea to Summit YKK Waterproof Airtight Zipper' },
      { url: 'https://images.unsplash.com/photo-1581605405669-fcdf81165afa?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Sea to Summit Heavy Anodized Aluminum Buckles' },
      { url: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Sea to Summit Removable EVA Padded Backpack Straps' },
    ],
    variants: [
      { sku: 'PROD-TRV-013-90L', name: '90 Liter Yellow Dry Duffel', price: 21249, mrp: 24999, stockQuantity: 10, attributes: { Volume: '90 Liters' } }
    ]
  },
  {
    sku: 'PROD-TRV-014',
    name: 'Babeeni Memory Foam Ergonomic Travel Neck Pillow',
    slug: 'babeeni-memory-foam-travel-neck-pillow',
    description: '360-degree chin support memory foam travel neck pillow with breathable washable velvet cover, adjustable rope lock buckle, and compact storage pouch.',
    brand: 'Cabeau',
    categorySlug: 'travel-luggage',
    subcategorySlug: 'travel-organizers',
    modelNumber: 'CAB-EVO-PLW',
    mrp: 3499,
    currentPrice: 2624,
    originalPrice: 3499,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.8,
    reviewCount: 650,
    tags: ['cabeau', 'travel pillow', 'neck pillow', 'memory foam pillow', 'airplane pillow'],
    specifications: { Core: '100% High Density Memory Foam', Cover: 'Soft Velour Removable Washable Cover', Support: 'Raised Side Supports + Flat Back Cushion', Includes: 'Travel Compress Case' },
    images: [
      { url: 'https://images.unsplash.com/photo-1581605405669-fcdf81165afa?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Cabeau Memory Foam Neck Pillow Charcoal Front' },
      { url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Cabeau Adjustable Toggle Chin Strap Lock' },
      { url: 'https://images.unsplash.com/photo-1565026057447-b88e3f29042b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Cabeau Raised Ergonomic Contour Cushion' },
      { url: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Cabeau Rolled Up Compressed Travel Pouch' },
    ],
    variants: [
      { sku: 'PROD-TRV-014-BLK', name: 'Charcoal Black Velour', price: 2624, mrp: 3499, stockQuantity: 25, attributes: { Color: 'Charcoal Black' } },
      { sku: 'PROD-TRV-014-BLU', name: 'Midnight Navy Velour', price: 2624, mrp: 3499, stockQuantity: 15, attributes: { Color: 'Midnight Navy' } },
    ]
  },
  {
    sku: 'PROD-TRV-015',
    name: 'Delsey Paris Chatelet Air 2.0 Hardside Trunk Spinner 73cm',
    slug: 'delsey-paris-chatelet-air-2-0-trunk-spinner',
    description: 'French vintage chic trunk suitcase made with durable polycarbonate, Securities 2 zip system, SILVADUR anti-microbial lining, and built-in tracking code.',
    brand: 'Delsey Paris',
    categorySlug: 'travel-luggage',
    subcategorySlug: 'trolley-suitcases',
    modelNumber: '00167682006',
    mrp: 32999,
    currentPrice: 26399,
    originalPrice: 32999,
    discount: 20.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 12,
    lowStockThreshold: 3,
    rating: 4.9,
    reviewCount: 280,
    tags: ['delsey paris', 'chatelet air', 'hardside luggage', 'trunk suitcase', 'french designer luggage'],
    specifications: { Dimensions: '73cm x 41.5cm x 36.5cm', Weight: '4.8 kg', Material: '100% Virgin Polycarbonate', Lock: 'Recessed TSA Combination Lock' },
    images: [
      { url: 'https://images.unsplash.com/photo-1565026057447-b88e3f29042b?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Delsey Paris Chatelet Air 2.0 Angora White Trunk' },
      { url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Delsey Paris Faux Leather Trim Accent Detail' },
      { url: 'https://images.unsplash.com/photo-1581605405669-fcdf81165afa?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Delsey Securities 2 Double Anti Theft Zipper' },
      { url: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Delsey Interior Peach Skin Velvet Lining Dividers' },
    ],
    variants: [
      { sku: 'PROD-TRV-015-WHT', name: '73cm Trunk / Angora White', price: 26399, mrp: 32999, stockQuantity: 7, attributes: { Color: 'Angora White' } },
      { sku: 'PROD-TRV-015-PNK', name: '73cm Trunk / Terracotta Pink', price: 26399, mrp: 32999, stockQuantity: 5, attributes: { Color: 'Terracotta Pink' } },
    ]
  }
];
