import { ProductStatus } from '@prisma/client';

export const womensClothingProducts = [
  {
    sku: 'PROD-WCL-001',
    name: "Levi's Women 721 High Rise Asian Fit Skinny Jeans",
    slug: 'levis-women-721-high-rise-skinny-jeans',
    description: 'Designed to flatter, hold and lift. Iconic 721 high-rise fit featuring Levi’s Stellar Stretch technology that holds its shape.',
    brand: "Levi's",
    categorySlug: 'womens-clothing',
    subcategorySlug: 'womens-jeans-skirts',
    modelNumber: '18882-0450',
    mrp: 4299,
    currentPrice: 3199,
    originalPrice: 4299,
    discount: 25.5,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.8,
    reviewCount: 380,
    tags: ['levis', 'womens jeans', '721 skinny', 'high rise', 'stretch denim'],
    specifications: { Fit: 'High Rise Skinny', Rise: '10 inch High Rise', Stretch: 'Stellar Stretch Tech' },
    images: [
      { url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: "Levi's 721 Women High Rise Blue Jeans" },
      { url: 'https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: "Levi's Women Leather Back Patch" },
      { url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: "Levi's Women Ankle Skinny Fit" },
      { url: 'https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: "Levi's Women Pocket Arcuate Stitching" },
    ]
  },
  {
    sku: 'PROD-WCL-002',
    name: 'Zara Tailored Double-Breasted Oversized Blazer',
    slug: 'zara-tailored-double-breasted-blazer',
    description: 'Chic structured blazer featuring peak lapels, double-breasted button front, shoulder pads, and front flap welt pockets.',
    brand: 'Zara',
    categorySlug: 'womens-clothing',
    subcategorySlug: 'womens-tops',
    modelNumber: 'ZR-BLZ-8820',
    mrp: 6990,
    currentPrice: 5490,
    originalPrice: 6990,
    discount: 21.4,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 25,
    lowStockThreshold: 5,
    rating: 4.7,
    reviewCount: 290,
    tags: ['zara', 'blazer', 'double breasted', 'womens blazer', 'workwear'],
    specifications: { Material: '64% Polyester, 32% Viscose, 4% Elastane', Fit: 'Oversized Tailored Fit', Closure: 'Tortoiseshell Buttons' },
    images: [
      { url: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Zara Tailored Beige Double Breasted Blazer' },
      { url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Zara Blazer Peak Lapels Close-up' },
      { url: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Zara Blazer Flap Pocket Detail' },
      { url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Zara Blazer Back Vent View' },
    ]
  },
  {
    sku: 'PROD-WCL-003',
    name: 'Biba Women Printed Cotton Anarkali Kurta Set with Dupatta',
    slug: 'biba-printed-anarkali-kurta-set',
    description: 'Elegant ethnic flared Anarkali kurta crafted from 100% breathable cotton, paired with matching pants and printed dupatta.',
    brand: 'Biba',
    categorySlug: 'womens-clothing',
    subcategorySlug: 'womens-dresses-kurtis',
    modelNumber: 'SKDF8821',
    mrp: 5995,
    currentPrice: 3995,
    originalPrice: 5995,
    discount: 33.3,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 6,
    rating: 4.8,
    reviewCount: 340,
    tags: ['biba', 'anarkali kurta', 'kurta set', 'cotton kurti', 'ethnic wear'],
    specifications: { Fabric: '100% Pure Cotton', Sleeve: 'Three-Quarter Sleeves', SetIncludes: 'Kurta + Bottom + Printed Dupatta' },
    images: [
      { url: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Biba Floral Anarkali Kurta Set Full View' },
      { url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Biba Kurta Neckline Embroidery' },
      { url: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Biba Printed Cotton Dupatta Border' },
      { url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Biba Flared Hemline Detail' },
    ]
  },
  {
    sku: 'PROD-WCL-004',
    name: 'Mango Floral Print Puff Sleeve Midi Dress',
    slug: 'mango-floral-puff-sleeve-midi-dress',
    description: 'Charming V-neck midi dress featuring vibrant floral print, elasticated puff sleeves, gathered waist, and front slit hem.',
    brand: 'Mango',
    categorySlug: 'womens-clothing',
    subcategorySlug: 'womens-dresses-kurtis',
    modelNumber: 'MNG-DRS-4421',
    mrp: 4990,
    currentPrice: 3490,
    originalPrice: 4990,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 28,
    lowStockThreshold: 5,
    rating: 4.7,
    reviewCount: 180,
    tags: ['mango', 'midi dress', 'floral dress', 'puff sleeve', 'summer dress'],
    specifications: { Material: '100% Sustainable Viscose', Neck: 'V-Neck', Length: 'Midi Length' },
    images: [
      { url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Mango Floral Midi Dress Front View' },
      { url: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Mango Puff Sleeve Cuff Detail' },
      { url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Mango Front Slit Hemline' },
      { url: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Mango Back Zipper Closure' },
    ]
  },
  {
    sku: 'PROD-WCL-005',
    name: 'H&M Ribbed Knit Fitted Crop Top',
    slug: 'hm-ribbed-knit-fitted-crop-top',
    description: 'Soft stretch cotton-blend ribbed knit top with sweetheart neckline and short sleeves.',
    brand: 'H&M',
    categorySlug: 'womens-clothing',
    subcategorySlug: 'womens-tops',
    modelNumber: 'HM-TP-0921',
    mrp: 1499,
    currentPrice: 999,
    originalPrice: 1499,
    discount: 33.3,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 50,
    lowStockThreshold: 10,
    rating: 4.5,
    reviewCount: 420,
    tags: ['hm', 'ribbed top', 'crop top', 'sweetheart neck', 'casual top'],
    specifications: { Fabric: '95% Cotton, 5% Elastane', Fit: 'Fitted', Neck: 'Sweetheart Neck' },
    images: [
      { url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'H&M White Ribbed Crop Top Front' },
      { url: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'H&M Ribbed Fabric Texture' },
      { url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'H&M Sleeve Hem Detail' },
      { url: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'H&M Back Neckline' },
    ]
  },
  {
    sku: 'PROD-WCL-006',
    name: 'W for Woman Geometric Printed Straight Cotton Kurta',
    slug: 'w-for-woman-geometric-printed-kurta',
    description: 'Modern geometric print straight cotton kurta featuring round neck with keyhole detail and metallic accents.',
    brand: 'W',
    categorySlug: 'womens-clothing',
    subcategorySlug: 'womens-dresses-kurtis',
    modelNumber: 'W-KRT-9921',
    mrp: 2999,
    currentPrice: 1999,
    originalPrice: 2999,
    discount: 33.3,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 35,
    lowStockThreshold: 6,
    rating: 4.7,
    reviewCount: 260,
    tags: ['w for woman', 'straight kurta', 'printed kurti', 'ethnic top'],
    specifications: { Fabric: '100% Cotton', Shape: 'Straight Cut', Sleeve: 'Three-Quarter Sleeves' },
    images: [
      { url: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'W Geometric Printed Kurta Front' },
      { url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'W Keyhole Neckline Metallic Detail' },
      { url: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'W Sleeve Cuff Print' },
      { url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'W Side Slits Hem' },
    ]
  },
  {
    sku: 'PROD-WCL-007',
    name: 'Vero Moda Women Denim Trucker Jacket',
    slug: 'vero-moda-women-denim-trucker-jacket',
    description: 'Classic light-wash denim jacket styled with button-down front, dual flap chest pockets, and buttoned cuffs.',
    brand: 'Vero Moda',
    categorySlug: 'womens-clothing',
    subcategorySlug: 'womens-tops',
    modelNumber: 'VM-JKT-1049',
    mrp: 4499,
    currentPrice: 2999,
    originalPrice: 4499,
    discount: 33.3,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 5,
    rating: 4.8,
    reviewCount: 210,
    tags: ['vero moda', 'denim jacket', 'trucker jacket', 'womens jacket'],
    specifications: { Fabric: '100% Cotton Denim', Wash: 'Light Blue Wash', Closure: 'Button Closure' },
    images: [
      { url: 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Vero Moda Light Blue Denim Jacket Front' },
      { url: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Vero Moda Buttoned Chest Pocket' },
      { url: 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Vero Moda Collar & Seam Detail' },
      { url: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Vero Moda Back Waist Tabs' },
    ]
  },
  {
    sku: 'PROD-WCL-008',
    name: 'Aurelia Women Chanderi Silk Blend Festive Straight Kurta',
    slug: 'aurelia-chanderi-silk-festive-kurta',
    description: 'Rich Chanderi silk blend kurta embellished with zari embroidery along the mandarin collar and placket.',
    brand: 'Aurelia',
    categorySlug: 'womens-clothing',
    subcategorySlug: 'womens-dresses-kurtis',
    modelNumber: 'AUR-KRT-8841',
    mrp: 3499,
    currentPrice: 2499,
    originalPrice: 3499,
    discount: 28.5,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 25,
    lowStockThreshold: 5,
    rating: 4.7,
    reviewCount: 190,
    tags: ['aurelia', 'chanderi silk', 'festive kurta', 'zari embroidery'],
    specifications: { Fabric: 'Chanderi Silk Blend', Neck: 'Mandarin Collar', Work: 'Zari Thread Work' },
    images: [
      { url: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Aurelia Maroon Chanderi Silk Kurta' },
      { url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Aurelia Mandarin Collar Zari Placket' },
      { url: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Aurelia Sleeve Border Embroidery' },
      { url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Aurelia Tissue Lining Edge' },
    ]
  },
  {
    sku: 'PROD-WCL-009',
    name: 'ONLY Women High Waist Wide Leg Cotton Cargo Trousers',
    slug: 'only-women-high-waist-wide-leg-cargo-trousers',
    description: 'Trendy high-waist wide-leg cargo pants tailored from durable cotton twill with dual cargo flap leg pockets.',
    brand: 'ONLY',
    categorySlug: 'womens-clothing',
    subcategorySlug: 'womens-jeans-skirts',
    modelNumber: 'ONLY-CRG-1102',
    mrp: 3999,
    currentPrice: 2799,
    originalPrice: 3999,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 35,
    lowStockThreshold: 6,
    rating: 4.6,
    reviewCount: 160,
    tags: ['only', 'wide leg cargo', 'cargo trousers', 'high waist pants'],
    specifications: { Material: '100% Cotton Twill', Fit: 'Wide Leg Loose Fit', Rise: 'High Rise' },
    images: [
      { url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'ONLY Wide Leg Khaki Cargo Pants Front' },
      { url: 'https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'ONLY Cargo Side Pocket Flap' },
      { url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'ONLY High Waist Button Detail' },
      { url: 'https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'ONLY Wide Leg Hem' },
    ]
  },
  {
    sku: 'PROD-WCL-010',
    name: 'Forever 21 Satin Cowl Neck Cami Top',
    slug: 'forever-21-satin-cowl-neck-cami-top',
    description: 'Silky satin camisole featuring draped cowl neck, adjustable spaghetti shoulder straps, and bias-cut drape.',
    brand: 'Forever 21',
    categorySlug: 'womens-clothing',
    subcategorySlug: 'womens-tops',
    modelNumber: 'F21-CAMI-992',
    mrp: 1999,
    currentPrice: 1299,
    originalPrice: 1999,
    discount: 35.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 40,
    lowStockThreshold: 8,
    rating: 4.5,
    reviewCount: 220,
    tags: ['forever 21', 'satin top', 'cowl neck', 'cami top', 'party top'],
    specifications: { Material: '100% Polyester Satin', Neck: 'Cowl Neck', Straps: 'Adjustable Spaghetti Straps' },
    images: [
      { url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Forever 21 Black Satin Cami Top Front' },
      { url: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Forever 21 Cowl Neck Drape Detail' },
      { url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Forever 21 Satin Sheen Finish' },
      { url: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Forever 21 Back Shoulder Straps' },
    ]
  },
  {
    sku: 'PROD-WCL-011',
    name: 'FabIndia Cotton Printed A-Line Maxi Skirt',
    slug: 'fabindia-cotton-printed-maxi-skirt',
    description: 'Hand block-printed cotton flared A-line maxi skirt with elasticated waist and tassel drawstring ties.',
    brand: 'FabIndia',
    categorySlug: 'womens-clothing',
    subcategorySlug: 'womens-jeans-skirts',
    modelNumber: 'FAB-SKRT-1092',
    mrp: 2990,
    currentPrice: 2190,
    originalPrice: 2990,
    discount: 26.7,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 30,
    lowStockThreshold: 6,
    rating: 4.8,
    reviewCount: 175,
    tags: ['fabindia', 'maxi skirt', 'cotton skirt', 'block print', 'ethnic skirt'],
    specifications: { Material: '100% Hand Block Printed Cotton', Length: 'Maxi Ankle Length', Waist: 'Elasticated with Tassels' },
    images: [
      { url: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'FabIndia Indigo Printed Maxi Skirt Flare' },
      { url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'FabIndia Hand Block Print Pattern Detail' },
      { url: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'FabIndia Drawstring Tassel Ties' },
      { url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'FabIndia Flared Hemline Border' },
    ]
  },
  {
    sku: 'PROD-WCL-012',
    name: 'Marks & Spencer Pure Cotton Oversized Linen Look Shirt',
    slug: 'marks-spencer-pure-cotton-oversized-shirt',
    description: 'Crisp pure breathable cotton shirt styled with front button placket, drop shoulders, and single patch chest pocket.',
    brand: 'Marks & Spencer',
    categorySlug: 'womens-clothing',
    subcategorySlug: 'womens-tops',
    modelNumber: 'MS-SHRT-8841',
    mrp: 3999,
    currentPrice: 2999,
    originalPrice: 3999,
    discount: 25.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 35,
    lowStockThreshold: 7,
    rating: 4.7,
    reviewCount: 140,
    tags: ['marks spencer', 'cotton shirt', 'oversized shirt', 'casual shirt'],
    specifications: { Material: '100% Cotton Linen-Weave', Fit: 'Relaxed Oversized Fit', Closure: 'Button Closure' },
    images: [
      { url: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Marks & Spencer White Cotton Oversized Shirt' },
      { url: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Marks & Spencer Chest Pocket Detail' },
      { url: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Marks & Spencer Button Collar' },
      { url: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Marks & Spencer Cuffed Sleeve' },
    ]
  },
  {
    sku: 'PROD-WCL-013',
    name: 'Allen Solly Woman Solid Notch Lapel Formal Blazer',
    slug: 'allen-solly-woman-notch-lapel-formal-blazer',
    description: 'Tailored single-breasted women’s formal blazer woven from stretch creped fabric with slim waist fit.',
    brand: 'Allen Solly',
    categorySlug: 'womens-clothing',
    subcategorySlug: 'womens-tops',
    modelNumber: 'ASW-BLZ-7711',
    mrp: 6499,
    currentPrice: 4799,
    originalPrice: 6499,
    discount: 26.1,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 20,
    lowStockThreshold: 4,
    rating: 4.8,
    reviewCount: 165,
    tags: ['allen solly woman', 'formal blazer', 'workwear blazer', 'notch lapel'],
    specifications: { Fabric: 'Polyester Viscose Stretch Crepe', Fit: 'Tailored Slim Fit', Pocket: '2 Welt Pockets' },
    images: [
      { url: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Allen Solly Woman Black Formal Blazer Front' },
      { url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Allen Solly Notch Lapel Collar' },
      { url: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Allen Solly Single Button Waist' },
      { url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Allen Solly Inner Lining Finish' },
    ]
  },
  {
    sku: 'PROD-WCL-014',
    name: 'AND Women Solid Fit and Flare Knee Length Dress',
    slug: 'and-women-fit-and-flare-knee-length-dress',
    description: 'Chic fit and flare dress with boat neckline, short sleeves, and cinched waist belt detail.',
    brand: 'AND',
    categorySlug: 'womens-clothing',
    subcategorySlug: 'womens-dresses-kurtis',
    modelNumber: 'AND-DRS-9012',
    mrp: 3999,
    currentPrice: 2799,
    originalPrice: 3999,
    discount: 30.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 28,
    lowStockThreshold: 5,
    rating: 4.6,
    reviewCount: 130,
    tags: ['and', 'fit and flare dress', 'knee length dress', 'casual dress'],
    specifications: { Material: '95% Polyester, 5% Elastane', Silhouette: 'Fit & Flare', Length: 'Knee Length' },
    images: [
      { url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'AND Red Fit and Flare Dress Front' },
      { url: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'AND Waist Belt Detail' },
      { url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'AND Boat Neckline Finish' },
      { url: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'AND Flared Skirt Hem' },
    ]
  },
  {
    sku: 'PROD-WCL-015',
    name: 'Global Desi Women Rayon Printed Straight Kurta',
    slug: 'global-desi-rayon-printed-straight-kurta',
    description: 'Soft breathable rayon printed ethnic kurta styled with round neck, contrasting border print, and side slits.',
    brand: 'Global Desi',
    categorySlug: 'womens-clothing',
    subcategorySlug: 'womens-dresses-kurtis',
    modelNumber: 'GD-KRT-6621',
    mrp: 2499,
    currentPrice: 1699,
    originalPrice: 2499,
    discount: 32.0,
    availabilityStatus: ProductStatus.AVAILABLE,
    stockQuantity: 35,
    lowStockThreshold: 6,
    rating: 4.7,
    reviewCount: 190,
    tags: ['global desi', 'rayon kurta', 'ethnic print', 'daily kurti'],
    specifications: { Fabric: '100% Liva Viscose Rayon', Neck: 'Round Neck with Notch', Pattern: 'Boho Ethnic Print' },
    images: [
      { url: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&q=80&w=800', isPrimary: true, altText: 'Global Desi Yellow Printed Rayon Kurta' },
      { url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Global Desi Yoke Pattern Detail' },
      { url: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Global Desi Sleeve Border Print' },
      { url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=800', isPrimary: false, altText: 'Global Desi Side Slit Hemline' },
    ]
  }
];
